WITH x AS (
  SELECT * FROM (VALUES
  (E'DF-2026-038'::text, E'DF'::text, E'GIRD/ KALITEKONTROLU- UYGUNSUZLUKTESPITI | MUAYENEBILGILERI | Kayit No: 26/02/056 | Muayene Tarihi: 10.02.2026 | Tedarikgi: Civata Ve Metal San.tic. A.s'::text, E'Tedarikçiden gelen parçalarda boyutsal, görsel veya fonksiyonel uygunsuzluk tespit edilmektedir.'::text, E'Muayenede uygunsuz parçalar, sevkiyattan önce tedarikçi tarafından eleneememektedir.'::text, E'Tedarikçi çıkış kontrol noktasında kritik karakteristikler ölçülmemekte ya da kayıt tutulmamaktadır.'::text, E'Kontrol planında kritik karakteristikler tanımlanmamış veya güncel değildir.'::text, E'Tedarikçi ile yapılan teknik toplantıda kritik özellikler yeterince vurgulanmamış, kontrol planı birlikte gözden geçirilmemiştir.'::text, E'Tedarikçi geliştirme/onay sürecinde ürün kalite planı (PPAP/APQP vb.) gerektiği düzeyde oluşturulmamış ve denetlenmemiştir.'::text, E'GIRD/ KALITEKONTROLU- UYGUNSUZLUKTESPITI | MUAYENEBILGILERI | Kayit No: 26/02/056 | Muayene Tarihi: 10.02.2026 | Tedarik'::text, E'Tedarikgi'::text, E'10.03.2026'::text, E'Tedarikgi'::text, E'Tedarikçi üretim sürecinde boyutsal/görsel/fonksiyonel kalite kontrol yeterli düzeyde uygulanmamaktadır. Kontrol planınd…'::text, E'GKK (Girdi Kalite Kontrol) muayenesinde veya saha geri bildirimi ile tespit edilmiştir.'::text, E'1. Uygunsuz \'Egzoz Baglanti Pimi\' partisi tedarikçiye iade edilmeli veya karantinaya alınmalıdır.\n2. Tedarikçiye DF-2026-038 numaralı DF kaydı iletilmeli, 15 iş günü içinde yazılı kök neden analizi ve düzeltici aksiyon planı talep edilmelidir.\n3. Tedarikçinin kontrol planı incelenmeli; kritik boyutlar ve kabul kriterleri yeniden belirlenmeli, onaylı kontrol planı alınmalıdır.\n4. Aynı tedarikçiden tekrarlayan uygunsuzluk varsa tedarikçi performans puanı düşürülmeli, alternatif tedarikçi değerlendirmesi başlatılmalıdır.'::text),
  (E'DF-2026-039'::text, E'DF'::text, E'GIRD/ KALITEKONTROLU- UYGUNSUZLUKTESPITI | MUAYENEBILGILERI | Kayit No: 26/02/058 | Muayene Tarihi: 10.02.2026 | Tedarikgi: Civata Ve Metal San.tic. A.s'::text, E'Tedarikçiden gelen parçalarda boyutsal, görsel veya fonksiyonel uygunsuzluk tespit edilmektedir.'::text, E'Muayenede uygunsuz parçalar, sevkiyattan önce tedarikçi tarafından eleneememektedir.'::text, E'Tedarikçi çıkış kontrol noktasında kritik karakteristikler ölçülmemekte ya da kayıt tutulmamaktadır.'::text, E'Kontrol planında kritik karakteristikler tanımlanmamış veya güncel değildir.'::text, E'Tedarikçi ile yapılan teknik toplantıda kritik özellikler yeterince vurgulanmamış, kontrol planı birlikte gözden geçirilmemiştir.'::text, E'Tedarikçi geliştirme/onay sürecinde ürün kalite planı (PPAP/APQP vb.) gerektiği düzeyde oluşturulmamış ve denetlenmemiştir.'::text, E'GIRD/ KALITEKONTROLU- UYGUNSUZLUKTESPITI | MUAYENEBILGILERI | Kayit No: 26/02/058 | Muayene Tarihi: 10.02.2026 | Tedarik'::text, E'Tedarikgi'::text, E'10.03.2026'::text, E'Tedarikgi'::text, E'Tedarikçi üretim sürecinde boyutsal/görsel/fonksiyonel kalite kontrol yeterli düzeyde uygulanmamaktadır. Kontrol planınd…'::text, E'GKK (Girdi Kalite Kontrol) muayenesinde veya saha geri bildirimi ile tespit edilmiştir.'::text, E'1. Uygunsuz \'Klape Kapatma Sist. Burcu\' partisi tedarikçiye iade edilmeli veya karantinaya alınmalıdır.\n2. Tedarikçiye DF-2026-039 numaralı DF kaydı iletilmeli, 15 iş günü içinde yazılı kök neden analizi ve düzeltici aksiyon planı talep edilmelidir.\n3. Tedarikçinin kontrol planı incelenmeli; kritik boyutlar ve kabul kriterleri yeniden belirlenmeli, onaylı kontrol planı alınmalıdır.\n4. Aynı tedarikçiden tekrarlayan uygunsuzluk varsa tedarikçi performans puanı düşürülmeli, alternatif tedarikçi değerlendirmesi başlatılmalıdır.'::text),
  (E'DF-2026-040'::text, E'DF'::text, E'GIRD/ KALITEKONTROLU- UYGUNSUZLUKTESPITI | MUAYENEBILGILERI | Kayit No: 26/02/062 | Muayene Tarihi: 10.02.2026 | Tedarikgi: Ozkan Makine Ltd. Sti.'::text, E'Tedarikçiden gelen parçalarda boyutsal, görsel veya fonksiyonel uygunsuzluk tespit edilmektedir.'::text, E'Muayenede uygunsuz parçalar, sevkiyattan önce tedarikçi tarafından eleneememektedir.'::text, E'Tedarikçi çıkış kontrol noktasında kritik karakteristikler ölçülmemekte ya da kayıt tutulmamaktadır.'::text, E'Kontrol planında kritik karakteristikler tanımlanmamış veya güncel değildir.'::text, E'Tedarikçi ile yapılan teknik toplantıda kritik özellikler yeterince vurgulanmamış, kontrol planı birlikte gözden geçirilmemiştir.'::text, E'Tedarikçi geliştirme/onay sürecinde ürün kalite planı (PPAP/APQP vb.) gerektiği düzeyde oluşturulmamış ve denetlenmemiştir.'::text, E'GIRD/ KALITEKONTROLU- UYGUNSUZLUKTESPITI | MUAYENEBILGILERI | Kayit No: 26/02/062 | Muayene Tarihi: 10.02.2026 | Tedarik'::text, E'Tedarikgi'::text, E'10.03.2026'::text, E'Tedarikgi'::text, E'Tedarikçi üretim sürecinde boyutsal/görsel/fonksiyonel kalite kontrol yeterli düzeyde uygulanmamaktadır. Kontrol planınd…'::text, E'GKK (Girdi Kalite Kontrol) muayenesinde veya saha geri bildirimi ile tespit edilmiştir.'::text, E'1. Uygunsuz \'Arka Firga Hidromotor Kaplini\' partisi tedarikçiye iade edilmeli veya karantinaya alınmalıdır.\n2. Tedarikçiye DF-2026-040 numaralı DF kaydı iletilmeli, 15 iş günü içinde yazılı kök neden analizi ve düzeltici aksiyon planı talep edilmelidir.\n3. Tedarikçinin kontrol planı incelenmeli; kritik boyutlar ve kabul kriterleri yeniden belirlenmeli, onaylı kontrol planı alınmalıdır.\n4. Aynı tedarikçiden tekrarlayan uygunsuzluk varsa tedarikçi performans puanı düşürülmeli, alternatif tedarikçi değerlendirmesi başlatılmalıdır.'::text),
  (E'DF-2026-041'::text, E'DF'::text, E'GIRD/ KALITEKONTROLU- UYGUNSUZLUKTESPITI | MUAYENEBILGILERI | Kayit No: 26/02/065 | Muayene Tarihi: 10.02.2026 | Tedarikgi: Uzcelik Makine Ltd. Sti.'::text, E'Tedarikçiden gelen parçalarda boyutsal, görsel veya fonksiyonel uygunsuzluk tespit edilmektedir.'::text, E'Muayenede uygunsuz parçalar, sevkiyattan önce tedarikçi tarafından eleneememektedir.'::text, E'Tedarikçi çıkış kontrol noktasında kritik karakteristikler ölçülmemekte ya da kayıt tutulmamaktadır.'::text, E'Kontrol planında kritik karakteristikler tanımlanmamış veya güncel değildir.'::text, E'Tedarikçi ile yapılan teknik toplantıda kritik özellikler yeterince vurgulanmamış, kontrol planı birlikte gözden geçirilmemiştir.'::text, E'Tedarikçi geliştirme/onay sürecinde ürün kalite planı (PPAP/APQP vb.) gerektiği düzeyde oluşturulmamış ve denetlenmemiştir.'::text, E'GIRD/ KALITEKONTROLU- UYGUNSUZLUKTESPITI | MUAYENEBILGILERI | Kayit No: 26/02/065 | Muayene Tarihi: 10.02.2026 | Tedarik'::text, E'Tedarikgi'::text, E'10.03.2026'::text, E'Tedarikgi'::text, E'Tedarikçi üretim sürecinde boyutsal/görsel/fonksiyonel kalite kontrol yeterli düzeyde uygulanmamaktadır. Kontrol planınd…'::text, E'GKK (Girdi Kalite Kontrol) muayenesinde veya saha geri bildirimi ile tespit edilmiştir.'::text, E'1. Uygunsuz \'Kapi Kilit Pimi\' partisi tedarikçiye iade edilmeli veya karantinaya alınmalıdır.\n2. Tedarikçiye DF-2026-041 numaralı DF kaydı iletilmeli, 15 iş günü içinde yazılı kök neden analizi ve düzeltici aksiyon planı talep edilmelidir.\n3. Tedarikçinin kontrol planı incelenmeli; kritik boyutlar ve kabul kriterleri yeniden belirlenmeli, onaylı kontrol planı alınmalıdır.\n4. Aynı tedarikçiden tekrarlayan uygunsuzluk varsa tedarikçi performans puanı düşürülmeli, alternatif tedarikçi değerlendirmesi başlatılmalıdır.'::text),
  (E'DF-2026-042'::text, E'DF'::text, E'GIRD/ KALITEKONTROLU- UYGUNSUZLUKTESPITI | MUAYENEBILGILERI | Kayit No: 26/02/075 | Muayene Tarihi: 11.02.2026 | Tedarikgi: Saytek Tasarim Mak.kal.kons'::text, E'Tedarikçiden gelen parçalarda boyutsal, görsel veya fonksiyonel uygunsuzluk tespit edilmektedir.'::text, E'Muayenede uygunsuz parçalar, sevkiyattan önce tedarikçi tarafından eleneememektedir.'::text, E'Tedarikçi çıkış kontrol noktasında kritik karakteristikler ölçülmemekte ya da kayıt tutulmamaktadır.'::text, E'Kontrol planında kritik karakteristikler tanımlanmamış veya güncel değildir.'::text, E'Tedarikçi ile yapılan teknik toplantıda kritik özellikler yeterince vurgulanmamış, kontrol planı birlikte gözden geçirilmemiştir.'::text, E'Tedarikçi geliştirme/onay sürecinde ürün kalite planı (PPAP/APQP vb.) gerektiği düzeyde oluşturulmamış ve denetlenmemiştir.'::text, E'GIRD/ KALITEKONTROLU- UYGUNSUZLUKTESPITI | MUAYENEBILGILERI | Kayit No: 26/02/075 | Muayene Tarihi: 11.02.2026 | Tedarik'::text, E'Tedarikgi'::text, E'Belirtilmemiş'::text, E'Tedarikgi'::text, E'Tedarikçi üretim sürecinde boyutsal/görsel/fonksiyonel kalite kontrol yeterli düzeyde uygulanmamaktadır. Kontrol planınd…'::text, E'GKK (Girdi Kalite Kontrol) muayenesinde veya saha geri bildirimi ile tespit edilmiştir.'::text, E'1. Uygunsuz \'Vakum Agzi Sulama Parcasi\' partisi tedarikçiye iade edilmeli veya karantinaya alınmalıdır.\n2. Tedarikçiye DF-2026-042 numaralı DF kaydı iletilmeli, 15 iş günü içinde yazılı kök neden analizi ve düzeltici aksiyon planı talep edilmelidir.\n3. Tedarikçinin kontrol planı incelenmeli; kritik boyutlar ve kabul kriterleri yeniden belirlenmeli, onaylı kontrol planı alınmalıdır.\n4. Aynı tedarikçiden tekrarlayan uygunsuzluk varsa tedarikçi performans puanı düşürülmeli, alternatif tedarikçi değerlendirmesi başlatılmalıdır.'::text),
  (E'DF-2026-045'::text, E'DF'::text, E'GIRD/ KALITEKONTROLU- UYGUNSUZLUKTESPITI | MUAYENEBILGILERI | Kayit No: 26/02/080 | Muayene Tarihi: 13.02.2026 | Tedarikgi: Civata Ve Metal San.tic. A.s'::text, E'Tedarikçiden gelen parçalarda boyutsal, görsel veya fonksiyonel uygunsuzluk tespit edilmektedir.'::text, E'Muayenede uygunsuz parçalar, sevkiyattan önce tedarikçi tarafından eleneememektedir.'::text, E'Tedarikçi çıkış kontrol noktasında kritik karakteristikler ölçülmemekte ya da kayıt tutulmamaktadır.'::text, E'Kontrol planında kritik karakteristikler tanımlanmamış veya güncel değildir.'::text, E'Tedarikçi ile yapılan teknik toplantıda kritik özellikler yeterince vurgulanmamış, kontrol planı birlikte gözden geçirilmemiştir.'::text, E'Tedarikçi geliştirme/onay sürecinde ürün kalite planı (PPAP/APQP vb.) gerektiği düzeyde oluşturulmamış ve denetlenmemiştir.'::text, E'GIRD/ KALITEKONTROLU- UYGUNSUZLUKTESPITI | MUAYENEBILGILERI | Kayit No: 26/02/080 | Muayene Tarihi: 13.02.2026 | Tedarik'::text, E'Tedarikgi'::text, E'13.03.2026'::text, E'Veli Muammer Inyayla'::text, E'Tedarikçi üretim sürecinde boyutsal/görsel/fonksiyonel kalite kontrol yeterli düzeyde uygulanmamaktadır. Kontrol planınd…'::text, E'GKK (Girdi Kalite Kontrol) muayenesinde veya saha geri bildirimi ile tespit edilmiştir.'::text, E'1. Uygunsuz \'Ceki Kolu Delrin Yuva\' partisi tedarikçiye iade edilmeli veya karantinaya alınmalıdır.\n2. Tedarikçiye DF-2026-045 numaralı DF kaydı iletilmeli, 15 iş günü içinde yazılı kök neden analizi ve düzeltici aksiyon planı talep edilmelidir.\n3. Tedarikçinin kontrol planı incelenmeli; kritik boyutlar ve kabul kriterleri yeniden belirlenmeli, onaylı kontrol planı alınmalıdır.\n4. Aynı tedarikçiden tekrarlayan uygunsuzluk varsa tedarikçi performans puanı düşürülmeli, alternatif tedarikçi değerlendirmesi başlatılmalıdır.'::text),
  (E'DF-2026-046'::text, E'DF'::text, E'Radyatérde yasanan catlak sebepli uygunsuzluk igin aksiyon alinmasi gerekmektedir .'::text, E'Tedarikçi malzemesinde çatlak veya mekanik bütünlük sorunu tespit edilmiştir.'::text, E'Malzeme, uygulanan kuvvet/stres altında yapısal bütünlüğünü koruyamamaktadır.'::text, E'Malzeme mekanik özellikleri (akma, çekme dayanımı) spesifikasyonu karşılamamaktadır.'::text, E'Tedarikçiden malzeme sertifikası (MTC) talep edilmemekte veya doğrulama yapılmamaktadır.'::text, E'Girdi muayenesinde malzeme mekanik testleri zorunlu adım olarak tanımlanmamıştır.'::text, E'Tedarikçi seçiminde malzeme kalite sertifikasyonu ve numune onay prosedürü (ilk numune onayı/ISIR) uygulanmamaktadır.'::text, E'Radyatérde yasanan catlak sebepli uygunsuzluk igin aksiyon alinmasi gerekmektedir .'::text, E'Tedarikci'::text, E'13.03.2026'::text, E'Tedarikci'::text, E'Tedarikçi malzeme kalitesi yetersiz veya üretim sürecinde çatlak oluşumuna neden olan mekanik stres kontrol edilmemiş.'::text, E'GKK (Girdi Kalite Kontrol) muayenesinde veya saha geri bildirimi ile tespit edilmiştir.'::text, E'1. Çatlak tespit edilen radyatör/parça iade edilmeli veya imha edilmelidir.\n2. Tedarikçiden malzeme sertifikası ve üretim kontrol raporu talep edilmelidir.\n3. Alternatif tedarikçi değerlendirmesi başlatılmalıdır.\n4. Giriş muayenesinde radyatör/ilgili parça için basınç testi eklenmesi değerlendirilmelidir.'::text),
  (E'DF-2026-047'::text, E'DF'::text, E'GIRD/ KALITEKONTROLU- UYGUNSUZLUKTESPITI | MUAYENEBILGILERI | Kayit No: 26/02/094 | Muayene Tarihi: 16.02.2026 | Tedarikgi: Saytek Tasarim Mak.kal.kons'::text, E'Tedarikçiden gelen parçalarda boyutsal, görsel veya fonksiyonel uygunsuzluk tespit edilmektedir.'::text, E'Muayenede uygunsuz parçalar, sevkiyattan önce tedarikçi tarafından eleneememektedir.'::text, E'Tedarikçi çıkış kontrol noktasında kritik karakteristikler ölçülmemekte ya da kayıt tutulmamaktadır.'::text, E'Kontrol planında kritik karakteristikler tanımlanmamış veya güncel değildir.'::text, E'Tedarikçi ile yapılan teknik toplantıda kritik özellikler yeterince vurgulanmamış, kontrol planı birlikte gözden geçirilmemiştir.'::text, E'Tedarikçi geliştirme/onay sürecinde ürün kalite planı (PPAP/APQP vb.) gerektiği düzeyde oluşturulmamış ve denetlenmemiştir.'::text, E'GIRD/ KALITEKONTROLU- UYGUNSUZLUKTESPITI | MUAYENEBILGILERI | Kayit No: 26/02/094 | Muayene Tarihi: 16.02.2026 | Tedarik'::text, E'Tedarikgi'::text, E'16.03.2026'::text, E'Tedarikgi'::text, E'Tedarikçi üretim sürecinde boyutsal/görsel/fonksiyonel kalite kontrol yeterli düzeyde uygulanmamaktadır. Kontrol planınd…'::text, E'GKK (Girdi Kalite Kontrol) muayenesinde veya saha geri bildirimi ile tespit edilmiştir.'::text, E'1. Uygunsuz \'On Dingil Merkezleme Mili\' partisi tedarikçiye iade edilmeli veya karantinaya alınmalıdır.\n2. Tedarikçiye DF-2026-047 numaralı DF kaydı iletilmeli, 15 iş günü içinde yazılı kök neden analizi ve düzeltici aksiyon planı talep edilmelidir.\n3. Tedarikçinin kontrol planı incelenmeli; kritik boyutlar ve kabul kriterleri yeniden belirlenmeli, onaylı kontrol planı alınmalıdır.\n4. Aynı tedarikçiden tekrarlayan uygunsuzluk varsa tedarikçi performans puanı düşürülmeli, alternatif tedarikçi değerlendirmesi başlatılmalıdır.'::text),
  (E'DF-2026-048'::text, E'DF'::text, E'GIRD/ KALITEKONTROLU- UYGUNSUZLUKTESPITI | MUAYENEBILGILERI | Kayit No: 26/02/096 | Muayene Tarihi: 16.02.2026 | Tedarikgi: Saytek Tasarim Mak.kal.kons'::text, E'Tedarikçiden gelen parçalarda boyutsal, görsel veya fonksiyonel uygunsuzluk tespit edilmektedir.'::text, E'Muayenede uygunsuz parçalar, sevkiyattan önce tedarikçi tarafından eleneememektedir.'::text, E'Tedarikçi çıkış kontrol noktasında kritik karakteristikler ölçülmemekte ya da kayıt tutulmamaktadır.'::text, E'Kontrol planında kritik karakteristikler tanımlanmamış veya güncel değildir.'::text, E'Tedarikçi ile yapılan teknik toplantıda kritik özellikler yeterince vurgulanmamış, kontrol planı birlikte gözden geçirilmemiştir.'::text, E'Tedarikçi geliştirme/onay sürecinde ürün kalite planı (PPAP/APQP vb.) gerektiği düzeyde oluşturulmamış ve denetlenmemiştir.'::text, E'GIRD/ KALITEKONTROLU- UYGUNSUZLUKTESPITI | MUAYENEBILGILERI | Kayit No: 26/02/096 | Muayene Tarihi: 16.02.2026 | Tedarik'::text, E'Tedarikgi'::text, E'16.03.2026'::text, E'Tedarikgi'::text, E'Tedarikçi üretim sürecinde boyutsal/görsel/fonksiyonel kalite kontrol yeterli düzeyde uygulanmamaktadır. Kontrol planınd…'::text, E'GKK (Girdi Kalite Kontrol) muayenesinde veya saha geri bildirimi ile tespit edilmiştir.'::text, E'1. Uygunsuz \'Ceki Kolu Delrin Yataklama\' partisi tedarikçiye iade edilmeli veya karantinaya alınmalıdır.\n2. Tedarikçiye DF-2026-048 numaralı DF kaydı iletilmeli, 15 iş günü içinde yazılı kök neden analizi ve düzeltici aksiyon planı talep edilmelidir.\n3. Tedarikçinin kontrol planı incelenmeli; kritik boyutlar ve kabul kriterleri yeniden belirlenmeli, onaylı kontrol planı alınmalıdır.\n4. Aynı tedarikçiden tekrarlayan uygunsuzluk varsa tedarikçi performans puanı düşürülmeli, alternatif tedarikçi değerlendirmesi başlatılmalıdır.'::text),
  (E'DF-2026-050'::text, E'DF'::text, E'GIRD/ KALITEKONTROLU- UYGUNSUZLUKTESPITI | MUAYENEBILGILERI | Kayit No: 26/02/104 | Muayene Tarihi: 20.02.2026 | Tedarikgi: Saytek Tasarim Mak.kal.kons'::text, E'Tedarikçiden gelen parçalarda boyutsal, görsel veya fonksiyonel uygunsuzluk tespit edilmektedir.'::text, E'Muayenede uygunsuz parçalar, sevkiyattan önce tedarikçi tarafından eleneememektedir.'::text, E'Tedarikçi çıkış kontrol noktasında kritik karakteristikler ölçülmemekte ya da kayıt tutulmamaktadır.'::text, E'Kontrol planında kritik karakteristikler tanımlanmamış veya güncel değildir.'::text, E'Tedarikçi ile yapılan teknik toplantıda kritik özellikler yeterince vurgulanmamış, kontrol planı birlikte gözden geçirilmemiştir.'::text, E'Tedarikçi geliştirme/onay sürecinde ürün kalite planı (PPAP/APQP vb.) gerektiği düzeyde oluşturulmamış ve denetlenmemiştir.'::text, E'GIRD/ KALITEKONTROLU- UYGUNSUZLUKTESPITI | MUAYENEBILGILERI | Kayit No: 26/02/104 | Muayene Tarihi: 20.02.2026 | Tedarik'::text, E'Tedarikgi'::text, E'Belirtilmemiş'::text, E'Tedarikgi'::text, E'Tedarikçi üretim sürecinde boyutsal/görsel/fonksiyonel kalite kontrol yeterli düzeyde uygulanmamaktadır. Kontrol planınd…'::text, E'GKK (Girdi Kalite Kontrol) muayenesinde veya saha geri bildirimi ile tespit edilmiştir.'::text, E'1. Uygunsuz \'Aga3000 Elektirikli Ispanya Kabin Baj Pernosu\' partisi tedarikçiye iade edilmeli veya karantinaya alınmalıdır.\n2. Tedarikçiye DF-2026-050 numaralı DF kaydı iletilmeli, 15 iş günü içinde yazılı kök neden analizi ve düzeltici aksiyon planı talep edilmelidir.\n3. Tedarikçinin kontrol planı incelenmeli; kritik boyutlar ve kabul kriterleri yeniden belirlenmeli, onaylı kontrol planı alınmalıdır.\n4. Aynı tedarikçiden tekrarlayan uygunsuzluk varsa tedarikçi performans puanı düşürülmeli, alternatif tedarikçi değerlendirmesi başlatılmalıdır.'::text),
  (E'DF-2026-051'::text, E'DF'::text, E'GIRD/ KALITEKONTROLU- UYGUNSUZLUKTESPITI | MUAYENEBILGILERI | Kayit No: 26/02/106 | Muayene Tarihi: 20.02.2026 | Tedarikgi: Saytek Tasarim Mak.kal.kons'::text, E'Tedarikçiden gelen parçalarda boyutsal, görsel veya fonksiyonel uygunsuzluk tespit edilmektedir.'::text, E'Muayenede uygunsuz parçalar, sevkiyattan önce tedarikçi tarafından eleneememektedir.'::text, E'Tedarikçi çıkış kontrol noktasında kritik karakteristikler ölçülmemekte ya da kayıt tutulmamaktadır.'::text, E'Kontrol planında kritik karakteristikler tanımlanmamış veya güncel değildir.'::text, E'Tedarikçi ile yapılan teknik toplantıda kritik özellikler yeterince vurgulanmamış, kontrol planı birlikte gözden geçirilmemiştir.'::text, E'Tedarikçi geliştirme/onay sürecinde ürün kalite planı (PPAP/APQP vb.) gerektiği düzeyde oluşturulmamış ve denetlenmemiştir.'::text, E'GIRD/ KALITEKONTROLU- UYGUNSUZLUKTESPITI | MUAYENEBILGILERI | Kayit No: 26/02/106 | Muayene Tarihi: 20.02.2026 | Tedarik'::text, E'Tedarikgi'::text, E'Belirtilmemiş'::text, E'Kiirgad Atalay'::text, E'Tedarikçi üretim sürecinde boyutsal/görsel/fonksiyonel kalite kontrol yeterli düzeyde uygulanmamaktadır. Kontrol planınd…'::text, E'GKK (Girdi Kalite Kontrol) muayenesinde veya saha geri bildirimi ile tespit edilmiştir.'::text, E'1. Uygunsuz \'Kapak Izgara Baglanti Parcasi\' partisi tedarikçiye iade edilmeli veya karantinaya alınmalıdır.\n2. Tedarikçiye DF-2026-051 numaralı DF kaydı iletilmeli, 15 iş günü içinde yazılı kök neden analizi ve düzeltici aksiyon planı talep edilmelidir.\n3. Tedarikçinin kontrol planı incelenmeli; kritik boyutlar ve kabul kriterleri yeniden belirlenmeli, onaylı kontrol planı alınmalıdır.\n4. Aynı tedarikçiden tekrarlayan uygunsuzluk varsa tedarikçi performans puanı düşürülmeli, alternatif tedarikçi değerlendirmesi başlatılmalıdır.'::text),
  (E'DF-2026-052'::text, E'DF'::text, E'GIRD/ KALITEKONTROLU- UYGUNSUZLUKTESPITI | MUAYENEBILGILERI | Kayit No: 26/02/108 | Muayene Tarihi: 20.02.2026 | Tedarikgi: Saytek Tasarim Mak.kal.kons'::text, E'Tedarikçiden gelen parçalarda boyutsal, görsel veya fonksiyonel uygunsuzluk tespit edilmektedir.'::text, E'Muayenede uygunsuz parçalar, sevkiyattan önce tedarikçi tarafından eleneememektedir.'::text, E'Tedarikçi çıkış kontrol noktasında kritik karakteristikler ölçülmemekte ya da kayıt tutulmamaktadır.'::text, E'Kontrol planında kritik karakteristikler tanımlanmamış veya güncel değildir.'::text, E'Tedarikçi ile yapılan teknik toplantıda kritik özellikler yeterince vurgulanmamış, kontrol planı birlikte gözden geçirilmemiştir.'::text, E'Tedarikçi geliştirme/onay sürecinde ürün kalite planı (PPAP/APQP vb.) gerektiği düzeyde oluşturulmamış ve denetlenmemiştir.'::text, E'GIRD/ KALITEKONTROLU- UYGUNSUZLUKTESPITI | MUAYENEBILGILERI | Kayit No: 26/02/108 | Muayene Tarihi: 20.02.2026 | Tedarik'::text, E'Tedarikgi'::text, E'Belirtilmemiş'::text, E'Tedarikgi'::text, E'Tedarikçi üretim sürecinde boyutsal/görsel/fonksiyonel kalite kontrol yeterli düzeyde uygulanmamaktadır. Kontrol planınd…'::text, E'GKK (Girdi Kalite Kontrol) muayenesinde veya saha geri bildirimi ile tespit edilmiştir.'::text, E'1. Uygunsuz \'Elek Mentese Pimi\' partisi tedarikçiye iade edilmeli veya karantinaya alınmalıdır.\n2. Tedarikçiye DF-2026-052 numaralı DF kaydı iletilmeli, 15 iş günü içinde yazılı kök neden analizi ve düzeltici aksiyon planı talep edilmelidir.\n3. Tedarikçinin kontrol planı incelenmeli; kritik boyutlar ve kabul kriterleri yeniden belirlenmeli, onaylı kontrol planı alınmalıdır.\n4. Aynı tedarikçiden tekrarlayan uygunsuzluk varsa tedarikçi performans puanı düşürülmeli, alternatif tedarikçi değerlendirmesi başlatılmalıdır.'::text)
  ) AS t(nc_number, typ, problem_def, symptom, why1, why2, why3, why4, why5, ne, nerede, ne_zaman, kim, neden, nasil, actions_text)
)
UPDATE non_conformities n
SET
  five_n1k_analysis = jsonb_build_object(
    'ne', to_jsonb(x.ne),
    'nerede', to_jsonb(x.nerede),
    'neZaman', to_jsonb(x.ne_zaman),
    'kim', to_jsonb(x.kim),
    'neden', to_jsonb(x.neden),
    'nasil', to_jsonb(x.nasil)
  ),
  five_why_analysis = jsonb_build_object(
    'problem', to_jsonb(x.problem_def),
    'why1', to_jsonb(x.why1),
    'why2', to_jsonb(x.why2),
    'why3', to_jsonb(x.why3),
    'why4', to_jsonb(x.why4),
    'why5', to_jsonb(x.why5),
    'rootCause', to_jsonb(x.why5),
    'immediateAction', to_jsonb(x.neden),
    'preventiveAction', to_jsonb(x.actions_text)
  ),
  eight_d_steps = CASE
    WHEN n.type = '8D' THEN
      jsonb_set(
        jsonb_set(
          COALESCE(n.eight_d_steps, '{}'::jsonb),
          '{D4,description}',
          to_jsonb(
            ('5 Neden (özet)'::text || E'\n\n' ||
             '1. ' || x.why1 || E'\n' ||
             '2. ' || x.why2 || E'\n' ||
             '3. ' || x.why3 || E'\n' ||
             '4. ' || x.why4 || E'\n' ||
             '5 (Kök): ' || x.why5)::text
          ),
          true
        ),
        '{D5,description}',
        to_jsonb(('Önerilen düzeltici faaliyetler'::text || E'\n\n' || x.actions_text)::text),
        true
      )
    ELSE n.eight_d_steps
  END,
  updated_at = now()
FROM x
WHERE n.nc_number = x.nc_number AND n.type = x.typ;
