WITH x AS (
  SELECT * FROM (VALUES
  (E'8D-2026-005'::text, E'8D'::text, E'™ GRUPOZETI | Kategori : Tasarim Hatas! | Tespit Alani : Uretilen Araclar | Toplam Kayit : 21 | Toplam Adet : 60'::text, E'Tasarım kaynaklı hatalar büyük araç popülasyonunu (21 kayıt, 60 araç) etkilemiştir.'::text, E'Tasarım, saha koşullarında beklenen performansı sağlayamamaktadır.'::text, E'Tasarım doğrulama testleri gerçek kullanım yüklerini ve koşullarını tam simüle edememiştir.'::text, E'DVP kapsamı yetersiz; kritik kullanım profilleri (ağır yük, çoklu siklus, iklim vb.) test matrisine dahil edilmemiştir.'::text, E'FMEA\'da yüksek RPN\'li modlar belirlenmemiş ya da doğrulama testleriyle kapatılmamıştır.'::text, E'Ürün tasarım doğrulama sürecinde saha simülasyonu ve FMEA tabanlı test kapsama analizi sistematik uygulanmamıştır.'::text, E'™ GRUPOZETI | Kategori : Tasarim Hatas! | Tespit Alani : Uretilen Araclar | Toplam Kayit : 21 | Toplam Adet : 60'::text, E'Ar-Ge Direktérliigi'::text, E'01.05.2026'::text, E'Kiirgad Atalay'::text, E'Tasarım hatası kategorisinde gruplandırılmış 21 kayıt'::text, E'Prototip/seri üretim doğrulama testi veya saha geri bildirimi ile tespit edilmiştir.'::text, E'1. 8D raporundaki her alt kayıt için ayrı tasarım revizyonu açılmalıdır.\n2. Gruplanan 60 araçtaki tasarım hataları önceliklendirilmeli; kritik güvenlik/fonksiyon etkisi olanlara acil MDB çıkarılmalıdır.\n3. Tasarım FMEA kapsamlı olarak güncellenmeli; hata modları ve önlemler gözden geçirilmelidir.\n4. Ar-Ge tasarım onay prosedürüne saha geri bildirimi döngüsü eklenmelidir.'::text),
  (E'DF-2026-049'::text, E'DF'::text, E'AGA6000aracimizda kazan kapaliyken , kazanin agilmasini engelleyen sistem aktif edilmedigi_ icin araclarimizda | misteri kullaniminda SSHtarafindan uygunsuzluk tespit edilmis olup aksiyon alinmalidir . | 3. |ILERLEME NOTLARI / YAPILAN CALISMALAR | | Yazilimgincellemesi yapildi tim 6000ler giincellendi'::text, E'Ürün sahada tasarım kaynaklı uygunsuzlukla karşılaşmaktadır.'::text, E'Müşteri kullanım senaryosunda ortaya çıkan hata, tasarım aşamasında öngörülmemiştir.'::text, E'Doğrulama planı (DVP) bu hata modunu kapsamamaktadır.'::text, E'DVP hazırlanırken müşteri kullanım profili ve olası hata modları yeterince tanımlanmamıştır.'::text, E'Tasarım FMEA bu senaryoyu içermemiş ya da düşük risk puanı verilmiştir.'::text, E'Tasarım doğrulama planı müşteri saha koşullarını tam yansıtacak test senaryolarını kapsamayacak biçimde eksik oluşturulmuştur.'::text, E'AGA6000aracimizda kazan kapaliyken , kazanin agilmasini engelleyen sistem aktif edilmedigi_ icin araclarimizda | misteri'::text, E'Ar-Ge'::text, E'17.03.2026'::text, E'Kiirsad Atalay'::text, E'Tasarım doğrulama aşamasında bu uygunsuzluk senaryosu yeterince test edilmemiş.'::text, E'Prototip/seri üretim doğrulama testi veya saha geri bildirimi ile tespit edilmiştir.'::text, E'1. Teknik resim revize edilmeli; gerekli tasarım değişikliği MDB ile yayınlanmalıdır.\n2. Prototip üzerinde doğrulama testi yapılmalıdır.\n3. Sahadaki araçlar için servis bildirimi hazırlanmalıdır.\n4. Tasarım FMEA güncellenmelidir.'::text),
  (E'DF-2026-082'::text, E'DF'::text, E'Araglarimiz igerisinde , joystick , firga kontrol butonlar! ve hareketli pargalara midahale edilen kontrol Unitelerinde | etiketleme calismasi yapiimamis olup , hangi diigme / joystick hangi ekipmani hareket ettiriyor bilinmemektedir | Kalite Kontrol birimine de bu konuyla ilgili bilgi verilmedigi tespit edilmistir . Aksiyon alinmasi gerekmektedir'::text, E'Ürün sahada tasarım kaynaklı uygunsuzlukla karşılaşmaktadır.'::text, E'Müşteri kullanım senaryosunda ortaya çıkan hata, tasarım aşamasında öngörülmemiştir.'::text, E'Doğrulama planı (DVP) bu hata modunu kapsamamaktadır.'::text, E'DVP hazırlanırken müşteri kullanım profili ve olası hata modları yeterince tanımlanmamıştır.'::text, E'Tasarım FMEA bu senaryoyu içermemiş ya da düşük risk puanı verilmiştir.'::text, E'Tasarım doğrulama planı müşteri saha koşullarını tam yansıtacak test senaryolarını kapsamayacak biçimde eksik oluşturulmuştur.'::text, E'Araglarimiz igerisinde , joystick , firga kontrol butonlar! ve hareketli pargalara midahale edilen kontrol Unitelerinde'::text, E'Ar-Ge'::text, E'Belirtilmemiş'::text, E'Kiirsad Atalay'::text, E'Tasarım doğrulama aşamasında bu uygunsuzluk senaryosu yeterince test edilmemiş.'::text, E'Prototip/seri üretim doğrulama testi veya saha geri bildirimi ile tespit edilmiştir.'::text, E'1. Teknik resim revize edilmeli; gerekli tasarım değişikliği MDB ile yayınlanmalıdır.\n2. Prototip üzerinde doğrulama testi yapılmalıdır.\n3. Sahadaki araçlar için servis bildirimi hazırlanmalıdır.\n4. Tasarım FMEA güncellenmelidir.'::text),
  (E'DF-2026-103'::text, E'DF'::text, E'AGA2100aracimizdaki kazan igi elegin késelerindeki aciklik bulunmasi sebebi ile icine giren poset vb malzemeler | fan Gizerine yapisip balansa sebep oluyor aksiyon alinmasi gerekmektedir .'::text, E'Ürün sahada tasarım kaynaklı uygunsuzlukla karşılaşmaktadır.'::text, E'Müşteri kullanım senaryosunda ortaya çıkan hata, tasarım aşamasında öngörülmemiştir.'::text, E'Doğrulama planı (DVP) bu hata modunu kapsamamaktadır.'::text, E'DVP hazırlanırken müşteri kullanım profili ve olası hata modları yeterince tanımlanmamıştır.'::text, E'Tasarım FMEA bu senaryoyu içermemiş ya da düşük risk puanı verilmiştir.'::text, E'Tasarım doğrulama planı müşteri saha koşullarını tam yansıtacak test senaryolarını kapsamayacak biçimde eksik oluşturulmuştur.'::text, E'AGA2100aracimizdaki kazan igi elegin késelerindeki aciklik bulunmasi sebebi ile icine giren poset vb malzemeler | fan Gi'::text, E'Ar-Ge Direktérliigii'::text, E'24.05.2026'::text, E'Kiirsad Atalay'::text, E'Tasarım doğrulama aşamasında bu uygunsuzluk senaryosu yeterince test edilmemiş.'::text, E'Prototip/seri üretim doğrulama testi veya saha geri bildirimi ile tespit edilmiştir.'::text, E'1. Teknik resim revize edilmeli; gerekli tasarım değişikliği MDB ile yayınlanmalıdır.\n2. Prototip üzerinde doğrulama testi yapılmalıdır.\n3. Sahadaki araçlar için servis bildirimi hazırlanmalıdır.\n4. Tasarım FMEA güncellenmelidir.'::text),
  (E'DF-2026-105'::text, E'DF'::text, E'MALIYETKAYDIDETAYLARI | Maliyet Tira: Hurda Maliyeti | Tarih: 09.12.2025 | Birim : Ar-Ge Direktérliigii | Parga Adi: Hiposan PTO Pompa'::text, E'Ürün sahada tasarım kaynaklı uygunsuzlukla karşılaşmaktadır.'::text, E'Müşteri kullanım senaryosunda ortaya çıkan hata, tasarım aşamasında öngörülmemiştir.'::text, E'Doğrulama planı (DVP) bu hata modunu kapsamamaktadır.'::text, E'DVP hazırlanırken müşteri kullanım profili ve olası hata modları yeterince tanımlanmamıştır.'::text, E'Tasarım FMEA bu senaryoyu içermemiş ya da düşük risk puanı verilmiştir.'::text, E'Tasarım doğrulama planı müşteri saha koşullarını tam yansıtacak test senaryolarını kapsamayacak biçimde eksik oluşturulmuştur.'::text, E'MALIYETKAYDIDETAYLARI | Maliyet Tira: Hurda Maliyeti | Tarih: 09.12.2025 | Birim : Ar-Ge Direktérliigii | Parga Adi: Hip'::text, E'Ar-Ge Direktérliigi'::text, E'04.06.2026'::text, E'Kiirgad Atalay'::text, E'Tasarım doğrulama aşamasında bu uygunsuzluk senaryosu yeterince test edilmemiş.'::text, E'Prototip/seri üretim doğrulama testi veya saha geri bildirimi ile tespit edilmiştir.'::text, E'1. Teknik resim revize edilmeli; gerekli tasarım değişikliği MDB ile yayınlanmalıdır.\n2. Prototip üzerinde doğrulama testi yapılmalıdır.\n3. Sahadaki araçlar için servis bildirimi hazırlanmalıdır.\n4. Tasarım FMEA güncellenmelidir.'::text),
  (E'DF-2026-004'::text, E'DF'::text, E'Sayim sonrasinda iiretim planlama tarafindan gerceklestirilen denetimde raflarda kodsuz ve etiketsiz iriinler tespit | edilmistir . | 3. |ILERLEME NOTLARI / YAPILAN CALISMALAR | | Depo Kodsuz iriin icin gerekli galigmalari gergeklestiriyor anit dokiiman yiiklenmistir .'::text, E'Depoya giren ürünlerde etiketleme veya kodlama uygunsuzluğu tespit edilmektedir.'::text, E'Ürünler doğru etiket veya kod olmadan kabul görüp raflara kaldırılmaktadır.'::text, E'Giriş kabul sırasında etiket/kod doğrulama adımı uygulanmamaktadır.'::text, E'Giriş kabul prosedürü bu kontrol adımını zorunlu kılmamakta veya güncel değildir.'::text, E'Personel prosedür gerekliliklerini bilmemekte veya bilinçli bir şekilde atlayabilmektedir.'::text, E'Depo giriş standartları belgelenmemiş; etiketleme hatalarını önleyecek çift kontrol mekanizması (Poka-Yoke) tasarlanmamıştır.'::text, E'Sayim sonrasinda iiretim planlama tarafindan gerceklestirilen denetimde raflarda kodsuz ve etiketsiz iriinler tespit | e'::text, E'Depo'::text, E'15.02.2026'::text, E'Depo'::text, E'Depo giriş kabul sürecinde ürün etiketleme ve kodlama standardı uygulanmamakta'::text, E'Depo rutin sayımı, giriş/çıkış takibi veya saha bildirimi ile tespit edilmiştir.'::text, E'1. Tüm raflardaki kodsuz/etiketsiz ürünler ivedilikle tanımlanmalı, mevcut stoklara etiket/barkod yapıştırılmalıdır.\n2. Depoya giriş kabul prosedürü yazılı hale getirilmeli; \'etiketsiz ürün depoya alınmaz\' kuralı tanımlanmalıdır.\n3. Depo personeline etiketleme ve ürün kodlama eğitimi verilmelidir.\n4. Haftalık depo turu ile etiketsiz ürün kontrolü rutin hale getirilmelidir.'::text),
  (E'DF-2026-005'::text, E'DF'::text, E'Sayim sonrasinda iiretim planiama tarafindan gerceklestirilen denetimde motor stoklama alani dis etkenlere acik | ve uygunsuz olarak tespit edilmistir .'::text, E'Depoda yanlış veya yetersiz stoklama nedeniyle ürünler hasar görmekte ya da kaybolmaktadır.'::text, E'Ürünler açık alanda veya uygun olmayan koşullarda bekletilmektedir.'::text, E'Raf sistemi yetersiz veya ürün türüne göre düzenlenmemiştir.'::text, E'Depo yerleşim planı (layout) hazırlanmamış ya da güncel değildir.'::text, E'Depo kapasite/altyapı ihtiyacı periyodik olarak değerlendirilmemektedir.'::text, E'Stok saklama standartları (nem, sıcaklık, raf tipi, dış alan kullanımı) yazılı prosedürle tanımlanmamış ve izlenmemektedir.'::text, E'Sayim sonrasinda iiretim planiama tarafindan gerceklestirilen denetimde motor stoklama alani dis etkenlere acik | ve uyg'::text, E'Depo'::text, E'01.06.2026'::text, E'Sinan Acar'::text, E'Depo stoklama alanı fiziksel düzenlemesi yetersiz'::text, E'Depo rutin sayımı, giriş/çıkış takibi veya saha bildirimi ile tespit edilmiştir.'::text, E'1. Motor ve büyük parça stoklama alanı kapalı veya örtülü hale getirilmeli; palet/raf düzenlemesi yapılmalıdır.\n2. Açık alana alınan ürünler için branda/koruyucu örtü kullanımı zorunlu hale getirilmelidir.\n3. Raf ve depolama sistemi kapasitesi gözden geçirilmeli; ihtiyaç halinde ek raf talep edilmelidir.\n4. Depo düzeni fotoğraflanarak referans düzen oluşturulmalı; 5S uygulaması başlatılmalıdır.'::text),
  (E'DF-2026-006'::text, E'DF'::text, E'Sayim sonrasinda iiretim planlama tarafindan gerceklestirilen denetimde rextrothlar zeminde ve depolama | y6ntemi uygunsuz olarak tespit edilmistir .'::text, E'Depoda yanlış veya yetersiz stoklama nedeniyle ürünler hasar görmekte ya da kaybolmaktadır.'::text, E'Ürünler açık alanda veya uygun olmayan koşullarda bekletilmektedir.'::text, E'Raf sistemi yetersiz veya ürün türüne göre düzenlenmemiştir.'::text, E'Depo yerleşim planı (layout) hazırlanmamış ya da güncel değildir.'::text, E'Depo kapasite/altyapı ihtiyacı periyodik olarak değerlendirilmemektedir.'::text, E'Stok saklama standartları (nem, sıcaklık, raf tipi, dış alan kullanımı) yazılı prosedürle tanımlanmamış ve izlenmemektedir.'::text, E'Sayim sonrasinda iiretim planlama tarafindan gerceklestirilen denetimde rextrothlar zeminde ve depolama | y6ntemi uyguns'::text, E'Depo'::text, E'01.06.2026'::text, E'Sinan Acar'::text, E'Depo stoklama alanı fiziksel düzenlemesi yetersiz'::text, E'Depo rutin sayımı, giriş/çıkış takibi veya saha bildirimi ile tespit edilmiştir.'::text, E'1. Motor ve büyük parça stoklama alanı kapalı veya örtülü hale getirilmeli; palet/raf düzenlemesi yapılmalıdır.\n2. Açık alana alınan ürünler için branda/koruyucu örtü kullanımı zorunlu hale getirilmelidir.\n3. Raf ve depolama sistemi kapasitesi gözden geçirilmeli; ihtiyaç halinde ek raf talep edilmelidir.\n4. Depo düzeni fotoğraflanarak referans düzen oluşturulmalı; 5S uygulaması başlatılmalıdır.'::text),
  (E'DF-2026-007'::text, E'DF'::text, E'Sayim sonrasinda iiretim planlama tarafindan gerceklestirilen denetimde Ax stoklari ve fiziki stoklarin uyusmadigi | igin uygunsuz olarak tespit edilmistir . | 3. |ILERLEME NOTLARI / YAPILAN CALISMALAR | | Gerekli sayim detaylan paylasilmig ve kanit dokiiman yiiklenmistir .'::text, E'ERP (AX) sistemindeki stok bilgisi ile fiziksel sayım arasında fark bulunmaktadır.'::text, E'Sistem üzerindeki stok miktarı gerçeği yansıtmamaktadır.'::text, E'Giriş/çıkış hareketleri sisteme zamanında veya doğru şekilde işlenmemektedir.'::text, E'AX sistemi üzerinde stok hareketi kayıt prosedürü çalışanlar tarafından tam uygulanmamaktadır.'::text, E'Eğitim yetersiz veya prosedür anlaşılır/erişilebilir değildir.'::text, E'Stok doğruluğunu garanti edecek periyodik sayım (cycle count) planı ve sapma kök neden analiz rutini oluşturulmamıştır.'::text, E'Sayim sonrasinda iiretim planlama tarafindan gerceklestirilen denetimde Ax stoklari ve fiziki stoklarin uyusmadigi | igi'::text, E'Depo'::text, E'15.02.2026'::text, E'‘Sinan Acar'::text, E'AX (ERP) sistemindeki kayıt ile fiziksel stok arasındaki fark'::text, E'Depo rutin sayımı, giriş/çıkış takibi veya saha bildirimi ile tespit edilmiştir.'::text, E'1. Fiziksel sayım sonuçları ile AX kayıtları karşılaştırılmalı; farkların kaynağı tespit edilerek sistem kayıtları düzeltilmelidir.\n2. Parti numarasına göre fiziksel ayrımlı depolama uygulaması başlatılmalıdır.\n3. Ay sonu stok sayım prosedürü oluşturulmalı; sorumlular belirlenmeli ve takip edilmelidir.\n4. Depo giriş/çıkış hareketlerinin sisteme anlık kaydedilmesi için personel eğitimi verilmelidir.'::text),
  (E'DF-2026-008'::text, E'DF'::text, E'Sayim sonrasinda iiretim planlama tarafindan gerceklestirilen denetimde , Ax kayitlarinda parti numaralarina gére | depolama yapilirken , fiziki depolarda parti numarasi ayrimi yapilmadigi uygunsuz olarak tespit edilmistir'::text, E'ERP (AX) sistemindeki stok bilgisi ile fiziksel sayım arasında fark bulunmaktadır.'::text, E'Sistem üzerindeki stok miktarı gerçeği yansıtmamaktadır.'::text, E'Giriş/çıkış hareketleri sisteme zamanında veya doğru şekilde işlenmemektedir.'::text, E'AX sistemi üzerinde stok hareketi kayıt prosedürü çalışanlar tarafından tam uygulanmamaktadır.'::text, E'Eğitim yetersiz veya prosedür anlaşılır/erişilebilir değildir.'::text, E'Stok doğruluğunu garanti edecek periyodik sayım (cycle count) planı ve sapma kök neden analiz rutini oluşturulmamıştır.'::text, E'Sayim sonrasinda iiretim planlama tarafindan gerceklestirilen denetimde , Ax kayitlarinda parti numaralarina gére | depo'::text, E'Depo'::text, E'01.06.2026'::text, E'Sinan Acar'::text, E'AX (ERP) sistemindeki kayıt ile fiziksel stok arasındaki fark'::text, E'Depo rutin sayımı, giriş/çıkış takibi veya saha bildirimi ile tespit edilmiştir.'::text, E'1. Fiziksel sayım sonuçları ile AX kayıtları karşılaştırılmalı; farkların kaynağı tespit edilerek sistem kayıtları düzeltilmelidir.\n2. Parti numarasına göre fiziksel ayrımlı depolama uygulaması başlatılmalıdır.\n3. Ay sonu stok sayım prosedürü oluşturulmalı; sorumlular belirlenmeli ve takip edilmelidir.\n4. Depo giriş/çıkış hareketlerinin sisteme anlık kaydedilmesi için personel eğitimi verilmelidir.'::text),
  (E'DF-2026-009'::text, E'DF'::text, E'Sayim sonrasinda iiretim planlama tarafindan gerceklestirilen denetimde Ax kayitlarinda bulunan 0 genel konumu | fiziki olarak bulunmamaktadir .0 genel konumunda bulunan iriinler hatali ,bekleyen , teslim alinmamis triinler | oldugu uygunsuz olarak tespit edilmistir .'::text, E'ERP (AX) sistemindeki stok bilgisi ile fiziksel sayım arasında fark bulunmaktadır.'::text, E'Sistem üzerindeki stok miktarı gerçeği yansıtmamaktadır.'::text, E'Giriş/çıkış hareketleri sisteme zamanında veya doğru şekilde işlenmemektedir.'::text, E'AX sistemi üzerinde stok hareketi kayıt prosedürü çalışanlar tarafından tam uygulanmamaktadır.'::text, E'Eğitim yetersiz veya prosedür anlaşılır/erişilebilir değildir.'::text, E'Stok doğruluğunu garanti edecek periyodik sayım (cycle count) planı ve sapma kök neden analiz rutini oluşturulmamıştır.'::text, E'Sayim sonrasinda iiretim planlama tarafindan gerceklestirilen denetimde Ax kayitlarinda bulunan 0 genel konumu | fiziki'::text, E'Depo'::text, E'15.05.2026'::text, E'Sinan Acar'::text, E'AX (ERP) sistemindeki kayıt ile fiziksel stok arasındaki fark'::text, E'Depo rutin sayımı, giriş/çıkış takibi veya saha bildirimi ile tespit edilmiştir.'::text, E'1. Fiziksel sayım sonuçları ile AX kayıtları karşılaştırılmalı; farkların kaynağı tespit edilerek sistem kayıtları düzeltilmelidir.\n2. Parti numarasına göre fiziksel ayrımlı depolama uygulaması başlatılmalıdır.\n3. Ay sonu stok sayım prosedürü oluşturulmalı; sorumlular belirlenmeli ve takip edilmelidir.\n4. Depo giriş/çıkış hareketlerinin sisteme anlık kaydedilmesi için personel eğitimi verilmelidir.'::text),
  (E'DF-2026-020'::text, E'DF'::text, E'Misterimiz tarafindan iletilen ve ekte yer alan gérseller incelendiginde , KADEMEtarafindan sevk edilen son 2 | adet Ural araci Gzerinde asagida belirtilen sevkiyat kaynakli uygunsuzluklar tespit edilmistir : | Gévde saclari ve sasi tizeri boyali yiizeylerde carpma , siirtme ve lokal boya hasarlar! , | KADEMEisim plakasinin (name plate) hasar gérdiigii / deforme oldugu , | Arag izerindeki ikaz lambalarindan birinin kirik oldugu (misteri , detay igin Engr. Ahmed ile iletisime gecilmesini'::text, E'Depo operasyonlarında standardı olmayan uygulamalar ve tekrarlayan hatalar yaşanmaktadır.'::text, E'Personel işlemleri kendi inisiyatifine göre yapmakta, standart bir yol izlememektedir.'::text, E'Hangi işlemin nasıl yapılacağına dair güncel ve erişilebilir talimat mevcut değildir.'::text, E'Mevcut prosedürler son değişiklikleri yansıtmayacak kadar eskidir veya hiç yazılmamıştır.'::text, E'Prosedür güncelleme sorumluluğu sahiplenilmemekte; periyodik gözden geçirme yapılmamaktadır.'::text, E'Depo süreçleri için bir dokümantasyon yönetim planı (revizyon periyodu, onay mekanizması) oluşturulmamıştır.'::text, E'Misterimiz tarafindan iletilen ve ekte yer alan gérseller incelendiginde , KADEMEtarafindan sevk edilen son 2 | adet Ura'::text, E'Depo'::text, E'20.02.2026'::text, E'‘Sinan Acar'::text, E'Depo yönetim prosedürü eksik veya güncel değil'::text, E'Depo rutin sayımı, giriş/çıkış takibi veya saha bildirimi ile tespit edilmiştir.'::text, E'1. İlgili uygunsuzluk için yazılı prosedür/talimat oluşturulmalı veya güncellenmeli; depo personeline iletilmelidir.\n2. Haftalık depo kontrol turu uygulanmalı; bulgular kayıt altına alınmalıdır.\n3. Depo personeline yönlendirici eğitim verilmeli ve eğitim kaydı tutulmalıdır.\n4. 5S uygulaması kapsamında depo düzenlemesi yapılmalıdır.'::text)
  ) AS t(nc_number, typ, problem_def, symptom, why1, why2, why3, why4, why5, ne, nerede, ne_zaman, kim, neden, nasil, actions_text)
)
UPDATE non_conformities n
SET
  five_n1k_analysis = jsonb_build_object(
    'ne', to_jsonb(x.ne),
    'nerede', to_jsonb(x.nerede),
    'neZaman', to_jsonb(x.ne_zaman),
    'kim', to_jsonb(x.kim),
    'neden', to_jsonb(x.neden),
    'nasil', to_jsonb(x.nasil)
  ),
  five_why_analysis = jsonb_build_object(
    'problem', to_jsonb(x.problem_def),
    'why1', to_jsonb(x.why1),
    'why2', to_jsonb(x.why2),
    'why3', to_jsonb(x.why3),
    'why4', to_jsonb(x.why4),
    'why5', to_jsonb(x.why5),
    'rootCause', to_jsonb(x.why5),
    'immediateAction', to_jsonb(x.neden),
    'preventiveAction', to_jsonb(x.actions_text)
  ),
  eight_d_steps = CASE
    WHEN n.type = '8D' THEN
      jsonb_set(
        jsonb_set(
          COALESCE(n.eight_d_steps, '{}'::jsonb),
          '{D4,description}',
          to_jsonb(
            ('5 Neden (özet)'::text || E'\n\n' ||
             '1. ' || x.why1 || E'\n' ||
             '2. ' || x.why2 || E'\n' ||
             '3. ' || x.why3 || E'\n' ||
             '4. ' || x.why4 || E'\n' ||
             '5 (Kök): ' || x.why5)::text
          ),
          true
        ),
        '{D5,description}',
        to_jsonb(('Önerilen düzeltici faaliyetler'::text || E'\n\n' || x.actions_text)::text),
        true
      )
    ELSE n.eight_d_steps
  END,
  updated_at = now()
FROM x
WHERE n.nc_number = x.nc_number AND n.type = x.typ;
