WITH x AS (
  SELECT * FROM (VALUES
  (E'DF-2026-093'::text, E'DF'::text, E'GIRDi KALITEKONTROLU- UYGUNSUZLUKTESPITIMUAYENEBILGILERI Kayit No: 26/04/031 Muayene Tarihi: | 07.04.2026 Tedarikci: Uzcelik Makina Sanayi Tic. Ltd. Sti. Parga Adi: Sispansiyon Kollektérii Parga Kodu: 37- | 5000164878 Gelen Miktar : 24 adet Kontrol Edilen Miktar : 24 adet Nihai Karar: Ret OLGCUM SONUCLARIVE | TESPITLEROLCGUM OZETI Toplam Olcgiim Sayist 36 Uygun Olgiimler : 0 Uygunsuz Olcti | Ee eae edd na a Sua alas'::text, E'Tedarikçiden gelen parçalarda boyutsal, görsel veya fonksiyonel uygunsuzluk tespit edilmektedir.'::text, E'Muayenede uygunsuz parçalar, sevkiyattan önce tedarikçi tarafından eleneememektedir.'::text, E'Tedarikçi çıkış kontrol noktasında kritik karakteristikler ölçülmemekte ya da kayıt tutulmamaktadır.'::text, E'Kontrol planında kritik karakteristikler tanımlanmamış veya güncel değildir.'::text, E'Tedarikçi ile yapılan teknik toplantıda kritik özellikler yeterince vurgulanmamış, kontrol planı birlikte gözden geçirilmemiştir.'::text, E'Tedarikçi geliştirme/onay sürecinde ürün kalite planı (PPAP/APQP vb.) gerektiği düzeyde oluşturulmamış ve denetlenmemiştir.'::text, E'GIRDi KALITEKONTROLU- UYGUNSUZLUKTESPITIMUAYENEBILGILERI Kayit No: 26/04/031 Muayene Tarihi: | 07.04.2026 Tedarikci: Uzc'::text, E'Tedarikgi'::text, E'07.05.2026'::text, E'Tedarikgi'::text, E'Tedarikçi üretim sürecinde boyutsal/görsel/fonksiyonel kalite kontrol yeterli düzeyde uygulanmamaktadır. Kontrol planınd…'::text, E'GKK (Girdi Kalite Kontrol) muayenesinde veya saha geri bildirimi ile tespit edilmiştir.'::text, E'1. Uygunsuz \'Sispansiyon Kollektérii Parga Kodu: 37-\' partisi tedarikçiye iade edilmeli veya karantinaya alınmalıdır.\n2. Tedarikçiye DF-2026-093 numaralı DF kaydı iletilmeli, 15 iş günü içinde yazılı kök neden analizi ve düzeltici aksiyon planı talep edilmelidir.\n3. Tedarikçinin kontrol planı incelenmeli; kritik boyutlar ve kabul kriterleri yeniden belirlenmeli, onaylı kontrol planı alınmalıdır.\n4. Aynı tedarikçiden tekrarlayan uygunsuzluk varsa tedarikçi performans puanı düşürülmeli, alternatif tedarikçi değerlendirmesi başlatılmalıdır.'::text),
  (E'DF-2026-094'::text, E'DF'::text, E'GIRDIKALITEKONTROLU- UYGUNSUZLUKTESPITIMUAYENEBILGILERI Kayit No: 26/04/036 Muayene Tarihi: | 08.04.2026 Tedarikci : Ozkan Makine Ltd. Sti. Parga Adi: Sag Su Deposu Alt Baglanti Parga Kodu: 37-5000151418 | Gelen Miktar : 5 adet Kontrol Edilen Miktar : 5 adet Nihai Karar: Ret OLCUM SONUCLARIVE TESPITLERUYGUNSUZ | BULUNAN OLCUMLER Fonksiyonel Ozellik (Olgiim 1/1): Beklenen Deger (Nomin | Ee eae edd na a Sua alas'::text, E'Tedarikçiden gelen parçalarda boyutsal, görsel veya fonksiyonel uygunsuzluk tespit edilmektedir.'::text, E'Muayenede uygunsuz parçalar, sevkiyattan önce tedarikçi tarafından eleneememektedir.'::text, E'Tedarikçi çıkış kontrol noktasında kritik karakteristikler ölçülmemekte ya da kayıt tutulmamaktadır.'::text, E'Kontrol planında kritik karakteristikler tanımlanmamış veya güncel değildir.'::text, E'Tedarikçi ile yapılan teknik toplantıda kritik özellikler yeterince vurgulanmamış, kontrol planı birlikte gözden geçirilmemiştir.'::text, E'Tedarikçi geliştirme/onay sürecinde ürün kalite planı (PPAP/APQP vb.) gerektiği düzeyde oluşturulmamış ve denetlenmemiştir.'::text, E'GIRDIKALITEKONTROLU- UYGUNSUZLUKTESPITIMUAYENEBILGILERI Kayit No: 26/04/036 Muayene Tarihi: | 08.04.2026 Tedarikci : Ozk'::text, E'Tedarikgi'::text, E'08.05.2026'::text, E'Tedarikgi'::text, E'Tedarikçi üretim sürecinde boyutsal/görsel/fonksiyonel kalite kontrol yeterli düzeyde uygulanmamaktadır. Kontrol planınd…'::text, E'GKK (Girdi Kalite Kontrol) muayenesinde veya saha geri bildirimi ile tespit edilmiştir.'::text, E'1. Uygunsuz \'Sag Su Deposu Alt Baglanti Parga Kodu: 37-5000151418\' partisi tedarikçiye iade edilmeli veya karantinaya alınmalıdır.\n2. Tedarikçiye DF-2026-094 numaralı DF kaydı iletilmeli, 15 iş günü içinde yazılı kök neden analizi ve düzeltici aksiyon planı talep edilmelidir.\n3. Tedarikçinin kontrol planı incelenmeli; kritik boyutlar ve kabul kriterleri yeniden belirlenmeli, onaylı kontrol planı alınmalıdır.\n4. Aynı tedarikçiden tekrarlayan uygunsuzluk varsa tedarikçi performans puanı düşürülmeli, alternatif tedarikçi değerlendirmesi başlatılmalıdır.'::text),
  (E'DF-2026-095'::text, E'DF'::text, E'GIRDi KALITEKONTROLU- UYGUNSUZLUKTESPITIMUAYENEBILGILERI Kayit No: 26/04/037 Muayene Tarihi: | 08.04.2026 Tedarikci: Ozkan Makine Ltd. Sti. Parga Adi: Sol Su Deposu Alt Kapak Baglantisi Parga Kodu: 37- | 5000151421 Gelen Miktar :5 adet Kontrol Edilen Miktar : 5 adet Nihai Karar: Ret OLCUMSONUCLARIVETESPITLER | UYGUNSUZBULUNAN OLGUMLER Minér Ozellik (Olgiim 1/1): Beklenen Deger (Nom | Ee eae edd na a Sua alas'::text, E'Tedarikçiden gelen parçalarda boyutsal, görsel veya fonksiyonel uygunsuzluk tespit edilmektedir.'::text, E'Muayenede uygunsuz parçalar, sevkiyattan önce tedarikçi tarafından eleneememektedir.'::text, E'Tedarikçi çıkış kontrol noktasında kritik karakteristikler ölçülmemekte ya da kayıt tutulmamaktadır.'::text, E'Kontrol planında kritik karakteristikler tanımlanmamış veya güncel değildir.'::text, E'Tedarikçi ile yapılan teknik toplantıda kritik özellikler yeterince vurgulanmamış, kontrol planı birlikte gözden geçirilmemiştir.'::text, E'Tedarikçi geliştirme/onay sürecinde ürün kalite planı (PPAP/APQP vb.) gerektiği düzeyde oluşturulmamış ve denetlenmemiştir.'::text, E'GIRDi KALITEKONTROLU- UYGUNSUZLUKTESPITIMUAYENEBILGILERI Kayit No: 26/04/037 Muayene Tarihi: | 08.04.2026 Tedarikci: Ozk'::text, E'Tedarikgi'::text, E'08.05.2026'::text, E'Tedarikgi'::text, E'Tedarikçi üretim sürecinde boyutsal/görsel/fonksiyonel kalite kontrol yeterli düzeyde uygulanmamaktadır. Kontrol planınd…'::text, E'GKK (Girdi Kalite Kontrol) muayenesinde veya saha geri bildirimi ile tespit edilmiştir.'::text, E'1. Uygunsuz \'Sol Su Deposu Alt Kapak Baglantisi Parga Kodu: 37-\' partisi tedarikçiye iade edilmeli veya karantinaya alınmalıdır.\n2. Tedarikçiye DF-2026-095 numaralı DF kaydı iletilmeli, 15 iş günü içinde yazılı kök neden analizi ve düzeltici aksiyon planı talep edilmelidir.\n3. Tedarikçinin kontrol planı incelenmeli; kritik boyutlar ve kabul kriterleri yeniden belirlenmeli, onaylı kontrol planı alınmalıdır.\n4. Aynı tedarikçiden tekrarlayan uygunsuzluk varsa tedarikçi performans puanı düşürülmeli, alternatif tedarikçi değerlendirmesi başlatılmalıdır.'::text),
  (E'DF-2026-096'::text, E'DF'::text, E'GIRDi KALITEKONTROLU- UYGUNSUZLUKTESPITIMUAYENEBILGILERI Kayit No: 26/04/055 Muayene Tarihi: | 09.04.2026 Tedarikgi: Ozkan Makine Ltd. Sti. Parga Adi: Filtre Haznesi On Kapak Komple Parga Kodu: 37- | 5000202103 Gelen Miktar : 1 adet Kontrol Edilen Miktar : 1 adet Nihai Karar: Sartli Kabul OLGUM SONUCLARIVE | TESPITLERUYGUNSUZBULUNAN OLGUMLER Minér Ozellik (Olgiim 1/1): Beklenen Deger'::text, E'Tedarikçiden gelen parçalarda boyutsal, görsel veya fonksiyonel uygunsuzluk tespit edilmektedir.'::text, E'Muayenede uygunsuz parçalar, sevkiyattan önce tedarikçi tarafından eleneememektedir.'::text, E'Tedarikçi çıkış kontrol noktasında kritik karakteristikler ölçülmemekte ya da kayıt tutulmamaktadır.'::text, E'Kontrol planında kritik karakteristikler tanımlanmamış veya güncel değildir.'::text, E'Tedarikçi ile yapılan teknik toplantıda kritik özellikler yeterince vurgulanmamış, kontrol planı birlikte gözden geçirilmemiştir.'::text, E'Tedarikçi geliştirme/onay sürecinde ürün kalite planı (PPAP/APQP vb.) gerektiği düzeyde oluşturulmamış ve denetlenmemiştir.'::text, E'GIRDi KALITEKONTROLU- UYGUNSUZLUKTESPITIMUAYENEBILGILERI Kayit No: 26/04/055 Muayene Tarihi: | 09.04.2026 Tedarikgi: Ozk'::text, E'Tedarikgi'::text, E'09.05.2026'::text, E'Tedarikgi'::text, E'Tedarikçi üretim sürecinde boyutsal/görsel/fonksiyonel kalite kontrol yeterli düzeyde uygulanmamaktadır. Kontrol planınd…'::text, E'GKK (Girdi Kalite Kontrol) muayenesinde veya saha geri bildirimi ile tespit edilmiştir.'::text, E'1. Uygunsuz \'Filtre Haznesi On Kapak Komple Parga Kodu: 37-\' partisi tedarikçiye iade edilmeli veya karantinaya alınmalıdır.\n2. Tedarikçiye DF-2026-096 numaralı DF kaydı iletilmeli, 15 iş günü içinde yazılı kök neden analizi ve düzeltici aksiyon planı talep edilmelidir.\n3. Tedarikçinin kontrol planı incelenmeli; kritik boyutlar ve kabul kriterleri yeniden belirlenmeli, onaylı kontrol planı alınmalıdır.\n4. Aynı tedarikçiden tekrarlayan uygunsuzluk varsa tedarikçi performans puanı düşürülmeli, alternatif tedarikçi değerlendirmesi başlatılmalıdır.'::text),
  (E'DF-2026-097'::text, E'DF'::text, E'GIRDIKALITEKONTROLU- UYGUNSUZLUKTESPITIMUAYENEBILGILERI Kayit No: 26/04/059 Muayene Tarihi: | 09.04.2026 Tedarikgi : Saytek Tasarim Mak.kal.kons Parga Adi: Ara Yataklama Mili Parga Kodu: 37-5000189111 Gelen | Miktar : 1 adet Kontrol Edilen Miktar : 1 adet Nihai Karar: Ret OLCUM SONUCLARIVE TESPITLEROLGUM OZETI: | Toplam Olgiim Sayist 5 Uygun Olgiimler : 0 Uygunsuz Olgiimler : 5 Ret Ora'::text, E'Tedarikçiden gelen parçalarda boyutsal, görsel veya fonksiyonel uygunsuzluk tespit edilmektedir.'::text, E'Muayenede uygunsuz parçalar, sevkiyattan önce tedarikçi tarafından eleneememektedir.'::text, E'Tedarikçi çıkış kontrol noktasında kritik karakteristikler ölçülmemekte ya da kayıt tutulmamaktadır.'::text, E'Kontrol planında kritik karakteristikler tanımlanmamış veya güncel değildir.'::text, E'Tedarikçi ile yapılan teknik toplantıda kritik özellikler yeterince vurgulanmamış, kontrol planı birlikte gözden geçirilmemiştir.'::text, E'Tedarikçi geliştirme/onay sürecinde ürün kalite planı (PPAP/APQP vb.) gerektiği düzeyde oluşturulmamış ve denetlenmemiştir.'::text, E'GIRDIKALITEKONTROLU- UYGUNSUZLUKTESPITIMUAYENEBILGILERI Kayit No: 26/04/059 Muayene Tarihi: | 09.04.2026 Tedarikgi : Say'::text, E'Tedarikgi'::text, E'09.05.2026'::text, E'Tedarikgi'::text, E'Tedarikçi üretim sürecinde boyutsal/görsel/fonksiyonel kalite kontrol yeterli düzeyde uygulanmamaktadır. Kontrol planınd…'::text, E'GKK (Girdi Kalite Kontrol) muayenesinde veya saha geri bildirimi ile tespit edilmiştir.'::text, E'1. Uygunsuz \'Ara Yataklama Mili Parga Kodu: 37-5000189111 Gelen\' partisi tedarikçiye iade edilmeli veya karantinaya alınmalıdır.\n2. Tedarikçiye DF-2026-097 numaralı DF kaydı iletilmeli, 15 iş günü içinde yazılı kök neden analizi ve düzeltici aksiyon planı talep edilmelidir.\n3. Tedarikçinin kontrol planı incelenmeli; kritik boyutlar ve kabul kriterleri yeniden belirlenmeli, onaylı kontrol planı alınmalıdır.\n4. Aynı tedarikçiden tekrarlayan uygunsuzluk varsa tedarikçi performans puanı düşürülmeli, alternatif tedarikçi değerlendirmesi başlatılmalıdır.'::text),
  (E'DF-2026-098'::text, E'DF'::text, E'GIRDIKALITEKONTROLU- UYGUNSUZLUKTESPITIMUAYENEBILGILERI Kayit No: 26/04/065 Muayene Tarihi: | 13.04.2026 Tedarikgi : Uzgelik Makine Ltd. $ti. Parga Adi: Sag Rad Kolu Parga Kodu: 37-5000143947 Gelen Miktar : 3 | adet Kontrol Edilen Miktar : 3 adet Nihai Karar: Ret OLCUM SONUCLARIVE TESPITLERUYGUNSUZBULUNAN | OLCUMLER Fonksiyonel Ozellik (Olgtim 1/1): Beklenen Deger (Nominal ): 17,50 m'::text, E'Tedarikçiden gelen parçalarda boyutsal, görsel veya fonksiyonel uygunsuzluk tespit edilmektedir.'::text, E'Muayenede uygunsuz parçalar, sevkiyattan önce tedarikçi tarafından eleneememektedir.'::text, E'Tedarikçi çıkış kontrol noktasında kritik karakteristikler ölçülmemekte ya da kayıt tutulmamaktadır.'::text, E'Kontrol planında kritik karakteristikler tanımlanmamış veya güncel değildir.'::text, E'Tedarikçi ile yapılan teknik toplantıda kritik özellikler yeterince vurgulanmamış, kontrol planı birlikte gözden geçirilmemiştir.'::text, E'Tedarikçi geliştirme/onay sürecinde ürün kalite planı (PPAP/APQP vb.) gerektiği düzeyde oluşturulmamış ve denetlenmemiştir.'::text, E'GIRDIKALITEKONTROLU- UYGUNSUZLUKTESPITIMUAYENEBILGILERI Kayit No: 26/04/065 Muayene Tarihi: | 13.04.2026 Tedarikgi : Uzg'::text, E'Tedarikgi'::text, E'13.05.2026'::text, E'Tedarikgi'::text, E'Tedarikçi üretim sürecinde boyutsal/görsel/fonksiyonel kalite kontrol yeterli düzeyde uygulanmamaktadır. Kontrol planınd…'::text, E'GKK (Girdi Kalite Kontrol) muayenesinde veya saha geri bildirimi ile tespit edilmiştir.'::text, E'1. Uygunsuz \'Sag Rad Kolu Parga Kodu: 37-5000143947 Gelen Miktar : 3\' partisi tedarikçiye iade edilmeli veya karantinaya alınmalıdır.\n2. Tedarikçiye DF-2026-098 numaralı DF kaydı iletilmeli, 15 iş günü içinde yazılı kök neden analizi ve düzeltici aksiyon planı talep edilmelidir.\n3. Tedarikçinin kontrol planı incelenmeli; kritik boyutlar ve kabul kriterleri yeniden belirlenmeli, onaylı kontrol planı alınmalıdır.\n4. Aynı tedarikçiden tekrarlayan uygunsuzluk varsa tedarikçi performans puanı düşürülmeli, alternatif tedarikçi değerlendirmesi başlatılmalıdır.'::text),
  (E'DF-2026-101'::text, E'DF'::text, E'GIRD/ KALITEKONTROLU- UYGUNSUZLUKTESPITI | MUAYENEBILGILERI | Kayit No: 26/04/104 | Muayene Tarihi: 24.04.2026 | Tedarikgi: Ozkan Makine Ltd. Sti.'::text, E'Tedarikçiden gelen parçalarda boyutsal, görsel veya fonksiyonel uygunsuzluk tespit edilmektedir.'::text, E'Muayenede uygunsuz parçalar, sevkiyattan önce tedarikçi tarafından eleneememektedir.'::text, E'Tedarikçi çıkış kontrol noktasında kritik karakteristikler ölçülmemekte ya da kayıt tutulmamaktadır.'::text, E'Kontrol planında kritik karakteristikler tanımlanmamış veya güncel değildir.'::text, E'Tedarikçi ile yapılan teknik toplantıda kritik özellikler yeterince vurgulanmamış, kontrol planı birlikte gözden geçirilmemiştir.'::text, E'Tedarikçi geliştirme/onay sürecinde ürün kalite planı (PPAP/APQP vb.) gerektiği düzeyde oluşturulmamış ve denetlenmemiştir.'::text, E'GIRD/ KALITEKONTROLU- UYGUNSUZLUKTESPITI | MUAYENEBILGILERI | Kayit No: 26/04/104 | Muayene Tarihi: 24.04.2026 | Tedarik'::text, E'Tedarikgi'::text, E'24.05.2026'::text, E'Tedarikgi'::text, E'Tedarikçi üretim sürecinde boyutsal/görsel/fonksiyonel kalite kontrol yeterli düzeyde uygulanmamaktadır. Kontrol planınd…'::text, E'GKK (Girdi Kalite Kontrol) muayenesinde veya saha geri bildirimi ile tespit edilmiştir.'::text, E'1. Uygunsuz \'Firca Baglanti Flansi\' partisi tedarikçiye iade edilmeli veya karantinaya alınmalıdır.\n2. Tedarikçiye DF-2026-101 numaralı DF kaydı iletilmeli, 15 iş günü içinde yazılı kök neden analizi ve düzeltici aksiyon planı talep edilmelidir.\n3. Tedarikçinin kontrol planı incelenmeli; kritik boyutlar ve kabul kriterleri yeniden belirlenmeli, onaylı kontrol planı alınmalıdır.\n4. Aynı tedarikçiden tekrarlayan uygunsuzluk varsa tedarikçi performans puanı düşürülmeli, alternatif tedarikçi değerlendirmesi başlatılmalıdır.'::text),
  (E'DF-2026-015'::text, E'DF'::text, E'55 KWperkins motorlarda 190 lik pompa kullanilmasi ile ilgili daha 6nce MDB yayinlanmis fakat dretim bu MDB | uymadan 160 lik pompa kullanmaya devam etmistir . Konuyla ilgili aksiyon alinmasi gerekmektedir . | 3. |ILERLEME NOTLARI / YAPILAN CALISMALAR | | kalite kontrol tarafindan kontrol planina eklendi . Montaj hatt! wsapp grubundan konu hakkinda bilgilendirme mesaji yayinlandi'::text, E'Yayınlanan MDB (Mühendislik Değişiklik Bildirimi) üretime uygulanamamıştır.'::text, E'Üretim hattı değişiklikten haberdar olmuş; ancak eski yöntemi uygulamaya devam etmiştir.'::text, E'MDB talimatı üretim talimatına ve hat üstü görsel rehbere yansıtılmamıştır.'::text, E'MDB yayınlandıktan sonra üretim talimatı güncelleme ve hat bilgilendirme adımları takip edilmemiştir.'::text, E'MDB uygulanabilirlik takibi için sorumlu bir kişi/ekip tanımlanmamıştır.'::text, E'Mühendislik değişikliklerinin üretime entegrasyonu için kapalı döngü takip süreci (ECR→ECN→üretim talimatı güncelleme→eğitim) kurulmamıştır.'::text, E'55 KWperkins motorlarda 190 lik pompa kullanilmasi ile ilgili daha 6nce MDB yayinlanmis fakat dretim bu MDB | uymadan 16'::text, E'Uretim'::text, E'28.02.2026'::text, E'Uretim'::text, E'Yayınlanan MDB (Mühendislik Değişiklik Bildirimi) talimatına üretim hattı uyum sağlamamış'::text, E'Üretim hattı kontrol noktası, ara ürün muayenesi veya son kontrol sırasında tespit edilmiştir.'::text, E'1. Üretim hattındaki tüm operatörlere 55 kW Perkins motor için 190\'lık pompa kullanım zorunluluğu acilen iletilmeli; MDB bildirimi imzalatılmalıdır.\n2. Üretimde kullanılan mevcut 160\'lık pompalar stoktan çekilmeli; yerine 190\'lık pompalar konulmalıdır.\n3. MDB uygulama takip mekanizması oluşturulmalı; yayınlanan her MDB için üretim hattı liderinden onay alınması prosedürü başlatılmalıdır.\n4. Değişiklik öncesi 160\'lık pompa ile üretilmiş araçlar için geri dönük muayene yapılmalı; gerekirse pompa değişimi planlanmalıdır.'::text),
  (E'DF-2026-028'::text, E'DF'::text, E'Firmamiz biinyesinde iretilen araglarimizin hepsinde mavi dosya olmasi gereklidir . Dosyalarin eksikligi tespit | edilmis konuyla ilgili aksiyon alinmasi gerekmektedir . | 3. |ILERLEME NOTLARI / YAPILAN CALISMALAR | | Dosyalar olusturulmaya baslamistir.'::text, E'Araç üretim takip dosyaları (mavi dosya) oluşturulmamakta veya eksik bırakılmaktadır.'::text, E'Dosya oluşturma görevi düzenli olarak atlanmaktadır.'::text, E'Dosyayı kimin, ne zaman oluşturacağı net olarak belirlenmemiştir.'::text, E'Bu görev iş tanımlarına ve üretim akış planına dahil edilmemiştir.'::text, E'Süreç başında sorumluluk dağılımı gözden geçirilmemekte; atlamalar fark edilmemektedir.'::text, E'Araç üretim sürecindeki belgelerle ilgili sorumluluk ve kontrol mekanizması (checklist/poka-yoke) tanımlanmamıştır.'::text, E'Firmamiz biinyesinde iretilen araglarimizin hepsinde mavi dosya olmasi gereklidir . Dosyalarin eksikligi tespit | edilmi'::text, E'Üretim Planlama'::text, E'05.03.2026'::text, E'Ahmet Kalipgi'::text, E'Araç üretim takip dosyalarının (mavi dosya) oluşturulması için tanımlanmış bir sorumluluk ve takip mekanizması mevcut de…'::text, E'Üretim hattı kontrol noktası, ara ürün muayenesi veya son kontrol sırasında tespit edilmiştir.'::text, E'1. Hangi araçlara mavi dosya açılacağı, içeriğinin ne olacağı ve sorumlusunun kim olduğu yazılı prosedüre bağlanmalıdır.\n2. Eksik mavi dosyalar için tamamlama takvimi belirlenmeli ve yapılan çalışmalar takip edilmelidir.\n3. Üretim programına mavi dosya açılışı görevi olarak eklenmeli; dosya açılmadan araç üretimine başlanmaması sağlanmalıdır.\n4. Mevcut araçların dosya durumu liste halinde çıkarılmalı; haftalık tamamlanma oranı izlenmelidir.'::text),
  (E'DF-2026-058'::text, E'DF'::text, E'Uretim sahasinda daha isi bitmemis araclarimiz kalite diizeltmelerinde géziikmekte olup, kalite biriminin heniz | Uretimden cikmayan araglarin gecikmesi veya teslim edilmemesi konusunda sorumlu gosterilmemesi | gerekmektedir . Konu hakkinda aksiyon alinmalidir'::text, E'Üretimden çıkmayan araçlara ait kalite düzeltme süreçlerinde gecikme yaşanmaktadır.'::text, E'Kalite düzeltme faaliyetleri üretim planlama takvimiyle uyumlu yürütülememektedir.'::text, E'Kalite uygunsuzlukları üretim planına yansıtılmamaktadır.'::text, E'Üretim planlama ve kalite birimi arasında bilgi akışı tanımlı değildir.'::text, E'Düzeltici faaliyetlerin plana dahil edilmesi için prosedür ve sorumluluk belirsizdir.'::text, E'Üretim planlama ile kalite yönetim sistemi arasındaki entegrasyon (kayıt, aksiyon, takip) formal bir süreçle kurgulanmamıştır.'::text, E'Uretim sahasinda daha isi bitmemis araclarimiz kalite diizeltmelerinde géziikmekte olup, kalite biriminin heniz | Uretim'::text, E'Uretim Planlama'::text, E'Belirtilmemiş'::text, E'Ahmet Kalipgi'::text, E'Üretim planlama-kalite entegrasyonu yetersiz'::text, E'Üretim hattı kontrol noktası, ara ürün muayenesi veya son kontrol sırasında tespit edilmiştir.'::text, E'1. Üretimden çıkmayan araçların kalite beklemesindeki gecikmelerin sorumluluğu net olarak belirlenmelidir; Üretim Planlama ile ilgili birim arasında sorumluluk matrisi oluşturulmalıdır.\n2. Araç gecikmelerinin günlük takibi için üretim planlama panosu oluşturulmalı; gecikmeler kayıt altına alınmalıdır.\n3. Üretimden çıkmayan araçların kalite süreçlerini etkilemeyeceği bir mekanizma (ayrı alan, önceliklendirme) geliştirilmelidir.\n4. Haftalık Üretim-Kalite koordinasyon toplantısı başlatılmalıdır.'::text),
  (E'DF-2026-068'::text, E'DF'::text, E'26-001 numarali is kazasi igin aksiyon alinmalidir.'::text, E'İş kazası (DF-İK-2026-001) yaşanmış; çalışan yaralanmış ya da tehlikeli durum oluşmuştur.'::text, E'Çalışan iş sırasında bir kaza geçirmiştir.'::text, E'Görev sırasında güvenli olmayan bir eylem veya koşul mevcuttur.'::text, E'Bu riski kapsayan Risk Değerlendirmesi güncel değildir ya da çalışana gerekli şekilde aktarılmamıştır.'::text, E'Güvensiz koşulun giderilmesi için önleyici tedbir alınmamış ya da izlenmemektedir.'::text, E'Kaza zinciri (tehlike → risk → koşul → eylem → kaza) analiz edilmemiş; bu senaryo için Risk Değerlendirmesi güncellenmemiş ve önleyici kontroller sisteme dahil edilmemiştir.'::text, E'26-001 numarali is kazasi igin aksiyon alinmalidir.'::text, E'Ust Yapi'::text, E'25.04.2026'::text, E'Ust Yapi'::text, E'İş kazası (26-001): Risk Değerlendirmesi güncel olmayabilir veya uygulamada sapma var'::text, E'İş kazası bildirimi veya güvensiz durum tespiti ile kayıt altına alınmıştır.'::text, E'1. Kaza 26-001 için detaylı Kaza Kök Neden Analizi yapılmalı (5 Neden veya SCAT yöntemi); bulgular belgeli hale getirilmelidir.\n2. Kazanın gerçekleştiği alan/proses için Risk Değerlendirmesi revize edilmeli; yeni kontrol önlemleri tanımlanmalı ve hayata geçirilmelidir.\n3. Tüm hat/saha personeline olay konusunda güvenlik brifing\'i verilmeli; imzalı katılım formu tutulmalıdır.\n4. Benzer kaza riski taşıyan diğer alanlar/prosesler değerlendirilmeli (yatay yayılım kontrolü); gerekirse fiziksel bariyer/ikaz levhası eklenmelidir.'::text),
  (E'DF-2026-069'::text, E'DF'::text, E'26-002 numarali is kazasi igin aksiyon alinmalidir .'::text, E'İş kazası (DF-İK-2026-002) yaşanmış; çalışan yaralanmış ya da tehlikeli durum oluşmuştur.'::text, E'Çalışan iş sırasında bir kaza geçirmiştir.'::text, E'Çalışma alanında kaza koşuluna yol açan bir güvensizlik (düşme, sıkışma, çarpma vb.) mevcuttur.'::text, E'Bu tehlikeye ait risk değerlendirmesi gözden geçirilmemiş ya da güncellenmemiştir.'::text, E'Risk kontrol önlemleri uygulanmış olsa da etkinliği doğrulanmamıştır.'::text, E'Benzer kaza senaryoları için sistematik kaza analizi ve kök neden araştırması yapılmamış; alınan tedbirler izlenmemektedir.'::text, E'26-002 numarali is kazasi igin aksiyon alinmalidir .'::text, E'Ust Yapi'::text, E'25.04.2026'::text, E'Ust Yapi'::text, E'İş kazası (26-002): Risk Değerlendirmesi güncel olmayabilir veya uygulamada sapma var'::text, E'İş kazası bildirimi veya güvensiz durum tespiti ile kayıt altına alınmıştır.'::text, E'1. Kaza 26-002 için detaylı Kaza Kök Neden Analizi yapılmalı (5 Neden veya SCAT yöntemi); bulgular belgeli hale getirilmelidir.\n2. Kazanın gerçekleştiği alan/proses için Risk Değerlendirmesi revize edilmeli; yeni kontrol önlemleri tanımlanmalı ve hayata geçirilmelidir.\n3. Tüm hat/saha personeline olay konusunda güvenlik brifing\'i verilmeli; imzalı katılım formu tutulmalıdır.\n4. Benzer kaza riski taşıyan diğer alanlar/prosesler değerlendirilmeli (yatay yayılım kontrolü); gerekirse fiziksel bariyer/ikaz levhası eklenmelidir.'::text)
  ) AS t(nc_number, typ, problem_def, symptom, why1, why2, why3, why4, why5, ne, nerede, ne_zaman, kim, neden, nasil, actions_text)
)
UPDATE non_conformities n
SET
  five_n1k_analysis = jsonb_build_object(
    'ne', to_jsonb(x.ne),
    'nerede', to_jsonb(x.nerede),
    'neZaman', to_jsonb(x.ne_zaman),
    'kim', to_jsonb(x.kim),
    'neden', to_jsonb(x.neden),
    'nasil', to_jsonb(x.nasil)
  ),
  five_why_analysis = jsonb_build_object(
    'problem', to_jsonb(x.problem_def),
    'why1', to_jsonb(x.why1),
    'why2', to_jsonb(x.why2),
    'why3', to_jsonb(x.why3),
    'why4', to_jsonb(x.why4),
    'why5', to_jsonb(x.why5),
    'rootCause', to_jsonb(x.why5),
    'immediateAction', to_jsonb(x.neden),
    'preventiveAction', to_jsonb(x.actions_text)
  ),
  eight_d_steps = CASE
    WHEN n.type = '8D' THEN
      jsonb_set(
        jsonb_set(
          COALESCE(n.eight_d_steps, '{}'::jsonb),
          '{D4,description}',
          to_jsonb(
            ('5 Neden (özet)'::text || E'\n\n' ||
             '1. ' || x.why1 || E'\n' ||
             '2. ' || x.why2 || E'\n' ||
             '3. ' || x.why3 || E'\n' ||
             '4. ' || x.why4 || E'\n' ||
             '5 (Kök): ' || x.why5)::text
          ),
          true
        ),
        '{D5,description}',
        to_jsonb(('Önerilen düzeltici faaliyetler'::text || E'\n\n' || x.actions_text)::text),
        true
      )
    ELSE n.eight_d_steps
  END,
  updated_at = now()
FROM x
WHERE n.nc_number = x.nc_number AND n.type = x.typ;
