WITH x AS (
  SELECT * FROM (VALUES
  (E'DF-2026-024'::text, E'DF'::text, E'AGA6000araclarimiz montajdan iktiktan sonra bazi araclarda hava tanki bosaliyor frenler devre disi kaliyor. | Konuyla ilgili aksiyon alinmasi gerekmektedir . (Devrek ve Safak temizlik araglarinda gaz kagagi mevcuttur . | 3. |ILERLEME NOTLARI / YAPILAN CALISMALAR | Devrek ve Kérfez araclari izerinde ; | + Role ventilleri kontrol edilmistir .'::text, E'Mekanik montaj sonrasında hava tankı sızdırmazlık uygunsuzlukları oluşmaktadır.'::text, E'Hava tankı bağlantıları istenen basınç altında sızdırmaktadır.'::text, E'Fitting ve hortum bağlantıları montaj sonrası kontrol edilmemektedir.'::text, E'Sızdırmazlık testi montaj akış planında zorunlu adım olarak bulunmamaktadır.'::text, E'Test prosedürü yazılmamış ya da son revizyonlar için güncellenmemiştir.'::text, E'Mekanik montaj sürecinde kritik bağlantı noktaları için zorunlu basınç testi protokolü ve kontrol formu tanımlanmamıştır.'::text, E'AGA6000araclarimiz montajdan iktiktan sonra bazi araclarda hava tanki bosaliyor frenler devre disi kaliyor. | Konuyla il'::text, E'Mekanik Montaj'::text, E'27.02.2026'::text, E'Erdogan Zengin'::text, E'Mekanik montaj sonrası hava tankı sızdırmazlık testi protokolü yeterince uygulanmamakta'::text, E'Kalite kontrol muayenesi veya saha bildirimi sırasında tespit edilmiştir.'::text, E'1. AGA6000 araçlarında hava tankı ve bağlantı noktaları için montaj sonrası basınç testi prosedürü oluşturulmalı; her araçta imzalı teyit alınmalıdır.\n2. Montaj talimatına kritik hortum/fitting bağlantı kontrol adımları eklenmeli; tork değerleri belirtilmelidir.\n3. Etkilenen araçlarda (Devrek ve Şafak araçları dahil) hava tankı bağlantıları kontrol edilmeli; sızan noktalar onarılmalıdır.\n4. Montaj operatörlerine hava tankı bağlantı ve sızdırmazlık kontrol eğitimi verilmeli; eğitim kayıt altına alınmalıdır.'::text),
  (E'DF-2026-099'::text, E'DF'::text, E'Fabrikada muhafaza edilen sifir motorlar gérsellerden de gériilebilecegi gibi korunaksiz bir sekilde muhafaza | ediliyor. | * Motor uzun siire korumasiz kalmis, bu da ig aksamin kirlenme riskini artirabilir | * Depolama -tasima sirasinda koruyucu értii kullanilmamis her yerinde toz, kir olusmus | * Emme-gikis agiziari agik'::text, E'Fabrikada bekletilen sıfır motorlarda depolama kaynaklı hasar veya bozulma meydana gelmektedir.'::text, E'Motorlar koruyucu örtü veya uygun muhafaza koşulları olmaksızın bekletilmektedir.'::text, E'Depolama süresi ve koşulları standart dışıdır; nem, toz ve titreşimden korunamıyorlar.'::text, E'Motora özgü bir depolama talimatı (muhafaza süresi, çevre koşulları, örtü standardı) hazırlanmamıştır.'::text, E'Tedarikçi tarafından verilen depolama önerileri dikkate alınmamış ya da iletilmemiştir.'::text, E'Bekleme stokları için ürün bazında muhafaza standartları oluşturulmamış; periyodik kontrol ve koşul izleme prosedürü tanımlanmamıştır.'::text, E'Fabrikada muhafaza edilen sifir motorlar gérsellerden de gériilebilecegi gibi korunaksiz bir sekilde muhafaza | ediliyor'::text, E'Lojistik Yéneticiligi'::text, E'17.05.2026'::text, E'‘Sinan Acar'::text, E'Fabrikada muhafaza edilen sıfır motorların depolama prosedürü tanımlanmamış'::text, E'Kalite kontrol muayenesi veya saha bildirimi sırasında tespit edilmiştir.'::text, E'1. Sıfır motor depolama alanı belirli bir bölgeye tahsis edilmeli; motorlar koruyucu örtü veya muhafaza kasası ile kapatılmalıdır.\n2. Motor depolama standardı yazılı hale getirilmeli (nem, toz, güneş koruması, zemin temas yasağı); sorumlu personele iletilmelidir.\n3. Mevcut korumasız motorlar için acil koruma önlemi (branda veya PE örtü) hemen uygulanmalıdır.\n4. Depo girişine \'motor depolama kuralları\' levhası asılmalı; motor deposu aylık kontrol rutinine alınmalıdır.'::text),
  (E'DF-2026-100'::text, E'DF'::text, E'Teknik resim revizyonlarinin (giincel gizim/model degisiklikleri ) Satinalma Midirligi tarafindan zamaninda ve | kontroll bigimde ilgili tedarikgilere iletiimedigi tespit edilmistir.Bu durum tedarikgilerin eski revizyona gére dretim | yapmasina , uygunsuz parca teslim etmesine ve montaj /kalite sorunlarina yol agmaktadir. Satinalma Midurligii ; | revizyon bildirim prosediriind olusturmali , tedarikci iletisim kayitlarini takip etmeli ve her revizyon degisikliginde | tedarikgi onay/teyit siirecini yiriitmelidir .'::text, E'Teknik revizyon tedarikçiye zamanında veya eksiksiz iletilememektedir.'::text, E'Tedarikçi eski revizyon teknik resme göre üretmeye devam etmektedir.'::text, E'Revizyon bildirimi tedarikçiye ulaşmamış veya ulaştığı teyit edilmemiştir.'::text, E'Teknik değişikliklerin tedarikçilere iletilmesi için tanımlı, onaylı bir iletişim akışı mevcut değildir.'::text, E'Revizyon yönetimi sistemi tedarikçi bildirimini otomatik kapsamına almamaktadır.'::text, E'Mühendislik değişiklik yönetimi (ECM) sürecinde tedarikçi zinciri güncelleme adımı tanımlanmamış ve sahiplenilmemiştir.'::text, E'Teknik resim revizyonlarinin (giincel gizim/model degisiklikleri ) Satinalma Midirligi tarafindan zamaninda ve | kontrol'::text, E'Satinalma Madurlaga'::text, E'17.05.2026'::text, E'Uysal Yilmaz'::text, E'Teknik resim/model revizyonlarının tedarikçilere iletimi için tanımlı bir süreç ve kontrol mekanizması mevcut değil'::text, E'Kalite kontrol muayenesi veya saha bildirimi sırasında tespit edilmiştir.'::text, E'1. Teknik resim revizyon iletim prosedürü oluşturulmalı: Ar-Ge → Satınalma → Tedarikçi iletim zinciri net tanımlanmalı, her revizyon için tedarikçi alındı onayı alınmalıdır.\n2. Tedarikçilere iletilen teknik resim versiyonlarının takibi için basit bir revizyon matrisi (Excel tabanlı da olabilir) tutulmalı; güncel versiyon her zaman kayıt altında olmalıdır.\n3. Teknik resim güncellendiğinde Satınalma birimine otomatik bildirim gönderecek bir iş akışı (e-posta alert veya ERP bildirimi) tanımlanmalıdır.\n4. Aktif tedarikçilere toplu olarak güncel teknik resimler gönderilmeli ve eski revizyonların imha edilmesi talep edilmelidir.'::text),
  (E'DF-2026-104'::text, E'DF'::text, E'MALIYETKAYDIDETAYLARI | Maliyet Tira: Hurda Maliyeti | Tarih: 30.04.2026 | Birim: Uretim Miidirligdé (Ust Yapi) | Parga Adi: JANFLASTIK'::text, E'Satınalma sürecinde tedarikçi seçimi veya takip eksikliği uygunsuzluk maliyetine yol açmıştır.'::text, E'Uygunsuz tedarikçi/ürün satınalma sürecinden geçebilmektedir.'::text, E'Tedarikçi değerlendirme ve onay kriterleri kalite performansını yeterince ağırlıklandırmamaktadır.'::text, E'Mevcut tedarikçilerin periyodik performans değerlendirmesi yapılmamaktadır.'::text, E'Tedarikçi red oranı ve kalite maliyeti KPI olarak izlenmemektedir.'::text, E'Satınalma sürecinde tedarikçi kalite performansını kayıt altına alan ve düşük performansa yaptırım uygulayan sistematik bir değerlendirme mekanizması kurulmamıştır.'::text, E'MALIYETKAYDIDETAYLARI | Maliyet Tira: Hurda Maliyeti | Tarih: 30.04.2026 | Birim: Uretim Miidirligdé (Ust Yapi) | Parga'::text, E'Satinalma Midirlagi'::text, E'04.06.2026'::text, E'Sedat Cetin'::text, E'Maliyet kaydı kapsamında Satınalma Müdürlüğü\'ne atıfta bulunulan uygunsuzluk'::text, E'Kalite kontrol muayenesi veya saha bildirimi sırasında tespit edilmiştir.'::text, E'1. İlgili parçanın tedarik sürecinde yaşanan sorun belgelenmeli; tedarikçi performans kaydına işlenmelidir.\n2. Alternatif tedarikçi araştırması başlatılmalı veya mevcut tedarikçiyle düzeltici aksiyon planı yapılmalıdır.\n3. Kritik parçalar için ikincil tedarikçi (yedek kaynak) tanımlanmalıdır.\n4. Satınalma sürecinde teknik şartname kontrolü aşaması eklenmelidir.'::text),
  (E'8D-2026-001'::text, E'8D'::text, E'MALIYETKAYDIDETAYLARI | Maliyet Turi: Yeniden islem Maliyeti | Tarih: 13.01.2026 | Birim : Tedarikgi | Parga Adi: COPKAZANI KAYNAKLI'::text, E'Tedarikçiden gelen ürünlerde tekrarlayan kalite uygunsuzlukları (maliyet/yeniden işlem) oluşmaktadır.'::text, E'Uygunsuz ürünler tedarikçi tarafından sevkiyat öncesinde tespit edilememektedir.'::text, E'Tedarikçi çıkış kontrol planında kritik karakteristikler tanımlanmamış; denetim periyodik değildir.'::text, E'Tedarikçi kalite yönetim sistemi kritik parametre takibini kapsayacak olgunlukta değildir.'::text, E'Tedarikçi onay/yeterlilik sürecinde kalite planı denetimi yüzeysel yapılmış, iyileştirici yaptırım mekanizması tanımlanmamıştır.'::text, E'Tedarikçi seçim kriterlerinde kalite sistem yeterliliği (süreç kapasitesi, FMEA, kontrol planı) yeterince ağırlıklandırılmamıştır.'::text, E'MALIYETKAYDIDETAYLARI | Maliyet Turi: Yeniden islem Maliyeti | Tarih: 13.01.2026 | Birim : Tedarikgi | Parga Adi: COPKAZ'::text, E'Tedarikgi'::text, E'13.02.2026'::text, E'Tedarikgi'::text, E'Tedarikçi kalite güvence sistemindeki yapısal eksiklik: kontrol planında kritik karakteristik tanımı ve periyodik deneti…'::text, E'GKK (Girdi Kalite Kontrol) muayenesinde veya saha geri bildirimi ile tespit edilmiştir.'::text, E'1. Uygunsuz partiler karantinaya alınmalı, %100 muayene başlatılmalıdır.\n2. Tedarikçi denetimi planlanmalı; kontrol planı kritik karakteristikler eklenerek revize edilmelidir.\n3. Tedarikçi kalite anlaşması güncellenmeli; ret oranı KPI olarak eklenmelidir.\n4. Alternatif tedarikçi yeterlilik süreci başlatılmalıdır.'::text),
  (E'DF-2026-001'::text, E'DF'::text, E'AGA2100i¢in gelen 37-5000190431 kodlu kabinlerde sizdirmazlik testleri basari ile sonuclandirilamamistir | Sizdirmazligin saglanmasi gerekmektedir .'::text, E'Tedarikçiden gelen parçalar sızdırmazlık testini geçememektedir.'::text, E'Kaynak dikişi, conta veya salmastra uygulama kalitesi yeterli değildir.'::text, E'Tedarikçi üretim hattında sızdırmazlık uygulaması standart dışı gerçekleşmektedir.'::text, E'Tedarikçi çıkış kontrol planında sızdırmazlık testi zorunlu adım olarak yer almamaktadır.'::text, E'Tedarikçi kalite planı kritik karakteristikleri (sızdırmazlık) kapsamayacak şekilde eksik oluşturulmuştur.'::text, E'Tedarikçi yeterlilik onayı sırasında sızdırmazlık test şartı ve kontrol planı denetimi yapılmamış; kritik karakteristik tanımı ihmal edilmiştir.'::text, E'AGA2100i¢in gelen 37-5000190431 kodlu kabinlerde sizdirmazlik testleri basari ile sonuclandirilamamistir | Sizdirmazligi'::text, E'Tedarikgi'::text, E'07.02.2026'::text, E'Tedarikgi'::text, E'Tedarikçi üretiminde sızdırmazlık uygulaması (kaynak, salmastra, conta) yetersiz veya malzeme spesifikasyonuna uygun değ…'::text, E'GKK (Girdi Kalite Kontrol) muayenesinde veya saha geri bildirimi ile tespit edilmiştir.'::text, E'1. Tedarikçi ile acil toplantı düzenlenmeli; sızdırmazlık testinin tedarikçi çıkış kontrolüne eklenmesi talep edilmelidir.\n2. Uygunsuz parçalar iade edilmeli, şartlı kabul yapılacaksa ikincil kontrol prosedürü uygulanmalıdır.\n3. Tedarikçiden sızdırmazlık test protokolü ve sonuç raporları talep edilmelidir.\n4. Kritik parçalar için tedarikçi onay/yeterlilik değerlendirmesi yapılmalıdır.'::text),
  (E'DF-2026-003'::text, E'DF'::text, E'ilgili parca miisteri sikayeti izerine tarafimizca incelemeye alinmis ve yapilan fonksiyonel testlerde islevierini yerine | getirmedigi gériilmis olup , kagak problemleri_ ile karsilasilmistir .'::text, E'Tedarikçiden gelen parçalar sızdırmazlık testini geçememektedir.'::text, E'Kaynak dikişi, conta veya salmastra uygulama kalitesi yeterli değildir.'::text, E'Tedarikçi üretim hattında sızdırmazlık uygulaması standart dışı gerçekleşmektedir.'::text, E'Tedarikçi çıkış kontrol planında sızdırmazlık testi zorunlu adım olarak yer almamaktadır.'::text, E'Tedarikçi kalite planı kritik karakteristikleri (sızdırmazlık) kapsamayacak şekilde eksik oluşturulmuştur.'::text, E'Tedarikçi yeterlilik onayı sırasında sızdırmazlık test şartı ve kontrol planı denetimi yapılmamış; kritik karakteristik tanımı ihmal edilmiştir.'::text, E'ilgili parca miisteri sikayeti izerine tarafimizca incelemeye alinmis ve yapilan fonksiyonel testlerde islevierini yerin'::text, E'Tedarikgi'::text, E'15.02.2026'::text, E'Tedarikgi'::text, E'Tedarikçi üretiminde sızdırmazlık uygulaması (kaynak, salmastra, conta) yetersiz veya malzeme spesifikasyonuna uygun değ…'::text, E'GKK (Girdi Kalite Kontrol) muayenesinde veya saha geri bildirimi ile tespit edilmiştir.'::text, E'1. Tedarikçi ile acil toplantı düzenlenmeli; sızdırmazlık testinin tedarikçi çıkış kontrolüne eklenmesi talep edilmelidir.\n2. Uygunsuz parçalar iade edilmeli, şartlı kabul yapılacaksa ikincil kontrol prosedürü uygulanmalıdır.\n3. Tedarikçiden sızdırmazlık test protokolü ve sonuç raporları talep edilmelidir.\n4. Kritik parçalar için tedarikçi onay/yeterlilik değerlendirmesi yapılmalıdır.'::text),
  (E'DF-2026-010'::text, E'DF'::text, E'GIRD/ KALITEKONTROLU- UYGUNSUZLUKTESPITI | MUAYENEBILGILERI | Kayit No: 26/01/114 | Muayene Tarihi: 21.01.2026 | Tedarikgi: Dh Makine Ltd. Sti'::text, E'Tedarikçiden gelen parçalarda boyutsal, görsel veya fonksiyonel uygunsuzluk tespit edilmektedir.'::text, E'Muayenede uygunsuz parçalar, sevkiyattan önce tedarikçi tarafından eleneememektedir.'::text, E'Tedarikçi çıkış kontrol noktasında kritik karakteristikler ölçülmemekte ya da kayıt tutulmamaktadır.'::text, E'Kontrol planında kritik karakteristikler tanımlanmamış veya güncel değildir.'::text, E'Tedarikçi ile yapılan teknik toplantıda kritik özellikler yeterince vurgulanmamış, kontrol planı birlikte gözden geçirilmemiştir.'::text, E'Tedarikçi geliştirme/onay sürecinde ürün kalite planı (PPAP/APQP vb.) gerektiği düzeyde oluşturulmamış ve denetlenmemiştir.'::text, E'GIRD/ KALITEKONTROLU- UYGUNSUZLUKTESPITI | MUAYENEBILGILERI | Kayit No: 26/01/114 | Muayene Tarihi: 21.01.2026 | Tedarik'::text, E'Tedarikgi'::text, E'21.02.2026'::text, E'Tedarikgi'::text, E'Tedarikçi üretim sürecinde boyutsal/görsel/fonksiyonel kalite kontrol yeterli düzeyde uygulanmamaktadır. Kontrol planınd…'::text, E'GKK (Girdi Kalite Kontrol) muayenesinde veya saha geri bildirimi ile tespit edilmiştir.'::text, E'1. Uygunsuz \'Mafsal Baglanti Pimi\' partisi tedarikçiye iade edilmeli veya karantinaya alınmalıdır.\n2. Tedarikçiye DF-2026-010 numaralı DF kaydı iletilmeli, 15 iş günü içinde yazılı kök neden analizi ve düzeltici aksiyon planı talep edilmelidir.\n3. Tedarikçinin kontrol planı incelenmeli; kritik boyutlar ve kabul kriterleri yeniden belirlenmeli, onaylı kontrol planı alınmalıdır.\n4. Aynı tedarikçiden tekrarlayan uygunsuzluk varsa tedarikçi performans puanı düşürülmeli, alternatif tedarikçi değerlendirmesi başlatılmalıdır.'::text),
  (E'DF-2026-011'::text, E'DF'::text, E'GIRD/ KALITEKONTROLU- UYGUNSUZLUKTESPITI | MUAYENEBILGILERI | Kayit No: 25/02/052 | Muayene Tarihi: 20.02.2025 | Tedarikci: Ekser Otomotiv Makina Yedek Parcalari imalat San. Ve Tic. A.s.'::text, E'Tedarikçiden gelen parçalarda boyutsal, görsel veya fonksiyonel uygunsuzluk tespit edilmektedir.'::text, E'Muayenede uygunsuz parçalar, sevkiyattan önce tedarikçi tarafından eleneememektedir.'::text, E'Tedarikçi çıkış kontrol noktasında kritik karakteristikler ölçülmemekte ya da kayıt tutulmamaktadır.'::text, E'Kontrol planında kritik karakteristikler tanımlanmamış veya güncel değildir.'::text, E'Tedarikçi ile yapılan teknik toplantıda kritik özellikler yeterince vurgulanmamış, kontrol planı birlikte gözden geçirilmemiştir.'::text, E'Tedarikçi geliştirme/onay sürecinde ürün kalite planı (PPAP/APQP vb.) gerektiği düzeyde oluşturulmamış ve denetlenmemiştir.'::text, E'GIRD/ KALITEKONTROLU- UYGUNSUZLUKTESPITI | MUAYENEBILGILERI | Kayit No: 25/02/052 | Muayene Tarihi: 20.02.2025 | Tedarik'::text, E'Tedarikgi'::text, E'19.02.2026'::text, E'Tedarikgi'::text, E'Tedarikçi üretim sürecinde boyutsal/görsel/fonksiyonel kalite kontrol yeterli düzeyde uygulanmamaktadır. Kontrol planınd…'::text, E'GKK (Girdi Kalite Kontrol) muayenesinde veya saha geri bildirimi ile tespit edilmiştir.'::text, E'1. Uygunsuz \'37-5000209166\' partisi tedarikçiye iade edilmeli veya karantinaya alınmalıdır.\n2. Tedarikçiye DF-2026-011 numaralı DF kaydı iletilmeli, 15 iş günü içinde yazılı kök neden analizi ve düzeltici aksiyon planı talep edilmelidir.\n3. Tedarikçinin kontrol planı incelenmeli; kritik boyutlar ve kabul kriterleri yeniden belirlenmeli, onaylı kontrol planı alınmalıdır.\n4. Aynı tedarikçiden tekrarlayan uygunsuzluk varsa tedarikçi performans puanı düşürülmeli, alternatif tedarikçi değerlendirmesi başlatılmalıdır.'::text),
  (E'DF-2026-012'::text, E'DF'::text, E'GIRD/ KALITEKONTROLU- UYGUNSUZLUKTESPITI | MUAYENEBILGILERI | Kayit No: 26/01/117 | Muayene Tarihi: 23.01.2026 | Tedarikgi: Uzcelik Makine Ltd. Sti.'::text, E'Tedarikçiden gelen parçalarda boyutsal, görsel veya fonksiyonel uygunsuzluk tespit edilmektedir.'::text, E'Muayenede uygunsuz parçalar, sevkiyattan önce tedarikçi tarafından eleneememektedir.'::text, E'Tedarikçi çıkış kontrol noktasında kritik karakteristikler ölçülmemekte ya da kayıt tutulmamaktadır.'::text, E'Kontrol planında kritik karakteristikler tanımlanmamış veya güncel değildir.'::text, E'Tedarikçi ile yapılan teknik toplantıda kritik özellikler yeterince vurgulanmamış, kontrol planı birlikte gözden geçirilmemiştir.'::text, E'Tedarikçi geliştirme/onay sürecinde ürün kalite planı (PPAP/APQP vb.) gerektiği düzeyde oluşturulmamış ve denetlenmemiştir.'::text, E'GIRD/ KALITEKONTROLU- UYGUNSUZLUKTESPITI | MUAYENEBILGILERI | Kayit No: 26/01/117 | Muayene Tarihi: 23.01.2026 | Tedarik'::text, E'Tedarikgi'::text, E'23.02.2026'::text, E'Tedarikgi'::text, E'Tedarikçi üretim sürecinde boyutsal/görsel/fonksiyonel kalite kontrol yeterli düzeyde uygulanmamaktadır. Kontrol planınd…'::text, E'GKK (Girdi Kalite Kontrol) muayenesinde veya saha geri bildirimi ile tespit edilmiştir.'::text, E'1. Uygunsuz \'Konveyor Burcu\' partisi tedarikçiye iade edilmeli veya karantinaya alınmalıdır.\n2. Tedarikçiye DF-2026-012 numaralı DF kaydı iletilmeli, 15 iş günü içinde yazılı kök neden analizi ve düzeltici aksiyon planı talep edilmelidir.\n3. Tedarikçinin kontrol planı incelenmeli; kritik boyutlar ve kabul kriterleri yeniden belirlenmeli, onaylı kontrol planı alınmalıdır.\n4. Aynı tedarikçiden tekrarlayan uygunsuzluk varsa tedarikçi performans puanı düşürülmeli, alternatif tedarikçi değerlendirmesi başlatılmalıdır.'::text),
  (E'DF-2026-013'::text, E'DF'::text, E'GIRD/ KALITEKONTROLU- UYGUNSUZLUKTESPITI | MUAYENEBILGILERI | Kayit No: 26/01/116 | Muayene Tarihi: 23.01.2026 | Tedarikgi: Ozkan Makine Ltd. Sti.'::text, E'Tedarikçiden gelen parçalarda boyutsal, görsel veya fonksiyonel uygunsuzluk tespit edilmektedir.'::text, E'Muayenede uygunsuz parçalar, sevkiyattan önce tedarikçi tarafından eleneememektedir.'::text, E'Tedarikçi çıkış kontrol noktasında kritik karakteristikler ölçülmemekte ya da kayıt tutulmamaktadır.'::text, E'Kontrol planında kritik karakteristikler tanımlanmamış veya güncel değildir.'::text, E'Tedarikçi ile yapılan teknik toplantıda kritik özellikler yeterince vurgulanmamış, kontrol planı birlikte gözden geçirilmemiştir.'::text, E'Tedarikçi geliştirme/onay sürecinde ürün kalite planı (PPAP/APQP vb.) gerektiği düzeyde oluşturulmamış ve denetlenmemiştir.'::text, E'GIRD/ KALITEKONTROLU- UYGUNSUZLUKTESPITI | MUAYENEBILGILERI | Kayit No: 26/01/116 | Muayene Tarihi: 23.01.2026 | Tedarik'::text, E'Tedarikgi'::text, E'23.02.2026'::text, E'Tedarikgi'::text, E'Tedarikçi üretim sürecinde boyutsal/görsel/fonksiyonel kalite kontrol yeterli düzeyde uygulanmamaktadır. Kontrol planınd…'::text, E'GKK (Girdi Kalite Kontrol) muayenesinde veya saha geri bildirimi ile tespit edilmiştir.'::text, E'1. Uygunsuz \'Firca Baglanti Blogu\' partisi tedarikçiye iade edilmeli veya karantinaya alınmalıdır.\n2. Tedarikçiye DF-2026-013 numaralı DF kaydı iletilmeli, 15 iş günü içinde yazılı kök neden analizi ve düzeltici aksiyon planı talep edilmelidir.\n3. Tedarikçinin kontrol planı incelenmeli; kritik boyutlar ve kabul kriterleri yeniden belirlenmeli, onaylı kontrol planı alınmalıdır.\n4. Aynı tedarikçiden tekrarlayan uygunsuzluk varsa tedarikçi performans puanı düşürülmeli, alternatif tedarikçi değerlendirmesi başlatılmalıdır.'::text),
  (E'DF-2026-014'::text, E'DF'::text, E'GIRD/ KALITEKONTROLU- UYGUNSUZLUKTESPITI | MUAYENEBILGILERI | Kayit No: 26/01/115 | Muayene Tarihi: 22.01.2026 | Tedarikgi: Ozkan Makine Ltd. Sti.'::text, E'Tedarikçiden gelen parçalarda boyutsal, görsel veya fonksiyonel uygunsuzluk tespit edilmektedir.'::text, E'Muayenede uygunsuz parçalar, sevkiyattan önce tedarikçi tarafından eleneememektedir.'::text, E'Tedarikçi çıkış kontrol noktasında kritik karakteristikler ölçülmemekte ya da kayıt tutulmamaktadır.'::text, E'Kontrol planında kritik karakteristikler tanımlanmamış veya güncel değildir.'::text, E'Tedarikçi ile yapılan teknik toplantıda kritik özellikler yeterince vurgulanmamış, kontrol planı birlikte gözden geçirilmemiştir.'::text, E'Tedarikçi geliştirme/onay sürecinde ürün kalite planı (PPAP/APQP vb.) gerektiği düzeyde oluşturulmamış ve denetlenmemiştir.'::text, E'GIRD/ KALITEKONTROLU- UYGUNSUZLUKTESPITI | MUAYENEBILGILERI | Kayit No: 26/01/115 | Muayene Tarihi: 22.01.2026 | Tedarik'::text, E'Tedarikgi'::text, E'22.02.2026'::text, E'Tedarikgi'::text, E'Tedarikçi üretim sürecinde boyutsal/görsel/fonksiyonel kalite kontrol yeterli düzeyde uygulanmamaktadır. Kontrol planınd…'::text, E'GKK (Girdi Kalite Kontrol) muayenesinde veya saha geri bildirimi ile tespit edilmiştir.'::text, E'1. Uygunsuz \'Jcb74kw Motor Pompa Kampanasi\' partisi tedarikçiye iade edilmeli veya karantinaya alınmalıdır.\n2. Tedarikçiye DF-2026-014 numaralı DF kaydı iletilmeli, 15 iş günü içinde yazılı kök neden analizi ve düzeltici aksiyon planı talep edilmelidir.\n3. Tedarikçinin kontrol planı incelenmeli; kritik boyutlar ve kabul kriterleri yeniden belirlenmeli, onaylı kontrol planı alınmalıdır.\n4. Aynı tedarikçiden tekrarlayan uygunsuzluk varsa tedarikçi performans puanı düşürülmeli, alternatif tedarikçi değerlendirmesi başlatılmalıdır.'::text)
  ) AS t(nc_number, typ, problem_def, symptom, why1, why2, why3, why4, why5, ne, nerede, ne_zaman, kim, neden, nasil, actions_text)
)
UPDATE non_conformities n
SET
  five_n1k_analysis = jsonb_build_object(
    'ne', to_jsonb(x.ne),
    'nerede', to_jsonb(x.nerede),
    'neZaman', to_jsonb(x.ne_zaman),
    'kim', to_jsonb(x.kim),
    'neden', to_jsonb(x.neden),
    'nasil', to_jsonb(x.nasil)
  ),
  five_why_analysis = jsonb_build_object(
    'problem', to_jsonb(x.problem_def),
    'why1', to_jsonb(x.why1),
    'why2', to_jsonb(x.why2),
    'why3', to_jsonb(x.why3),
    'why4', to_jsonb(x.why4),
    'why5', to_jsonb(x.why5),
    'rootCause', to_jsonb(x.why5),
    'immediateAction', to_jsonb(x.neden),
    'preventiveAction', to_jsonb(x.actions_text)
  ),
  eight_d_steps = CASE
    WHEN n.type = '8D' THEN
      jsonb_set(
        jsonb_set(
          COALESCE(n.eight_d_steps, '{}'::jsonb),
          '{D4,description}',
          to_jsonb(
            ('5 Neden (özet)'::text || E'\n\n' ||
             '1. ' || x.why1 || E'\n' ||
             '2. ' || x.why2 || E'\n' ||
             '3. ' || x.why3 || E'\n' ||
             '4. ' || x.why4 || E'\n' ||
             '5 (Kök): ' || x.why5)::text
          ),
          true
        ),
        '{D5,description}',
        to_jsonb(('Önerilen düzeltici faaliyetler'::text || E'\n\n' || x.actions_text)::text),
        true
      )
    ELSE n.eight_d_steps
  END,
  updated_at = now()
FROM x
WHERE n.nc_number = x.nc_number AND n.type = x.typ;
