WITH x AS (
  SELECT * FROM (VALUES
  (E'DF-2026-025'::text, E'DF'::text, E'Dis kaynakli igleme g6nderilen Griinlerde takipsizlikler ve belirsizlikler tespit edilmistir .Giden Grin adeti gelen Grin | adeti sayiliyor olsa bile kaydi tutulmadigi , hangi malzemeye ne islem yapilacaginin da kag giin siirdiigiintin de | gorillebilecegi herhangi kaydi olmadigi tespit edilmistir .Bu da kalite kontrol siireclerini ve tedarikci takibini | zorlastirmaktadir . Sorun 48lik kaplinlerde yasanan miisteri sikayeti ile arastiniip tespit edilmis olup , konuyla ilgili | aksiyon alinmasi gerekmektedir .'::text, E'Dış işleme gönderilen malzemelerin giriş/çıkış takibinde kayıp veya belirsizlik yaşanmaktadır.'::text, E'Gönderilen ve geri gelen adet bilgisi doğrulanamamaktadır.'::text, E'Çıkış sırasında irsaliye/sevk belgesi düzenlenmemekte ya da muhasebeleştirilmemektedir.'::text, E'Dış işlem sürecini kapsayan bir kayıt/takip formu veya sistemi tanımlanmamıştır.'::text, E'Sorumluluk dağılımı belirsiz; kimse bu takibi görev tanımında sahiplenmemektedir.'::text, E'Depo operasyon prosedürleri dış kaynaklı işlemleri kapsayacak şekilde yazılı ve onaylı hâle getirilmemiştir.'::text, E'Dis kaynakli igleme g6nderilen Griinlerde takipsizlikler ve belirsizlikler tespit edilmistir .Giden Grin adeti gelen Gri'::text, E'Depo'::text, E'15.05.2026'::text, E'‘Sinan Acar'::text, E'Dış kaynaklı işleme gönderilen ürünlerin takibi için yazılı prosedür ve kayıt sistemi mevcut değil'::text, E'Depo rutin sayımı, giriş/çıkış takibi veya saha bildirimi ile tespit edilmiştir.'::text, E'1. Dış işleme gidiş-dönüş için teslimat fişi/formu oluşturulmalı; her sevkiyatta imzalı belge alınmalıdır.\n2. Dış işlemde bulunan parçalar için AX\'ta ayrı bir depo konumu tanımlanmalıdır.\n3. İşleme gönderilen ürünlerin adet ve süre takibi haftalık olarak yapılmalıdır.\n4. Taşıma sırasında boyalı ürünlerin birbirine sürtmesini önlemek için köpük/karton ara kat kullanımı zorunlu hale getirilmelidir.'::text),
  (E'DF-2026-030'::text, E'DF'::text, E'Depo birimimize baGli teslim teselliim ve forklift kaynakli, teslim alinan driinlerde gizilmeler ve ezilmeler meydana | gelmis. teslim teselliim siireci diizensiz (teslim alinan riinlerin nereye ne sekilde teslim alinacagi ve uygun palet | takoz vb sartlarin saglanmamas: ) ayrica forklift kullaniminin 6zensiz oldugu (iriinlerin birbirleri Uzerine | bindirilmesi indirirken ve tasirken driinlerin birbirine sirtiilip boyasina ve formuna zarar verilerek yapildigi) tespit | edilmistir . Konuyla ilgili aksiyon alinmasi gerekmektedir .'::text, E'Taşıma veya istifleme operasyonlarında ürünler hasar görmektedir.'::text, E'Forklift veya taşıma aracı ürüne fiziksel zarar vermektedir.'::text, E'Operatör doğru taşıma yöntemini ve güzergâhı bilmemekte ya da uygulamamaktadır.'::text, E'Forklift operasyon talimatı (hız, yük kapasitesi, yaklaşma mesafesi) tanımlanmamıştır.'::text, E'Operatörler yetkinlik değerlendirmesinden geçirilmemiş veya sertifika yenileme periyoduna uyulmamaktadır.'::text, E'İşyerinde taşıma güvenliğini düzenleyen prosedür hazırlanmamış; ekipman kullanım eğitimi sistematik değildir.'::text, E'Depo birimimize baGli teslim teselliim ve forklift kaynakli, teslim alinan driinlerde gizilmeler ve ezilmeler meydana |'::text, E'Depo'::text, E'05.03.2026'::text, E'‘Sinan Acar'::text, E'Teslim alma ve forklift operasyonları sırasında ürün hasarını önleyecek prosedür ve talimatlar tanımlı değil'::text, E'Depo rutin sayımı, giriş/çıkış takibi veya saha bildirimi ile tespit edilmiştir.'::text, E'1. Forklift operatörlerine ürün hasarı önleme eğitimi verilmeli; hassas/boyalı ürünlerde köpük/karton koruma kullanımı zorunlu hale getirilmelidir.\n2. Teslim alma prosedürü yazılı hale getirilmeli; palet ve takoz kullanım standardı belirlenmeli, ekibe iletilmelidir.\n3. Teslim alınan ürünlerde hasar kontrolü formu oluşturulmalı; giriş hasarları kayıt altına alınmalıdır.\n4. Depo içi trafik güzergahı işaretlenmeli; forklift hız limiti belirlenmeli ve uygulanmalıdır.'::text),
  (E'DF-2026-032'::text, E'DF'::text, E'Depoya teslim edilen (igeriden ve disaridan (kaynakli imalat , bdb , ginar, almaksan ,) tim diriinler.) ortam sart | kosullarindan minimum etkilesimle saklanmali ve yipranmalardan muhafaza edilmelidir . Direkt olarak zemine | birakilarak atil stoklama sisteminin 6niine gecilmesi gerekmektedir . | eee OLE ac ea Sua alas | | Altlarina saceklenerek depolanmaya baslandi'::text, E'Depoda yanlış veya yetersiz stoklama nedeniyle ürünler hasar görmekte ya da kaybolmaktadır.'::text, E'Ürünler açık alanda veya uygun olmayan koşullarda bekletilmektedir.'::text, E'Raf sistemi yetersiz veya ürün türüne göre düzenlenmemiştir.'::text, E'Depo yerleşim planı (layout) hazırlanmamış ya da güncel değildir.'::text, E'Depo kapasite/altyapı ihtiyacı periyodik olarak değerlendirilmemektedir.'::text, E'Stok saklama standartları (nem, sıcaklık, raf tipi, dış alan kullanımı) yazılı prosedürle tanımlanmamış ve izlenmemektedir.'::text, E'Depoya teslim edilen (igeriden ve disaridan (kaynakli imalat , bdb , ginar, almaksan ,) tim diriinler.) ortam sart | kos'::text, E'Depo'::text, E'09.03.2026'::text, E'‘Sinan Acar'::text, E'Depo stoklama alanı fiziksel düzenlemesi yetersiz'::text, E'Depo rutin sayımı, giriş/çıkış takibi veya saha bildirimi ile tespit edilmiştir.'::text, E'1. Motor ve büyük parça stoklama alanı kapalı veya örtülü hale getirilmeli; palet/raf düzenlemesi yapılmalıdır.\n2. Açık alana alınan ürünler için branda/koruyucu örtü kullanımı zorunlu hale getirilmelidir.\n3. Raf ve depolama sistemi kapasitesi gözden geçirilmeli; ihtiyaç halinde ek raf talep edilmelidir.\n4. Depo düzeni fotoğraflanarak referans düzen oluşturulmalı; 5S uygulaması başlatılmalıdır.'::text),
  (E'DF-2026-044'::text, E'DF'::text, E'Teselliim ve essek diye tabir edilen tekerlekli tasima sasi dizerine HSCKiistyapilari alinirken uygunsuzluk tespit | edilmis ve 6nlem alinmasi gerekmektedir . | 3. |ILERLEME NOTLARI / YAPILAN CALISMALAR | | egitim verildi'::text, E'Depo operasyonlarında standardı olmayan uygulamalar ve tekrarlayan hatalar yaşanmaktadır.'::text, E'Personel işlemleri kendi inisiyatifine göre yapmakta, standart bir yol izlememektedir.'::text, E'Hangi işlemin nasıl yapılacağına dair güncel ve erişilebilir talimat mevcut değildir.'::text, E'Mevcut prosedürler son değişiklikleri yansıtmayacak kadar eskidir veya hiç yazılmamıştır.'::text, E'Prosedür güncelleme sorumluluğu sahiplenilmemekte; periyodik gözden geçirme yapılmamaktadır.'::text, E'Depo süreçleri için bir dokümantasyon yönetim planı (revizyon periyodu, onay mekanizması) oluşturulmamıştır.'::text, E'Teselliim ve essek diye tabir edilen tekerlekli tasima sasi dizerine HSCKiistyapilari alinirken uygunsuzluk tespit | edi'::text, E'Depo'::text, E'12.03.2026'::text, E'‘Sinan Acar'::text, E'Depo yönetim prosedürü eksik veya güncel değil'::text, E'Depo rutin sayımı, giriş/çıkış takibi veya saha bildirimi ile tespit edilmiştir.'::text, E'1. İlgili uygunsuzluk için yazılı prosedür/talimat oluşturulmalı veya güncellenmeli; depo personeline iletilmelidir.\n2. Haftalık depo kontrol turu uygulanmalı; bulgular kayıt altına alınmalıdır.\n3. Depo personeline yönlendirici eğitim verilmeli ve eğitim kaydı tutulmalıdır.\n4. 5S uygulaması kapsamında depo düzenlemesi yapılmalıdır.'::text),
  (E'DF-2026-059'::text, E'DF'::text, E'Dis kaynakli isleme giden iiriinler araca yiiklenirken boyali boyasiz farketmeksizin ig ige birbirlerine siirtecek | sekilde koyulup g6nderildigi tespit edilmistir .Malzemelerin formu bozulmamasi igin ve Boyali Griinlerin zarar | gérmemesi icin aksiyon alinmasi gerekmektedir . | eee OLE ac ea Sua alas | | egitim verilmistir .'::text, E'Dış işleme gönderilen malzemelerin giriş/çıkış takibinde kayıp veya belirsizlik yaşanmaktadır.'::text, E'Gönderilen ve geri gelen adet bilgisi doğrulanamamaktadır.'::text, E'Çıkış sırasında irsaliye/sevk belgesi düzenlenmemekte ya da muhasebeleştirilmemektedir.'::text, E'Dış işlem sürecini kapsayan bir kayıt/takip formu veya sistemi tanımlanmamıştır.'::text, E'Sorumluluk dağılımı belirsiz; kimse bu takibi görev tanımında sahiplenmemektedir.'::text, E'Depo operasyon prosedürleri dış kaynaklı işlemleri kapsayacak şekilde yazılı ve onaylı hâle getirilmemiştir.'::text, E'Dis kaynakli isleme giden iiriinler araca yiiklenirken boyali boyasiz farketmeksizin ig ige birbirlerine siirtecek | sek'::text, E'Depo'::text, E'03.04.2026'::text, E'‘Sinan Acar'::text, E'Dış kaynaklı işleme gönderilen ürünlerin takibi için yazılı prosedür ve kayıt sistemi mevcut değil'::text, E'Depo rutin sayımı, giriş/çıkış takibi veya saha bildirimi ile tespit edilmiştir.'::text, E'1. Dış işleme gidiş-dönüş için teslimat fişi/formu oluşturulmalı; her sevkiyatta imzalı belge alınmalıdır.\n2. Dış işlemde bulunan parçalar için AX\'ta ayrı bir depo konumu tanımlanmalıdır.\n3. İşleme gönderilen ürünlerin adet ve süre takibi haftalık olarak yapılmalıdır.\n4. Taşıma sırasında boyalı ürünlerin birbirine sürtmesini önlemek için köpük/karton ara kat kullanımı zorunlu hale getirilmelidir.'::text),
  (E'DF-2026-072'::text, E'DF'::text, E'26-005 numarali is kazasi igin aksiyon alinmasi gerekmektedir .'::text, E'Taşıma veya kaldırma işlemleri sırasında iş güvenliği ihlali yaşanmıştır.'::text, E'Çalışan, kaldırma veya taşıma yaparken güvenli olmayan bir yöntemi kullanmıştır.'::text, E'Ergonomik kaldırma teknikleri ve yardımcı ekipman kullanımı (transpalet, vinç) konusunda yeterli farkındalık yoktur.'::text, E'Taşıma/kaldırma güvenliği talimatı sahada görünür ya da anlaşılır değildir.'::text, E'İSG eğitimi soyut kalmakta; pratik uygulamayı pekiştiren sahada gösteri yapılmamaktadır.'::text, E'Manuel taşıma riskini minimize edecek ergonomik düzenleme ve kaldırma yardımcısı donanım sağlanmamış; taşıma güvenliği talimatı güncellenmemiştir.'::text, E'26-005 numarali is kazasi igin aksiyon alinmasi gerekmektedir .'::text, E'Depo'::text, E'25.04.2026'::text, E'Sinan Acar'::text, E'Taşıma/kaldırma operasyonu sırasında iş güvenliği prosedürlerine uyulmamış'::text, E'Depo rutin sayımı, giriş/çıkış takibi veya saha bildirimi ile tespit edilmiştir.'::text, E'1. Kaza ile ilgili olay kökü analizi yapılmalı; fiziksel/davranışsal kök nedenler tespit edilmelidir.\n2. İlgili operasyon için Risk Değerlendirmesi yeniden yapılmalı; kritik adımlara güvenli çalışma talimatı eklenmeli ve asılmalıdır.\n3. Benzer kaza riskini önlemek için ekipmana fiziksel engel/ikaz levhası eklenmeli; gerekirse jig/aparat tasarlanmalıdır.\n4. Tüm depo personeline İSG eğitimi verilmeli; eğitim kayıt altına alınmalıdır.'::text),
  (E'DF-2026-078'::text, E'DF'::text, E'37-5000187765 Kodlu iiriin depo siparis yetkisinde olmadan siparis agildigi ve durumun uygunsuzlugu_tespit | edilmis olup aksiyon alinmasi gerekmektedir .'::text, E'Yetkisiz veya hatalı sipariş oluşturulması nedeniyle tedarik süreci aksamaktadır.'::text, E'Sistemde yetkisiz kullanıcı sipariş açabilmektedir.'::text, E'Sistem üzerinde sipariş onay hiyerarşisi ve yetki sınırlama kontrolü aktif değildir.'::text, E'ERP sistemi rol ve yetki tanımlamaları yapılmamış ya da güncellenmemiştir.'::text, E'Sistem yöneticisi ve ilgili birim yetki matrisini birlikte gözden geçirmemiştir.'::text, E'Tedarik süreçlerinde yetki kontrolünü sağlayacak sistem konfigürasyonu ve iş akışı (workflow) oluşturulmamıştır.'::text, E'37-5000187765 Kodlu iiriin depo siparis yetkisinde olmadan siparis agildigi ve durumun uygunsuzlugu_tespit | edilmis olu'::text, E'Depo Sefigi'::text, E'27.04.2026'::text, E'Sinan Acar'::text, E'Sipariş açma yetki matrisi ve sistem kontrolleri yeterince tanımlanmamış'::text, E'Depo rutin sayımı, giriş/çıkış takibi veya saha bildirimi ile tespit edilmiştir.'::text, E'1. Yetkisiz açılan sipariş iptal edilmeli veya gerekli onaylardan geçirilmeli; konu kayıt altına alınmalıdır.\n2. Sipariş açma yetki matrisi gözden geçirilmeli ve sisteme işlenmelidir.\n3. Sistem üzerinde yetki dışı sipariş girişini engelleyen kontrol aktivasyonu IT birimiyle koordineli yapılmalıdır.\n4. Depo personeline hangi ürünler için sipariş açma yetkisinin olduğu yazılı olarak bildirilmeli, imzalatılmalıdır.'::text),
  (E'8D-2026-002'::text, E'8D'::text, E'MALIYETKAYDIDETAYLARI | Maliyet Turi: Hurda Maliyeti | Tarih: 15.01.2026 | Birim : Elektrik Montaj | Parga Adi: Geri Goris Kamerasi ve Ekran'::text, E'Elektrik montaj hataları büyük hacimde araç etkileyecek şekilde tekrarlanmaktadır.'::text, E'Kablolama veya bağlantı hataları hat çıkışında tespit edilememektedir.'::text, E'Elektrik montaj sonrası fonksiyon testi istasyon bazında uygulanmamaktadır.'::text, E'Fonksiyon test prosedürü tanımlanmış olsa bile istasyonda zorunlu adım olarak uygulanmamaktadır.'::text, E'Operatör yetkinlik değerlendirmesi ve sertifikasyon sistemi elektrik montaj için oluşturulmamıştır.'::text, E'Elektrik montaj istasyonlarında görsel talimat, yetkinlik yönetimi ve zorunlu çıkış test mekanizması sistematik olarak kurgulanmamıştır.'::text, E'MALIYETKAYDIDETAYLARI | Maliyet Turi: Hurda Maliyeti | Tarih: 15.01.2026 | Birim : Elektrik Montaj | Parga Adi: Geri Gor'::text, E'Uretim Midirligi (Ust Yap)'::text, E'18.02.2026'::text, E'Abdurrahman Bigrii'::text, E'Elektrik montaj sürecinde operatör yetkinlik yönetimi ve görsel talimatlar yetersiz'::text, E'Üretim hattı kontrol noktası, ara ürün muayenesi veya son kontrol sırasında tespit edilmiştir.'::text, E'1. Elektrik montaj talimatları her araç tipi ve ünite bazında görsellerle güncellenmeli; talimatlar istasyonlara asılmalıdır.\n2. Etkilenen araçlarda hatalı elektrik bağlantıları düzeltilmeli, tam fonksiyon testi yapılmalıdır.\n3. Elektrik montaj operatörlerinin kablo şeması okuma ve bağlantı doğrulama yetkinliği test edilmeli; gerekirse eğitim verilmelidir.\n4. Hat sonu elektrik fonksiyon test protokolü güncellenmeli; geri görüş kamerası ve ekranı test adımları teyit listesine eklenmeli, imzalı kaydı tutulmalıdır.'::text),
  (E'8D-2026-003'::text, E'8D'::text, E'™ GRUPOZETI | Kategori : Hatali Montaj Uygulamasi | Tespit Alani : Uretilen Araclar | Toplam Kayit : 57 | Toplam Adet : 515'::text, E'Üretim hattında hatalı montaj kayıtları (57 kayıt, 515 araç) oluşmaktadır.'::text, E'Operatörler montaj adımlarını yanlış veya eksik uygulamaktadır.'::text, E'Kritik montaj adımları için görsel talimat ve kontrol listesi yetersizdir veya güncel değildir.'::text, E'Talimat güncelleme sorumluluğu ve periyodik kontrol mekanizması tanımlanmamıştır.'::text, E'Tasarım değişiklikleri montaj talimatlarına otomatik yansıtılmamakta; iletişim kopukluğu yaşanmaktadır.'::text, E'Üretim talimat yönetimi (oluşturma, güncelleme, onay, hat üzerinde görünürlük) sistematik bir süreçle yönetilmemektedir.'::text, E'™ GRUPOZETI | Kategori : Hatali Montaj Uygulamasi | Tespit Alani : Uretilen Araclar | Toplam Kayit : 57 | Toplam Adet :'::text, E'Uretim Madariaga (Ust Yapi)'::text, E'01.05.2026'::text, E'Erdogan Zengin'::text, E'Montaj operasyonlarında görsel talimat ve kontrol listesi yetersiz'::text, E'Üretim hattı kontrol noktası, ara ürün muayenesi veya son kontrol sırasında tespit edilmiştir.'::text, E'1. Her montaj istasyonu için güncel görsel çalışma talimatları (resimli talimat) hazırlanmalı/güncellenmeli ve istasyonlara asılmalıdır.\n2. Etkilenen 515 araçta hatalı montaj noktaları tespit edilmeli ve düzeltme çalışması yapılmalıdır.\n3. Operatör yetkinlik değerlendirmesi yapılmalı; kritik istasyonlarda yetersiz bulunan operatörlere yerinde eğitim verilmelidir.\n4. Hat sonu montaj kontrol listesi oluşturulmalı; her araçta imzalı teyit alınmalıdır.'::text),
  (E'8D-2026-004'::text, E'8D'::text, E'™ GRUPOZETI | Kategori : Eksik Montaj Uygulamasi | Tespit Alani : Uretilen Araclar | Toplam Kayit : 31 | Toplam Adet : 225'::text, E'Üretim hattında eksik montaj kayıtları (31 kayıt, 225 araç) oluşmaktadır.'::text, E'Bazı montaj adımları tamamlanmadan ürün bir sonraki istasyona geçmektedir.'::text, E'Kontrol listesi uygulanmamakta ya da eksik doldurulmaktadır.'::text, E'İstasyon geçiş onay mekanizması (kapı kontrolü/poka-yoke) tanımlı değildir.'::text, E'Operatör kontrol listesi doldurmak için yeterince zaman ve alan bulamamaktadır veya önem vermemektedir.'::text, E'Üretim hattında adım atlama ve eksik montajı önleyecek zorunlu onay/bariyer sistemi (hata geçirmez mekanizma) kurulmamıştır.'::text, E'™ GRUPOZETI | Kategori : Eksik Montaj Uygulamasi | Tespit Alani : Uretilen Araclar | Toplam Kayit : 31 | Toplam Adet : 2'::text, E'Uretim Madariaga (Ust Yapi)'::text, E'01.05.2026'::text, E'Erdogan Zengin'::text, E'Montaj takip sistemi yetersiz'::text, E'Üretim hattı kontrol noktası, ara ürün muayenesi veya son kontrol sırasında tespit edilmiştir.'::text, E'1. Montaj kontrol listesi revizyona alınmalı; eksik parçalar için özel kontrol adımı eklenmeli ve imzalı onay alınmalıdır.\n2. Etkilenen 225 araçta eksik montaj tamamlanmalı; araçlar tekrar kontrol edilmelidir.\n3. Montaj operatörlerine eksik montajın neden olduğu sorunlar hakkında bilinçlendirme eğitimi verilmelidir.\n4. Hat sonu \'eksik parça kontrolü\' prosedürüne final check adımı eklenmeli; araç teslimatı bu kontrol olmadan yapılmamalıdır.'::text),
  (E'8D-2026-006'::text, E'8D'::text, E'™ GRUPOZETI | Kategori : Hatali Elektrik Montaji | Tespit Alani : Uretilen Araclar | Toplam Kayit : 15 | Toplam Adet : 35'::text, E'Elektrik montaj hataları (15 kayıt, 35 araç) tekrarlayan nitelikte oluşmaktadır.'::text, E'Kablolama veya konektör bağlantı hataları üretim sırasında fark edilmemektedir.'::text, E'Elektrik montaj sonrası hat üzerinde fonksiyon testi yapılmamaktadır.'::text, E'Test adımı tanımlı olmadığından operatör bu kontrolü yapmaya zorunlu hissetmemektedir.'::text, E'Operatör görsel talimatları elektrik montaj detaylarını yeterince kapsamımamaktadır.'::text, E'Elektrik montaj istasyonunda yetkinlik bazlı eğitim programı ve zorunlu test adımı prosedüre dahil edilmemiştir.'::text, E'™ GRUPOZETI | Kategori : Hatali Elektrik Montaji | Tespit Alani : Uretilen Araclar | Toplam Kayit : 15 | Toplam Adet : 3'::text, E'Uretim Madariaga (Ust Yapi)'::text, E'01.05.2026'::text, E'Abdurrahman Bugrii'::text, E'Elektrik montaj sürecinde operatör yetkinlik yönetimi ve görsel talimatlar yetersiz'::text, E'Üretim hattı kontrol noktası, ara ürün muayenesi veya son kontrol sırasında tespit edilmiştir.'::text, E'1. Elektrik montaj talimatları her araç tipi ve ünite bazında görsellerle güncellenmeli; talimatlar istasyonlara asılmalıdır.\n2. Etkilenen 35 araçta hatalı elektrik bağlantıları düzeltilmeli, tam fonksiyon testi yapılmalıdır.\n3. Elektrik montaj operatörlerinin kablo şeması okuma ve bağlantı doğrulama yetkinliği test edilmeli; gerekirse eğitim verilmelidir.\n4. Hat sonu elektrik fonksiyon test protokolü güncellenmeli; geri görüş kamerası ve ekranı test adımları teyit listesine eklenmeli, imzalı kaydı tutulmalıdır.'::text),
  (E'8D-2026-007'::text, E'8D'::text, E'™ GRUPOZETI | Kategori : Diger | Tespit Alani : Hat Sonu Kontrol | Toplam Kayit : 3 | Toplam Adet : 42'::text, E'Üretim sürecinde prosedür dışı uygulama ve uygunsuzluklar oluşmaktadır.'::text, E'Operatörler tanımlı prosedürden sapmaktadır.'::text, E'Prosedürlerin neden uygulanması gerektiği yeterince sahada görünür ve anlaşılır değildir.'::text, E'Eğitim etkinliği ölçülmemekte; prosedür bilgisi pekiştirilmemektedir.'::text, E'Hat üstü denetim ve prosedür uyum takibi düzenli yapılmamaktadır.'::text, E'Üretim prosedürlerinin sahada görünürlüğünü, personel uyumunu ve periyodik doğrulamasını sağlayacak hat denetim sistemi kurulmamıştır.'::text, E'™ GRUPOZETI | Kategori : Diger | Tespit Alani : Hat Sonu Kontrol | Toplam Kayit : 3 | Toplam Adet : 42'::text, E'Uretim Madariaga (Ust Yapi)'::text, E'01.05.2026'::text, E'Uretim Madariaga (Ust Yapi)'::text, E'Üretim sürecinde prosedür/talimat uygulanmaması veya kontrol mekanizması eksikliği nedeniyle uygunsuzluk oluşmuş.'::text, E'Üretim hattı kontrol noktası, ara ürün muayenesi veya son kontrol sırasında tespit edilmiştir.'::text, E'1. İlgili üretim talimatı/prosedürü güncellenmeli; personele iletilmelidir.\n2. Etkilenen araçlarda düzeltici işlem yapılmalıdır.\n3. Hat sonu kontrol listesi bu uygunsuzluğu kapsayacak şekilde güncellenmelidir.\n4. Periyodik proses denetimi ile uyumun takibi yapılmalıdır.'::text)
  ) AS t(nc_number, typ, problem_def, symptom, why1, why2, why3, why4, why5, ne, nerede, ne_zaman, kim, neden, nasil, actions_text)
)
UPDATE non_conformities n
SET
  five_n1k_analysis = jsonb_build_object(
    'ne', to_jsonb(x.ne),
    'nerede', to_jsonb(x.nerede),
    'neZaman', to_jsonb(x.ne_zaman),
    'kim', to_jsonb(x.kim),
    'neden', to_jsonb(x.neden),
    'nasil', to_jsonb(x.nasil)
  ),
  five_why_analysis = jsonb_build_object(
    'problem', to_jsonb(x.problem_def),
    'why1', to_jsonb(x.why1),
    'why2', to_jsonb(x.why2),
    'why3', to_jsonb(x.why3),
    'why4', to_jsonb(x.why4),
    'why5', to_jsonb(x.why5),
    'rootCause', to_jsonb(x.why5),
    'immediateAction', to_jsonb(x.neden),
    'preventiveAction', to_jsonb(x.actions_text)
  ),
  eight_d_steps = CASE
    WHEN n.type = '8D' THEN
      jsonb_set(
        jsonb_set(
          COALESCE(n.eight_d_steps, '{}'::jsonb),
          '{D4,description}',
          to_jsonb(
            ('5 Neden (özet)'::text || E'\n\n' ||
             '1. ' || x.why1 || E'\n' ||
             '2. ' || x.why2 || E'\n' ||
             '3. ' || x.why3 || E'\n' ||
             '4. ' || x.why4 || E'\n' ||
             '5 (Kök): ' || x.why5)::text
          ),
          true
        ),
        '{D5,description}',
        to_jsonb(('Önerilen düzeltici faaliyetler'::text || E'\n\n' || x.actions_text)::text),
        true
      )
    ELSE n.eight_d_steps
  END,
  updated_at = now()
FROM x
WHERE n.nc_number = x.nc_number AND n.type = x.typ;
