WITH x AS (
  SELECT * FROM (VALUES
  (E'DF-2026-053'::text, E'DF'::text, E'GIRD/ KALITEKONTROLU- UYGUNSUZLUKTESPITI | MUAYENEBILGILERI | Kayit No: 26/02/109 | Muayene Tarihi: 20.02.2026 | Tedarikgi: Saytek Tasarim Mak.kal.kons'::text, E'Tedarikçiden gelen parçalarda boyutsal, görsel veya fonksiyonel uygunsuzluk tespit edilmektedir.'::text, E'Muayenede uygunsuz parçalar, sevkiyattan önce tedarikçi tarafından eleneememektedir.'::text, E'Tedarikçi çıkış kontrol noktasında kritik karakteristikler ölçülmemekte ya da kayıt tutulmamaktadır.'::text, E'Kontrol planında kritik karakteristikler tanımlanmamış veya güncel değildir.'::text, E'Tedarikçi ile yapılan teknik toplantıda kritik özellikler yeterince vurgulanmamış, kontrol planı birlikte gözden geçirilmemiştir.'::text, E'Tedarikçi geliştirme/onay sürecinde ürün kalite planı (PPAP/APQP vb.) gerektiği düzeyde oluşturulmamış ve denetlenmemiştir.'::text, E'GIRD/ KALITEKONTROLU- UYGUNSUZLUKTESPITI | MUAYENEBILGILERI | Kayit No: 26/02/109 | Muayene Tarihi: 20.02.2026 | Tedarik'::text, E'Tedarikgi'::text, E'Belirtilmemiş'::text, E'Tedarikgi'::text, E'Tedarikçi üretim sürecinde boyutsal/görsel/fonksiyonel kalite kontrol yeterli düzeyde uygulanmamaktadır. Kontrol planınd…'::text, E'GKK (Girdi Kalite Kontrol) muayenesinde veya saha geri bildirimi ile tespit edilmiştir.'::text, E'1. Uygunsuz \'Firca Agma Silindiri Mil Basi\' partisi tedarikçiye iade edilmeli veya karantinaya alınmalıdır.\n2. Tedarikçiye DF-2026-053 numaralı DF kaydı iletilmeli, 15 iş günü içinde yazılı kök neden analizi ve düzeltici aksiyon planı talep edilmelidir.\n3. Tedarikçinin kontrol planı incelenmeli; kritik boyutlar ve kabul kriterleri yeniden belirlenmeli, onaylı kontrol planı alınmalıdır.\n4. Aynı tedarikçiden tekrarlayan uygunsuzluk varsa tedarikçi performans puanı düşürülmeli, alternatif tedarikçi değerlendirmesi başlatılmalıdır.'::text),
  (E'DF-2026-054'::text, E'DF'::text, E'GIRD/ KALITEKONTROLU- UYGUNSUZLUKTESPITI | MUAYENEBILGILERI | Kayit No: 26/02/110 | Muayene Tarihi: 20.02.2026 | Tedarikgi: Saytek Tasarim Mak.kal.kons'::text, E'Tedarikçiden gelen parçalarda boyutsal, görsel veya fonksiyonel uygunsuzluk tespit edilmektedir.'::text, E'Muayenede uygunsuz parçalar, sevkiyattan önce tedarikçi tarafından eleneememektedir.'::text, E'Tedarikçi çıkış kontrol noktasında kritik karakteristikler ölçülmemekte ya da kayıt tutulmamaktadır.'::text, E'Kontrol planında kritik karakteristikler tanımlanmamış veya güncel değildir.'::text, E'Tedarikçi ile yapılan teknik toplantıda kritik özellikler yeterince vurgulanmamış, kontrol planı birlikte gözden geçirilmemiştir.'::text, E'Tedarikçi geliştirme/onay sürecinde ürün kalite planı (PPAP/APQP vb.) gerektiği düzeyde oluşturulmamış ve denetlenmemiştir.'::text, E'GIRD/ KALITEKONTROLU- UYGUNSUZLUKTESPITI | MUAYENEBILGILERI | Kayit No: 26/02/110 | Muayene Tarihi: 20.02.2026 | Tedarik'::text, E'Tedarikgi'::text, E'Belirtilmemiş'::text, E'Tedarikgi'::text, E'Tedarikçi üretim sürecinde boyutsal/görsel/fonksiyonel kalite kontrol yeterli düzeyde uygulanmamaktadır. Kontrol planınd…'::text, E'GKK (Girdi Kalite Kontrol) muayenesinde veya saha geri bildirimi ile tespit edilmiştir.'::text, E'1. Uygunsuz \'Vakum Agzi Baglanti Mili\' partisi tedarikçiye iade edilmeli veya karantinaya alınmalıdır.\n2. Tedarikçiye DF-2026-054 numaralı DF kaydı iletilmeli, 15 iş günü içinde yazılı kök neden analizi ve düzeltici aksiyon planı talep edilmelidir.\n3. Tedarikçinin kontrol planı incelenmeli; kritik boyutlar ve kabul kriterleri yeniden belirlenmeli, onaylı kontrol planı alınmalıdır.\n4. Aynı tedarikçiden tekrarlayan uygunsuzluk varsa tedarikçi performans puanı düşürülmeli, alternatif tedarikçi değerlendirmesi başlatılmalıdır.'::text),
  (E'DF-2026-055'::text, E'DF'::text, E'GIRD/ KALITEKONTROLU- UYGUNSUZLUKTESPITI | MUAYENEBILGILERI | Kayit No: 26/02/113 | Muayene Tarihi: 20.02.2026 | Tedarikgi: Saytek Tasarim Mak.kal.kons'::text, E'Tedarikçiden gelen parçalarda boyutsal, görsel veya fonksiyonel uygunsuzluk tespit edilmektedir.'::text, E'Muayenede uygunsuz parçalar, sevkiyattan önce tedarikçi tarafından eleneememektedir.'::text, E'Tedarikçi çıkış kontrol noktasında kritik karakteristikler ölçülmemekte ya da kayıt tutulmamaktadır.'::text, E'Kontrol planında kritik karakteristikler tanımlanmamış veya güncel değildir.'::text, E'Tedarikçi ile yapılan teknik toplantıda kritik özellikler yeterince vurgulanmamış, kontrol planı birlikte gözden geçirilmemiştir.'::text, E'Tedarikçi geliştirme/onay sürecinde ürün kalite planı (PPAP/APQP vb.) gerektiği düzeyde oluşturulmamış ve denetlenmemiştir.'::text, E'GIRD/ KALITEKONTROLU- UYGUNSUZLUKTESPITI | MUAYENEBILGILERI | Kayit No: 26/02/113 | Muayene Tarihi: 20.02.2026 | Tedarik'::text, E'Tedarikgi'::text, E'Belirtilmemiş'::text, E'Tedarikgi'::text, E'Tedarikçi üretim sürecinde boyutsal/görsel/fonksiyonel kalite kontrol yeterli düzeyde uygulanmamaktadır. Kontrol planınd…'::text, E'GKK (Girdi Kalite Kontrol) muayenesinde veya saha geri bildirimi ile tespit edilmiştir.'::text, E'1. Uygunsuz \'Kapak Kilavuzu Mafsal Gatali\' partisi tedarikçiye iade edilmeli veya karantinaya alınmalıdır.\n2. Tedarikçiye DF-2026-055 numaralı DF kaydı iletilmeli, 15 iş günü içinde yazılı kök neden analizi ve düzeltici aksiyon planı talep edilmelidir.\n3. Tedarikçinin kontrol planı incelenmeli; kritik boyutlar ve kabul kriterleri yeniden belirlenmeli, onaylı kontrol planı alınmalıdır.\n4. Aynı tedarikçiden tekrarlayan uygunsuzluk varsa tedarikçi performans puanı düşürülmeli, alternatif tedarikçi değerlendirmesi başlatılmalıdır.'::text),
  (E'DF-2026-056'::text, E'DF'::text, E'GIRD/ KALITEKONTROLU- UYGUNSUZLUKTESPITI | MUAYENEBILGILERI | Kayit No: 26/02/137 | Muayene Tarihi: 23.02.2026 | Tedarikgi: Ozkan Makine Ltd. Sti.'::text, E'Tedarikçiden gelen parçalarda boyutsal, görsel veya fonksiyonel uygunsuzluk tespit edilmektedir.'::text, E'Muayenede uygunsuz parçalar, sevkiyattan önce tedarikçi tarafından eleneememektedir.'::text, E'Tedarikçi çıkış kontrol noktasında kritik karakteristikler ölçülmemekte ya da kayıt tutulmamaktadır.'::text, E'Kontrol planında kritik karakteristikler tanımlanmamış veya güncel değildir.'::text, E'Tedarikçi ile yapılan teknik toplantıda kritik özellikler yeterince vurgulanmamış, kontrol planı birlikte gözden geçirilmemiştir.'::text, E'Tedarikçi geliştirme/onay sürecinde ürün kalite planı (PPAP/APQP vb.) gerektiği düzeyde oluşturulmamış ve denetlenmemiştir.'::text, E'GIRD/ KALITEKONTROLU- UYGUNSUZLUKTESPITI | MUAYENEBILGILERI | Kayit No: 26/02/137 | Muayene Tarihi: 23.02.2026 | Tedarik'::text, E'Tedarikgi'::text, E'23.03.2026'::text, E'Tedarikgi'::text, E'Tedarikçi üretim sürecinde boyutsal/görsel/fonksiyonel kalite kontrol yeterli düzeyde uygulanmamaktadır. Kontrol planınd…'::text, E'GKK (Girdi Kalite Kontrol) muayenesinde veya saha geri bildirimi ile tespit edilmiştir.'::text, E'1. Uygunsuz \'Emis Adaptérii_ Fan Pompasi\' partisi tedarikçiye iade edilmeli veya karantinaya alınmalıdır.\n2. Tedarikçiye DF-2026-056 numaralı DF kaydı iletilmeli, 15 iş günü içinde yazılı kök neden analizi ve düzeltici aksiyon planı talep edilmelidir.\n3. Tedarikçinin kontrol planı incelenmeli; kritik boyutlar ve kabul kriterleri yeniden belirlenmeli, onaylı kontrol planı alınmalıdır.\n4. Aynı tedarikçiden tekrarlayan uygunsuzluk varsa tedarikçi performans puanı düşürülmeli, alternatif tedarikçi değerlendirmesi başlatılmalıdır.'::text),
  (E'DF-2026-057'::text, E'DF'::text, E'GIRD/ KALITEKONTROLU- UYGUNSUZLUKTESPITI | MUAYENEBILGILERI | Kayit No: 26/02/152 | Muayene Tarihi: 26.02.2026 | Tedarikgi: Saytek Tasarim Mak.kal.kons'::text, E'Tedarikçiden gelen parçalarda boyutsal, görsel veya fonksiyonel uygunsuzluk tespit edilmektedir.'::text, E'Muayenede uygunsuz parçalar, sevkiyattan önce tedarikçi tarafından eleneememektedir.'::text, E'Tedarikçi çıkış kontrol noktasında kritik karakteristikler ölçülmemekte ya da kayıt tutulmamaktadır.'::text, E'Kontrol planında kritik karakteristikler tanımlanmamış veya güncel değildir.'::text, E'Tedarikçi ile yapılan teknik toplantıda kritik özellikler yeterince vurgulanmamış, kontrol planı birlikte gözden geçirilmemiştir.'::text, E'Tedarikçi geliştirme/onay sürecinde ürün kalite planı (PPAP/APQP vb.) gerektiği düzeyde oluşturulmamış ve denetlenmemiştir.'::text, E'GIRD/ KALITEKONTROLU- UYGUNSUZLUKTESPITI | MUAYENEBILGILERI | Kayit No: 26/02/152 | Muayene Tarihi: 26.02.2026 | Tedarik'::text, E'Tedarikgi'::text, E'26.03.2026'::text, E'Tedarikgi'::text, E'Tedarikçi üretim sürecinde boyutsal/görsel/fonksiyonel kalite kontrol yeterli düzeyde uygulanmamaktadır. Kontrol planınd…'::text, E'GKK (Girdi Kalite Kontrol) muayenesinde veya saha geri bildirimi ile tespit edilmiştir.'::text, E'1. Uygunsuz \'Kazan Baglanti Lamasi\' partisi tedarikçiye iade edilmeli veya karantinaya alınmalıdır.\n2. Tedarikçiye DF-2026-057 numaralı DF kaydı iletilmeli, 15 iş günü içinde yazılı kök neden analizi ve düzeltici aksiyon planı talep edilmelidir.\n3. Tedarikçinin kontrol planı incelenmeli; kritik boyutlar ve kabul kriterleri yeniden belirlenmeli, onaylı kontrol planı alınmalıdır.\n4. Aynı tedarikçiden tekrarlayan uygunsuzluk varsa tedarikçi performans puanı düşürülmeli, alternatif tedarikçi değerlendirmesi başlatılmalıdır.'::text),
  (E'DF-2026-060'::text, E'DF'::text, E'GIRD/ KALITEKONTROLU- UYGUNSUZLUKTESPITI | MUAYENEBILGILERI | Kayit No: 26/03/019 | Muayene Tarihi: 03.03.2026 | Tedarikgi: Saytek Tasarim Mak.kal.kons'::text, E'Tedarikçiden gelen parçalarda boyutsal, görsel veya fonksiyonel uygunsuzluk tespit edilmektedir.'::text, E'Muayenede uygunsuz parçalar, sevkiyattan önce tedarikçi tarafından eleneememektedir.'::text, E'Tedarikçi çıkış kontrol noktasında kritik karakteristikler ölçülmemekte ya da kayıt tutulmamaktadır.'::text, E'Kontrol planında kritik karakteristikler tanımlanmamış veya güncel değildir.'::text, E'Tedarikçi ile yapılan teknik toplantıda kritik özellikler yeterince vurgulanmamış, kontrol planı birlikte gözden geçirilmemiştir.'::text, E'Tedarikçi geliştirme/onay sürecinde ürün kalite planı (PPAP/APQP vb.) gerektiği düzeyde oluşturulmamış ve denetlenmemiştir.'::text, E'GIRD/ KALITEKONTROLU- UYGUNSUZLUKTESPITI | MUAYENEBILGILERI | Kayit No: 26/03/019 | Muayene Tarihi: 03.03.2026 | Tedarik'::text, E'Tedarikgi'::text, E'03.04.2026'::text, E'Tedarikgi'::text, E'Tedarikçi üretim sürecinde boyutsal/görsel/fonksiyonel kalite kontrol yeterli düzeyde uygulanmamaktadır. Kontrol planınd…'::text, E'GKK (Girdi Kalite Kontrol) muayenesinde veya saha geri bildirimi ile tespit edilmiştir.'::text, E'1. Uygunsuz \'On Dingil Kiti\' partisi tedarikçiye iade edilmeli veya karantinaya alınmalıdır.\n2. Tedarikçiye DF-2026-060 numaralı DF kaydı iletilmeli, 15 iş günü içinde yazılı kök neden analizi ve düzeltici aksiyon planı talep edilmelidir.\n3. Tedarikçinin kontrol planı incelenmeli; kritik boyutlar ve kabul kriterleri yeniden belirlenmeli, onaylı kontrol planı alınmalıdır.\n4. Aynı tedarikçiden tekrarlayan uygunsuzluk varsa tedarikçi performans puanı düşürülmeli, alternatif tedarikçi değerlendirmesi başlatılmalıdır.'::text),
  (E'DF-2026-061'::text, E'DF'::text, E'GIRD/ KALITEKONTROLU- UYGUNSUZLUKTESPITI | MUAYENEBILGILERI | Kayit No: 26/03/021 | Muayene Tarihi: 03.03.2026 | Tedarikgi: Saytek Tasarim Mak.kal.kons'::text, E'Tedarikçiden gelen parçalarda boyutsal, görsel veya fonksiyonel uygunsuzluk tespit edilmektedir.'::text, E'Muayenede uygunsuz parçalar, sevkiyattan önce tedarikçi tarafından eleneememektedir.'::text, E'Tedarikçi çıkış kontrol noktasında kritik karakteristikler ölçülmemekte ya da kayıt tutulmamaktadır.'::text, E'Kontrol planında kritik karakteristikler tanımlanmamış veya güncel değildir.'::text, E'Tedarikçi ile yapılan teknik toplantıda kritik özellikler yeterince vurgulanmamış, kontrol planı birlikte gözden geçirilmemiştir.'::text, E'Tedarikçi geliştirme/onay sürecinde ürün kalite planı (PPAP/APQP vb.) gerektiği düzeyde oluşturulmamış ve denetlenmemiştir.'::text, E'GIRD/ KALITEKONTROLU- UYGUNSUZLUKTESPITI | MUAYENEBILGILERI | Kayit No: 26/03/021 | Muayene Tarihi: 03.03.2026 | Tedarik'::text, E'Tedarikgi'::text, E'03.04.2026'::text, E'Tedarikgi'::text, E'Tedarikçi üretim sürecinde boyutsal/görsel/fonksiyonel kalite kontrol yeterli düzeyde uygulanmamaktadır. Kontrol planınd…'::text, E'GKK (Girdi Kalite Kontrol) muayenesinde veya saha geri bildirimi ile tespit edilmiştir.'::text, E'1. Uygunsuz \'Ceki Kolu Delrin Yataklama\' partisi tedarikçiye iade edilmeli veya karantinaya alınmalıdır.\n2. Tedarikçiye DF-2026-061 numaralı DF kaydı iletilmeli, 15 iş günü içinde yazılı kök neden analizi ve düzeltici aksiyon planı talep edilmelidir.\n3. Tedarikçinin kontrol planı incelenmeli; kritik boyutlar ve kabul kriterleri yeniden belirlenmeli, onaylı kontrol planı alınmalıdır.\n4. Aynı tedarikçiden tekrarlayan uygunsuzluk varsa tedarikçi performans puanı düşürülmeli, alternatif tedarikçi değerlendirmesi başlatılmalıdır.'::text),
  (E'DF-2026-062'::text, E'DF'::text, E'GIRD/ KALITEKONTROLU- UYGUNSUZLUKTESPITI | MUAYENEBILGILERI | Kayit No: 26/03/023 | Muayene Tarihi: 03.03.2026 | Tedarikgi: Saytek Tasarim Mak.kal.kons'::text, E'Tedarikçiden gelen parçalarda boyutsal, görsel veya fonksiyonel uygunsuzluk tespit edilmektedir.'::text, E'Muayenede uygunsuz parçalar, sevkiyattan önce tedarikçi tarafından eleneememektedir.'::text, E'Tedarikçi çıkış kontrol noktasında kritik karakteristikler ölçülmemekte ya da kayıt tutulmamaktadır.'::text, E'Kontrol planında kritik karakteristikler tanımlanmamış veya güncel değildir.'::text, E'Tedarikçi ile yapılan teknik toplantıda kritik özellikler yeterince vurgulanmamış, kontrol planı birlikte gözden geçirilmemiştir.'::text, E'Tedarikçi geliştirme/onay sürecinde ürün kalite planı (PPAP/APQP vb.) gerektiği düzeyde oluşturulmamış ve denetlenmemiştir.'::text, E'GIRD/ KALITEKONTROLU- UYGUNSUZLUKTESPITI | MUAYENEBILGILERI | Kayit No: 26/03/023 | Muayene Tarihi: 03.03.2026 | Tedarik'::text, E'Tedarikgi'::text, E'03.04.2026'::text, E'Tedarikgi'::text, E'Tedarikçi üretim sürecinde boyutsal/görsel/fonksiyonel kalite kontrol yeterli düzeyde uygulanmamaktadır. Kontrol planınd…'::text, E'GKK (Girdi Kalite Kontrol) muayenesinde veya saha geri bildirimi ile tespit edilmiştir.'::text, E'1. Uygunsuz \'Elevator Kasnagi\' partisi tedarikçiye iade edilmeli veya karantinaya alınmalıdır.\n2. Tedarikçiye DF-2026-062 numaralı DF kaydı iletilmeli, 15 iş günü içinde yazılı kök neden analizi ve düzeltici aksiyon planı talep edilmelidir.\n3. Tedarikçinin kontrol planı incelenmeli; kritik boyutlar ve kabul kriterleri yeniden belirlenmeli, onaylı kontrol planı alınmalıdır.\n4. Aynı tedarikçiden tekrarlayan uygunsuzluk varsa tedarikçi performans puanı düşürülmeli, alternatif tedarikçi değerlendirmesi başlatılmalıdır.'::text),
  (E'DF-2026-063'::text, E'DF'::text, E'GIRD/ KALITEKONTROLU- UYGUNSUZLUKTESPITI | MUAYENEBILGILERI | Kayit No: 26/03/029 | Muayene Tarihi: 04.03.2026 | Tedarikgi: Saytek Tasarim Mak.kal.kons'::text, E'Tedarikçiden gelen parçalarda boyutsal, görsel veya fonksiyonel uygunsuzluk tespit edilmektedir.'::text, E'Muayenede uygunsuz parçalar, sevkiyattan önce tedarikçi tarafından eleneememektedir.'::text, E'Tedarikçi çıkış kontrol noktasında kritik karakteristikler ölçülmemekte ya da kayıt tutulmamaktadır.'::text, E'Kontrol planında kritik karakteristikler tanımlanmamış veya güncel değildir.'::text, E'Tedarikçi ile yapılan teknik toplantıda kritik özellikler yeterince vurgulanmamış, kontrol planı birlikte gözden geçirilmemiştir.'::text, E'Tedarikçi geliştirme/onay sürecinde ürün kalite planı (PPAP/APQP vb.) gerektiği düzeyde oluşturulmamış ve denetlenmemiştir.'::text, E'GIRD/ KALITEKONTROLU- UYGUNSUZLUKTESPITI | MUAYENEBILGILERI | Kayit No: 26/03/029 | Muayene Tarihi: 04.03.2026 | Tedarik'::text, E'Tedarikgi'::text, E'04.04.2026'::text, E'Tedarikgi'::text, E'Tedarikçi üretim sürecinde boyutsal/görsel/fonksiyonel kalite kontrol yeterli düzeyde uygulanmamaktadır. Kontrol planınd…'::text, E'GKK (Girdi Kalite Kontrol) muayenesinde veya saha geri bildirimi ile tespit edilmiştir.'::text, E'1. Uygunsuz \'Firca Kol Parcasi\' partisi tedarikçiye iade edilmeli veya karantinaya alınmalıdır.\n2. Tedarikçiye DF-2026-063 numaralı DF kaydı iletilmeli, 15 iş günü içinde yazılı kök neden analizi ve düzeltici aksiyon planı talep edilmelidir.\n3. Tedarikçinin kontrol planı incelenmeli; kritik boyutlar ve kabul kriterleri yeniden belirlenmeli, onaylı kontrol planı alınmalıdır.\n4. Aynı tedarikçiden tekrarlayan uygunsuzluk varsa tedarikçi performans puanı düşürülmeli, alternatif tedarikçi değerlendirmesi başlatılmalıdır.'::text),
  (E'DF-2026-064'::text, E'DF'::text, E'GIRD/ KALITEKONTROLU- UYGUNSUZLUKTESPITI | MUAYENEBILGILERI | Kayit No: 26/03/051 | Muayene Tarihi: 10.03.2026 | Tedarikgi: Uzcelik Makine Ltd. Sti.'::text, E'Tedarikçiden gelen parçalarda boyutsal, görsel veya fonksiyonel uygunsuzluk tespit edilmektedir.'::text, E'Muayenede uygunsuz parçalar, sevkiyattan önce tedarikçi tarafından eleneememektedir.'::text, E'Tedarikçi çıkış kontrol noktasında kritik karakteristikler ölçülmemekte ya da kayıt tutulmamaktadır.'::text, E'Kontrol planında kritik karakteristikler tanımlanmamış veya güncel değildir.'::text, E'Tedarikçi ile yapılan teknik toplantıda kritik özellikler yeterince vurgulanmamış, kontrol planı birlikte gözden geçirilmemiştir.'::text, E'Tedarikçi geliştirme/onay sürecinde ürün kalite planı (PPAP/APQP vb.) gerektiği düzeyde oluşturulmamış ve denetlenmemiştir.'::text, E'GIRD/ KALITEKONTROLU- UYGUNSUZLUKTESPITI | MUAYENEBILGILERI | Kayit No: 26/03/051 | Muayene Tarihi: 10.03.2026 | Tedarik'::text, E'Tedarikgi'::text, E'10.04.2026'::text, E'Tedarikgi'::text, E'Tedarikçi üretim sürecinde boyutsal/görsel/fonksiyonel kalite kontrol yeterli düzeyde uygulanmamaktadır. Kontrol planınd…'::text, E'GKK (Girdi Kalite Kontrol) muayenesinde veya saha geri bildirimi ile tespit edilmiştir.'::text, E'1. Uygunsuz \'SasiBaglanti Pernosu\' partisi tedarikçiye iade edilmeli veya karantinaya alınmalıdır.\n2. Tedarikçiye DF-2026-064 numaralı DF kaydı iletilmeli, 15 iş günü içinde yazılı kök neden analizi ve düzeltici aksiyon planı talep edilmelidir.\n3. Tedarikçinin kontrol planı incelenmeli; kritik boyutlar ve kabul kriterleri yeniden belirlenmeli, onaylı kontrol planı alınmalıdır.\n4. Aynı tedarikçiden tekrarlayan uygunsuzluk varsa tedarikçi performans puanı düşürülmeli, alternatif tedarikçi değerlendirmesi başlatılmalıdır.'::text),
  (E'DF-2026-065'::text, E'DF'::text, E'GIRD/ KALITEKONTROLU- UYGUNSUZLUKTESPITI | MUAYENEBILGILERI | Kayit No: 26/03/056 | Muayene Tarihi: 12.03.2026 | Tedarikgi: Ozkan Makine Ltd. Sti.'::text, E'Tedarikçiden gelen parçalarda boyutsal, görsel veya fonksiyonel uygunsuzluk tespit edilmektedir.'::text, E'Muayenede uygunsuz parçalar, sevkiyattan önce tedarikçi tarafından eleneememektedir.'::text, E'Tedarikçi çıkış kontrol noktasında kritik karakteristikler ölçülmemekte ya da kayıt tutulmamaktadır.'::text, E'Kontrol planında kritik karakteristikler tanımlanmamış veya güncel değildir.'::text, E'Tedarikçi ile yapılan teknik toplantıda kritik özellikler yeterince vurgulanmamış, kontrol planı birlikte gözden geçirilmemiştir.'::text, E'Tedarikçi geliştirme/onay sürecinde ürün kalite planı (PPAP/APQP vb.) gerektiği düzeyde oluşturulmamış ve denetlenmemiştir.'::text, E'GIRD/ KALITEKONTROLU- UYGUNSUZLUKTESPITI | MUAYENEBILGILERI | Kayit No: 26/03/056 | Muayene Tarihi: 12.03.2026 | Tedarik'::text, E'Tedarikgi'::text, E'12.04.2026'::text, E'Tedarikgi'::text, E'Tedarikçi üretim sürecinde boyutsal/görsel/fonksiyonel kalite kontrol yeterli düzeyde uygulanmamaktadır. Kontrol planınd…'::text, E'GKK (Girdi Kalite Kontrol) muayenesinde veya saha geri bildirimi ile tespit edilmiştir.'::text, E'1. Uygunsuz \'Filtre Haznesi On Kapak Komple\' partisi tedarikçiye iade edilmeli veya karantinaya alınmalıdır.\n2. Tedarikçiye DF-2026-065 numaralı DF kaydı iletilmeli, 15 iş günü içinde yazılı kök neden analizi ve düzeltici aksiyon planı talep edilmelidir.\n3. Tedarikçinin kontrol planı incelenmeli; kritik boyutlar ve kabul kriterleri yeniden belirlenmeli, onaylı kontrol planı alınmalıdır.\n4. Aynı tedarikçiden tekrarlayan uygunsuzluk varsa tedarikçi performans puanı düşürülmeli, alternatif tedarikçi değerlendirmesi başlatılmalıdır.'::text),
  (E'DF-2026-066'::text, E'DF'::text, E'GIRD/ KALITEKONTROLU- UYGUNSUZLUKTESPITI | MUAYENEBILGILERI | Kayit No: 26/03/057 | Muayene Tarihi: 12.03.2026 | Tedarikgi: Ozkan Makine Ltd. Sti.'::text, E'Tedarikçiden gelen parçalarda boyutsal, görsel veya fonksiyonel uygunsuzluk tespit edilmektedir.'::text, E'Muayenede uygunsuz parçalar, sevkiyattan önce tedarikçi tarafından eleneememektedir.'::text, E'Tedarikçi çıkış kontrol noktasında kritik karakteristikler ölçülmemekte ya da kayıt tutulmamaktadır.'::text, E'Kontrol planında kritik karakteristikler tanımlanmamış veya güncel değildir.'::text, E'Tedarikçi ile yapılan teknik toplantıda kritik özellikler yeterince vurgulanmamış, kontrol planı birlikte gözden geçirilmemiştir.'::text, E'Tedarikçi geliştirme/onay sürecinde ürün kalite planı (PPAP/APQP vb.) gerektiği düzeyde oluşturulmamış ve denetlenmemiştir.'::text, E'GIRD/ KALITEKONTROLU- UYGUNSUZLUKTESPITI | MUAYENEBILGILERI | Kayit No: 26/03/057 | Muayene Tarihi: 12.03.2026 | Tedarik'::text, E'Tedarikgi'::text, E'12.04.2026'::text, E'Tedarikgi'::text, E'Tedarikçi üretim sürecinde boyutsal/görsel/fonksiyonel kalite kontrol yeterli düzeyde uygulanmamaktadır. Kontrol planınd…'::text, E'GKK (Girdi Kalite Kontrol) muayenesinde veya saha geri bildirimi ile tespit edilmiştir.'::text, E'1. Uygunsuz \'Arka Dingil Rakoru\' partisi tedarikçiye iade edilmeli veya karantinaya alınmalıdır.\n2. Tedarikçiye DF-2026-066 numaralı DF kaydı iletilmeli, 15 iş günü içinde yazılı kök neden analizi ve düzeltici aksiyon planı talep edilmelidir.\n3. Tedarikçinin kontrol planı incelenmeli; kritik boyutlar ve kabul kriterleri yeniden belirlenmeli, onaylı kontrol planı alınmalıdır.\n4. Aynı tedarikçiden tekrarlayan uygunsuzluk varsa tedarikçi performans puanı düşürülmeli, alternatif tedarikçi değerlendirmesi başlatılmalıdır.'::text)
  ) AS t(nc_number, typ, problem_def, symptom, why1, why2, why3, why4, why5, ne, nerede, ne_zaman, kim, neden, nasil, actions_text)
)
UPDATE non_conformities n
SET
  five_n1k_analysis = jsonb_build_object(
    'ne', to_jsonb(x.ne),
    'nerede', to_jsonb(x.nerede),
    'neZaman', to_jsonb(x.ne_zaman),
    'kim', to_jsonb(x.kim),
    'neden', to_jsonb(x.neden),
    'nasil', to_jsonb(x.nasil)
  ),
  five_why_analysis = jsonb_build_object(
    'problem', to_jsonb(x.problem_def),
    'why1', to_jsonb(x.why1),
    'why2', to_jsonb(x.why2),
    'why3', to_jsonb(x.why3),
    'why4', to_jsonb(x.why4),
    'why5', to_jsonb(x.why5),
    'rootCause', to_jsonb(x.why5),
    'immediateAction', to_jsonb(x.neden),
    'preventiveAction', to_jsonb(x.actions_text)
  ),
  eight_d_steps = CASE
    WHEN n.type = '8D' THEN
      jsonb_set(
        jsonb_set(
          COALESCE(n.eight_d_steps, '{}'::jsonb),
          '{D4,description}',
          to_jsonb(
            ('5 Neden (özet)'::text || E'\n\n' ||
             '1. ' || x.why1 || E'\n' ||
             '2. ' || x.why2 || E'\n' ||
             '3. ' || x.why3 || E'\n' ||
             '4. ' || x.why4 || E'\n' ||
             '5 (Kök): ' || x.why5)::text
          ),
          true
        ),
        '{D5,description}',
        to_jsonb(('Önerilen düzeltici faaliyetler'::text || E'\n\n' || x.actions_text)::text),
        true
      )
    ELSE n.eight_d_steps
  END,
  updated_at = now()
FROM x
WHERE n.nc_number = x.nc_number AND n.type = x.typ;
