WITH x AS (
  SELECT * FROM (VALUES
  (E'8D-2026-008'::text, E'8D'::text, E'-'::text, E'Üretim sürecinde prosedür dışı uygulama ve uygunsuzluklar oluşmaktadır.'::text, E'Operatörler tanımlı prosedürden sapmaktadır.'::text, E'Prosedürlerin neden uygulanması gerektiği yeterince sahada görünür ve anlaşılır değildir.'::text, E'Eğitim etkinliği ölçülmemekte; prosedür bilgisi pekiştirilmemektedir.'::text, E'Hat üstü denetim ve prosedür uyum takibi düzenli yapılmamaktadır.'::text, E'Üretim prosedürlerinin sahada görünürlüğünü, personel uyumunu ve periyodik doğrulamasını sağlayacak hat denetim sistemi kurulmamıştır.'::text, E'-'::text, E'Uretim Midurligi (Ost Yapi)'::text, E'01.05.2026'::text, E'Kadir Toraman'::text, E'Üretim sürecinde prosedür/talimat uygulanmaması veya kontrol mekanizması eksikliği nedeniyle uygunsuzluk oluşmuş.'::text, E'Üretim hattı kontrol noktası, ara ürün muayenesi veya son kontrol sırasında tespit edilmiştir.'::text, E'1. İlgili üretim talimatı/prosedürü güncellenmeli; personele iletilmelidir.\n2. Etkilenen araçlarda düzeltici işlem yapılmalıdır.\n3. Hat sonu kontrol listesi bu uygunsuzluğu kapsayacak şekilde güncellenmelidir.\n4. Periyodik proses denetimi ile uyumun takibi yapılmalıdır.'::text),
  (E'8D-2026-009'::text, E'8D'::text, E'MALIYETKAYDIDETAYLARI | Maliyet Tira: Hurda Maliyeti | Tarih: 25.06.2025 | Birim: Uretim Miidirligdé (Ust Yapi) | Parga Kodu: 7261241-1 & 7261241 -2'::text, E'Üretim hattında hurda oluşumu maliyet kaydına konu olmuştur.'::text, E'Hatalı üretilen parça veya ürün kullanılamaz hâle gelmektedir.'::text, E'Hata üretim hattında erken tespit edilememekte; parça son kontrol ya da kullanım sonrasında hurca çıkmaktadır.'::text, E'İstasyon başı görsel kontrol ve ölçüm kriterleri tanımlanmamıştır.'::text, E'Operatör hatalı parçayı reddedip raporlama konusunda teşvik edilmemektedir.'::text, E'Üretim hattında erken hata tespitini sağlayacak istasyon kontrol noktaları (poka-yoke, kalibre ölçüm) ve raporlama kültürü oluşturulmamıştır.'::text, E'MALIYETKAYDIDETAYLARI | Maliyet Tira: Hurda Maliyeti | Tarih: 25.06.2025 | Birim: Uretim Miidirligdé (Ust Yapi) | Parga'::text, E'Uretim Madariaga (Ust Yapi)'::text, E'04.06.2026'::text, E'Uretim Madariaga (Ust Yapi)'::text, E'Hurda maliyet kaydı açılmış'::text, E'Üretim hattı kontrol noktası, ara ürün muayenesi veya son kontrol sırasında tespit edilmiştir.'::text, E'1. Hurda ürün için kök neden belirlenmelidir; üretim parametreleri ve talimatlar gözden geçirilmelidir.\n2. Montaj veya üretim talimatı güncellenmeli; benzer hurda riskini önlemek için önlem alınmalıdır.\n3. Operatör veya prosese yönelik düzeltici aksiyon tanımlanmalı ve takibi yapılmalıdır.\n4. Hurda parça için tedarikçiye iade veya ikame sipariş süreci başlatılmalıdır.'::text),
  (E'DF-2026-021'::text, E'DF'::text, E'AGA6000araclarimiz montajdan iktiktan sonra bazi araclarda hava tanki bosaliyor frenler devre disi kaliyor. | Konuyla ilgili aksiyon alinmasi gerekmektedir . (Devrek ve Safak temizlik araglarinda gaz kagagi meveuttur . 3. | ILERLEMENOTLARI/ YAPILANCALISMALARDevrek ve K6rfez araglari Uizerinde ;+ + + Role ventilleri kontrol edilmistir . | Fren kériikleri kontrol edilmistir Fren beyni kontrol edilm'::text, E'Üretim sürecinde prosedür dışı uygulama ve uygunsuzluklar oluşmaktadır.'::text, E'Operatörler tanımlı prosedürden sapmaktadır.'::text, E'Prosedürlerin neden uygulanması gerektiği yeterince sahada görünür ve anlaşılır değildir.'::text, E'Eğitim etkinliği ölçülmemekte; prosedür bilgisi pekiştirilmemektedir.'::text, E'Hat üstü denetim ve prosedür uyum takibi düzenli yapılmamaktadır.'::text, E'Üretim prosedürlerinin sahada görünürlüğünü, personel uyumunu ve periyodik doğrulamasını sağlayacak hat denetim sistemi kurulmamıştır.'::text, E'AGA6000araclarimiz montajdan iktiktan sonra bazi araclarda hava tanki bosaliyor frenler devre disi kaliyor. | Konuyla il'::text, E'Uretim Midirligi (Ust Yap)'::text, E'Belirtilmemiş'::text, E'Erdogan Zengin'::text, E'Üretim sürecinde prosedür/talimat uygulanmaması veya kontrol mekanizması eksikliği nedeniyle uygunsuzluk oluşmuş.'::text, E'Üretim hattı kontrol noktası, ara ürün muayenesi veya son kontrol sırasında tespit edilmiştir.'::text, E'1. İlgili üretim talimatı/prosedürü güncellenmeli; personele iletilmelidir.\n2. Etkilenen araçlarda düzeltici işlem yapılmalıdır.\n3. Hat sonu kontrol listesi bu uygunsuzluğu kapsayacak şekilde güncellenmelidir.\n4. Periyodik proses denetimi ile uyumun takibi yapılmalıdır.'::text),
  (E'DF-2026-079'::text, E'DF'::text, E'Depo birimimiz tarafindan agilan ve deponun kanban harici driinlerde siparis yetkisi olmadig genel miidiiriimiiz | tarafindan bildirilmis olup yetkisiz agilan bu siparisin onaylanmasinda uygunsuzluk tespit edilmistir .'::text, E'Üretim sürecinde prosedür dışı uygulama ve uygunsuzluklar oluşmaktadır.'::text, E'Operatörler tanımlı prosedürden sapmaktadır.'::text, E'Prosedürlerin neden uygulanması gerektiği yeterince sahada görünür ve anlaşılır değildir.'::text, E'Eğitim etkinliği ölçülmemekte; prosedür bilgisi pekiştirilmemektedir.'::text, E'Hat üstü denetim ve prosedür uyum takibi düzenli yapılmamaktadır.'::text, E'Üretim prosedürlerinin sahada görünürlüğünü, personel uyumunu ve periyodik doğrulamasını sağlayacak hat denetim sistemi kurulmamıştır.'::text, E'Depo birimimiz tarafindan agilan ve deponun kanban harici driinlerde siparis yetkisi olmadig genel miidiiriimiiz | taraf'::text, E'Uretim Midurligi (Ost Yapi)'::text, E'27.04.2026'::text, E'Uretim Midurligi (Ost Yapi)'::text, E'Üretim sürecinde prosedür/talimat uygulanmaması veya kontrol mekanizması eksikliği nedeniyle uygunsuzluk oluşmuş.'::text, E'Üretim hattı kontrol noktası, ara ürün muayenesi veya son kontrol sırasında tespit edilmiştir.'::text, E'1. İlgili üretim talimatı/prosedürü güncellenmeli; personele iletilmelidir.\n2. Etkilenen araçlarda düzeltici işlem yapılmalıdır.\n3. Hat sonu kontrol listesi bu uygunsuzluğu kapsayacak şekilde güncellenmelidir.\n4. Periyodik proses denetimi ile uyumun takibi yapılmalıdır.'::text),
  (E'DF-2026-083'::text, E'DF'::text, E'MALIYETKAYDIDETAYLARI | Maliyet Tira: Hurda Maliyeti | Tarih: 06.02.2026 | Birim: Ssh | Parga Adi: Fan Gévdesi Kaynakli Komple'::text, E'Kaynak hataları üretim sürecinde tekrarlayan biçimde oluşmaktadır.'::text, E'Kaynak dikişleri standartta belirtilen kaliteyi sağlayamamaktadır.'::text, E'Kaynak parametreleri (akım, voltaj, hız, dolgu teli) kaynak sırasında kontrol edilmemektedir.'::text, E'Kaynak prosedür spesifikasyonu (WPS) oluşturulmamış veya hat üzerinde erişilebilir değildir.'::text, E'Kaynakçı yetkinlik belgesi (sertifika) sistematik olarak yönetilmemekte; yenileme periyotları takip edilmemektedir.'::text, E'Kaynak proses kalifikasyonu (WPS/PQR) ve kaynakçı sertifikasyon sistemi oluşturulmamış; kaynak sonrası NDT/görsel kontrol prosedürü tanımlanmamıştır.'::text, E'MALIYETKAYDIDETAYLARI | Maliyet Tira: Hurda Maliyeti | Tarih: 06.02.2026 | Birim: Ssh | Parga Adi: Fan Gévdesi Kaynakli'::text, E'Uretim Madariaga (Ust Yapi)'::text, E'06.03.2026'::text, E'Uretim Madariaga (Ust Yapi)'::text, E'Kaynak operasyonu sırasında parametreler (akım, hız, dolgu malzemesi) kontrol edilmemekte'::text, E'Üretim hattı kontrol noktası, ara ürün muayenesi veya son kontrol sırasında tespit edilmiştir.'::text, E'1. Kaynak talimatları (WPS) gözden geçirilmeli ve güncellenmeli; kritik kaynak noktaları için görsel kabul kriterleri belirlenmeli ve asılmalıdır.\n2. Etkilenen araçlarda kaynak hataları tespit edilerek tamir kaynağı yapılmalı veya parçalar değiştirilmelidir.\n3. Kaynak operatörlerinin sertifikasyonu ve yetkinlik durumu kontrol edilmelidir.\n4. Hat sonu kaynak görsel muayenesi kontrol listesine eklenmeli; kaynak hataları imzalı kayıt altına alınmalıdır.'::text),
  (E'DF-2026-084'::text, E'DF'::text, E'™ GRUPOZETI | Kategori : Sizdirmazlik Kagagi | Tespit Alani : Sizdirmazlik Kontrol | Toplam Kayit : 8 | Toplam Adet : 12'::text, E'Üretim sonrası yapılan sızdırmazlık testleri (8 kayıt, 12 araç) başarısız çıkmaktadır.'::text, E'Conta veya O-ring takılmamış ya da hatalı tork değerinde sıkılmıştır.'::text, E'Montaj talimatlarında conta takma adımı ve tork değeri yeterli netlikte yer almamaktadır.'::text, E'Sızdırmazlık kontrolü montaj sonrası zorunlu adım olarak tanımlanmamış veya uygulanmamaktadır.'::text, E'Kontrol listesi bu adımı içermemekte ya da operatörler atlayabilmektedir.'::text, E'Sızdırmazlık kritik parametre olarak tanımlanmamış; montaj talimatı ve kontrol listesine zorunlu test adımı olarak eklenmemiştir.'::text, E'™ GRUPOZETI | Kategori : Sizdirmazlik Kagagi | Tespit Alani : Sizdirmazlik Kontrol | Toplam Kayit : 8 | Toplam Adet : 12'::text, E'Uretim Midurligi (Ost Yapi)'::text, E'01.05.2026'::text, E'Kadir Toraman'::text, E'Sızdırmazlık kontrolü üretimde yetersiz uygulanmakta'::text, E'Üretim hattı kontrol noktası, ara ürün muayenesi veya son kontrol sırasında tespit edilmiştir.'::text, E'1. Sızdırmazlık kritik noktaları için tork değerleri, conta/o-ring takma talimatı güncellenmeli ve istasyonlara asılmalıdır.\n2. Etkilenen 12 araçta sızdırmazlık testi tekrarlanmalı; hata noktaları onarılmalıdır.\n3. Üretim hattı sızdırmazlık test istasyonu gözden geçirilmeli; basınç testi parametreleri doğrulanmalıdır.\n4. Montaj operatörlerine conta ve sızdırmazlık elemanı takma eğitimi verilmelidir.'::text),
  (E'DF-2026-085'::text, E'DF'::text, E'™ GRUPOZETI | Kategori : Eksik Elektrik Montaji | Tespit Alani : Uretilen Araclar | Toplam Kayit : 7 | Toplam Adet : 14'::text, E'Elektrik montaj hataları (7 kayıt, 14 araç) tekrarlayan nitelikte oluşmaktadır.'::text, E'Bağlantı veya kablolama hataları tespit edilmeden ürün bir sonraki aşamaya geçmektedir.'::text, E'İstasyon çıkışında basit fonksiyon testi (akım ölçümü, ışık testi vb.) yapılmamaktadır.'::text, E'Test adımı operatör talimatlarına eklenmemiş ya da zorunlu kılınmamıştır.'::text, E'Tekrarlayan elektrik montaj hataları nedeniyle talimat revizyon talebinin üretilmediği görülmektedir.'::text, E'Elektrik montaj alanında görsel talimat revizyonu ve yetkinlik bazlı işe alım/eğitim sistemi henüz kurulmamıştır.'::text, E'™ GRUPOZETI | Kategori : Eksik Elektrik Montaji | Tespit Alani : Uretilen Araclar | Toplam Kayit : 7 | Toplam Adet : 14'::text, E'Uretim Madariaga (Ust Yapi)'::text, E'01.05.2026'::text, E'Abdurrahman Bugrii'::text, E'Elektrik montaj sürecinde operatör yetkinlik yönetimi ve görsel talimatlar yetersiz'::text, E'Üretim hattı kontrol noktası, ara ürün muayenesi veya son kontrol sırasında tespit edilmiştir.'::text, E'1. Elektrik montaj talimatları her araç tipi ve ünite bazında görsellerle güncellenmeli; talimatlar istasyonlara asılmalıdır.\n2. Etkilenen 14 araçta hatalı elektrik bağlantıları düzeltilmeli, tam fonksiyon testi yapılmalıdır.\n3. Elektrik montaj operatörlerinin kablo şeması okuma ve bağlantı doğrulama yetkinliği test edilmeli; gerekirse eğitim verilmelidir.\n4. Hat sonu elektrik fonksiyon test protokolü güncellenmeli; geri görüş kamerası ve ekranı test adımları teyit listesine eklenmeli, imzalı kaydı tutulmalıdır.'::text),
  (E'DF-2026-086'::text, E'DF'::text, E'™ GRUPOZETI | Kategori : Eksik Boya Uygulamasi | Tespit Alani : Uretilen Araclar | Toplam Kayit : 6 | Toplam Adet : 14'::text, E'Boya hataları (6 kayıt, 14 araç) üretim sürecinde tekrarlayan biçimde oluşmaktadır.'::text, E'Boya uygulaması (renk, kaplama kalınlığı, aderans) standart dışı kalmaktadır.'::text, E'Boya uygulama talimatı uygulanmamakta veya eksik uygulanmaktadır.'::text, E'Talimat boyahane personeli tarafından bilinmekte ancak iş yükü veya gözetim eksikliği nedeniyle atlanmaktadır.'::text, E'Boya öncesi yüzey hazırlık (astar, yağ alma, kaplama kalınlığı ölçümü) denetimsizdir.'::text, E'Boya prosesi için hazırlık ve uygulama kontrol listesi (dipping sheet) oluşturulmamış; boyahane çıkış muayenesi sistematize edilmemiştir.'::text, E'™ GRUPOZETI | Kategori : Eksik Boya Uygulamasi | Tespit Alani : Uretilen Araclar | Toplam Kayit : 6 | Toplam Adet : 14'::text, E'Uretim Madariaga (Ust Yapi)'::text, E'01.05.2026'::text, E'Uretim Madariaga (Ust Yapi)'::text, E'Boya uygulama talimatı yetersiz veya uygulanmıyor'::text, E'Üretim hattı kontrol noktası, ara ürün muayenesi veya son kontrol sırasında tespit edilmiştir.'::text, E'1. Boya hazırlık ve uygulama talimatı (yüzey temizliği, zımpara, astar, kat sayısı) revizyona alınmalı; boyahane talimatları güncellenmeli ve asılmalıdır.\n2. Etkilenen 14 araçta boya uygunsuzlukları giderilmeli; yeniden rötüş yapılmalıdır.\n3. Boyahane operatörlerine boya hazırlık prosedürü eğitimi verilmeli; eğitim kayıt altına alınmalıdır.\n4. Boyahane çıkış kontrol formu oluşturulmalı; her araç için boya kalite onayı imzalı olarak alınmalıdır.'::text),
  (E'DF-2026-087'::text, E'DF'::text, E'™ GRUPOZETI | Kategori : Kaynak Hatas! | Tespit Alani : Hat Sonu Kontrol | Toplam Kayit : 1 | Toplam Adet : 12'::text, E'Bir kaynak hatası 12 aracı etkiler nitelikte büyük kapsamlı sonuç doğurmuştur.'::text, E'Kaynak dikişi gerekli mekanik dayanımı sağlayamamış; seri üretime yayılmıştır.'::text, E'Kaynakçı parametre sapmasını fark etmemiş ya da raporlamamıştır.'::text, E'Kaynak işlemi sırasında ara kontrol noktası bulunmamaktadır.'::text, E'WPS\'te kritik parametreler (ısı girdisi, paso sayısı) net belirtilmemiştir.'::text, E'Kaynak işleminin proses kalifikasyonu tamamlanmamış ve kritik kaynak adımlarında operatör bağımsız doğrulama yapabilecek kontrol belgesi hazırlanmamıştır.'::text, E'™ GRUPOZETI | Kategori : Kaynak Hatas! | Tespit Alani : Hat Sonu Kontrol | Toplam Kayit : 1 | Toplam Adet : 12'::text, E'Uretim Midurligi (Ost Yapi)'::text, E'01.05.2026'::text, E'Kadir Toraman'::text, E'Kaynak operasyonu sırasında parametreler (akım, hız, dolgu malzemesi) kontrol edilmemekte'::text, E'Üretim hattı kontrol noktası, ara ürün muayenesi veya son kontrol sırasında tespit edilmiştir.'::text, E'1. Kaynak talimatları (WPS) gözden geçirilmeli ve güncellenmeli; kritik kaynak noktaları için görsel kabul kriterleri belirlenmeli ve asılmalıdır.\n2. Etkilenen 12 araçta kaynak hataları tespit edilerek tamir kaynağı yapılmalı veya parçalar değiştirilmelidir.\n3. Kaynak operatörlerinin sertifikasyonu ve yetkinlik durumu kontrol edilmelidir.\n4. Hat sonu kaynak görsel muayenesi kontrol listesine eklenmeli; kaynak hataları imzalı kayıt altına alınmalıdır.'::text),
  (E'DF-2026-088'::text, E'DF'::text, E'™ GRUPOZETI | Kategori : Hatali Boya Uygulamasi | Tespit Alani : Uretilen Araclar | Toplam Kayit : 7 | Toplam Adet : 9'::text, E'Boya uygunsuzlukları (7 kayıt, 9 araç) tekrarlayan nitelikte oluşmaktadır.'::text, E'Boya kalınlığı veya renk kodu hatalı uygulanmaktadır.'::text, E'Boya hazırlama ve uygulama sırası talimatla örtüşmemektedir.'::text, E'Talimat güncellenmemiş ya da operatörler revize sürümden haberdar değildir.'::text, E'Boya talimatı güncelleme ve dağıtım mekanizması tanımlanmamıştır.'::text, E'Boya prosesinde yazılı talimat yönetimi (hazırlama, uygulama, son kontrol) ve periyodik kalibrasyon/revizyon akışı kurulmamıştır.'::text, E'™ GRUPOZETI | Kategori : Hatali Boya Uygulamasi | Tespit Alani : Uretilen Araclar | Toplam Kayit : 7 | Toplam Adet : 9'::text, E'Uretim Madariaga (Ust Yapi)'::text, E'01.05.2026'::text, E'Uretim Madariaga (Ust Yapi)'::text, E'Boya uygulama talimatı yetersiz veya uygulanmıyor'::text, E'Üretim hattı kontrol noktası, ara ürün muayenesi veya son kontrol sırasında tespit edilmiştir.'::text, E'1. Boya hazırlık ve uygulama talimatı (yüzey temizliği, zımpara, astar, kat sayısı) revizyona alınmalı; boyahane talimatları güncellenmeli ve asılmalıdır.\n2. Etkilenen 9 araçta boya uygunsuzlukları giderilmeli; yeniden rötüş yapılmalıdır.\n3. Boyahane operatörlerine boya hazırlık prosedürü eğitimi verilmeli; eğitim kayıt altına alınmalıdır.\n4. Boyahane çıkış kontrol formu oluşturulmalı; her araç için boya kalite onayı imzalı olarak alınmalıdır.'::text),
  (E'DF-2026-102'::text, E'DF'::text, E'A056762sicil numarali MUSTAFABURAKMERGENadhi caligan 17.04.2026tarihinde saat 14: 50 sirasinda fuar Cép | aracinin elektrik tesisatin! désedigi sirada ( heniiz belirlenemeyen hastaligi nedeniyle ¢galigsma sirasinda kriz ( | kasilma biling kaybi ) gegiriyor . Kriz gecirmesi sonucu bulundugu yerden diistiyor. Gevrede bulunan arkadaslar | midahale ederek caligani giivenli bélgeye aliyor. Caligana ilk yardim yapildiktan sonra ambulans ile Beyhekim | Devlet hastanesine sevk edilmistir . Yapilan kontrollerde diismeye bagli doku zedelenmesi oldugu tespit edilmistir .'::text, E'Elektrik montaj hataları büyük hacimde araç etkileyecek şekilde tekrarlanmaktadır.'::text, E'Kablolama veya bağlantı hataları hat çıkışında tespit edilememektedir.'::text, E'Elektrik montaj sonrası fonksiyon testi istasyon bazında uygulanmamaktadır.'::text, E'Fonksiyon test prosedürü tanımlanmış olsa bile istasyonda zorunlu adım olarak uygulanmamaktadır.'::text, E'Operatör yetkinlik değerlendirmesi ve sertifikasyon sistemi elektrik montaj için oluşturulmamıştır.'::text, E'Elektrik montaj istasyonlarında görsel talimat, yetkinlik yönetimi ve zorunlu çıkış test mekanizması sistematik olarak kurgulanmamıştır.'::text, E'A056762sicil numarali MUSTAFABURAKMERGENadhi caligan 17.04.2026tarihinde saat 14: 50 sirasinda fuar Cép | aracinin elekt'::text, E'Uretim Midirligi (Ust Yap)'::text, E'29.05.2026'::text, E'Abdurrahman Bigrii'::text, E'Elektrik montaj sürecinde operatör yetkinlik yönetimi ve görsel talimatlar yetersiz'::text, E'Üretim hattı kontrol noktası, ara ürün muayenesi veya son kontrol sırasında tespit edilmiştir.'::text, E'1. Elektrik montaj talimatları her araç tipi ve ünite bazında görsellerle güncellenmeli; talimatlar istasyonlara asılmalıdır.\n2. Etkilenen araçlarda hatalı elektrik bağlantıları düzeltilmeli, tam fonksiyon testi yapılmalıdır.\n3. Elektrik montaj operatörlerinin kablo şeması okuma ve bağlantı doğrulama yetkinliği test edilmeli; gerekirse eğitim verilmelidir.\n4. Hat sonu elektrik fonksiyon test protokolü güncellenmeli; geri görüş kamerası ve ekranı test adımları teyit listesine eklenmeli, imzalı kaydı tutulmalıdır.'::text),
  (E'DF-2026-017'::text, E'DF'::text, E'Boya rétus islemleri yapilirken gerekli hazirlik yapilmadigi (kaynak yanigindan kabaran boyalar temizlenmeden | kazinip zimpara yapilmadan izerine boya yapildig! ) ve rétus isleminin yapilmasi gereken genis alana degil de daha | kiigiik ve belirsizligi_saglanmadan yapildigi tespit edilmistir . | (1. hata rétus yapilan yiizeyin hazirlanmamasini 2. hata rétus islemini belli olmadan yapilmasina 6zen | gésterilmedigi_ konusundadir .) Konular hakkinda aksiyon alinmalidir. Rétus dizensizligi konulu oldugu igin ayr! DF'::text, E'Boya rötüş sonrası yüzeyler kalite standartlarını karşılamamaktadır.'::text, E'Rötüş sonrası boya yüzeyi istenilen yapışma ve görünüm kalitesini sağlayamamaktadır.'::text, E'Rötüş öncesinde kaynak yanıkları ve kir temizlenmemiş; astar uygulanmamıştır.'::text, E'Rötüş talimatı yüzey hazırlık adımlarını (zımpara, solvent temizleme, astar) detaylı tarif etmemektedir.'::text, E'Boyahane personeli rötüş prosedürünü kısa kesmekte; hazırlık adımları zaman baskısı ile atlanmaktadır.'::text, E'Rötüş prosesi standart talimatla tanımlanmamış; hazırlık adımlarının uygulanmasını zorunlu kılan kontrol mekanizması kurulmamıştır.'::text, E'Boya rétus islemleri yapilirken gerekli hazirlik yapilmadigi (kaynak yanigindan kabaran boyalar temizlenmeden | kazinip'::text, E'Boyahane'::text, E'Belirtilmemiş'::text, E'Sefa inan'::text, E'Boya rötüş işlemi öncesinde yüzey hazırlık prosedürüne (kaynak yanıklarının temizlenmesi, zımpara, astar) uyulmamakta'::text, E'Boya kabul muayenesi veya görsel kontrol sırasında tespit edilmiştir.'::text, E'1. Boya rötüş talimatı revizyona alınmalı; kaynak yanığı temizliği → zımpara → astar → kat boya sırasına göre adım adım görsellerle hazırlanmalı ve boyahaneye asılmalıdır.\n2. Boyahane operatörlerine yüzey hazırlık ve rötüş prosedürü eğitimi verilmeli; imzalı katılım kaydı tutulmalıdır.\n3. Günlük çalışma başı kısa teftiş uygulaması başlatılmalı; amirler boya hazırlık adımlarını spot kontrol etmelidir.\n4. Uygun olmayan boya işlemi tespit edildiğinde \'dur-düzelt-devam et\' yetkisi tanımlanmalıdır.'::text)
  ) AS t(nc_number, typ, problem_def, symptom, why1, why2, why3, why4, why5, ne, nerede, ne_zaman, kim, neden, nasil, actions_text)
)
UPDATE non_conformities n
SET
  five_n1k_analysis = jsonb_build_object(
    'ne', to_jsonb(x.ne),
    'nerede', to_jsonb(x.nerede),
    'neZaman', to_jsonb(x.ne_zaman),
    'kim', to_jsonb(x.kim),
    'neden', to_jsonb(x.neden),
    'nasil', to_jsonb(x.nasil)
  ),
  five_why_analysis = jsonb_build_object(
    'problem', to_jsonb(x.problem_def),
    'why1', to_jsonb(x.why1),
    'why2', to_jsonb(x.why2),
    'why3', to_jsonb(x.why3),
    'why4', to_jsonb(x.why4),
    'why5', to_jsonb(x.why5),
    'rootCause', to_jsonb(x.why5),
    'immediateAction', to_jsonb(x.neden),
    'preventiveAction', to_jsonb(x.actions_text)
  ),
  eight_d_steps = CASE
    WHEN n.type = '8D' THEN
      jsonb_set(
        jsonb_set(
          COALESCE(n.eight_d_steps, '{}'::jsonb),
          '{D4,description}',
          to_jsonb(
            ('5 Neden (özet)'::text || E'\n\n' ||
             '1. ' || x.why1 || E'\n' ||
             '2. ' || x.why2 || E'\n' ||
             '3. ' || x.why3 || E'\n' ||
             '4. ' || x.why4 || E'\n' ||
             '5 (Kök): ' || x.why5)::text
          ),
          true
        ),
        '{D5,description}',
        to_jsonb(('Önerilen düzeltici faaliyetler'::text || E'\n\n' || x.actions_text)::text),
        true
      )
    ELSE n.eight_d_steps
  END,
  updated_at = now()
FROM x
WHERE n.nc_number = x.nc_number AND n.type = x.typ;
