WITH x AS (
  SELECT * FROM (VALUES
  (E'DF-2026-067'::text, E'DF'::text, E'GIRD/ KALITEKONTROLU- UYGUNSUZLUKTESPITI | MUAYENEBILGILERI | Kayit No: 26/03/071 | Muayene Tarihi: 17.03.2026 | Tedarikgi: Uzcelik Makine Ltd. Sti.'::text, E'Tedarikçiden gelen parçalarda boyutsal, görsel veya fonksiyonel uygunsuzluk tespit edilmektedir.'::text, E'Muayenede uygunsuz parçalar, sevkiyattan önce tedarikçi tarafından eleneememektedir.'::text, E'Tedarikçi çıkış kontrol noktasında kritik karakteristikler ölçülmemekte ya da kayıt tutulmamaktadır.'::text, E'Kontrol planında kritik karakteristikler tanımlanmamış veya güncel değildir.'::text, E'Tedarikçi ile yapılan teknik toplantıda kritik özellikler yeterince vurgulanmamış, kontrol planı birlikte gözden geçirilmemiştir.'::text, E'Tedarikçi geliştirme/onay sürecinde ürün kalite planı (PPAP/APQP vb.) gerektiği düzeyde oluşturulmamış ve denetlenmemiştir.'::text, E'GIRD/ KALITEKONTROLU- UYGUNSUZLUKTESPITI | MUAYENEBILGILERI | Kayit No: 26/03/071 | Muayene Tarihi: 17.03.2026 | Tedarik'::text, E'Tedarikgi'::text, E'17.04.2026'::text, E'Tedarikgi'::text, E'Tedarikçi üretim sürecinde boyutsal/görsel/fonksiyonel kalite kontrol yeterli düzeyde uygulanmamaktadır. Kontrol planınd…'::text, E'GKK (Girdi Kalite Kontrol) muayenesinde veya saha geri bildirimi ile tespit edilmiştir.'::text, E'1. Uygunsuz \'Firca Ana Baglanti Pimi\' partisi tedarikçiye iade edilmeli veya karantinaya alınmalıdır.\n2. Tedarikçiye DF-2026-067 numaralı DF kaydı iletilmeli, 15 iş günü içinde yazılı kök neden analizi ve düzeltici aksiyon planı talep edilmelidir.\n3. Tedarikçinin kontrol planı incelenmeli; kritik boyutlar ve kabul kriterleri yeniden belirlenmeli, onaylı kontrol planı alınmalıdır.\n4. Aynı tedarikçiden tekrarlayan uygunsuzluk varsa tedarikçi performans puanı düşürülmeli, alternatif tedarikçi değerlendirmesi başlatılmalıdır.'::text),
  (E'DF-2026-073'::text, E'DF'::text, E'GIRD/ KALITEKONTROLU- UYGUNSUZLUKTESPITI | MUAYENEBILGILERI | Kayit No: 26/03/110 | Muayene Tarihi: 26.03.2026 | Tedarikgi: Uzcelik Makine Ltd. Sti.'::text, E'Tedarikçiden gelen parçalarda boyutsal, görsel veya fonksiyonel uygunsuzluk tespit edilmektedir.'::text, E'Muayenede uygunsuz parçalar, sevkiyattan önce tedarikçi tarafından eleneememektedir.'::text, E'Tedarikçi çıkış kontrol noktasında kritik karakteristikler ölçülmemekte ya da kayıt tutulmamaktadır.'::text, E'Kontrol planında kritik karakteristikler tanımlanmamış veya güncel değildir.'::text, E'Tedarikçi ile yapılan teknik toplantıda kritik özellikler yeterince vurgulanmamış, kontrol planı birlikte gözden geçirilmemiştir.'::text, E'Tedarikçi geliştirme/onay sürecinde ürün kalite planı (PPAP/APQP vb.) gerektiği düzeyde oluşturulmamış ve denetlenmemiştir.'::text, E'GIRD/ KALITEKONTROLU- UYGUNSUZLUKTESPITI | MUAYENEBILGILERI | Kayit No: 26/03/110 | Muayene Tarihi: 26.03.2026 | Tedarik'::text, E'Tedarikgi'::text, E'26.04.2026'::text, E'Tedarikgi'::text, E'Tedarikçi üretim sürecinde boyutsal/görsel/fonksiyonel kalite kontrol yeterli düzeyde uygulanmamaktadır. Kontrol planınd…'::text, E'GKK (Girdi Kalite Kontrol) muayenesinde veya saha geri bildirimi ile tespit edilmiştir.'::text, E'1. Uygunsuz \'Baglanti Mili\' partisi tedarikçiye iade edilmeli veya karantinaya alınmalıdır.\n2. Tedarikçiye DF-2026-073 numaralı DF kaydı iletilmeli, 15 iş günü içinde yazılı kök neden analizi ve düzeltici aksiyon planı talep edilmelidir.\n3. Tedarikçinin kontrol planı incelenmeli; kritik boyutlar ve kabul kriterleri yeniden belirlenmeli, onaylı kontrol planı alınmalıdır.\n4. Aynı tedarikçiden tekrarlayan uygunsuzluk varsa tedarikçi performans puanı düşürülmeli, alternatif tedarikçi değerlendirmesi başlatılmalıdır.'::text),
  (E'DF-2026-074'::text, E'DF'::text, E'GIRD/ KALITEKONTROLU- UYGUNSUZLUKTESPITI | MUAYENEBILGILERI | Kayit No: 26/03/111 | Muayene Tarihi: 26.03.2026 | Tedarikgi: Uzcelik Makine Ltd. Sti.'::text, E'Tedarikçiden gelen parçalarda boyutsal, görsel veya fonksiyonel uygunsuzluk tespit edilmektedir.'::text, E'Muayenede uygunsuz parçalar, sevkiyattan önce tedarikçi tarafından eleneememektedir.'::text, E'Tedarikçi çıkış kontrol noktasında kritik karakteristikler ölçülmemekte ya da kayıt tutulmamaktadır.'::text, E'Kontrol planında kritik karakteristikler tanımlanmamış veya güncel değildir.'::text, E'Tedarikçi ile yapılan teknik toplantıda kritik özellikler yeterince vurgulanmamış, kontrol planı birlikte gözden geçirilmemiştir.'::text, E'Tedarikçi geliştirme/onay sürecinde ürün kalite planı (PPAP/APQP vb.) gerektiği düzeyde oluşturulmamış ve denetlenmemiştir.'::text, E'GIRD/ KALITEKONTROLU- UYGUNSUZLUKTESPITI | MUAYENEBILGILERI | Kayit No: 26/03/111 | Muayene Tarihi: 26.03.2026 | Tedarik'::text, E'Tedarikgi'::text, E'26.04.2026'::text, E'Tedarikgi'::text, E'Tedarikçi üretim sürecinde boyutsal/görsel/fonksiyonel kalite kontrol yeterli düzeyde uygulanmamaktadır. Kontrol planınd…'::text, E'GKK (Girdi Kalite Kontrol) muayenesinde veya saha geri bildirimi ile tespit edilmiştir.'::text, E'1. Uygunsuz \'Baglanti Mili\' partisi tedarikçiye iade edilmeli veya karantinaya alınmalıdır.\n2. Tedarikçiye DF-2026-074 numaralı DF kaydı iletilmeli, 15 iş günü içinde yazılı kök neden analizi ve düzeltici aksiyon planı talep edilmelidir.\n3. Tedarikçinin kontrol planı incelenmeli; kritik boyutlar ve kabul kriterleri yeniden belirlenmeli, onaylı kontrol planı alınmalıdır.\n4. Aynı tedarikçiden tekrarlayan uygunsuzluk varsa tedarikçi performans puanı düşürülmeli, alternatif tedarikçi değerlendirmesi başlatılmalıdır.'::text),
  (E'DF-2026-075'::text, E'DF'::text, E'GIRD/ KALITEKONTROLU- UYGUNSUZLUKTESPITI | MUAYENEBILGILERI | Kayit No: 26/03/112 | Muayene Tarihi: 26.03.2026 | Tedarikgi: Uzcelik Makine Ltd. Sti.'::text, E'Tedarikçiden gelen parçalarda boyutsal, görsel veya fonksiyonel uygunsuzluk tespit edilmektedir.'::text, E'Muayenede uygunsuz parçalar, sevkiyattan önce tedarikçi tarafından eleneememektedir.'::text, E'Tedarikçi çıkış kontrol noktasında kritik karakteristikler ölçülmemekte ya da kayıt tutulmamaktadır.'::text, E'Kontrol planında kritik karakteristikler tanımlanmamış veya güncel değildir.'::text, E'Tedarikçi ile yapılan teknik toplantıda kritik özellikler yeterince vurgulanmamış, kontrol planı birlikte gözden geçirilmemiştir.'::text, E'Tedarikçi geliştirme/onay sürecinde ürün kalite planı (PPAP/APQP vb.) gerektiği düzeyde oluşturulmamış ve denetlenmemiştir.'::text, E'GIRD/ KALITEKONTROLU- UYGUNSUZLUKTESPITI | MUAYENEBILGILERI | Kayit No: 26/03/112 | Muayene Tarihi: 26.03.2026 | Tedarik'::text, E'Tedarikgi'::text, E'26.04.2026'::text, E'Tedarikgi'::text, E'Tedarikçi üretim sürecinde boyutsal/görsel/fonksiyonel kalite kontrol yeterli düzeyde uygulanmamaktadır. Kontrol planınd…'::text, E'GKK (Girdi Kalite Kontrol) muayenesinde veya saha geri bildirimi ile tespit edilmiştir.'::text, E'1. Uygunsuz \'Yay Tutucu Mili\' partisi tedarikçiye iade edilmeli veya karantinaya alınmalıdır.\n2. Tedarikçiye DF-2026-075 numaralı DF kaydı iletilmeli, 15 iş günü içinde yazılı kök neden analizi ve düzeltici aksiyon planı talep edilmelidir.\n3. Tedarikçinin kontrol planı incelenmeli; kritik boyutlar ve kabul kriterleri yeniden belirlenmeli, onaylı kontrol planı alınmalıdır.\n4. Aynı tedarikçiden tekrarlayan uygunsuzluk varsa tedarikçi performans puanı düşürülmeli, alternatif tedarikçi değerlendirmesi başlatılmalıdır.'::text),
  (E'DF-2026-076'::text, E'DF'::text, E'GIRD/ KALITEKONTROLU- UYGUNSUZLUKTESPITI | MUAYENEBILGILERI | Kayit No: 26/03/113 | Muayene Tarihi: 26.03.2026 | Tedarikgi: Arda Cakir'::text, E'Tedarikçiden gelen parçalarda boyutsal, görsel veya fonksiyonel uygunsuzluk tespit edilmektedir.'::text, E'Muayenede uygunsuz parçalar, sevkiyattan önce tedarikçi tarafından eleneememektedir.'::text, E'Tedarikçi çıkış kontrol noktasında kritik karakteristikler ölçülmemekte ya da kayıt tutulmamaktadır.'::text, E'Kontrol planında kritik karakteristikler tanımlanmamış veya güncel değildir.'::text, E'Tedarikçi ile yapılan teknik toplantıda kritik özellikler yeterince vurgulanmamış, kontrol planı birlikte gözden geçirilmemiştir.'::text, E'Tedarikçi geliştirme/onay sürecinde ürün kalite planı (PPAP/APQP vb.) gerektiği düzeyde oluşturulmamış ve denetlenmemiştir.'::text, E'GIRD/ KALITEKONTROLU- UYGUNSUZLUKTESPITI | MUAYENEBILGILERI | Kayit No: 26/03/113 | Muayene Tarihi: 26.03.2026 | Tedarik'::text, E'Tedarikgi'::text, E'26.04.2026'::text, E'Tedarikgi'::text, E'Tedarikçi üretim sürecinde boyutsal/görsel/fonksiyonel kalite kontrol yeterli düzeyde uygulanmamaktadır. Kontrol planınd…'::text, E'GKK (Girdi Kalite Kontrol) muayenesinde veya saha geri bildirimi ile tespit edilmiştir.'::text, E'1. Uygunsuz \'Kapak Yan Kilavuz Parcasi\' partisi tedarikçiye iade edilmeli veya karantinaya alınmalıdır.\n2. Tedarikçiye DF-2026-076 numaralı DF kaydı iletilmeli, 15 iş günü içinde yazılı kök neden analizi ve düzeltici aksiyon planı talep edilmelidir.\n3. Tedarikçinin kontrol planı incelenmeli; kritik boyutlar ve kabul kriterleri yeniden belirlenmeli, onaylı kontrol planı alınmalıdır.\n4. Aynı tedarikçiden tekrarlayan uygunsuzluk varsa tedarikçi performans puanı düşürülmeli, alternatif tedarikçi değerlendirmesi başlatılmalıdır.'::text),
  (E'DF-2026-077'::text, E'DF'::text, E'Tat27301 kodu 19.02.2026 tarihinde sistemde olan aksaklik sebebi ile satinalma havuzuna diismemis ve konu ile | ilgili anlasmali oldugumuz Albil firmasina gerekli mail atilmasina ragmen déniis saglanmamistir . Konu hakkinda | aksiyon alinmasi gerekmektedir .'::text, E'Sipariş sürecinde iletişim kopukluğu veya takip eksikliği nedeniyle gecikmeler yaşanmaktadır.'::text, E'Sipariş talebi tedarikçiye veya ilgili birime ulaşmamıştır.'::text, E'Sipariş bildiriminde kullanılan kanal (e-posta, sistem mesajı) takip edilmemektedir.'::text, E'Tedarikçi/birim bildirim alındı onayı için tanımlı bir mekanizma mevcut değildir.'::text, E'Satınalma-Depo-Tedarikçi iletişim protokolü güncel değildir.'::text, E'Sipariş sürecinin uçtan uca takibini sağlayacak tanımlı bir iletişim ve eskalasyon prosedürü bulunmamaktadır.'::text, E'Tat27301 kodu 19.02.2026 tarihinde sistemde olan aksaklik sebebi ile satinalma havuzuna diismemis ve konu ile | ilgili a'::text, E'Tedarikgi'::text, E'Belirtilmemiş'::text, E'Tedarikgi'::text, E'Sistem hatası ya da takip eksikliği nedeniyle sipariş süreci aksadı'::text, E'GKK (Girdi Kalite Kontrol) muayenesinde veya saha geri bildirimi ile tespit edilmiştir.'::text, E'1. İlgili tedarikçi ile hemen iletişime geçilmeli; beklenen teslimat tarihi teyit edilmelidir.\n2. Manuel sipariş açma yetkisi ve onay prosedürü oluşturulmalıdır.\n3. Sistem üzerindeki teknik aksaklık için IT birimine bildirim yapılmalıdır.\n4. Benzer durumlar için alternatif iletişim kanalı (e-posta onayı vb.) tanımlanmalıdır.'::text),
  (E'DF-2026-080'::text, E'DF'::text, E'GIRD/ KALITEKONTROLU- UYGUNSUZLUKTESPITI | MUAYENEBILGILERI | Kayit No: 26/03/119 | Muayene Tarihi: 31.03.2026 | Tedarikgi: Saytek Tasarim Mak.kal.kons'::text, E'Tedarikçiden gelen parçalarda boyutsal, görsel veya fonksiyonel uygunsuzluk tespit edilmektedir.'::text, E'Muayenede uygunsuz parçalar, sevkiyattan önce tedarikçi tarafından eleneememektedir.'::text, E'Tedarikçi çıkış kontrol noktasında kritik karakteristikler ölçülmemekte ya da kayıt tutulmamaktadır.'::text, E'Kontrol planında kritik karakteristikler tanımlanmamış veya güncel değildir.'::text, E'Tedarikçi ile yapılan teknik toplantıda kritik özellikler yeterince vurgulanmamış, kontrol planı birlikte gözden geçirilmemiştir.'::text, E'Tedarikçi geliştirme/onay sürecinde ürün kalite planı (PPAP/APQP vb.) gerektiği düzeyde oluşturulmamış ve denetlenmemiştir.'::text, E'GIRD/ KALITEKONTROLU- UYGUNSUZLUKTESPITI | MUAYENEBILGILERI | Kayit No: 26/03/119 | Muayene Tarihi: 31.03.2026 | Tedarik'::text, E'Tedarikgi'::text, E'30.04.2026'::text, E'Tedarikgi'::text, E'Tedarikçi üretim sürecinde boyutsal/görsel/fonksiyonel kalite kontrol yeterli düzeyde uygulanmamaktadır. Kontrol planınd…'::text, E'GKK (Girdi Kalite Kontrol) muayenesinde veya saha geri bildirimi ile tespit edilmiştir.'::text, E'1. Uygunsuz \'On Dingil Merkezleme Mili\' partisi tedarikçiye iade edilmeli veya karantinaya alınmalıdır.\n2. Tedarikçiye DF-2026-080 numaralı DF kaydı iletilmeli, 15 iş günü içinde yazılı kök neden analizi ve düzeltici aksiyon planı talep edilmelidir.\n3. Tedarikçinin kontrol planı incelenmeli; kritik boyutlar ve kabul kriterleri yeniden belirlenmeli, onaylı kontrol planı alınmalıdır.\n4. Aynı tedarikçiden tekrarlayan uygunsuzluk varsa tedarikçi performans puanı düşürülmeli, alternatif tedarikçi değerlendirmesi başlatılmalıdır.'::text),
  (E'DF-2026-081'::text, E'DF'::text, E'GIRD/ KALITEKONTROLU- UYGUNSUZLUKTESPITI | MUAYENEBILGILERI | Kayit No: 26/03/120 | Muayene Tarihi: 31.03.2026 | Tedarikgi: Saytek Tasarim Mak.kal.kons'::text, E'Tedarikçiden gelen parçalarda boyutsal, görsel veya fonksiyonel uygunsuzluk tespit edilmektedir.'::text, E'Muayenede uygunsuz parçalar, sevkiyattan önce tedarikçi tarafından eleneememektedir.'::text, E'Tedarikçi çıkış kontrol noktasında kritik karakteristikler ölçülmemekte ya da kayıt tutulmamaktadır.'::text, E'Kontrol planında kritik karakteristikler tanımlanmamış veya güncel değildir.'::text, E'Tedarikçi ile yapılan teknik toplantıda kritik özellikler yeterince vurgulanmamış, kontrol planı birlikte gözden geçirilmemiştir.'::text, E'Tedarikçi geliştirme/onay sürecinde ürün kalite planı (PPAP/APQP vb.) gerektiği düzeyde oluşturulmamış ve denetlenmemiştir.'::text, E'GIRD/ KALITEKONTROLU- UYGUNSUZLUKTESPITI | MUAYENEBILGILERI | Kayit No: 26/03/120 | Muayene Tarihi: 31.03.2026 | Tedarik'::text, E'Tedarikgi'::text, E'30.04.2026'::text, E'Ozcan Gilleg'::text, E'Tedarikçi üretim sürecinde boyutsal/görsel/fonksiyonel kalite kontrol yeterli düzeyde uygulanmamaktadır. Kontrol planınd…'::text, E'GKK (Girdi Kalite Kontrol) muayenesinde veya saha geri bildirimi ile tespit edilmiştir.'::text, E'1. Uygunsuz \'Salyangoz Fan Mafsal Rakoru\' partisi tedarikçiye iade edilmeli veya karantinaya alınmalıdır.\n2. Tedarikçiye DF-2026-081 numaralı DF kaydı iletilmeli, 15 iş günü içinde yazılı kök neden analizi ve düzeltici aksiyon planı talep edilmelidir.\n3. Tedarikçinin kontrol planı incelenmeli; kritik boyutlar ve kabul kriterleri yeniden belirlenmeli, onaylı kontrol planı alınmalıdır.\n4. Aynı tedarikçiden tekrarlayan uygunsuzluk varsa tedarikçi performans puanı düşürülmeli, alternatif tedarikçi değerlendirmesi başlatılmalıdır.'::text),
  (E'DF-2026-089'::text, E'DF'::text, E'GIRD/ KALITEKONTROLU- UYGUNSUZLUKTESPITI | MUAYENEBILGILERI | Kayit No: 26/04/007 | Muayene Tarihi: 01.04.2026 | Tedarikgi: Dh Makine Ltd. Sti'::text, E'Tedarikçiden gelen parçalarda boyutsal, görsel veya fonksiyonel uygunsuzluk tespit edilmektedir.'::text, E'Muayenede uygunsuz parçalar, sevkiyattan önce tedarikçi tarafından eleneememektedir.'::text, E'Tedarikçi çıkış kontrol noktasında kritik karakteristikler ölçülmemekte ya da kayıt tutulmamaktadır.'::text, E'Kontrol planında kritik karakteristikler tanımlanmamış veya güncel değildir.'::text, E'Tedarikçi ile yapılan teknik toplantıda kritik özellikler yeterince vurgulanmamış, kontrol planı birlikte gözden geçirilmemiştir.'::text, E'Tedarikçi geliştirme/onay sürecinde ürün kalite planı (PPAP/APQP vb.) gerektiği düzeyde oluşturulmamış ve denetlenmemiştir.'::text, E'GIRD/ KALITEKONTROLU- UYGUNSUZLUKTESPITI | MUAYENEBILGILERI | Kayit No: 26/04/007 | Muayene Tarihi: 01.04.2026 | Tedarik'::text, E'Tedarikgi'::text, E'01.05.2026'::text, E'Tedarikgi'::text, E'Tedarikçi üretim sürecinde boyutsal/görsel/fonksiyonel kalite kontrol yeterli düzeyde uygulanmamaktadır. Kontrol planınd…'::text, E'GKK (Girdi Kalite Kontrol) muayenesinde veya saha geri bildirimi ile tespit edilmiştir.'::text, E'1. Uygunsuz \'Kazan Baglanti Mili\' partisi tedarikçiye iade edilmeli veya karantinaya alınmalıdır.\n2. Tedarikçiye DF-2026-089 numaralı DF kaydı iletilmeli, 15 iş günü içinde yazılı kök neden analizi ve düzeltici aksiyon planı talep edilmelidir.\n3. Tedarikçinin kontrol planı incelenmeli; kritik boyutlar ve kabul kriterleri yeniden belirlenmeli, onaylı kontrol planı alınmalıdır.\n4. Aynı tedarikçiden tekrarlayan uygunsuzluk varsa tedarikçi performans puanı düşürülmeli, alternatif tedarikçi değerlendirmesi başlatılmalıdır.'::text),
  (E'DF-2026-090'::text, E'DF'::text, E'GIRDi KALITEKONTROLU- UYGUNSUZLUKTESPITIMUAYENEBILGILERI Kayit No: 26/04/016 Muayene Tarihi: | 06.04.2026 Tedarikgi : Civata Ve Metal San.tic. A.s Parga Adi: Firga Yataklama Mili Parga Kodu : 37-5000103019 Gelen | Miktar : 30 adet Kontrol Edilen Miktar : 30 adet Nihai Karar: Sartl Kabul OLCUM SONUGLARIVE TESPITLER | UYGUNSUZBULUNAN OLGUMLER Fonksiyone! Ozellik (Olgiim 1/6): Beklenen D'::text, E'Tedarikçiden gelen parçalarda boyutsal, görsel veya fonksiyonel uygunsuzluk tespit edilmektedir.'::text, E'Muayenede uygunsuz parçalar, sevkiyattan önce tedarikçi tarafından eleneememektedir.'::text, E'Tedarikçi çıkış kontrol noktasında kritik karakteristikler ölçülmemekte ya da kayıt tutulmamaktadır.'::text, E'Kontrol planında kritik karakteristikler tanımlanmamış veya güncel değildir.'::text, E'Tedarikçi ile yapılan teknik toplantıda kritik özellikler yeterince vurgulanmamış, kontrol planı birlikte gözden geçirilmemiştir.'::text, E'Tedarikçi geliştirme/onay sürecinde ürün kalite planı (PPAP/APQP vb.) gerektiği düzeyde oluşturulmamış ve denetlenmemiştir.'::text, E'GIRDi KALITEKONTROLU- UYGUNSUZLUKTESPITIMUAYENEBILGILERI Kayit No: 26/04/016 Muayene Tarihi: | 06.04.2026 Tedarikgi : Ci'::text, E'Tedarikgi'::text, E'06.05.2026'::text, E'Tedarikgi'::text, E'Tedarikçi üretim sürecinde boyutsal/görsel/fonksiyonel kalite kontrol yeterli düzeyde uygulanmamaktadır. Kontrol planınd…'::text, E'GKK (Girdi Kalite Kontrol) muayenesinde veya saha geri bildirimi ile tespit edilmiştir.'::text, E'1. Uygunsuz \'Firga Yataklama Mili Parga Kodu : 37-5000103019 Gelen\' partisi tedarikçiye iade edilmeli veya karantinaya alınmalıdır.\n2. Tedarikçiye DF-2026-090 numaralı DF kaydı iletilmeli, 15 iş günü içinde yazılı kök neden analizi ve düzeltici aksiyon planı talep edilmelidir.\n3. Tedarikçinin kontrol planı incelenmeli; kritik boyutlar ve kabul kriterleri yeniden belirlenmeli, onaylı kontrol planı alınmalıdır.\n4. Aynı tedarikçiden tekrarlayan uygunsuzluk varsa tedarikçi performans puanı düşürülmeli, alternatif tedarikçi değerlendirmesi başlatılmalıdır.'::text),
  (E'DF-2026-091'::text, E'DF'::text, E'GIRDIKALITEKONTROLU- UYGUNSUZLUKTESPITIMUAYENEBILGILERI Kayit No: 26/04/028 Muayene Tarihi: | 07.04.2026 Tedarikci: Dh Makine Ltd. $ti Parga Adi: Manyetik Bariyer Saplamasi Parga Kodu: 37-5000215189 Gelen | Miktar : 2 adet Kontrol Edilen Miktar : 2 adet Nihai Karar : Sartl Kabul OLGUM SONUCLARIVE TESPITLERUYGUNSUZ | BULUNAN OLCUMLER Minér Ozellik (Olgiim 1/1): Beklenen Deger (Nomina'::text, E'Tedarikçiden gelen parçalarda boyutsal, görsel veya fonksiyonel uygunsuzluk tespit edilmektedir.'::text, E'Muayenede uygunsuz parçalar, sevkiyattan önce tedarikçi tarafından eleneememektedir.'::text, E'Tedarikçi çıkış kontrol noktasında kritik karakteristikler ölçülmemekte ya da kayıt tutulmamaktadır.'::text, E'Kontrol planında kritik karakteristikler tanımlanmamış veya güncel değildir.'::text, E'Tedarikçi ile yapılan teknik toplantıda kritik özellikler yeterince vurgulanmamış, kontrol planı birlikte gözden geçirilmemiştir.'::text, E'Tedarikçi geliştirme/onay sürecinde ürün kalite planı (PPAP/APQP vb.) gerektiği düzeyde oluşturulmamış ve denetlenmemiştir.'::text, E'GIRDIKALITEKONTROLU- UYGUNSUZLUKTESPITIMUAYENEBILGILERI Kayit No: 26/04/028 Muayene Tarihi: | 07.04.2026 Tedarikci: Dh M'::text, E'Tedarikgi'::text, E'07.05.2026'::text, E'Tedarikgi'::text, E'Tedarikçi üretim sürecinde boyutsal/görsel/fonksiyonel kalite kontrol yeterli düzeyde uygulanmamaktadır. Kontrol planınd…'::text, E'GKK (Girdi Kalite Kontrol) muayenesinde veya saha geri bildirimi ile tespit edilmiştir.'::text, E'1. Uygunsuz \'Manyetik Bariyer Saplamasi Parga Kodu: 37-5000215189 Gelen\' partisi tedarikçiye iade edilmeli veya karantinaya alınmalıdır.\n2. Tedarikçiye DF-2026-091 numaralı DF kaydı iletilmeli, 15 iş günü içinde yazılı kök neden analizi ve düzeltici aksiyon planı talep edilmelidir.\n3. Tedarikçinin kontrol planı incelenmeli; kritik boyutlar ve kabul kriterleri yeniden belirlenmeli, onaylı kontrol planı alınmalıdır.\n4. Aynı tedarikçiden tekrarlayan uygunsuzluk varsa tedarikçi performans puanı düşürülmeli, alternatif tedarikçi değerlendirmesi başlatılmalıdır.'::text),
  (E'DF-2026-092'::text, E'DF'::text, E'GIRDIKALITEKONTROLU- UYGUNSUZLUKTESPITIMUAYENEBILGILERI Kayit No: 26/04/029 Muayene Tarihi: | 07.04.2026 Tedarikci: Dh Makine Ltd. $ti Parga Adi: Manyetik Bariyer Saplamasi Parga Kodu: 37-5000215194 Gelen | Miktar : 2 adet Kontrol Edilen Miktar : 2 adet Nihai Karar : Sartl Kabul OLGUM SONUCLARIVE TESPITLERUYGUNSUZ | BULUNAN OLCUMLER Minér Ozellik (Olgiim 1/1): Beklenen Deger (Nomina'::text, E'Tedarikçiden gelen parçalarda boyutsal, görsel veya fonksiyonel uygunsuzluk tespit edilmektedir.'::text, E'Muayenede uygunsuz parçalar, sevkiyattan önce tedarikçi tarafından eleneememektedir.'::text, E'Tedarikçi çıkış kontrol noktasında kritik karakteristikler ölçülmemekte ya da kayıt tutulmamaktadır.'::text, E'Kontrol planında kritik karakteristikler tanımlanmamış veya güncel değildir.'::text, E'Tedarikçi ile yapılan teknik toplantıda kritik özellikler yeterince vurgulanmamış, kontrol planı birlikte gözden geçirilmemiştir.'::text, E'Tedarikçi geliştirme/onay sürecinde ürün kalite planı (PPAP/APQP vb.) gerektiği düzeyde oluşturulmamış ve denetlenmemiştir.'::text, E'GIRDIKALITEKONTROLU- UYGUNSUZLUKTESPITIMUAYENEBILGILERI Kayit No: 26/04/029 Muayene Tarihi: | 07.04.2026 Tedarikci: Dh M'::text, E'Tedarikgi'::text, E'07.05.2026'::text, E'Tedarikgi'::text, E'Tedarikçi üretim sürecinde boyutsal/görsel/fonksiyonel kalite kontrol yeterli düzeyde uygulanmamaktadır. Kontrol planınd…'::text, E'GKK (Girdi Kalite Kontrol) muayenesinde veya saha geri bildirimi ile tespit edilmiştir.'::text, E'1. Uygunsuz \'Manyetik Bariyer Saplamasi Parga Kodu: 37-5000215194 Gelen\' partisi tedarikçiye iade edilmeli veya karantinaya alınmalıdır.\n2. Tedarikçiye DF-2026-092 numaralı DF kaydı iletilmeli, 15 iş günü içinde yazılı kök neden analizi ve düzeltici aksiyon planı talep edilmelidir.\n3. Tedarikçinin kontrol planı incelenmeli; kritik boyutlar ve kabul kriterleri yeniden belirlenmeli, onaylı kontrol planı alınmalıdır.\n4. Aynı tedarikçiden tekrarlayan uygunsuzluk varsa tedarikçi performans puanı düşürülmeli, alternatif tedarikçi değerlendirmesi başlatılmalıdır.'::text)
  ) AS t(nc_number, typ, problem_def, symptom, why1, why2, why3, why4, why5, ne, nerede, ne_zaman, kim, neden, nasil, actions_text)
)
UPDATE non_conformities n
SET
  five_n1k_analysis = jsonb_build_object(
    'ne', to_jsonb(x.ne),
    'nerede', to_jsonb(x.nerede),
    'neZaman', to_jsonb(x.ne_zaman),
    'kim', to_jsonb(x.kim),
    'neden', to_jsonb(x.neden),
    'nasil', to_jsonb(x.nasil)
  ),
  five_why_analysis = jsonb_build_object(
    'problem', to_jsonb(x.problem_def),
    'why1', to_jsonb(x.why1),
    'why2', to_jsonb(x.why2),
    'why3', to_jsonb(x.why3),
    'why4', to_jsonb(x.why4),
    'why5', to_jsonb(x.why5),
    'rootCause', to_jsonb(x.why5),
    'immediateAction', to_jsonb(x.neden),
    'preventiveAction', to_jsonb(x.actions_text)
  ),
  eight_d_steps = CASE
    WHEN n.type = '8D' THEN
      jsonb_set(
        jsonb_set(
          COALESCE(n.eight_d_steps, '{}'::jsonb),
          '{D4,description}',
          to_jsonb(
            ('5 Neden (özet)'::text || E'\n\n' ||
             '1. ' || x.why1 || E'\n' ||
             '2. ' || x.why2 || E'\n' ||
             '3. ' || x.why3 || E'\n' ||
             '4. ' || x.why4 || E'\n' ||
             '5 (Kök): ' || x.why5)::text
          ),
          true
        ),
        '{D5,description}',
        to_jsonb(('Önerilen düzeltici faaliyetler'::text || E'\n\n' || x.actions_text)::text),
        true
      )
    ELSE n.eight_d_steps
  END,
  updated_at = now()
FROM x
WHERE n.nc_number = x.nc_number AND n.type = x.typ;
