WITH x AS (
  SELECT * FROM (VALUES
  (E'DF-2026-018'::text, E'DF'::text, E'GIRD/ KALITEKONTROLU- UYGUNSUZLUKTESPITI | MUAYENEBILGILERI | Kayit No: 26/01/079 | Muayene Tarihi: 14.01.2026 | Tedarikgi: Baloglu Hidrolik Mak.san.'::text, E'Tedarikçiden gelen parçalarda boyutsal, görsel veya fonksiyonel uygunsuzluk tespit edilmektedir.'::text, E'Muayenede uygunsuz parçalar, sevkiyattan önce tedarikçi tarafından eleneememektedir.'::text, E'Tedarikçi çıkış kontrol noktasında kritik karakteristikler ölçülmemekte ya da kayıt tutulmamaktadır.'::text, E'Kontrol planında kritik karakteristikler tanımlanmamış veya güncel değildir.'::text, E'Tedarikçi ile yapılan teknik toplantıda kritik özellikler yeterince vurgulanmamış, kontrol planı birlikte gözden geçirilmemiştir.'::text, E'Tedarikçi geliştirme/onay sürecinde ürün kalite planı (PPAP/APQP vb.) gerektiği düzeyde oluşturulmamış ve denetlenmemiştir.'::text, E'GIRD/ KALITEKONTROLU- UYGUNSUZLUKTESPITI | MUAYENEBILGILERI | Kayit No: 26/01/079 | Muayene Tarihi: 14.01.2026 | Tedarik'::text, E'Tedarikgi'::text, E'14.02.2026'::text, E'Tedarikgi'::text, E'Tedarikçi üretim sürecinde boyutsal/görsel/fonksiyonel kalite kontrol yeterli düzeyde uygulanmamaktadır. Kontrol planınd…'::text, E'GKK (Girdi Kalite Kontrol) muayenesinde veya saha geri bildirimi ile tespit edilmiştir.'::text, E'1. Uygunsuz \'Arka Kapak Silindiri\' partisi tedarikçiye iade edilmeli veya karantinaya alınmalıdır.\n2. Tedarikçiye DF-2026-018 numaralı DF kaydı iletilmeli, 15 iş günü içinde yazılı kök neden analizi ve düzeltici aksiyon planı talep edilmelidir.\n3. Tedarikçinin kontrol planı incelenmeli; kritik boyutlar ve kabul kriterleri yeniden belirlenmeli, onaylı kontrol planı alınmalıdır.\n4. Aynı tedarikçiden tekrarlayan uygunsuzluk varsa tedarikçi performans puanı düşürülmeli, alternatif tedarikçi değerlendirmesi başlatılmalıdır.'::text),
  (E'DF-2026-019'::text, E'DF'::text, E'Mustafa Geng firmasi tarafindan Uretilen AGA2100 kazanlarda , ekli teknik resimde belirtilen kaldirma kilic! boy | dlgistintin 977 mm olmasi gerekirken 968 mm olarak kesildigi ve bu sekilde kazan izerine hatali konumda | kaynatildigi tespit edilmistir . | Bu hataya bagli olarak kazanin hidrolik silindir ve arag sasesine baGlanti merkezleri 7-9 mm ice dogru kaymis, | kazan mevcut haliyle montaj yapilmaya uygun olmayan bir duruma gelmistir .'::text, E'Tedarikçiden gelen parçalarda boyutsal sapma ve tolerans dışı üretim tespit edilmektedir.'::text, E'Üretilen parçalar tolerans bandının dışında çıkmaktadır.'::text, E'Tezgah ayarları hatalı yapılmış veya kalibrasyon periyoduna uyulmamıştır.'::text, E'Tezgah kalibrasyon ve bakım planı uygulanmamakta ya da kayıt tutulmamaktadır.'::text, E'Tedarikçi iç kalite sisteminde ölçüm teçhizatı yönetimi prosedürü eksik veya işlevsizdir.'::text, E'Tedarikçide boyutsal uygunluğu garanti edecek istatistiksel proses kontrol (SPC) veya süreç yeterliliği (Cpk) uygulaması bulunmamaktadır.'::text, E'Mustafa Geng firmasi tarafindan Uretilen AGA2100 kazanlarda , ekli teknik resimde belirtilen kaldirma kilic! boy | dlgis'::text, E'Tedarikgi'::text, E'19.02.2026'::text, E'Tedarikgi'::text, E'Tedarikçi üretiminde boyutsal kontrol yeterli düzeyde uygulanmamakta'::text, E'GKK (Girdi Kalite Kontrol) muayenesinde veya saha geri bildirimi ile tespit edilmiştir.'::text, E'1. Uygunsuz parti iade edilmeli; tedarikçiden düzeltilmiş parti talep edilmelidir.\n2. Tedarikçi ölçüm cihazlarının kalibrasyonu kontrol edilmeli, gerekirse Gage R&R çalışması yapılması talep edilmelidir.\n3. Kritik boyutlar için tedarikçi ilk numune onay (PPAP) sürecine alınmalıdır.\n4. Tekrarlayan boyutsal hatalar için tedarikçi üretim tezgahlarına bakım-onarım yapılması takip edilmelidir.'::text),
  (E'DF-2026-022'::text, E'DF'::text, E'GIRD/ KALITEKONTROLU- UYGUNSUZLUKTESPITI | MUAYENEBILGILERI | Kayit No: 26/01/146 | Muayene Tarihi: 29.01.2026 | Tedarikgi: Ozkan Makine Ltd. Sti.'::text, E'Tedarikçiden gelen parçalarda boyutsal, görsel veya fonksiyonel uygunsuzluk tespit edilmektedir.'::text, E'Muayenede uygunsuz parçalar, sevkiyattan önce tedarikçi tarafından eleneememektedir.'::text, E'Tedarikçi çıkış kontrol noktasında kritik karakteristikler ölçülmemekte ya da kayıt tutulmamaktadır.'::text, E'Kontrol planında kritik karakteristikler tanımlanmamış veya güncel değildir.'::text, E'Tedarikçi ile yapılan teknik toplantıda kritik özellikler yeterince vurgulanmamış, kontrol planı birlikte gözden geçirilmemiştir.'::text, E'Tedarikçi geliştirme/onay sürecinde ürün kalite planı (PPAP/APQP vb.) gerektiği düzeyde oluşturulmamış ve denetlenmemiştir.'::text, E'GIRD/ KALITEKONTROLU- UYGUNSUZLUKTESPITI | MUAYENEBILGILERI | Kayit No: 26/01/146 | Muayene Tarihi: 29.01.2026 | Tedarik'::text, E'Tedarikgi'::text, E'28.02.2026'::text, E'Erdogan Zengin'::text, E'Tedarikçi üretim sürecinde boyutsal/görsel/fonksiyonel kalite kontrol yeterli düzeyde uygulanmamaktadır. Kontrol planınd…'::text, E'GKK (Girdi Kalite Kontrol) muayenesinde veya saha geri bildirimi ile tespit edilmiştir.'::text, E'1. Uygunsuz \'Jcb74kw Motor Pompa Kampanasi\' partisi tedarikçiye iade edilmeli veya karantinaya alınmalıdır.\n2. Tedarikçiye DF-2026-022 numaralı DF kaydı iletilmeli, 15 iş günü içinde yazılı kök neden analizi ve düzeltici aksiyon planı talep edilmelidir.\n3. Tedarikçinin kontrol planı incelenmeli; kritik boyutlar ve kabul kriterleri yeniden belirlenmeli, onaylı kontrol planı alınmalıdır.\n4. Aynı tedarikçiden tekrarlayan uygunsuzluk varsa tedarikçi performans puanı düşürülmeli, alternatif tedarikçi değerlendirmesi başlatılmalıdır.'::text),
  (E'DF-2026-023'::text, E'DF'::text, E'GIRD/ KALITEKONTROLU- UYGUNSUZLUKTESPITI | MUAYENEBILGILERI | Kayit No: 26/01/118 | Muayene Tarihi: 23.01.2026 | Tedarikgi: Ozkan Makine Ltd. Sti.'::text, E'Tedarikçiden gelen parçalarda boyutsal, görsel veya fonksiyonel uygunsuzluk tespit edilmektedir.'::text, E'Muayenede uygunsuz parçalar, sevkiyattan önce tedarikçi tarafından eleneememektedir.'::text, E'Tedarikçi çıkış kontrol noktasında kritik karakteristikler ölçülmemekte ya da kayıt tutulmamaktadır.'::text, E'Kontrol planında kritik karakteristikler tanımlanmamış veya güncel değildir.'::text, E'Tedarikçi ile yapılan teknik toplantıda kritik özellikler yeterince vurgulanmamış, kontrol planı birlikte gözden geçirilmemiştir.'::text, E'Tedarikçi geliştirme/onay sürecinde ürün kalite planı (PPAP/APQP vb.) gerektiği düzeyde oluşturulmamış ve denetlenmemiştir.'::text, E'GIRD/ KALITEKONTROLU- UYGUNSUZLUKTESPITI | MUAYENEBILGILERI | Kayit No: 26/01/118 | Muayene Tarihi: 23.01.2026 | Tedarik'::text, E'Tedarikgi'::text, E'23.02.2026'::text, E'Erdogan Zengin'::text, E'Tedarikçi üretim sürecinde boyutsal/görsel/fonksiyonel kalite kontrol yeterli düzeyde uygulanmamaktadır. Kontrol planınd…'::text, E'GKK (Girdi Kalite Kontrol) muayenesinde veya saha geri bildirimi ile tespit edilmiştir.'::text, E'1. Uygunsuz \'Pervane Baglantisi Kaynakli Komple\' partisi tedarikçiye iade edilmeli veya karantinaya alınmalıdır.\n2. Tedarikçiye DF-2026-023 numaralı DF kaydı iletilmeli, 15 iş günü içinde yazılı kök neden analizi ve düzeltici aksiyon planı talep edilmelidir.\n3. Tedarikçinin kontrol planı incelenmeli; kritik boyutlar ve kabul kriterleri yeniden belirlenmeli, onaylı kontrol planı alınmalıdır.\n4. Aynı tedarikçiden tekrarlayan uygunsuzluk varsa tedarikçi performans puanı düşürülmeli, alternatif tedarikçi değerlendirmesi başlatılmalıdır.'::text),
  (E'DF-2026-026'::text, E'DF'::text, E'GIRD/ KALITEKONTROLU- UYGUNSUZLUKTESPITI | MUAYENEBILGILERI | Kayit No: 26/01/061 | Muayene Tarihi: 13.01.2026 | Tedarikgi: Civata Ve Metal San.tic. A.s'::text, E'Tedarikçiden gelen parçalarda boyutsal, görsel veya fonksiyonel uygunsuzluk tespit edilmektedir.'::text, E'Muayenede uygunsuz parçalar, sevkiyattan önce tedarikçi tarafından eleneememektedir.'::text, E'Tedarikçi çıkış kontrol noktasında kritik karakteristikler ölçülmemekte ya da kayıt tutulmamaktadır.'::text, E'Kontrol planında kritik karakteristikler tanımlanmamış veya güncel değildir.'::text, E'Tedarikçi ile yapılan teknik toplantıda kritik özellikler yeterince vurgulanmamış, kontrol planı birlikte gözden geçirilmemiştir.'::text, E'Tedarikçi geliştirme/onay sürecinde ürün kalite planı (PPAP/APQP vb.) gerektiği düzeyde oluşturulmamış ve denetlenmemiştir.'::text, E'GIRD/ KALITEKONTROLU- UYGUNSUZLUKTESPITI | MUAYENEBILGILERI | Kayit No: 26/01/061 | Muayene Tarihi: 13.01.2026 | Tedarik'::text, E'Tedarikgi'::text, E'13.02.2026'::text, E'Tedarikgi'::text, E'Tedarikçi üretim sürecinde boyutsal/görsel/fonksiyonel kalite kontrol yeterli düzeyde uygulanmamaktadır. Kontrol planınd…'::text, E'GKK (Girdi Kalite Kontrol) muayenesinde veya saha geri bildirimi ile tespit edilmiştir.'::text, E'1. Uygunsuz \'Konveyor Mafsal Civatasi\' partisi tedarikçiye iade edilmeli veya karantinaya alınmalıdır.\n2. Tedarikçiye DF-2026-026 numaralı DF kaydı iletilmeli, 15 iş günü içinde yazılı kök neden analizi ve düzeltici aksiyon planı talep edilmelidir.\n3. Tedarikçinin kontrol planı incelenmeli; kritik boyutlar ve kabul kriterleri yeniden belirlenmeli, onaylı kontrol planı alınmalıdır.\n4. Aynı tedarikçiden tekrarlayan uygunsuzluk varsa tedarikçi performans puanı düşürülmeli, alternatif tedarikçi değerlendirmesi başlatılmalıdır.'::text),
  (E'DF-2026-027'::text, E'DF'::text, E'GIRD/ KALITEKONTROLU- UYGUNSUZLUKTESPITI | MUAYENEBILGILERI | Kayit No: 26/01/147 | Muayene Tarihi: 29.01.2026 | Tedarikgi: Uzcelik Makine Ltd. Sti.'::text, E'Tedarikçiden gelen parçalarda boyutsal, görsel veya fonksiyonel uygunsuzluk tespit edilmektedir.'::text, E'Muayenede uygunsuz parçalar, sevkiyattan önce tedarikçi tarafından eleneememektedir.'::text, E'Tedarikçi çıkış kontrol noktasında kritik karakteristikler ölçülmemekte ya da kayıt tutulmamaktadır.'::text, E'Kontrol planında kritik karakteristikler tanımlanmamış veya güncel değildir.'::text, E'Tedarikçi ile yapılan teknik toplantıda kritik özellikler yeterince vurgulanmamış, kontrol planı birlikte gözden geçirilmemiştir.'::text, E'Tedarikçi geliştirme/onay sürecinde ürün kalite planı (PPAP/APQP vb.) gerektiği düzeyde oluşturulmamış ve denetlenmemiştir.'::text, E'GIRD/ KALITEKONTROLU- UYGUNSUZLUKTESPITI | MUAYENEBILGILERI | Kayit No: 26/01/147 | Muayene Tarihi: 29.01.2026 | Tedarik'::text, E'Tedarikgi'::text, E'28.02.2026'::text, E'Tedarikgi'::text, E'Tedarikçi üretim sürecinde boyutsal/görsel/fonksiyonel kalite kontrol yeterli düzeyde uygulanmamaktadır. Kontrol planınd…'::text, E'GKK (Girdi Kalite Kontrol) muayenesinde veya saha geri bildirimi ile tespit edilmiştir.'::text, E'1. Uygunsuz \'Arka Firga Silindir Pimi\' partisi tedarikçiye iade edilmeli veya karantinaya alınmalıdır.\n2. Tedarikçiye DF-2026-027 numaralı DF kaydı iletilmeli, 15 iş günü içinde yazılı kök neden analizi ve düzeltici aksiyon planı talep edilmelidir.\n3. Tedarikçinin kontrol planı incelenmeli; kritik boyutlar ve kabul kriterleri yeniden belirlenmeli, onaylı kontrol planı alınmalıdır.\n4. Aynı tedarikçiden tekrarlayan uygunsuzluk varsa tedarikçi performans puanı düşürülmeli, alternatif tedarikçi değerlendirmesi başlatılmalıdır.'::text),
  (E'DF-2026-031'::text, E'DF'::text, E'GIRD/ KALITEKONTROLU- UYGUNSUZLUKTESPITI | MUAYENEBILGILERI | Kayit No: 26/02/038 | Muayene Tarihi: 09.02.2026 | Tedarikgi: Saytek Tasarim Mak.kal.kons'::text, E'Tedarikçiden gelen parçalarda boyutsal, görsel veya fonksiyonel uygunsuzluk tespit edilmektedir.'::text, E'Muayenede uygunsuz parçalar, sevkiyattan önce tedarikçi tarafından eleneememektedir.'::text, E'Tedarikçi çıkış kontrol noktasında kritik karakteristikler ölçülmemekte ya da kayıt tutulmamaktadır.'::text, E'Kontrol planında kritik karakteristikler tanımlanmamış veya güncel değildir.'::text, E'Tedarikçi ile yapılan teknik toplantıda kritik özellikler yeterince vurgulanmamış, kontrol planı birlikte gözden geçirilmemiştir.'::text, E'Tedarikçi geliştirme/onay sürecinde ürün kalite planı (PPAP/APQP vb.) gerektiği düzeyde oluşturulmamış ve denetlenmemiştir.'::text, E'GIRD/ KALITEKONTROLU- UYGUNSUZLUKTESPITI | MUAYENEBILGILERI | Kayit No: 26/02/038 | Muayene Tarihi: 09.02.2026 | Tedarik'::text, E'Tedarikgi'::text, E'Belirtilmemiş'::text, E'Kiirgad Atalay'::text, E'Tedarikçi üretim sürecinde boyutsal/görsel/fonksiyonel kalite kontrol yeterli düzeyde uygulanmamaktadır. Kontrol planınd…'::text, E'GKK (Girdi Kalite Kontrol) muayenesinde veya saha geri bildirimi ile tespit edilmiştir.'::text, E'1. Uygunsuz \'Salyongoz Fan Mafsal Rakoru Kontra Somunu\' partisi tedarikçiye iade edilmeli veya karantinaya alınmalıdır.\n2. Tedarikçiye DF-2026-031 numaralı DF kaydı iletilmeli, 15 iş günü içinde yazılı kök neden analizi ve düzeltici aksiyon planı talep edilmelidir.\n3. Tedarikçinin kontrol planı incelenmeli; kritik boyutlar ve kabul kriterleri yeniden belirlenmeli, onaylı kontrol planı alınmalıdır.\n4. Aynı tedarikçiden tekrarlayan uygunsuzluk varsa tedarikçi performans puanı düşürülmeli, alternatif tedarikçi değerlendirmesi başlatılmalıdır.'::text),
  (E'DF-2026-033'::text, E'DF'::text, E'GIRD/ KALITEKONTROLU- UYGUNSUZLUKTESPITI | MUAYENEBILGILERI | Kayit No: 26/02/039 | Muayene Tarihi: 09.02.2026 | Tedarikgi: Saytek Tasarim Mak.kal.kons'::text, E'Tedarikçiden gelen parçalarda boyutsal, görsel veya fonksiyonel uygunsuzluk tespit edilmektedir.'::text, E'Muayenede uygunsuz parçalar, sevkiyattan önce tedarikçi tarafından eleneememektedir.'::text, E'Tedarikçi çıkış kontrol noktasında kritik karakteristikler ölçülmemekte ya da kayıt tutulmamaktadır.'::text, E'Kontrol planında kritik karakteristikler tanımlanmamış veya güncel değildir.'::text, E'Tedarikçi ile yapılan teknik toplantıda kritik özellikler yeterince vurgulanmamış, kontrol planı birlikte gözden geçirilmemiştir.'::text, E'Tedarikçi geliştirme/onay sürecinde ürün kalite planı (PPAP/APQP vb.) gerektiği düzeyde oluşturulmamış ve denetlenmemiştir.'::text, E'GIRD/ KALITEKONTROLU- UYGUNSUZLUKTESPITI | MUAYENEBILGILERI | Kayit No: 26/02/039 | Muayene Tarihi: 09.02.2026 | Tedarik'::text, E'Tedarikgi'::text, E'Belirtilmemiş'::text, E'Tedarikgi'::text, E'Tedarikçi üretim sürecinde boyutsal/görsel/fonksiyonel kalite kontrol yeterli düzeyde uygulanmamaktadır. Kontrol planınd…'::text, E'GKK (Girdi Kalite Kontrol) muayenesinde veya saha geri bildirimi ile tespit edilmiştir.'::text, E'1. Uygunsuz \'Mentese Mili\' partisi tedarikçiye iade edilmeli veya karantinaya alınmalıdır.\n2. Tedarikçiye DF-2026-033 numaralı DF kaydı iletilmeli, 15 iş günü içinde yazılı kök neden analizi ve düzeltici aksiyon planı talep edilmelidir.\n3. Tedarikçinin kontrol planı incelenmeli; kritik boyutlar ve kabul kriterleri yeniden belirlenmeli, onaylı kontrol planı alınmalıdır.\n4. Aynı tedarikçiden tekrarlayan uygunsuzluk varsa tedarikçi performans puanı düşürülmeli, alternatif tedarikçi değerlendirmesi başlatılmalıdır.'::text),
  (E'DF-2026-034'::text, E'DF'::text, E'GIRD/ KALITEKONTROLU- UYGUNSUZLUKTESPITI | MUAYENEBILGILERI | Kayit No: 26/02/040 | Muayene Tarihi: 09.02.2026 | Tedarikgi: Saytek Tasarim Mak.kal.kons'::text, E'Tedarikçiden gelen parçalarda boyutsal, görsel veya fonksiyonel uygunsuzluk tespit edilmektedir.'::text, E'Muayenede uygunsuz parçalar, sevkiyattan önce tedarikçi tarafından eleneememektedir.'::text, E'Tedarikçi çıkış kontrol noktasında kritik karakteristikler ölçülmemekte ya da kayıt tutulmamaktadır.'::text, E'Kontrol planında kritik karakteristikler tanımlanmamış veya güncel değildir.'::text, E'Tedarikçi ile yapılan teknik toplantıda kritik özellikler yeterince vurgulanmamış, kontrol planı birlikte gözden geçirilmemiştir.'::text, E'Tedarikçi geliştirme/onay sürecinde ürün kalite planı (PPAP/APQP vb.) gerektiği düzeyde oluşturulmamış ve denetlenmemiştir.'::text, E'GIRD/ KALITEKONTROLU- UYGUNSUZLUKTESPITI | MUAYENEBILGILERI | Kayit No: 26/02/040 | Muayene Tarihi: 09.02.2026 | Tedarik'::text, E'Tedarikgi'::text, E'Belirtilmemiş'::text, E'Tedarikgi'::text, E'Tedarikçi üretim sürecinde boyutsal/görsel/fonksiyonel kalite kontrol yeterli düzeyde uygulanmamaktadır. Kontrol planınd…'::text, E'GKK (Girdi Kalite Kontrol) muayenesinde veya saha geri bildirimi ile tespit edilmiştir.'::text, E'1. Uygunsuz \'Vakum Agzi Baglanti Burcu\' partisi tedarikçiye iade edilmeli veya karantinaya alınmalıdır.\n2. Tedarikçiye DF-2026-034 numaralı DF kaydı iletilmeli, 15 iş günü içinde yazılı kök neden analizi ve düzeltici aksiyon planı talep edilmelidir.\n3. Tedarikçinin kontrol planı incelenmeli; kritik boyutlar ve kabul kriterleri yeniden belirlenmeli, onaylı kontrol planı alınmalıdır.\n4. Aynı tedarikçiden tekrarlayan uygunsuzluk varsa tedarikçi performans puanı düşürülmeli, alternatif tedarikçi değerlendirmesi başlatılmalıdır.'::text),
  (E'DF-2026-035'::text, E'DF'::text, E'GIRD/ KALITEKONTROLU- UYGUNSUZLUKTESPITI | MUAYENEBILGILERI | Kayit No: 26/02/041 | Muayene Tarihi: 09.02.2026 | Tedarikgi: Saytek Tasarim Mak.kal.kons'::text, E'Tedarikçiden gelen parçalarda boyutsal, görsel veya fonksiyonel uygunsuzluk tespit edilmektedir.'::text, E'Muayenede uygunsuz parçalar, sevkiyattan önce tedarikçi tarafından eleneememektedir.'::text, E'Tedarikçi çıkış kontrol noktasında kritik karakteristikler ölçülmemekte ya da kayıt tutulmamaktadır.'::text, E'Kontrol planında kritik karakteristikler tanımlanmamış veya güncel değildir.'::text, E'Tedarikçi ile yapılan teknik toplantıda kritik özellikler yeterince vurgulanmamış, kontrol planı birlikte gözden geçirilmemiştir.'::text, E'Tedarikçi geliştirme/onay sürecinde ürün kalite planı (PPAP/APQP vb.) gerektiği düzeyde oluşturulmamış ve denetlenmemiştir.'::text, E'GIRD/ KALITEKONTROLU- UYGUNSUZLUKTESPITI | MUAYENEBILGILERI | Kayit No: 26/02/041 | Muayene Tarihi: 09.02.2026 | Tedarik'::text, E'Tedarikgi'::text, E'Belirtilmemiş'::text, E'Tedarikgi'::text, E'Tedarikçi üretim sürecinde boyutsal/görsel/fonksiyonel kalite kontrol yeterli düzeyde uygulanmamaktadır. Kontrol planınd…'::text, E'GKK (Girdi Kalite Kontrol) muayenesinde veya saha geri bildirimi ile tespit edilmiştir.'::text, E'1. Uygunsuz \'Direksiyon Silindir Burcu\' partisi tedarikçiye iade edilmeli veya karantinaya alınmalıdır.\n2. Tedarikçiye DF-2026-035 numaralı DF kaydı iletilmeli, 15 iş günü içinde yazılı kök neden analizi ve düzeltici aksiyon planı talep edilmelidir.\n3. Tedarikçinin kontrol planı incelenmeli; kritik boyutlar ve kabul kriterleri yeniden belirlenmeli, onaylı kontrol planı alınmalıdır.\n4. Aynı tedarikçiden tekrarlayan uygunsuzluk varsa tedarikçi performans puanı düşürülmeli, alternatif tedarikçi değerlendirmesi başlatılmalıdır.'::text),
  (E'DF-2026-036'::text, E'DF'::text, E'GIRD/ KALITEKONTROLU- UYGUNSUZLUKTESPITI | MUAYENEBILGILERI | Kayit No: 26/02/042 | Muayene Tarihi: 09.02.2026 | Tedarikgi: Saytek Tasarim Mak.kal.kons'::text, E'Tedarikçiden gelen parçalarda boyutsal, görsel veya fonksiyonel uygunsuzluk tespit edilmektedir.'::text, E'Muayenede uygunsuz parçalar, sevkiyattan önce tedarikçi tarafından eleneememektedir.'::text, E'Tedarikçi çıkış kontrol noktasında kritik karakteristikler ölçülmemekte ya da kayıt tutulmamaktadır.'::text, E'Kontrol planında kritik karakteristikler tanımlanmamış veya güncel değildir.'::text, E'Tedarikçi ile yapılan teknik toplantıda kritik özellikler yeterince vurgulanmamış, kontrol planı birlikte gözden geçirilmemiştir.'::text, E'Tedarikçi geliştirme/onay sürecinde ürün kalite planı (PPAP/APQP vb.) gerektiği düzeyde oluşturulmamış ve denetlenmemiştir.'::text, E'GIRD/ KALITEKONTROLU- UYGUNSUZLUKTESPITI | MUAYENEBILGILERI | Kayit No: 26/02/042 | Muayene Tarihi: 09.02.2026 | Tedarik'::text, E'Tedarikgi'::text, E'09.03.2026'::text, E'Tedarikgi'::text, E'Tedarikçi üretim sürecinde boyutsal/görsel/fonksiyonel kalite kontrol yeterli düzeyde uygulanmamaktadır. Kontrol planınd…'::text, E'GKK (Girdi Kalite Kontrol) muayenesinde veya saha geri bildirimi ile tespit edilmiştir.'::text, E'1. Uygunsuz \'Arka Firga Kaldirma Borusu\' partisi tedarikçiye iade edilmeli veya karantinaya alınmalıdır.\n2. Tedarikçiye DF-2026-036 numaralı DF kaydı iletilmeli, 15 iş günü içinde yazılı kök neden analizi ve düzeltici aksiyon planı talep edilmelidir.\n3. Tedarikçinin kontrol planı incelenmeli; kritik boyutlar ve kabul kriterleri yeniden belirlenmeli, onaylı kontrol planı alınmalıdır.\n4. Aynı tedarikçiden tekrarlayan uygunsuzluk varsa tedarikçi performans puanı düşürülmeli, alternatif tedarikçi değerlendirmesi başlatılmalıdır.'::text),
  (E'DF-2026-037'::text, E'DF'::text, E'HSCKaraci konteyner kaldirma islemini yaparken gdp konteyner kapagi HSCKaracina carpiyor. Gép dékme islemi | gergeklesmiyor . Manuel el ile kullanildiginda gdépler kazandan fazla yere dokiiliiyor .'::text, E'Tedarikçi kaynaklı kaynak, işleme veya montaj hataları ürünlere yansımaktadır.'::text, E'Uygunsuz ürünler tedarikçi sürecinde tespit edilemeden sevk edilmektedir.'::text, E'Tedarikçide kaynak/montaj prosedürüne uygunluk kontrol edilmemektedir.'::text, E'Tedarikçi proses kontrolü (parametre takibi, operatör eğitimi) yetersizdir.'::text, E'Tedarikçi FMEA ve kontrol planı revize edilmemiş; kritik proses adımları izlenmemektedir.'::text, E'Tedarikçi periyodik denetim ve sürekliliğini sağlayacak sistematik bir kalite geliştirme programı bulunmamaktadır.'::text, E'HSCKaraci konteyner kaldirma islemini yaparken gdp konteyner kapagi HSCKaracina carpiyor. Gép dékme islemi | gergeklesmi'::text, E'Tedarikgi'::text, E'09.03.2026'::text, E'Tedarikgi'::text, E'Tedarikçi üretim sürecinde yeterli kalite güvencesi uygulanmamaktadır'::text, E'GKK (Girdi Kalite Kontrol) muayenesinde veya saha geri bildirimi ile tespit edilmiştir.'::text, E'1. Tedarikçiye uygunsuzluk bildirimi yapılmalı ve yazılı aksiyon planı talep edilmelidir.\n2. Uygunsuz parçalar karantinaya alınarak iade süreci başlatılmalıdır.\n3. Tedarikçi ile teknik görüşme yapılarak kök neden doğrulanmalıdır.\n4. Tedarikçi performans değerlendirmesine bu kayıt işlenmelidir.'::text)
  ) AS t(nc_number, typ, problem_def, symptom, why1, why2, why3, why4, why5, ne, nerede, ne_zaman, kim, neden, nasil, actions_text)
)
UPDATE non_conformities n
SET
  five_n1k_analysis = jsonb_build_object(
    'ne', to_jsonb(x.ne),
    'nerede', to_jsonb(x.nerede),
    'neZaman', to_jsonb(x.ne_zaman),
    'kim', to_jsonb(x.kim),
    'neden', to_jsonb(x.neden),
    'nasil', to_jsonb(x.nasil)
  ),
  five_why_analysis = jsonb_build_object(
    'problem', to_jsonb(x.problem_def),
    'why1', to_jsonb(x.why1),
    'why2', to_jsonb(x.why2),
    'why3', to_jsonb(x.why3),
    'why4', to_jsonb(x.why4),
    'why5', to_jsonb(x.why5),
    'rootCause', to_jsonb(x.why5),
    'immediateAction', to_jsonb(x.neden),
    'preventiveAction', to_jsonb(x.actions_text)
  ),
  eight_d_steps = CASE
    WHEN n.type = '8D' THEN
      jsonb_set(
        jsonb_set(
          COALESCE(n.eight_d_steps, '{}'::jsonb),
          '{D4,description}',
          to_jsonb(
            ('5 Neden (özet)'::text || E'\n\n' ||
             '1. ' || x.why1 || E'\n' ||
             '2. ' || x.why2 || E'\n' ||
             '3. ' || x.why3 || E'\n' ||
             '4. ' || x.why4 || E'\n' ||
             '5 (Kök): ' || x.why5)::text
          ),
          true
        ),
        '{D5,description}',
        to_jsonb(('Önerilen düzeltici faaliyetler'::text || E'\n\n' || x.actions_text)::text),
        true
      )
    ELSE n.eight_d_steps
  END,
  updated_at = now()
FROM x
WHERE n.nc_number = x.nc_number AND n.type = x.typ;
