#!/usr/bin/env python3
"""One-off: build JSON for DF-2026 root cause updates from KademeQMS_Analiz_Raporu_2026.docx content."""
import json

def fw(p, w1, w2, w3, w4, w5, rc, im, pr):
    return {
        "problem": p,
        "why1": w1,
        "why2": w2,
        "why3": w3,
        "why4": w4,
        "why5": w5,
        "rootCause": rc,
        "immediateAction": im,
        "preventiveAction": pr,
    }

def ish(p, man, mat, mach, env, meas, metot):
    return {
        "problem": p,
        "man": [man],
        "material": [mat],
        "machine": [mach],
        "environment": [env],
        "measurement": [meas],
        "management": [metot],
    }

DATA = {
    "DF-2026-001": (
        fw(
            "Giriş kalite kontrolünde ve sahada kabinlerde su kaçağı tespit edildi.",
            "Giriş kalite kontrolünde ve sahada kabinlerde su kaçağı tespit edildi.",
            "Tedarikçinin üretim sürecinde sızdırmazlık testi uygulanmıyor veya yetersiz uygulanıyor.",
            "Tedarikçinin kalite kontrol planında sızdırmazlık testi parametreleri tanımlı değil.",
            "Tedarikçi ile yapılan yeterlilik görüşmelerinde bu konu kapsam dışı bırakılmış.",
            "Tedarikçi onay sürecinde sızdırmazlık test kriterleri kontrol planına dahil edilmemiştir.",
            "Tedarikçi onay sürecinde sızdırmazlık test kriterleri kontrol planına dahil edilmemiştir.",
            "Tedarikçiyle sızdırmazlık şartnamesini içeren gözden geçirilmiş teknik şartname ve onaylı numune imzalanmalıdır. Mevcut uygunsuz kabinler iade edilmeli.",
            "Tedarikçi kalite planına sızdırmazlık testi zorunlu adım olarak eklenmeli; %100 hidrostatik test veya basınç testi koşulu konulmalı.",
        ),
        ish(
            "Giriş kalite kontrolünde ve sahada kabinlerde su kaçağı tespit edildi.",
            "Tedarikçi operatörleri sızdırmazlık kontrolü konusunda eğitilmemiş.",
            "Kabin malzemesinde veya conta tasarımında değişiklik yapılmış ve Kademe'ye bildirilmemiş.",
            "Tedarikçide sızdırmazlık test ekipmanı bulunmuyor veya kalibre değil.",
            "Tedarikçi, kabin tipine göre değişen sızdırmazlık gereksinimlerini ölçemiyor.",
            "Sızdırmazlık kriterleri muayene planında yer almıyor.",
            "Tedarikçiye iletilen teknik şartnamede sızdırmazlık gereksinimleri açıkça belirtilmemiş.",
        ),
    ),
    "DF-2026-003": (
        fw(
            "11 adet Konveyor Mafsal Civatası girdi kontrolünde reddedildi. Nominal 167 mm, ölçülen 182,54 mm (sapma: +15,5 mm).",
            "11 adet Konveyor Mafsal Civatası girdi kontrolünde reddedildi. Nominal 167 mm, ölçülen 182,54 mm (sapma: +15,5 mm).",
            "Tedarikçi üretim sonrası boyutsal kontrol yapmıyor.",
            "Tedarikçide bu parçaya ait kontrol planı veya çalışma talimatı eksik/yetersiz.",
            "Parça üretim prosesi standart dışı bir bağlantı veya kesim adımı içeriyor, prosedür takip edilmiyor.",
            "Tedarikçide imalat prosesinde parça kontrolsüz kesim/işleme yapılmakta; ölçü doğrulaması üretim sonunda uygulanmamaktadır.",
            "Tedarikçide imalat prosesinde parça kontrolsüz kesim/işleme yapılmakta; ölçü doğrulaması üretim sonunda uygulanmamaktadır.",
            "11 adet parça iade edilmeli. Tedarikçiden 8D/düzeltici faaliyet ve yeni doğrulanmış parti gönderilmeli.",
            "Tedarikçi kontrol planına parça kodu 37-5000121577 için ölçüm teyit adımı eklenmeli. Tedarikçi değerlendirme puanı güncellenmeli.",
        ),
        ish(
            "11 adet Konveyor Mafsal Civatası girdi kontrolünde reddedildi.",
            "Tedarikçide üretim sorumlusu parça boyutunu kontrol etmemiş veya yanlış iş talimatı kullanılmış.",
            "Mafsal civatası hammaddesi yanlış ebat kullanılmış.",
            "Ölçüm aleti (kumpas/gönyeli) kalibrasyonu yapılmamış veya doğru kullanılmamış.",
            "Tedarikçide çevresel faktörler (hata yapmayı artıran ergonomi vb.) tanımlanmamış.",
            "Tedarikçi ölçüm sistemi analizi (MSA) yapılmamış; ölçüm hatası doğrulanmamış.",
            "Kontrol planı, bu parça kodu için boyutsal kontrol adımı içermiyor.",
        ),
    ),
    "DF-2026-005": (
        fw(
            "Müşteri şikayeti üzerine incelenen parça fonksiyonel testlerde kaçak verdi.",
            "Müşteri şikayeti üzerine incelenen parça fonksiyonel testlerde kaçak verdi.",
            "Parça tedarikçiden gelmeden önce sızdırmazlık testi yapılmamış.",
            "Girdi kalite kontrolünde fonksiyonel test kapsamına bu parça dahil edilmemiş.",
            "Parçanın fonksiyonel test gerektirdiği muayene planına yansıtılmamış.",
            "Bu parça kodunun fonksiyonel test kriter ve yöntemi muayene planında tanımlı değildir.",
            "Bu parça kodunun fonksiyonel test kriter ve yöntemi muayene planında tanımlı değildir.",
            "Mevcut stok gözden geçirilmeli; şüpheli parti sahaya çıkmadan önce %100 fonksiyonel test yapılmalı.",
            "Muayene planı güncellenerek bu parça kodu için kaçak testi zorunlu adım yapılmalı. Tedarikçiye sızdırmazlık sertifikası şartı getirilmeli.",
        ),
        ish(
            "Müşteri şikayeti üzerine incelenen parça fonksiyonel testlerde kaçak verdi.",
            "Kalite kontrol personeli parçanın kritikliğini fark etmeden görsel kontrolle bırakmış.",
            "Parçanın sızdırmazlık contaları veya hammaddesi tedarikçi tarafından değiştirilmiş olabilir.",
            "Parça test ekipmanı (kaçak test standı) mevcut değil veya kapasitesi yetersiz.",
            "Tedarikçi depolama/taşıma koşulları conta ömrünü olumsuz etkilemiş olabilir.",
            "Ölçüm kapsamı yetersiz; fonksiyonel test metodolojisi tanımlı değil.",
            "Muayene planı bu kritik parça için fonksiyonel test içermiyor.",
        ),
    ),
    "DF-2026-016": (
        fw(
            "Pompa kampanası iki kritik ölçüde tolerans dışında (219,1→217,1 mm ve 15→12,5 mm).",
            "Pompa kampanası iki kritik ölçüde tolerans dışında (219,1→217,1 mm ve 15→12,5 mm).",
            "Özkan Makine bu parçayı teknik resme göre üretmemiş.",
            "Teknik resim revizyonu tedarikçiye ulaşmamış veya güncel resim kullanılmamış.",
            "Tedarikçi ile teknik resim yönetimi ve revizyon süreci resmi olarak yapılandırılmamış.",
            "Tedarikçiye güncel teknik resim sağlanmamış veya uygulama teyidi yapılmamış.",
            "Tedarikçiye güncel teknik resim sağlanmamış veya uygulama teyidi yapılmamış.",
            "Şartlı kabul yerine parçanın kullanılabilirliği takip edilmeli. Parça izlenmeli.",
            "Teknik resim dağıtım prosedürü oluşturulmalı; tedarikçi onaylı resmin son revizyonunu kullandığını belgelemeli.",
        ),
        ish(
            "Özkan Makine — JCB 74kW Motor Pompa Kampanası ölçü hatası (şartlı kabul).",
            "Operatör eski teknik resmi kullanmış; revizyon duyurulmamış.",
            "Hammadde doğru boyutta değil veya farklı lot kullanılmış.",
            "İşleme tezgahının takım aşınması veya ayar hatası.",
            "Tedarikçi ortamındaki titreşim/sıcaklık takım ayarını etkilemiş olabilir.",
            "Tedarikçi son kontrol yapmıyor; muayene aleti kalibre değil.",
            "Teknik resim revizyon tebliği prosedürü tedarikçi ile mutabık kılınmamış.",
        ),
    ),
    "DF-2026-017": (
        fw(
            "12 adet konveyor burcu GKK'da şartlı kabul edildi. 5 ölçümde %100 uygunsuz.",
            "12 adet konveyor burcu GKK'da şartlı kabul edildi. 5 ölçümde %100 uygunsuz.",
            "Uzçelik üretim sonrası boyutsal teyit yapmıyor.",
            "Tedarikçide bu parça için bir doğrulama adımı yok.",
            "Kalite güvence adımları parça bazlı değil, parti bazlı ve seyrek uygulanıyor.",
            "Uzçelik'te bu parçaya yönelik son kontrol prosedürü tanımlı değildir.",
            "Uzçelik'te bu parçaya yönelik son kontrol prosedürü tanımlı değildir.",
            "12 adet şartlı kabul edilen parçanın kullanımı izlenmeli; kritik ölçüler yerleşik konumda doğrulanmalı.",
            "Uzçelik ile yapılacak tedarikçi denetiminde kontrol planı ve kalibrasyon kayıtları incelenmeli.",
        ),
        ish(
            "Uzçelik Makine — Konveyor Burcu ölçü hatası (şartlı kabul, 12 adet).",
            "Operatör ölçüm yapmamış.",
            "Malzeme ısıl işlem sonrası boyutsal değişime uğramış olabilir.",
            "Tezgah kalibrasyonu eksik veya takım aşınmış.",
            "Üretim ortamı sıcaklık kontrolsüz.",
            "Tedarikçide ölçüm aleti kalibrasyon kaydı yok.",
            "Parça kodu bazlı kontrol talimatı yok.",
        ),
    ),
    "DF-2026-038": (
        fw(
            "5 adet Arka Fırça Kaldırma Borusu'nda M8 diş NOK (tüm parçalar).",
            "5 adet Arka Fırça Kaldırma Borusu'nda M8 diş NOK (tüm parçalar).",
            "Saytek üretim sırasında diş açma kalitesini kontrol etmemiş.",
            "Diş açma (kılavuz) adımında hata kontrolü yok.",
            "Saytek'in iş talimatı bu parça için diş kontrolü içermiyor.",
            "Saytek'in Arka Fırça Kaldırma Borusu üretim talimatında M8 diş kalite doğrulaması yer almıyor.",
            "Saytek'in Arka Fırça Kaldırma Borusu üretim talimatında M8 diş kalite doğrulaması yer almıyor.",
            "5 adet iade. Saytek'ten düzeltilmiş parti ve kök neden raporu talep edilmeli.",
            "Saytek üretim talimatına M8 diş kontrol adımı (go/no-go) eklenmeli.",
        ),
        ish(
            "Saytek — Arka Fırça Kaldırma Borusu M8 diş hatası (5 adet, %100 ret).",
            "Operatör kılavuz diş kalitesini görmezden gelmiş.",
            "Boru malzemesinin sertliği belirtilen ölçüde değil, diş açma güçleşmiş.",
            "Kılavuz (tap) aşınmış veya kırık; parça üretilmeye devam edilmiş.",
            "Talaş birikimi diş kalitesini bozmuş.",
            "Go/no-go mastarı kullanılmıyor; diş derinliği ölçülmüyor.",
            "Diş kontrolü talimatı ve go/no-go mastarı kullanımı tanımlanmamış.",
        ),
    ),
    "DF-2026-039": (
        fw(
            "HSCK aracı konteyner kaldırırken çöp konteyner kapağı araca çarpıyor, çöp dökülemiyor veya kontrol dışı dökülüyor.",
            "HSCK aracı konteyner kaldırırken çöp konteyner kapağı araca çarpıyor, çöp dökülemiyor veya kontrol dışı dökülüyor.",
            "HSCK'nın kaldırma mekanizması bölgede kullanılan konteyner kapağı ölçüleriyle uyumsuz.",
            "Müşteri sahasındaki konteyner tipi/boyutu araç tasarım kriterlerinde dikkate alınmamış.",
            "Araç tasarımı belirli bir standart konteyner boyutuna göre yapılmış; saha diversitesi değerlendirilmemiş.",
            "Araç montaj/kabul testlerinde, bölgeye özgü konteyner boyutları kullanılarak senaryo testi yapılmamıştır.",
            "Araç montaj/kabul testlerinde, bölgeye özgü konteyner boyutları kullanılarak senaryo testi yapılmamıştır.",
            "Saha müdahalesi yapılarak kaldırma yüksekliği ve açısı ayarlanmalı. Müşteriye bilgi verilmeli.",
            "Ar-Ge ile konteyner kapağı çarpmasını önleyecek kılavuz/limitör tasarımı değerlendirilmeli. Benzer sahalar için konteyner uyumluluk testi protokolü oluşturulmalı.",
        ),
        ish(
            "HSCK aracı — Konteyner kapağı çarpma / çöp dökme sorunu (müşteri sahası).",
            "Saha testleri veya kabul sürecinde farklı konteyner tipleri denenmemiş.",
            "Konteyner kapak geometrisi standart dışı veya farklı üretici.",
            "Kaldırma mekanizması farklı kapak boyutlarına adapte edilecek şekilde ayarlanamıyor.",
            "Rüzgar, kaldırma açısı gibi çevresel faktörler kapağı iterek devreye giriyor.",
            "Saha kabul testimde çarpma mesafesi ölçülmememiş.",
            "Müşteri tesliminden önce saha kabul testi yapılmamış veya kapsamı yetersiz.",
        ),
    ),
    "DF-2026-040": (
        fw(
            "4 adet Egzoz Bağlantı Pimi tolerans dışında (12 mm yerine 12,9 mm; +%5,7 sapma).",
            "4 adet Egzoz Bağlantı Pimi tolerans dışında (12 mm yerine 12,9 mm; +%5,7 sapma).",
            "Civata Ve Metal üretim sonrası boyutsal teyit yapmıyor.",
            "Bu parça kodu için spesifik kontrol talimatı eksik.",
            "Kalite kontrol adımları yüzeysel; pim çapı doğrulanmıyor.",
            "Üretimde kullanılan kalıp/taşlama parametresi güncel teknik resimle uyumsuz kalmıştır.",
            "Üretimde kullanılan kalıp/taşlama parametresi güncel teknik resimle uyumsuz kalmıştır.",
            "4 adet iade. Tedarikçiden yeni lot ve onaylı ölçüm kaydı talep edilmeli.",
            "Civata Ve Metal kontrol planına bu parça kodu için çap kontrolü eklenmeli.",
        ),
        ish(
            "Civata Ve Metal — Egzoz Bağlantı Pimi ölçü hatası (4 adet ret).",
            "Operatör parça ölçüsünü kontrol etmemiş.",
            "Hammadde ölçüsel toleransı gevşek.",
            "İşleme tezgahı veya kalıp aşınmış; boyutsal sürükleme yaşanıyor.",
            "Çevre faktörü katkısı düşük.",
            "Tedarikçide boyutsal ölçüm metodu standartlaştırılmamış.",
            "Kontrol planında bu pim boyutu yer almıyor.",
        ),
    ),
    "DF-2026-048": (
        fw(
            "Tedarikçiden gelen radyatörde çatlak tespit edildi.",
            "Tedarikçiden gelen radyatörde çatlak tespit edildi.",
            "Radyatör temin edilmeden önce basınç testi veya görsel inceleme yapılmamış.",
            "Girdi kalite kontrolü kapsamında radyatöre yönelik kontrol kriteri tanımlanmamış.",
            "Radyatörün kritikliği göz ardı edilerek standart girdi kontrolüyle geçilmiş.",
            "Radyatör muayene planında çatlak, deformasyon ve basınç testi kriterleri yer almamaktadır.",
            "Radyatör muayene planında çatlak, deformasyon ve basınç testi kriterleri yer almamaktadır.",
            "Uygun olmayan radyatör iade. Tedarikçi muayene kriterleri güncellenmeli.",
            "Radyatör kontrol planına basınç testi (hidrostatik) ve görsel bütünlük kontrolü eklenmelidir.",
        ),
        ish(
            "Radyatör çatlağı (tedarikçi).",
            "Kalite kontrol personeli radyatör kontrolünde görsel incelemeyi yeterli saymış.",
            "Radyatör hammaddesi/kaynak kalitesi yetersiz olabilir.",
            "Basınç test stanı radyatör boyutuna uygun değil veya prosedür belirsiz.",
            "Taşıma sırasında termal veya mekanik stres uygulanmış.",
            "Çatlak tahribatsız muayene (PT/MT) yapılmadan tespit edilemez; bu test uygulanmamış.",
            "Radyatör kabulünde sadece paket bütünlüğü kontrol edilmiş.",
        ),
    ),
    "DF-2026-049": (
        fw(
            "Saytek'ten gelen parçada GKK'da ölçü hatası (Şartlı Kabul).",
            "Saytek'ten gelen parçada GKK'da ölçü hatası (Şartlı Kabul).",
            "Saytek üretim sırasında boyutsal kontrol uygulamıyor.",
            "Bu parça kodu için tedarikçi kontrol planı güncel değil.",
            "Tedarikçi kalite sistemi yeterli denetlenmemiş.",
            "Saytek'in kalite güvence sistemi bu parça tipindeki boyutsal sapmaları sürece dahil etmemektedir.",
            "Saytek'in kalite güvence sistemi bu parça tipindeki boyutsal sapmaları sürece dahil etmemektedir.",
            "Parça şartlı kabul edilmiş; kullanım sonuçları izlenmeli.",
            "Saytek denetimi planlanmalı. 10+ reddedilen DF göz önünde bulundurularak Saytek için tedarikçi geliştirme planı oluşturulmalı.",
        ),
        ish(
            "Saytek — GKK uygunsuzluğu (26/02/094).",
            "Operatör ölçüm yapmamış.",
            "Malzeme lot farklılığı.",
            "Ekipman kalibrasyonu eksik.",
            "Depolama koşulları.",
            "Ölçüm sistemi yetersiz.",
            "Kontrol planında ilgili boyut kriteri yok.",
        ),
    ),
    "DF-2026-058": (
        fw(
            "İki kritik ölçüde büyük sapma: Ø36 mm yerine 30 mm (-%16,3) ve 10 mm yerine 12 mm (+%18,8).",
            "İki kritik ölçüde büyük sapma: Ø36 mm yerine 30 mm (-%16,3) ve 10 mm yerine 12 mm (+%18,8).",
            "Özkan Makine bu parçayı teknik resme göre üretmemiş.",
            "Parça kodu için teknik resim tedarikçide güncel değil veya uygulanmıyor.",
            "Tedarikçide bu parça tipi için kalite güvence adımı tanımlanmamış.",
            "Özkan Makine'de fan pompası adaptörü için teknik resim kontrol zorunluluğu uygulanmamaktadır.",
            "Özkan Makine'de fan pompası adaptörü için teknik resim kontrol zorunluluğu uygulanmamaktadır.",
            "9 adet iade. Tedarikçiden kök neden ve %100 boyutsal doğrulanmış yeni parti talep edilmeli.",
            "Özkan Makine için bu parça kodu dahil edilmiş kontrol planı revize edilmeli.",
        ),
        ish(
            "Özkan Makine — Emiş Adaptörü Fan Pompası ölçü hatası (9 adet, ret).",
            "Tezgah operatörü yanlış program veya kalıp kullanmış.",
            "Hammadde ölçüleri farklı.",
            "İşleme tezgahı veya CNC programı hatası.",
            "Tezgah sıcaklığı/titreşim etkisi.",
            "Son kontrol kumpası veya ölçüm aleti kalibrasyonu eksik.",
            "Teknik resim revizyonu operatöre ulaşmamış.",
        ),
    ),
    "DF-2026-062": (
        fw(
            "14 adet Ön Dingil Kiti'nde hem boyutsal hem de M18x1,25 ve M8x1,5 diş hatası (tümü NOK).",
            "14 adet Ön Dingil Kiti'nde hem boyutsal hem de M18x1,25 ve M8x1,5 diş hatası (tümü NOK).",
            "Saytek Ön Dingil Kiti üretiminde hem boyutsal hem diş kontrolü yapmamış.",
            "Birden fazla kalite kriteri aynı anda başarısız olmuş; kök neden üretim sürecinin bütününde.",
            "Saytek kalite sistemi bu karmaşık parça için yetersiz kalmaktadır.",
            "Saytek'te Ön Dingil Kiti üretim sürecinde çok parametreli kalite kontrolü uygulanmamakta; hem boyut hem diş kalitesi doğrulanmadan sevkiyat yapılmaktadır.",
            "Saytek'te Ön Dingil Kiti üretim sürecinde çok parametreli kalite kontrolü uygulanmamakta; hem boyut hem diş kalitesi doğrulanmadan sevkiyat yapılmaktadır.",
            "14 adet tamamen iade. Tedarikçiden kök neden analizi ve kapsamlı düzeltici faaliyet planı talep edilmeli.",
            "Saytek'in bu seviyedeki kalite performansı tedarikçi değerlendirme sistemine yansıtılmalı. Alternatif tedarikçi araştırılmalı.",
        ),
        ish(
            "Saytek — Ön Dingil Kiti boyutsal ve diş hatası (14 adet, ret).",
            "Operatör birden fazla özelliği kontrol etmemiş.",
            "Malzeme sertlik seviyesi işlemeye uygun değil.",
            "Tezgah takımları aşınmış; hem boyut hem diş etkilenmiş.",
            "Üretim baskısı kontrol adımlarını atlatmış.",
            "Go/no-go mastarı kullanılmıyor.",
            "Kontrol talimatı bu parça tipi için tüm özellikleri kapsamıyor.",
        ),
    ),
    "DF-2026-075": (
        fw(
            "Bağlantı milinde kritik özellik: nominal 8 mm, ölçülen 0 mm (eksik delik/işlem). Ayrıca 27 mm yerine 30 mm.",
            "Bağlantı milinde kritik özellik: nominal 8 mm, ölçülen 0 mm (eksik delik/işlem). Ayrıca 27 mm yerine 30 mm.",
            "Bir boyut tamamen sıfır çıkmış — bu boyut için işlem yapılmamış veya tamamen atlanmış.",
            "Üretim sürecinde bu adım için doğrulama yapılmıyor.",
            "İş talimatı bu kritik delik/boyut adımını içermiyor.",
            "Uzçelik üretim talimatında kritik boyut için ayrı bir proses adımı tanımlanmamıştır; işlem atlanmış ve kontrol edilmemiştir.",
            "Uzçelik üretim talimatında kritik boyut için ayrı bir proses adımı tanımlanmamıştır; işlem atlanmış ve kontrol edilmemiştir.",
            "Şartlı kabul takibi zorunlu. Bu boyutsuz parçanın montajda neden olabileceği risk değerlendirilmeli.",
            "Uzçelik üretim talimatı acilen revize edilmeli. Kritik boyut için ayrı onay adımı tanımlanmalı.",
        ),
        ish(
            "Uzçelik — Bağlantı mili kritik ölçü hatası (5 adet, şartlı kabul).",
            "Operatör veya hat sorumlusu kritik adımı atlamış.",
            "Hammadde bu boyutu karşılamıyor.",
            "İlgili takım veya kalıp mevcut değildi.",
            "Çevre faktörü katkısı düşük.",
            "Kritik boyut son kontrol kapsamı dışında.",
            "İş talimatında kritik delik/boyut belirtilmemiş.",
        ),
    ),
    "DF-2026-007": (
        fw(
            "Motor stoklama alanı dış hava koşullarına açık durumda; uygunsuz stoklama tespit edildi.",
            "Motor stoklama alanı dış hava koşullarına açık durumda; uygunsuz stoklama tespit edildi.",
            "Motor stoklama için uygun kapalı bir alan tahsis edilmemiş.",
            "Depo alanı planlaması motorlar için gerekli çevre koşullarını gözetmemiş.",
            "Depo alan düzenleme standartları oluşturulurken motor özellikleri dikkate alınmamış.",
            "Depo alan planlamasında motor tipindeki hassas ekipmanlar için korumalı alan ayrılmamıştır.",
            "Depo alan planlamasında motor tipindeki hassas ekipmanlar için korumalı alan ayrılmamıştır.",
            "Motor stoklama için kapalı alan veya branda/kapak temin edilmeli. Geçici çözüm uygulanmalı.",
            "Depo yerleşim planı revize edilmeli; motor tipindeki ekipmanlar için korumalı raf/sundurma alanı tahsis edilmeli. Stoklama koşulları talimatı oluşturulmalı.",
        ),
        ish(
            "Motor stoklama alanı dış etkenlere açık ve uygunsuz.",
            "Depo personeli motorların dış ortama maruz kalmaması gerektiğini bilmemiş.",
            "Motor tipi/ağırlığı uygun bir palet/raf sistemini zorlaştırıyor.",
            "Motorları koruyacak kapalı/sundurmalı alan mevcut değil.",
            "Havanın nemi ve sıcaklık değişimleri motorları olumsuz etkiliyor.",
            "Motor stoklama koşulları için ölçüm/izleme yapılmıyor.",
            "Depolama standartları parça tipine göre segmentasyon içermiyor.",
        ),
    ),
    "DF-2026-008": (
        fw(
            "Rextroth (hidrolik kumanda) ekipmanları zeminde dağınık ve uygunsuz şekilde depolanıyor.",
            "Rextroth (hidrolik kumanda) ekipmanları zeminde dağınık ve uygunsuz şekilde depolanıyor.",
            "Rextroth ekipmanları için uygun raf veya askı sistemi sağlanmamış.",
            "Bu ekipmanların depolanmasına ilişkin talimat veya zimmet takibi yok.",
            "Depo stoklama prosedürü hassas hidrolik bileşenleri kapsamıyor.",
            "Depo stoklama talimatında Rextroth tipi hassas ekipmanlar için uygun depolama yöntemi tanımlanmamıştır.",
            "Depo stoklama talimatında Rextroth tipi hassas ekipmanlar için uygun depolama yöntemi tanımlanmamıştır.",
            "Mevcut Rextroth ekipmanları uygun palet/kasa üzerine alınmalı; zemin teması kesilmeli.",
            "Depo talimatına Rextroth tipi ekipmanlar için özel stoklama yöntemi eklenmeli. Raf/askı sistemi temin planı yapılmalı.",
        ),
        ish(
            "Rextroth ekipmanları zeminde ve uygunsuz depolanıyor.",
            "Depo personeli bu ekipmanların uygun stoklama koşullarını bilmiyor.",
            "Rextroth ekipmanları ağır ve hacimli; zeminde bırakılmış.",
            "Uygun raf/ask sistemi fiziksel olarak mevcut değil.",
            "Zemine bırakılan ekipmanlar nem ve darbeden etkileniyor.",
            "Ekipman durumu ve konumu kayıt altına alınmıyor.",
            "Talimat veya prosedürde bu parça tipi için stoklama standardı yok.",
        ),
    ),
    "DF-2026-010": (
        fw(
            "Ax sisteminde parti numarası bazlı kayıt tutulurken fiziki depoda parti ayrımı yapılmıyor.",
            "Ax sisteminde parti numarası bazlı kayıt tutulurken fiziki depoda parti ayrımı yapılmıyor.",
            "Depo personeli fiziki ürünleri Ax'taki parti yapısına göre ayırmıyor.",
            "Parti numarası bazlı ayrım yapılması gerektiği konusunda yeterli eğitim ve talimat yok.",
            "Depo prosedürü, sistemdeki parti yapısının fiziki depoya yansıtılmasını şart koşmuyor.",
            "Depo stoklama talimatı, Ax sistemindeki parti numarasının fiziksel alanda da birebir uygulanmasını zorunlu kılmamaktadır.",
            "Depo stoklama talimatı, Ax sistemindeki parti numarasının fiziksel alanda da birebir uygulanmasını zorunlu kılmamaktadır.",
            "Mevcut ürünler yeniden parti bazlı bölümlere ayrılmalı. Etiketleme yapılmalı.",
            "Depo talimatı güncellenmeli: parti numarası bazlı stoklama zorunlu yapılmalı. Ax girişi ile etiket eşleştirme prosedürü oluşturulmalı.",
        ),
        ish(
            "Ax sisteminde parti no ayrımı yapılmaması.",
            "Personel parti ayrımı konusunda eğitim almamış.",
            "Farklı partiler aynı raf/alanda yer alıyor; karışmaya uygun ortam.",
            "Depo fiziksel alanında parti bazlı bölümlendirme yok; etiketleme eksik.",
            "Parti ayrımını zorlaştıran depo düzeni.",
            "Ax'taki parti ile fiziksel ürün eşleştirmesi doğrulanmıyor.",
            "Ax sistemi ile fiziksel depo uyumu prosedüre bağlanmamış.",
        ),
    ),
    "DF-2026-011": (
        fw(
            "Ax kaydında '0 Genel Konumu'nda görünen ürünler (hatalı, bekleyen, teslim alınmamış) fiziksel depoda bulunmuyor.",
            "Ax kaydında '0 Genel Konumu'nda görünen ürünler (hatalı, bekleyen, teslim alınmamış) fiziksel depoda bulunmuyor.",
            "0 Genel Konumu soyut bir Ax kategorisi olarak kullanılıyor, fiziksel alan tanımlanmamış.",
            "Bu kategoriye giren ürünlerin fiziksel konumu belirsiz; karantina alanı oluşturulmamış.",
            "Depo prosedüründe 0 konumundaki ürünler için fiziksel alan ve izleme tanımlanmamış.",
            "Ax sisteminde '0 Genel Konumu' kategorisindeki ürünler için fiziksel bir karantina alanı ve izleme prosedürü yoktur.",
            "Ax sisteminde '0 Genel Konumu' kategorisindeki ürünler için fiziksel bir karantina alanı ve izleme prosedürü yoktur.",
            "0 Genel Konumu ürünleri için fiziksel karantina alanı oluşturulmalı; mevcut ürünler tespit edilmeli.",
            "Ax'ta 0 konumuna giren her ürün için fiziksel karantina kuralı işlemselleştirilmeli. Depo talimatı güncellenmeli.",
        ),
        ish(
            "Ax'ta 0 Genel Konumunda bulunan ürünler — fiziksel karşılığı yok.",
            "Personel bu kategorinin ne anlama geldiğini bilmiyor.",
            "Hatalı ve bekleyen ürünler diğer ürünlerle karışabilir.",
            "Fiziksel karantina alanı yok.",
            "Karantina uygulanmazsa saha koşulları ürünü olumsuz etkiler.",
            "0 konumundaki ürünler takip edilemiyor; kayıplar fark edilemiyor.",
            "Prosedürde bu kategori için fiziksel tanım eksik.",
        ),
    ),
    "DF-2026-025": (
        fw(
            "Dış işleme gönderilen ürünlerde giriş-çıkış kaydı yok; hangi işlemin yapıldığı ve ne kadar sürdüğü bilinmiyor.",
            "Dış işleme gönderilen ürünlerde giriş-çıkış kaydı yok; hangi işlemin yapıldığı ve ne kadar sürdüğü bilinmiyor.",
            "Dış kaynaklı işlem gönderim-dönüş süreci kayıt altına alınmıyor.",
            "Bu süreç için standart bir form veya talimat oluşturulmamış.",
            "Tedarikçi/dış kaynak yönetimi kapsamında dış işlem takibi prosedürü yazılmamış.",
            "Dış kaynaklı işlem sürecinde gönderim formu, iş emri ve dönüş takip mekanizması tanımlanmamıştır.",
            "Dış kaynaklı işlem sürecinde gönderim formu, iş emri ve dönüş takip mekanizması tanımlanmamıştır.",
            "Anlık düzeltme: Mevcut dış işlem stoğu sayılmalı ve belgelenmeli.",
            "Dış kaynaklı işlem formu/süreci tasarlanmalı: gönderim tarih/adet/işlem türü, dönüş teyit ve kalite onay adımı içermeli.",
        ),
        ish(
            "Dış kaynaklı işlem gönderilen ürünlerde takipsizlik.",
            "Personel kaydın zorunlu olduğunu bilmiyor.",
            "Gönderilen parça cinsi, adedi ve işlem türü takip edilemiyor.",
            "Dış işlem için kayıt formu veya sistemi mevcut değil.",
            "Dış tedarikçi ortamı ve işlem süreci kontrol dışı.",
            "Dış işlem kalitesi doğrulanamıyor; gönderilen ile gelen ürün karşılaştırılamıyor.",
            "Dış kaynak yönetimi prosedürü bu adımı içermiyor.",
        ),
    ),
    "DF-2026-080": (
        fw(
            "37-5000187765 kodlu ürün için deponun sipariş yetkisi olmadığı halde sipariş açıldı.",
            "37-5000187765 kodlu ürün için deponun sipariş yetkisi olmadığı halde sipariş açıldı.",
            "Depo personeli kanban dışı ürünlerde sipariş açma yetkisinin olmadığının farkında değil.",
            "Yetkilendirme sınırları personele yeterince duyurulmamış.",
            "Ax sistemi veya tedarik akışı, yetkisiz sipariş açılmasını önleyen kontrol içermiyor.",
            "Ax sipariş modülünde depo kullanıcıları için kanban dışı ürünlere sipariş kısıtlaması uygulanmamaktadır.",
            "Ax sipariş modülünde depo kullanıcıları için kanban dışı ürünlere sipariş kısıtlaması uygulanmamaktadır.",
            "Yetkisiz siparişin akıbeti belirlenmeli; gerekirse iptal edilmeli.",
            "Ax sipariş modülünde depo kullanıcıları için kanban dışı ürünlerde sipariş engelleyici yetki kontrolü kurulmalı.",
        ),
        ish(
            "Depo — Kanban dışı ürün için yetkisiz sipariş.",
            "Personel kanalların sınırını bilmiyor.",
            "Parça spesifik durum (stok tükenmesi vb.) personeli hızlı eylem yapmaya itti.",
            "Ax sisteminde kullanıcı bazlı sipariş yetki matrisi tanımlanmamış.",
            "Kontrol mekanizması yok.",
            "Yetkisiz sipariş Ax'ta fark edilemedi; onay adımı geçildi.",
            "Satın alma yetki prosedürü depo personelini kapsamamış.",
        ),
    ),
    "DF-2026-020": (
        fw(
            "Uygunsuz ürünler, üretim veya hat sorumlusu tarafından sapma talebi hazırlanmadan alınıp kullanılıyor.",
            "Uygunsuz ürünler, üretim veya hat sorumlusu tarafından sapma talebi hazırlanmadan alınıp kullanılıyor.",
            "Üretim personeli sapma talebi prosedürünü bilmiyor veya uygulamıyor.",
            "Sapma talebi sürecinin işlevselliği üretim hızına feda ediliyor.",
            "Kalite kontrol sapma talebini zorunlu kılacak bir süreç güvencesi uygulamıyor.",
            "Uygunsuz ürün tespitinde üretim personelinin sapma talebi prosedürünü uygulamasını zorlayan bir sistem/kontrol mekanizması yoktur.",
            "Uygunsuz ürün tespitinde üretim personelinin sapma talebi prosedürünü uygulamasını zorlayan bir sistem/kontrol mekanizması yoktur.",
            "Uygunsuz ürün depolarının fiziksel karantina ile hat arasında net sınır belirlenmeli.",
            "Üretim personeline sapma talebi prosedürü yeniden eğitim verilmeli. Hat sorumlusu kontrolünde uygunsuz ürün izin mekanizması uygulamaya alınmalı.",
        ),
        ish(
            "Sapma talebi hazırlanmadan uygunsuz ürün kullanımı.",
            "Personel uygunsuz ürünü kullanmanın hızlı bir çözüm olduğunu düşünüyor.",
            "Uygunsuz ürünler karantina alanı yerine üretim hattına bırakılıyor.",
            "Sapma formu doldurmak için zaman veya araç yokluğu.",
            "Zaman baskısı sapma prosedürünü atlatmayı teşvik ediyor.",
            "Uygunsuz ürün kaydı tutulmadığından sapma takibi yapılamıyor.",
            "Sapma prosedürü yeterince duyurulmamış veya eğitim verilmemiş.",
        ),
    ),
    "DF-2026-024": (
        fw(
            "55 KW Perkins motorlar için 190'lık pompa zorunlu MDB yayınlanmış, üretim buna rağmen 160'lık pompa kullanmaya devam etmiştir.",
            "55 KW Perkins motorlar için 190'lık pompa zorunlu MDB yayınlanmış, üretim buna rağmen 160'lık pompa kullanmaya devam etmiştir.",
            "MDB duyurusu üretim hattına etkin biçimde iletilmemiş.",
            "Üretim sorumlusu MDB'yi okuyup uygulamayı sağlamamış.",
            "MDB yayınlama süreci üretim departmanının bilgilendirilmesini garanti etmiyor.",
            "MDB yayınlama prosedürü, ilgili üretim hatlarına zorunlu onay/imzalatma adımı içermediğinden değişiklik fiilen uygulanmamıştır.",
            "MDB yayınlama prosedürü, ilgili üretim hatlarına zorunlu onay/imzalatma adımı içermediğinden değişiklik fiilen uygulanmamıştır.",
            "Stokta kalan 160'lık pompalar kaldırılmalı veya etiketlenmeli. Bu parça kodu kontrol planına eklenmeli.",
            "MDB yayın prosedürü güncellenmeli: İlgili hat sorumlusunun okudu-anladı imzası ve eski parça iadesi adımı eklenmeli.",
        ),
        ish(
            "55 KW Perkins Motor — MDB'ye rağmen 160'lık pompa kullanımı.",
            "Hat personeli yanlış pompa stoğundan almaya devam etmiş.",
            "Stokta 160'lık pompalar kalmış; personel eskiyi kullanmış.",
            "Stok alanında 160'lık pompalar hala erişilebilir konumda.",
            "Acele üretim baskısı MDB uyumunu geciktirmiş.",
            "160'lık pompa yerine 190'lık kullanılıp kullanılmadığı kontrol planında doğrulanmıyor.",
            "MDB dağıtım akışı üretim hattına tebligat mekanizması içermiyor.",
        ),
    ),
    "DF-2026-031": (
        fw(
            "Ordu üst yapıdan sökülen Fan Gövdesi Kaynaklı Komple kullanıma uygun bulunmayarak hurdaya ayrıldı. Araç bazlı hurda ağırlığı hedefin (20 kg/araç) üzerinde (31,5 kg/araç).",
            "Ordu üst yapıdan sökülen Fan Gövdesi Kaynaklı Komple kullanıma uygun bulunmayarak hurdaya ayrıldı. Araç bazlı hurda ağırlığı hedefin (20 kg/araç) üzerinde (31,5 kg/araç).",
            "Fan gövdesi sökümde hasar gördü veya montaj öncesi uygunsuz durumda geldi.",
            "Söküm sırasında fan gövdesinin korunmasına yönelik talimat/prosedür yok.",
            "Fan gövdesinin söküm ve yeniden montaj uygunluğu değerlendirilmiyor.",
            "Söküm prosedürü, fan gövdesi kaynaklı kompleksin demontajında hasar önleme adımlarını içermemektedir.",
            "Söküm prosedürü, fan gövdesi kaynaklı kompleksin demontajında hasar önleme adımlarını içermemektedir.",
            "Hurda kayıt altına alınmalı; hurda analiz raporu dosyalanmalı.",
            "Fan gövdesi demontaj talimatı hazırlanmalı. Söküm sırasında parçanın korunması için fikstür ve hassas söküm prosedürü oluşturulmalı.",
        ),
        ish(
            "Fan gövdesi kaynaklı komple — hurda (KDM 80).",
            "Söküm yapan personel parçayı hasarsız sökmek için gerekli yöntemi bilmiyor.",
            "Fan gövdesi ağır ve hassas; yanlış söküm geometri bozukluğuna neden oluyor.",
            "Uygun söküm takımları ve fikstür yok.",
            "Söküm sırasında çevresel faktörler (diğer parçaların çarpması vb.) hasara katkıda bulunuyor.",
            "Söküm sonrası parça kalitesi kontrol edilmiyor.",
            "Demontaj talimatı bu parça için hazırlanmamış.",
        ),
    ),
    "DF-2026-081": (
        fw(
            "Depo birimi tarafından açılan yetkisiz sipariş (bkz. DF-2026-080), Genel Müdür tarafından yasaklanmış olmasına rağmen onaylanmıştır.",
            "Depo birimi tarafından açılan yetkisiz sipariş (bkz. DF-2026-080), Genel Müdür tarafından yasaklanmış olmasına rağmen onaylanmıştır.",
            "Onay veren kişi siparişin yetkisiz olduğunu fark etmemiştir.",
            "Sipariş onay sürecinde sipariş açan birimin yetkisi kontrol edilmemektedir.",
            "Ax onay akışı sipariş yetkisi matrisiyle entegre değildir.",
            "Sipariş onay mekanizması, sipariş talep edenin yetki profilini ve bu parça kodu için izin durumunu doğrulayan bir kontrol içermemektedir.",
            "Sipariş onay mekanizması, sipariş talep edenin yetki profilini ve bu parça kodu için izin durumunu doğrulayan bir kontrol içermemektedir.",
            "Onayı geri alarak siparişi iptal etmek veya yetkili kişiye yönlendirmek gerekmektedir.",
            "Ax sisteminde kanban dışı siparişler için açık yetki matrisi oluşturulmalı; onay akışına 'Sipariş Yetkisi Teyit' adımı eklenmeli.",
        ),
        ish(
            "Yetkisiz depo siparişinin üst yönetim onayından geçmesi.",
            "Onaylayan kişi siparişin kaynağını/yetkisini sorgulamadan onaylamış.",
            "Parça kodu veya sipariş formu kaynağı belirsiz bırakılmış.",
            "Ax sisteminde yetki kontrolü otomatik değil; manüel incelemeye bırakılmış.",
            "Çevre faktörü katkısı yok.",
            "Ax onay ekranı yetki ihlali uyarısı vermiyor.",
            "Onay prosedürü yetki teyit adımı içermiyor.",
        ),
    ),
    "DF-2026-045": (
        fw(
            "Almaksan firmasından gelen HSCK araçlarında sevkiyat sırasında arka kapak emniyet direğinde ezilmeler tespit edildi.",
            "Almaksan firmasından gelen HSCK araçlarında sevkiyat sırasında arka kapak emniyet direğinde ezilmeler tespit edildi.",
            "Sevkiyat sırasında emniyet direği bölgesine darbe gelmektedir.",
            "Sevkiyat ambalajlama/sabitleme yöntemi emniyet direğini korumak üzere tasarlanmamıştır.",
            "Almaksan sevkiyat için özel koruma gerekliliklerini bilmemekte veya uygulamıyor.",
            "Almaksan ile mutabık kılınan sevkiyat teknik şartnamesinde emniyet direği bölgesine özel koruma zorunluluğu tanımlanmamıştır.",
            "Almaksan ile mutabık kılınan sevkiyat teknik şartnamesinde emniyet direği bölgesine özel koruma zorunluluğu tanımlanmamıştır.",
            "Almaksan'a ezilme bildirilmeli. Mevcut ezik araç onarılmalı veya revize edilmeli.",
            "Almaksan sevkiyat şartnamesine emniyet direği bölgesi için zorunlu koruyucu eleman eklenmeli. Düzenli sevkiyat denetimi planlanmalı.",
        ),
        ish(
            "Almaksan HSCK — Arka kapak emniyet direğinde ezilme (sevkiyat uygunsuzluğu).",
            "Almaksan personeli ezilme riskini görmezden gelmiş veya bilmemiş.",
            "Emniyet direği yüksekliği ve çevresinde diğer yük veya bağlantı noktaları riske açık.",
            "Emniyet direğini koruyacak köpük/kaplin veya bariyer yok.",
            "Taşıma titreşimi ve darbesi ezilmeye neden oluyor.",
            "Sevkiyat sonrası ezilme ölçülüp kayıt altına alınmıyor.",
            "Sevkiyat şartnamesinde hassas bölge listesi yok.",
        ),
    ),
    "DF-2026-051": (
        fw(
            "Kazan kapalıyken açılmasını engelleyen sistem aktif edilmemiş. SSH sahasında müşteri şikayeti. Yazılım güncellemesiyle kapatılmış.",
            "Kazan kapalıyken açılmasını engelleyen sistem aktif edilmemiş. SSH sahasında müşteri şikayeti. Yazılım güncellemesiyle kapatılmış.",
            "Yazılım özelliği test ve doğrulama aşamasında aktifleştirilmemiş.",
            "AGA6000 üretim doğrulama kontrol listesi bu güvenlik yazılım özelliğini içermiyordu.",
            "Yazılım güvenlik özellikleri kontrol planıyla entegre edilmemiş.",
            "AGA6000 üretim son kontrol prosedüründe yazılım güvenlik kilitleri doğrulama adımı tanımlı değildir.",
            "AGA6000 üretim son kontrol prosedüründe yazılım güvenlik kilitleri doğrulama adımı tanımlı değildir.",
            "Yazılım güncellemesi tüm AGA6000'lere uygulanmış (Kapatıldı).",
            "AGA6000 üretim son kontrol listesine kazan kilidi doğrulama adımı kalıcı olarak eklenmeli. Yazılım güvenlik özellik testi standart hale getirilmeli.",
        ),
        ish(
            "AGA6000 — Kazan kilitleme sistemi aktif edilmedi (Ar-Ge, kapatıldı).",
            "Yazılım geliştirici bu özelliğin üretimde aktif edilmesi gerektiğini varsaymış.",
            "Yazılım sürüm yönetimi bu özelliğin aktif durumunu takip etmemiş.",
            "Test cihazı veya ortamı bu senaryoyu test etmemiş.",
            "Çevre faktörü katkısı yok.",
            "Yazılım test metodolojisi güvenlik kilidi senaryolarını içermemiş.",
            "Üretim kontrol planı yazılım özellik testini kapsamamış.",
        ),
    ),
}


def main():
    for nc, (fwi, ishi) in DATA.items():
        jf = json.dumps(fwi, ensure_ascii=False)
        ji = json.dumps(ishi, ensure_ascii=False)
        # escape single quotes for SQL string literal
        jf = jf.replace("'", "''")
        ji = ji.replace("'", "''")
        print(
            f"UPDATE non_conformities SET five_why_analysis = '{jf}'::jsonb, ishikawa_analysis = '{ji}'::jsonb WHERE nc_number = '{nc}';"
        )


if __name__ == "__main__":
    main()
