WITH x(nc_number, typ, problem, root_cause, actions_text) AS (
  VALUES
  (E'DF-2026-078'::text, E'DF'::text, E'37-5000187765 Kodlu iiriin depo siparis yetkisinde olmadan siparis agildigi ve durumun uygunsuzlugu_tespit | edilmis olup aksiyon alinmasi gerekmektedir .'::text, E'Sipariş açma yetki matrisi ve sistem kontrolleri yeterince tanımlanmamış; yetkisiz sipariş oluşturulmasını engelleyecek sistem kilidi aktif değil.'::text, E'1. Yetkisiz açılan sipariş iptal edilmeli veya gerekli onaylardan geçirilmeli; konu kayıt altına alınmalıdır.\n2. Sipariş açma yetki matrisi gözden geçirilmeli ve sisteme işlenmelidir.\n3. Sistem üzerinde yetki dışı sipariş girişini engelleyen kontrol aktivasyonu IT birimiyle koordineli yapılmalıdır.\n4. Depo personeline hangi ürünler için sipariş açma yetkisinin olduğu yazılı olarak bildirilmeli, imzalatılmalıdır.'::text),
  (E'8D-2026-002'::text, E'8D'::text, E'MALIYETKAYDIDETAYLARI | Maliyet Turi: Hurda Maliyeti | Tarih: 15.01.2026 | Birim : Elektrik Montaj | Parga Adi: Geri Goris Kamerasi ve Ekran'::text, E'Elektrik montaj sürecinde operatör yetkinlik yönetimi ve görsel talimatlar yetersiz; fonksiyon testi mekanizması eksik.  kayıt,  araçta elektrik montaj hatası tespit edilmiş.'::text, E'1. Elektrik montaj talimatları her araç tipi ve ünite bazında görsellerle güncellenmeli; talimatlar istasyonlara asılmalıdır.\n2. Etkilenen araçlarda hatalı elektrik bağlantıları düzeltilmeli, tam fonksiyon testi yapılmalıdır.\n3. Elektrik montaj operatörlerinin kablo şeması okuma ve bağlantı doğrulama yetkinliği test edilmeli; gerekirse eğitim verilmelidir.\n4. Hat sonu elektrik fonksiyon test protokolü güncellenmeli; geri görüş kamerası ve ekranı test adımları teyit listesine eklenmeli, imzalı kaydı tutulmalıdır.'::text),
  (E'8D-2026-003'::text, E'8D'::text, E'™ GRUPOZETI | Kategori : Hatali Montaj Uygulamasi | Tespit Alani : Uretilen Araclar | Toplam Kayit : 57 | Toplam Adet : 515'::text, E'Montaj operasyonlarında görsel talimat ve kontrol listesi yetersiz; 57 kayıt, 515 araçta hatalı montaj tespit edilmiş. Operatörlerin kritik montaj adımlarına ilişkin yetkinliği doğrulanmamış.'::text, E'1. Her montaj istasyonu için güncel görsel çalışma talimatları (resimli talimat) hazırlanmalı/güncellenmeli ve istasyonlara asılmalıdır.\n2. Etkilenen 515 araçta hatalı montaj noktaları tespit edilmeli ve düzeltme çalışması yapılmalıdır.\n3. Operatör yetkinlik değerlendirmesi yapılmalı; kritik istasyonlarda yetersiz bulunan operatörlere yerinde eğitim verilmelidir.\n4. Hat sonu montaj kontrol listesi oluşturulmalı; her araçta imzalı teyit alınmalıdır.'::text),
  (E'8D-2026-004'::text, E'8D'::text, E'™ GRUPOZETI | Kategori : Eksik Montaj Uygulamasi | Tespit Alani : Uretilen Araclar | Toplam Kayit : 31 | Toplam Adet : 225'::text, E'Montaj takip sistemi yetersiz; 31 kayıt, 225 araçta eksik montaj tespit edilmiş. Kontrol listesi uygulanmıyor veya eksik kalıyor.'::text, E'1. Montaj kontrol listesi revizyona alınmalı; eksik parçalar için özel kontrol adımı eklenmeli ve imzalı onay alınmalıdır.\n2. Etkilenen 225 araçta eksik montaj tamamlanmalı; araçlar tekrar kontrol edilmelidir.\n3. Montaj operatörlerine eksik montajın neden olduğu sorunlar hakkında bilinçlendirme eğitimi verilmelidir.\n4. Hat sonu \'eksik parça kontrolü\' prosedürüne final check adımı eklenmeli; araç teslimatı bu kontrol olmadan yapılmamalıdır.'::text),
  (E'8D-2026-006'::text, E'8D'::text, E'™ GRUPOZETI | Kategori : Hatali Elektrik Montaji | Tespit Alani : Uretilen Araclar | Toplam Kayit : 15 | Toplam Adet : 35'::text, E'Elektrik montaj sürecinde operatör yetkinlik yönetimi ve görsel talimatlar yetersiz; fonksiyon testi mekanizması eksik. 15 kayıt, 35 araçta elektrik montaj hatası tespit edilmiş.'::text, E'1. Elektrik montaj talimatları her araç tipi ve ünite bazında görsellerle güncellenmeli; talimatlar istasyonlara asılmalıdır.\n2. Etkilenen 35 araçta hatalı elektrik bağlantıları düzeltilmeli, tam fonksiyon testi yapılmalıdır.\n3. Elektrik montaj operatörlerinin kablo şeması okuma ve bağlantı doğrulama yetkinliği test edilmeli; gerekirse eğitim verilmelidir.\n4. Hat sonu elektrik fonksiyon test protokolü güncellenmeli; geri görüş kamerası ve ekranı test adımları teyit listesine eklenmeli, imzalı kaydı tutulmalıdır.'::text),
  (E'8D-2026-007'::text, E'8D'::text, E'™ GRUPOZETI | Kategori : Diger | Tespit Alani : Hat Sonu Kontrol | Toplam Kayit : 3 | Toplam Adet : 42'::text, E'Üretim sürecinde prosedür/talimat uygulanmaması veya kontrol mekanizması eksikliği nedeniyle uygunsuzluk oluşmuş.'::text, E'1. İlgili üretim talimatı/prosedürü güncellenmeli; personele iletilmelidir.\n2. Etkilenen araçlarda düzeltici işlem yapılmalıdır.\n3. Hat sonu kontrol listesi bu uygunsuzluğu kapsayacak şekilde güncellenmelidir.\n4. Periyodik proses denetimi ile uyumun takibi yapılmalıdır.'::text),
  (E'8D-2026-008'::text, E'8D'::text, E'-'::text, E'Üretim sürecinde prosedür/talimat uygulanmaması veya kontrol mekanizması eksikliği nedeniyle uygunsuzluk oluşmuş.'::text, E'1. İlgili üretim talimatı/prosedürü güncellenmeli; personele iletilmelidir.\n2. Etkilenen araçlarda düzeltici işlem yapılmalıdır.\n3. Hat sonu kontrol listesi bu uygunsuzluğu kapsayacak şekilde güncellenmelidir.\n4. Periyodik proses denetimi ile uyumun takibi yapılmalıdır.'::text),
  (E'8D-2026-009'::text, E'8D'::text, E'MALIYETKAYDIDETAYLARI | Maliyet Tira: Hurda Maliyeti | Tarih: 25.06.2025 | Birim: Uretim Miidirligdé (Ust Yapi) | Parga Kodu: 7261241-1 & 7261241 -2'::text, E'Hurda maliyet kaydı açılmış; üretim hattında kontrol yetersizliği nedeniyle parça/ürün hurda olmuş.'::text, E'1. Hurda ürün için kök neden belirlenmelidir; üretim parametreleri ve talimatlar gözden geçirilmelidir.\n2. Montaj veya üretim talimatı güncellenmeli; benzer hurda riskini önlemek için önlem alınmalıdır.\n3. Operatör veya prosese yönelik düzeltici aksiyon tanımlanmalı ve takibi yapılmalıdır.\n4. Hurda parça için tedarikçiye iade veya ikame sipariş süreci başlatılmalıdır.'::text),
  (E'DF-2026-021'::text, E'DF'::text, E'AGA6000araclarimiz montajdan iktiktan sonra bazi araclarda hava tanki bosaliyor frenler devre disi kaliyor. | Konuyla ilgili aksiyon alinmasi gerekmektedir . (Devrek ve Safak temizlik araglarinda gaz kagagi meveuttur . 3. | ILERLEMENOTLARI/ YAPILANCALISMALARDevrek ve K6rfez araglari Uizerinde ;+ + + Role ventilleri kontrol edilmistir . | Fren kériikleri kontrol edilmistir Fren beyni kontrol edilm'::text, E'Üretim sürecinde prosedür/talimat uygulanmaması veya kontrol mekanizması eksikliği nedeniyle uygunsuzluk oluşmuş.'::text, E'1. İlgili üretim talimatı/prosedürü güncellenmeli; personele iletilmelidir.\n2. Etkilenen araçlarda düzeltici işlem yapılmalıdır.\n3. Hat sonu kontrol listesi bu uygunsuzluğu kapsayacak şekilde güncellenmelidir.\n4. Periyodik proses denetimi ile uyumun takibi yapılmalıdır.'::text),
  (E'DF-2026-079'::text, E'DF'::text, E'Depo birimimiz tarafindan agilan ve deponun kanban harici driinlerde siparis yetkisi olmadig genel miidiiriimiiz | tarafindan bildirilmis olup yetkisiz agilan bu siparisin onaylanmasinda uygunsuzluk tespit edilmistir .'::text, E'Üretim sürecinde prosedür/talimat uygulanmaması veya kontrol mekanizması eksikliği nedeniyle uygunsuzluk oluşmuş.'::text, E'1. İlgili üretim talimatı/prosedürü güncellenmeli; personele iletilmelidir.\n2. Etkilenen araçlarda düzeltici işlem yapılmalıdır.\n3. Hat sonu kontrol listesi bu uygunsuzluğu kapsayacak şekilde güncellenmelidir.\n4. Periyodik proses denetimi ile uyumun takibi yapılmalıdır.'::text),
  (E'DF-2026-083'::text, E'DF'::text, E'MALIYETKAYDIDETAYLARI | Maliyet Tira: Hurda Maliyeti | Tarih: 06.02.2026 | Birim: Ssh | Parga Adi: Fan Gévdesi Kaynakli Komple'::text, E'Kaynak operasyonu sırasında parametreler (akım, hız, dolgu malzemesi) kontrol edilmemekte; kaynak kalite doğrulama prosedürü yetersiz.  kayıt,  araçta kaynak hatası.'::text, E'1. Kaynak talimatları (WPS) gözden geçirilmeli ve güncellenmeli; kritik kaynak noktaları için görsel kabul kriterleri belirlenmeli ve asılmalıdır.\n2. Etkilenen araçlarda kaynak hataları tespit edilerek tamir kaynağı yapılmalı veya parçalar değiştirilmelidir.\n3. Kaynak operatörlerinin sertifikasyonu ve yetkinlik durumu kontrol edilmelidir.\n4. Hat sonu kaynak görsel muayenesi kontrol listesine eklenmeli; kaynak hataları imzalı kayıt altına alınmalıdır.'::text),
  (E'DF-2026-084'::text, E'DF'::text, E'™ GRUPOZETI | Kategori : Sizdirmazlik Kagagi | Tespit Alani : Sizdirmazlik Kontrol | Toplam Kayit : 8 | Toplam Adet : 12'::text, E'Sızdırmazlık kontrolü üretimde yetersiz uygulanmakta; conta/o-ring takma prosedürü veya tork değerleri kontrol edilmemekte. 8 kayıt, 12 araçta sızdırmazlık problemi.'::text, E'1. Sızdırmazlık kritik noktaları için tork değerleri, conta/o-ring takma talimatı güncellenmeli ve istasyonlara asılmalıdır.\n2. Etkilenen 12 araçta sızdırmazlık testi tekrarlanmalı; hata noktaları onarılmalıdır.\n3. Üretim hattı sızdırmazlık test istasyonu gözden geçirilmeli; basınç testi parametreleri doğrulanmalıdır.\n4. Montaj operatörlerine conta ve sızdırmazlık elemanı takma eğitimi verilmelidir.'::text),
  (E'DF-2026-085'::text, E'DF'::text, E'™ GRUPOZETI | Kategori : Eksik Elektrik Montaji | Tespit Alani : Uretilen Araclar | Toplam Kayit : 7 | Toplam Adet : 14'::text, E'Elektrik montaj sürecinde operatör yetkinlik yönetimi ve görsel talimatlar yetersiz; fonksiyon testi mekanizması eksik. 7 kayıt, 14 araçta elektrik montaj hatası tespit edilmiş.'::text, E'1. Elektrik montaj talimatları her araç tipi ve ünite bazında görsellerle güncellenmeli; talimatlar istasyonlara asılmalıdır.\n2. Etkilenen 14 araçta hatalı elektrik bağlantıları düzeltilmeli, tam fonksiyon testi yapılmalıdır.\n3. Elektrik montaj operatörlerinin kablo şeması okuma ve bağlantı doğrulama yetkinliği test edilmeli; gerekirse eğitim verilmelidir.\n4. Hat sonu elektrik fonksiyon test protokolü güncellenmeli; geri görüş kamerası ve ekranı test adımları teyit listesine eklenmeli, imzalı kaydı tutulmalıdır.'::text),
  (E'DF-2026-086'::text, E'DF'::text, E'™ GRUPOZETI | Kategori : Eksik Boya Uygulamasi | Tespit Alani : Uretilen Araclar | Toplam Kayit : 6 | Toplam Adet : 14'::text, E'Boya uygulama talimatı yetersiz veya uygulanmıyor; 6 kayıt, 14 araçta boya uygunsuzluğu (eksik/hatalı boya) tespit edilmiş. Hazırlık ve uygulama prosedürüne uyum kontrol edilmemektedir.'::text, E'1. Boya hazırlık ve uygulama talimatı (yüzey temizliği, zımpara, astar, kat sayısı) revizyona alınmalı; boyahane talimatları güncellenmeli ve asılmalıdır.\n2. Etkilenen 14 araçta boya uygunsuzlukları giderilmeli; yeniden rötüş yapılmalıdır.\n3. Boyahane operatörlerine boya hazırlık prosedürü eğitimi verilmeli; eğitim kayıt altına alınmalıdır.\n4. Boyahane çıkış kontrol formu oluşturulmalı; her araç için boya kalite onayı imzalı olarak alınmalıdır.'::text),
  (E'DF-2026-087'::text, E'DF'::text, E'™ GRUPOZETI | Kategori : Kaynak Hatas! | Tespit Alani : Hat Sonu Kontrol | Toplam Kayit : 1 | Toplam Adet : 12'::text, E'Kaynak operasyonu sırasında parametreler (akım, hız, dolgu malzemesi) kontrol edilmemekte; kaynak kalite doğrulama prosedürü yetersiz. 1 kayıt, 12 araçta kaynak hatası.'::text, E'1. Kaynak talimatları (WPS) gözden geçirilmeli ve güncellenmeli; kritik kaynak noktaları için görsel kabul kriterleri belirlenmeli ve asılmalıdır.\n2. Etkilenen 12 araçta kaynak hataları tespit edilerek tamir kaynağı yapılmalı veya parçalar değiştirilmelidir.\n3. Kaynak operatörlerinin sertifikasyonu ve yetkinlik durumu kontrol edilmelidir.\n4. Hat sonu kaynak görsel muayenesi kontrol listesine eklenmeli; kaynak hataları imzalı kayıt altına alınmalıdır.'::text),
  (E'DF-2026-088'::text, E'DF'::text, E'™ GRUPOZETI | Kategori : Hatali Boya Uygulamasi | Tespit Alani : Uretilen Araclar | Toplam Kayit : 7 | Toplam Adet : 9'::text, E'Boya uygulama talimatı yetersiz veya uygulanmıyor; 7 kayıt, 9 araçta boya uygunsuzluğu (eksik/hatalı boya) tespit edilmiş. Hazırlık ve uygulama prosedürüne uyum kontrol edilmemektedir.'::text, E'1. Boya hazırlık ve uygulama talimatı (yüzey temizliği, zımpara, astar, kat sayısı) revizyona alınmalı; boyahane talimatları güncellenmeli ve asılmalıdır.\n2. Etkilenen 9 araçta boya uygunsuzlukları giderilmeli; yeniden rötüş yapılmalıdır.\n3. Boyahane operatörlerine boya hazırlık prosedürü eğitimi verilmeli; eğitim kayıt altına alınmalıdır.\n4. Boyahane çıkış kontrol formu oluşturulmalı; her araç için boya kalite onayı imzalı olarak alınmalıdır.'::text),
  (E'DF-2026-102'::text, E'DF'::text, E'A056762sicil numarali MUSTAFABURAKMERGENadhi caligan 17.04.2026tarihinde saat 14: 50 sirasinda fuar Cép | aracinin elektrik tesisatin! désedigi sirada ( heniiz belirlenemeyen hastaligi nedeniyle ¢galigsma sirasinda kriz ( | kasilma biling kaybi ) gegiriyor . Kriz gecirmesi sonucu bulundugu yerden diistiyor. Gevrede bulunan arkadaslar | midahale ederek caligani giivenli bélgeye aliyor. Caligana ilk yardim yapildiktan sonra ambulans ile Beyhekim | Devlet hastanesine sevk edilmistir . Yapilan kontrollerde diismeye bagli doku zedelenmesi oldugu tespit edilmistir .'::text, E'Elektrik montaj sürecinde operatör yetkinlik yönetimi ve görsel talimatlar yetersiz; fonksiyon testi mekanizması eksik.  kayıt,  araçta elektrik montaj hatası tespit edilmiş.'::text, E'1. Elektrik montaj talimatları her araç tipi ve ünite bazında görsellerle güncellenmeli; talimatlar istasyonlara asılmalıdır.\n2. Etkilenen araçlarda hatalı elektrik bağlantıları düzeltilmeli, tam fonksiyon testi yapılmalıdır.\n3. Elektrik montaj operatörlerinin kablo şeması okuma ve bağlantı doğrulama yetkinliği test edilmeli; gerekirse eğitim verilmelidir.\n4. Hat sonu elektrik fonksiyon test protokolü güncellenmeli; geri görüş kamerası ve ekranı test adımları teyit listesine eklenmeli, imzalı kaydı tutulmalıdır.'::text),
  (E'DF-2026-017'::text, E'DF'::text, E'Boya rétus islemleri yapilirken gerekli hazirlik yapilmadigi (kaynak yanigindan kabaran boyalar temizlenmeden | kazinip zimpara yapilmadan izerine boya yapildig! ) ve rétus isleminin yapilmasi gereken genis alana degil de daha | kiigiik ve belirsizligi_saglanmadan yapildigi tespit edilmistir . | (1. hata rétus yapilan yiizeyin hazirlanmamasini 2. hata rétus islemini belli olmadan yapilmasina 6zen | gésterilmedigi_ konusundadir .) Konular hakkinda aksiyon alinmalidir. Rétus dizensizligi konulu oldugu igin ayr! DF'::text, E'Boya rötüş işlemi öncesinde yüzey hazırlık prosedürüne (kaynak yanıklarının temizlenmesi, zımpara, astar) uyulmamakta; boya uygulaması standardı dışında yapılmaktadır.'::text, E'1. Boya rötüş talimatı revizyona alınmalı; kaynak yanığı temizliği → zımpara → astar → kat boya sırasına göre adım adım görsellerle hazırlanmalı ve boyahaneye asılmalıdır.\n2. Boyahane operatörlerine yüzey hazırlık ve rötüş prosedürü eğitimi verilmeli; imzalı katılım kaydı tutulmalıdır.\n3. Günlük çalışma başı kısa teftiş uygulaması başlatılmalı; amirler boya hazırlık adımlarını spot kontrol etmelidir.\n4. Uygun olmayan boya işlemi tespit edildiğinde \'dur-düzelt-devam et\' yetkisi tanımlanmalıdır.'::text)
)
UPDATE non_conformities n
SET
  five_why_analysis = COALESCE(n.five_why_analysis, '{}'::jsonb)
    || jsonb_build_object(
      'problem', to_jsonb(x.problem),
      'rootCause', to_jsonb(x.root_cause),
      'why5', to_jsonb(x.root_cause),
      'preventiveAction', to_jsonb(x.actions_text)
    ),
  eight_d_steps = CASE
    WHEN n.type = '8D' THEN
      jsonb_set(
        jsonb_set(
          COALESCE(n.eight_d_steps, '{}'::jsonb),
          '{D4,description}',
          to_jsonb(('Kök neden (rapor özeti)'::text || E'\n\n' || x.root_cause)::text),
          true
        ),
        '{D5,description}',
        to_jsonb(('Önerilen düzeltici faaliyetler'::text || E'\n\n' || x.actions_text)::text),
        true
      )
    ELSE n.eight_d_steps
  END,
  updated_at = now()
FROM x
WHERE n.nc_number = x.nc_number AND n.type = x.typ;
