WITH x(nc_number, typ, problem, root_cause, actions_text) AS (
  VALUES
  (E'DF-2026-080'::text, E'DF'::text, E'GIRD/ KALITEKONTROLU- UYGUNSUZLUKTESPITI | MUAYENEBILGILERI | Kayit No: 26/03/119 | Muayene Tarihi: 31.03.2026 | Tedarikgi: Saytek Tasarim Mak.kal.kons'::text, E'Tedarikçi üretim sürecinde boyutsal/görsel/fonksiyonel kalite kontrol yeterli düzeyde uygulanmamaktadır. Kontrol planında kritik karakteristikler tanımlanmamış veya muayene sürecinde sapma tespit edilememiştir.'::text, E'1. Uygunsuz \'On Dingil Merkezleme Mili\' partisi tedarikçiye iade edilmeli veya karantinaya alınmalıdır.\n2. Tedarikçiye DF-2026-080 numaralı DF kaydı iletilmeli, 15 iş günü içinde yazılı kök neden analizi ve düzeltici aksiyon planı talep edilmelidir.\n3. Tedarikçinin kontrol planı incelenmeli; kritik boyutlar ve kabul kriterleri yeniden belirlenmeli, onaylı kontrol planı alınmalıdır.\n4. Aynı tedarikçiden tekrarlayan uygunsuzluk varsa tedarikçi performans puanı düşürülmeli, alternatif tedarikçi değerlendirmesi başlatılmalıdır.'::text),
  (E'DF-2026-081'::text, E'DF'::text, E'GIRD/ KALITEKONTROLU- UYGUNSUZLUKTESPITI | MUAYENEBILGILERI | Kayit No: 26/03/120 | Muayene Tarihi: 31.03.2026 | Tedarikgi: Saytek Tasarim Mak.kal.kons'::text, E'Tedarikçi üretim sürecinde boyutsal/görsel/fonksiyonel kalite kontrol yeterli düzeyde uygulanmamaktadır. Kontrol planında kritik karakteristikler tanımlanmamış veya muayene sürecinde sapma tespit edilememiştir.'::text, E'1. Uygunsuz \'Salyangoz Fan Mafsal Rakoru\' partisi tedarikçiye iade edilmeli veya karantinaya alınmalıdır.\n2. Tedarikçiye DF-2026-081 numaralı DF kaydı iletilmeli, 15 iş günü içinde yazılı kök neden analizi ve düzeltici aksiyon planı talep edilmelidir.\n3. Tedarikçinin kontrol planı incelenmeli; kritik boyutlar ve kabul kriterleri yeniden belirlenmeli, onaylı kontrol planı alınmalıdır.\n4. Aynı tedarikçiden tekrarlayan uygunsuzluk varsa tedarikçi performans puanı düşürülmeli, alternatif tedarikçi değerlendirmesi başlatılmalıdır.'::text),
  (E'DF-2026-089'::text, E'DF'::text, E'GIRD/ KALITEKONTROLU- UYGUNSUZLUKTESPITI | MUAYENEBILGILERI | Kayit No: 26/04/007 | Muayene Tarihi: 01.04.2026 | Tedarikgi: Dh Makine Ltd. Sti'::text, E'Tedarikçi üretim sürecinde boyutsal/görsel/fonksiyonel kalite kontrol yeterli düzeyde uygulanmamaktadır. Kontrol planında kritik karakteristikler tanımlanmamış veya muayene sürecinde sapma tespit edilememiştir.'::text, E'1. Uygunsuz \'Kazan Baglanti Mili\' partisi tedarikçiye iade edilmeli veya karantinaya alınmalıdır.\n2. Tedarikçiye DF-2026-089 numaralı DF kaydı iletilmeli, 15 iş günü içinde yazılı kök neden analizi ve düzeltici aksiyon planı talep edilmelidir.\n3. Tedarikçinin kontrol planı incelenmeli; kritik boyutlar ve kabul kriterleri yeniden belirlenmeli, onaylı kontrol planı alınmalıdır.\n4. Aynı tedarikçiden tekrarlayan uygunsuzluk varsa tedarikçi performans puanı düşürülmeli, alternatif tedarikçi değerlendirmesi başlatılmalıdır.'::text),
  (E'DF-2026-090'::text, E'DF'::text, E'GIRDi KALITEKONTROLU- UYGUNSUZLUKTESPITIMUAYENEBILGILERI Kayit No: 26/04/016 Muayene Tarihi: | 06.04.2026 Tedarikgi : Civata Ve Metal San.tic. A.s Parga Adi: Firga Yataklama Mili Parga Kodu : 37-5000103019 Gelen | Miktar : 30 adet Kontrol Edilen Miktar : 30 adet Nihai Karar: Sartl Kabul OLCUM SONUGLARIVE TESPITLER | UYGUNSUZBULUNAN OLGUMLER Fonksiyone! Ozellik (Olgiim 1/6): Beklenen D'::text, E'Tedarikçi üretim sürecinde boyutsal/görsel/fonksiyonel kalite kontrol yeterli düzeyde uygulanmamaktadır. Kontrol planında kritik karakteristikler tanımlanmamış veya muayene sürecinde sapma tespit edilememiştir.'::text, E'1. Uygunsuz \'Firga Yataklama Mili Parga Kodu : 37-5000103019 Gelen\' partisi tedarikçiye iade edilmeli veya karantinaya alınmalıdır.\n2. Tedarikçiye DF-2026-090 numaralı DF kaydı iletilmeli, 15 iş günü içinde yazılı kök neden analizi ve düzeltici aksiyon planı talep edilmelidir.\n3. Tedarikçinin kontrol planı incelenmeli; kritik boyutlar ve kabul kriterleri yeniden belirlenmeli, onaylı kontrol planı alınmalıdır.\n4. Aynı tedarikçiden tekrarlayan uygunsuzluk varsa tedarikçi performans puanı düşürülmeli, alternatif tedarikçi değerlendirmesi başlatılmalıdır.'::text),
  (E'DF-2026-091'::text, E'DF'::text, E'GIRDIKALITEKONTROLU- UYGUNSUZLUKTESPITIMUAYENEBILGILERI Kayit No: 26/04/028 Muayene Tarihi: | 07.04.2026 Tedarikci: Dh Makine Ltd. $ti Parga Adi: Manyetik Bariyer Saplamasi Parga Kodu: 37-5000215189 Gelen | Miktar : 2 adet Kontrol Edilen Miktar : 2 adet Nihai Karar : Sartl Kabul OLGUM SONUCLARIVE TESPITLERUYGUNSUZ | BULUNAN OLCUMLER Minér Ozellik (Olgiim 1/1): Beklenen Deger (Nomina'::text, E'Tedarikçi üretim sürecinde boyutsal/görsel/fonksiyonel kalite kontrol yeterli düzeyde uygulanmamaktadır. Kontrol planında kritik karakteristikler tanımlanmamış veya muayene sürecinde sapma tespit edilememiştir.'::text, E'1. Uygunsuz \'Manyetik Bariyer Saplamasi Parga Kodu: 37-5000215189 Gelen\' partisi tedarikçiye iade edilmeli veya karantinaya alınmalıdır.\n2. Tedarikçiye DF-2026-091 numaralı DF kaydı iletilmeli, 15 iş günü içinde yazılı kök neden analizi ve düzeltici aksiyon planı talep edilmelidir.\n3. Tedarikçinin kontrol planı incelenmeli; kritik boyutlar ve kabul kriterleri yeniden belirlenmeli, onaylı kontrol planı alınmalıdır.\n4. Aynı tedarikçiden tekrarlayan uygunsuzluk varsa tedarikçi performans puanı düşürülmeli, alternatif tedarikçi değerlendirmesi başlatılmalıdır.'::text),
  (E'DF-2026-092'::text, E'DF'::text, E'GIRDIKALITEKONTROLU- UYGUNSUZLUKTESPITIMUAYENEBILGILERI Kayit No: 26/04/029 Muayene Tarihi: | 07.04.2026 Tedarikci: Dh Makine Ltd. $ti Parga Adi: Manyetik Bariyer Saplamasi Parga Kodu: 37-5000215194 Gelen | Miktar : 2 adet Kontrol Edilen Miktar : 2 adet Nihai Karar : Sartl Kabul OLGUM SONUCLARIVE TESPITLERUYGUNSUZ | BULUNAN OLCUMLER Minér Ozellik (Olgiim 1/1): Beklenen Deger (Nomina'::text, E'Tedarikçi üretim sürecinde boyutsal/görsel/fonksiyonel kalite kontrol yeterli düzeyde uygulanmamaktadır. Kontrol planında kritik karakteristikler tanımlanmamış veya muayene sürecinde sapma tespit edilememiştir.'::text, E'1. Uygunsuz \'Manyetik Bariyer Saplamasi Parga Kodu: 37-5000215194 Gelen\' partisi tedarikçiye iade edilmeli veya karantinaya alınmalıdır.\n2. Tedarikçiye DF-2026-092 numaralı DF kaydı iletilmeli, 15 iş günü içinde yazılı kök neden analizi ve düzeltici aksiyon planı talep edilmelidir.\n3. Tedarikçinin kontrol planı incelenmeli; kritik boyutlar ve kabul kriterleri yeniden belirlenmeli, onaylı kontrol planı alınmalıdır.\n4. Aynı tedarikçiden tekrarlayan uygunsuzluk varsa tedarikçi performans puanı düşürülmeli, alternatif tedarikçi değerlendirmesi başlatılmalıdır.'::text),
  (E'DF-2026-093'::text, E'DF'::text, E'GIRDi KALITEKONTROLU- UYGUNSUZLUKTESPITIMUAYENEBILGILERI Kayit No: 26/04/031 Muayene Tarihi: | 07.04.2026 Tedarikci: Uzcelik Makina Sanayi Tic. Ltd. Sti. Parga Adi: Sispansiyon Kollektérii Parga Kodu: 37- | 5000164878 Gelen Miktar : 24 adet Kontrol Edilen Miktar : 24 adet Nihai Karar: Ret OLGCUM SONUCLARIVE | TESPITLEROLCGUM OZETI Toplam Olcgiim Sayist 36 Uygun Olgiimler : 0 Uygunsuz Olcti | Ee eae edd na a Sua alas'::text, E'Tedarikçi üretim sürecinde boyutsal/görsel/fonksiyonel kalite kontrol yeterli düzeyde uygulanmamaktadır. Kontrol planında kritik karakteristikler tanımlanmamış veya muayene sürecinde sapma tespit edilememiştir.'::text, E'1. Uygunsuz \'Sispansiyon Kollektérii Parga Kodu: 37-\' partisi tedarikçiye iade edilmeli veya karantinaya alınmalıdır.\n2. Tedarikçiye DF-2026-093 numaralı DF kaydı iletilmeli, 15 iş günü içinde yazılı kök neden analizi ve düzeltici aksiyon planı talep edilmelidir.\n3. Tedarikçinin kontrol planı incelenmeli; kritik boyutlar ve kabul kriterleri yeniden belirlenmeli, onaylı kontrol planı alınmalıdır.\n4. Aynı tedarikçiden tekrarlayan uygunsuzluk varsa tedarikçi performans puanı düşürülmeli, alternatif tedarikçi değerlendirmesi başlatılmalıdır.'::text),
  (E'DF-2026-094'::text, E'DF'::text, E'GIRDIKALITEKONTROLU- UYGUNSUZLUKTESPITIMUAYENEBILGILERI Kayit No: 26/04/036 Muayene Tarihi: | 08.04.2026 Tedarikci : Ozkan Makine Ltd. Sti. Parga Adi: Sag Su Deposu Alt Baglanti Parga Kodu: 37-5000151418 | Gelen Miktar : 5 adet Kontrol Edilen Miktar : 5 adet Nihai Karar: Ret OLCUM SONUCLARIVE TESPITLERUYGUNSUZ | BULUNAN OLCUMLER Fonksiyonel Ozellik (Olgiim 1/1): Beklenen Deger (Nomin | Ee eae edd na a Sua alas'::text, E'Tedarikçi üretim sürecinde boyutsal/görsel/fonksiyonel kalite kontrol yeterli düzeyde uygulanmamaktadır. Kontrol planında kritik karakteristikler tanımlanmamış veya muayene sürecinde sapma tespit edilememiştir.'::text, E'1. Uygunsuz \'Sag Su Deposu Alt Baglanti Parga Kodu: 37-5000151418\' partisi tedarikçiye iade edilmeli veya karantinaya alınmalıdır.\n2. Tedarikçiye DF-2026-094 numaralı DF kaydı iletilmeli, 15 iş günü içinde yazılı kök neden analizi ve düzeltici aksiyon planı talep edilmelidir.\n3. Tedarikçinin kontrol planı incelenmeli; kritik boyutlar ve kabul kriterleri yeniden belirlenmeli, onaylı kontrol planı alınmalıdır.\n4. Aynı tedarikçiden tekrarlayan uygunsuzluk varsa tedarikçi performans puanı düşürülmeli, alternatif tedarikçi değerlendirmesi başlatılmalıdır.'::text),
  (E'DF-2026-095'::text, E'DF'::text, E'GIRDi KALITEKONTROLU- UYGUNSUZLUKTESPITIMUAYENEBILGILERI Kayit No: 26/04/037 Muayene Tarihi: | 08.04.2026 Tedarikci: Ozkan Makine Ltd. Sti. Parga Adi: Sol Su Deposu Alt Kapak Baglantisi Parga Kodu: 37- | 5000151421 Gelen Miktar :5 adet Kontrol Edilen Miktar : 5 adet Nihai Karar: Ret OLCUMSONUCLARIVETESPITLER | UYGUNSUZBULUNAN OLGUMLER Minér Ozellik (Olgiim 1/1): Beklenen Deger (Nom | Ee eae edd na a Sua alas'::text, E'Tedarikçi üretim sürecinde boyutsal/görsel/fonksiyonel kalite kontrol yeterli düzeyde uygulanmamaktadır. Kontrol planında kritik karakteristikler tanımlanmamış veya muayene sürecinde sapma tespit edilememiştir.'::text, E'1. Uygunsuz \'Sol Su Deposu Alt Kapak Baglantisi Parga Kodu: 37-\' partisi tedarikçiye iade edilmeli veya karantinaya alınmalıdır.\n2. Tedarikçiye DF-2026-095 numaralı DF kaydı iletilmeli, 15 iş günü içinde yazılı kök neden analizi ve düzeltici aksiyon planı talep edilmelidir.\n3. Tedarikçinin kontrol planı incelenmeli; kritik boyutlar ve kabul kriterleri yeniden belirlenmeli, onaylı kontrol planı alınmalıdır.\n4. Aynı tedarikçiden tekrarlayan uygunsuzluk varsa tedarikçi performans puanı düşürülmeli, alternatif tedarikçi değerlendirmesi başlatılmalıdır.'::text),
  (E'DF-2026-096'::text, E'DF'::text, E'GIRDi KALITEKONTROLU- UYGUNSUZLUKTESPITIMUAYENEBILGILERI Kayit No: 26/04/055 Muayene Tarihi: | 09.04.2026 Tedarikgi: Ozkan Makine Ltd. Sti. Parga Adi: Filtre Haznesi On Kapak Komple Parga Kodu: 37- | 5000202103 Gelen Miktar : 1 adet Kontrol Edilen Miktar : 1 adet Nihai Karar: Sartli Kabul OLGUM SONUCLARIVE | TESPITLERUYGUNSUZBULUNAN OLGUMLER Minér Ozellik (Olgiim 1/1): Beklenen Deger'::text, E'Tedarikçi üretim sürecinde boyutsal/görsel/fonksiyonel kalite kontrol yeterli düzeyde uygulanmamaktadır. Kontrol planında kritik karakteristikler tanımlanmamış veya muayene sürecinde sapma tespit edilememiştir.'::text, E'1. Uygunsuz \'Filtre Haznesi On Kapak Komple Parga Kodu: 37-\' partisi tedarikçiye iade edilmeli veya karantinaya alınmalıdır.\n2. Tedarikçiye DF-2026-096 numaralı DF kaydı iletilmeli, 15 iş günü içinde yazılı kök neden analizi ve düzeltici aksiyon planı talep edilmelidir.\n3. Tedarikçinin kontrol planı incelenmeli; kritik boyutlar ve kabul kriterleri yeniden belirlenmeli, onaylı kontrol planı alınmalıdır.\n4. Aynı tedarikçiden tekrarlayan uygunsuzluk varsa tedarikçi performans puanı düşürülmeli, alternatif tedarikçi değerlendirmesi başlatılmalıdır.'::text),
  (E'DF-2026-097'::text, E'DF'::text, E'GIRDIKALITEKONTROLU- UYGUNSUZLUKTESPITIMUAYENEBILGILERI Kayit No: 26/04/059 Muayene Tarihi: | 09.04.2026 Tedarikgi : Saytek Tasarim Mak.kal.kons Parga Adi: Ara Yataklama Mili Parga Kodu: 37-5000189111 Gelen | Miktar : 1 adet Kontrol Edilen Miktar : 1 adet Nihai Karar: Ret OLCUM SONUCLARIVE TESPITLEROLGUM OZETI: | Toplam Olgiim Sayist 5 Uygun Olgiimler : 0 Uygunsuz Olgiimler : 5 Ret Ora'::text, E'Tedarikçi üretim sürecinde boyutsal/görsel/fonksiyonel kalite kontrol yeterli düzeyde uygulanmamaktadır. Kontrol planında kritik karakteristikler tanımlanmamış veya muayene sürecinde sapma tespit edilememiştir.'::text, E'1. Uygunsuz \'Ara Yataklama Mili Parga Kodu: 37-5000189111 Gelen\' partisi tedarikçiye iade edilmeli veya karantinaya alınmalıdır.\n2. Tedarikçiye DF-2026-097 numaralı DF kaydı iletilmeli, 15 iş günü içinde yazılı kök neden analizi ve düzeltici aksiyon planı talep edilmelidir.\n3. Tedarikçinin kontrol planı incelenmeli; kritik boyutlar ve kabul kriterleri yeniden belirlenmeli, onaylı kontrol planı alınmalıdır.\n4. Aynı tedarikçiden tekrarlayan uygunsuzluk varsa tedarikçi performans puanı düşürülmeli, alternatif tedarikçi değerlendirmesi başlatılmalıdır.'::text),
  (E'DF-2026-098'::text, E'DF'::text, E'GIRDIKALITEKONTROLU- UYGUNSUZLUKTESPITIMUAYENEBILGILERI Kayit No: 26/04/065 Muayene Tarihi: | 13.04.2026 Tedarikgi : Uzgelik Makine Ltd. $ti. Parga Adi: Sag Rad Kolu Parga Kodu: 37-5000143947 Gelen Miktar : 3 | adet Kontrol Edilen Miktar : 3 adet Nihai Karar: Ret OLCUM SONUCLARIVE TESPITLERUYGUNSUZBULUNAN | OLCUMLER Fonksiyonel Ozellik (Olgtim 1/1): Beklenen Deger (Nominal ): 17,50 m'::text, E'Tedarikçi üretim sürecinde boyutsal/görsel/fonksiyonel kalite kontrol yeterli düzeyde uygulanmamaktadır. Kontrol planında kritik karakteristikler tanımlanmamış veya muayene sürecinde sapma tespit edilememiştir.'::text, E'1. Uygunsuz \'Sag Rad Kolu Parga Kodu: 37-5000143947 Gelen Miktar : 3\' partisi tedarikçiye iade edilmeli veya karantinaya alınmalıdır.\n2. Tedarikçiye DF-2026-098 numaralı DF kaydı iletilmeli, 15 iş günü içinde yazılı kök neden analizi ve düzeltici aksiyon planı talep edilmelidir.\n3. Tedarikçinin kontrol planı incelenmeli; kritik boyutlar ve kabul kriterleri yeniden belirlenmeli, onaylı kontrol planı alınmalıdır.\n4. Aynı tedarikçiden tekrarlayan uygunsuzluk varsa tedarikçi performans puanı düşürülmeli, alternatif tedarikçi değerlendirmesi başlatılmalıdır.'::text),
  (E'DF-2026-101'::text, E'DF'::text, E'GIRD/ KALITEKONTROLU- UYGUNSUZLUKTESPITI | MUAYENEBILGILERI | Kayit No: 26/04/104 | Muayene Tarihi: 24.04.2026 | Tedarikgi: Ozkan Makine Ltd. Sti.'::text, E'Tedarikçi üretim sürecinde boyutsal/görsel/fonksiyonel kalite kontrol yeterli düzeyde uygulanmamaktadır. Kontrol planında kritik karakteristikler tanımlanmamış veya muayene sürecinde sapma tespit edilememiştir.'::text, E'1. Uygunsuz \'Firca Baglanti Flansi\' partisi tedarikçiye iade edilmeli veya karantinaya alınmalıdır.\n2. Tedarikçiye DF-2026-101 numaralı DF kaydı iletilmeli, 15 iş günü içinde yazılı kök neden analizi ve düzeltici aksiyon planı talep edilmelidir.\n3. Tedarikçinin kontrol planı incelenmeli; kritik boyutlar ve kabul kriterleri yeniden belirlenmeli, onaylı kontrol planı alınmalıdır.\n4. Aynı tedarikçiden tekrarlayan uygunsuzluk varsa tedarikçi performans puanı düşürülmeli, alternatif tedarikçi değerlendirmesi başlatılmalıdır.'::text),
  (E'DF-2026-015'::text, E'DF'::text, E'55 KWperkins motorlarda 190 lik pompa kullanilmasi ile ilgili daha 6nce MDB yayinlanmis fakat dretim bu MDB | uymadan 160 lik pompa kullanmaya devam etmistir . Konuyla ilgili aksiyon alinmasi gerekmektedir . | 3. |ILERLEME NOTLARI / YAPILAN CALISMALAR | | kalite kontrol tarafindan kontrol planina eklendi . Montaj hatt! wsapp grubundan konu hakkinda bilgilendirme mesaji yayinlandi'::text, E'Yayınlanan MDB (Mühendislik Değişiklik Bildirimi) talimatına üretim hattı uyum sağlamamış; 55 kW Perkins motorlarda pompa boyutu değişikliği üretimde uygulanmamaya devam etmiştir.'::text, E'1. Üretim hattındaki tüm operatörlere 55 kW Perkins motor için 190\'lık pompa kullanım zorunluluğu acilen iletilmeli; MDB bildirimi imzalatılmalıdır.\n2. Üretimde kullanılan mevcut 160\'lık pompalar stoktan çekilmeli; yerine 190\'lık pompalar konulmalıdır.\n3. MDB uygulama takip mekanizması oluşturulmalı; yayınlanan her MDB için üretim hattı liderinden onay alınması prosedürü başlatılmalıdır.\n4. Değişiklik öncesi 160\'lık pompa ile üretilmiş araçlar için geri dönük muayene yapılmalı; gerekirse pompa değişimi planlanmalıdır.'::text),
  (E'DF-2026-028'::text, E'DF'::text, E'Firmamiz biinyesinde iretilen araglarimizin hepsinde mavi dosya olmasi gereklidir . Dosyalarin eksikligi tespit | edilmis konuyla ilgili aksiyon alinmasi gerekmektedir . | 3. |ILERLEME NOTLARI / YAPILAN CALISMALAR | | Dosyalar olusturulmaya baslamistir.'::text, E'Araç üretim takip dosyalarının (mavi dosya) oluşturulması için tanımlanmış bir sorumluluk ve takip mekanizması mevcut değil.'::text, E'1. Hangi araçlara mavi dosya açılacağı, içeriğinin ne olacağı ve sorumlusunun kim olduğu yazılı prosedüre bağlanmalıdır.\n2. Eksik mavi dosyalar için tamamlama takvimi belirlenmeli ve yapılan çalışmalar takip edilmelidir.\n3. Üretim programına mavi dosya açılışı görevi olarak eklenmeli; dosya açılmadan araç üretimine başlanmaması sağlanmalıdır.\n4. Mevcut araçların dosya durumu liste halinde çıkarılmalı; haftalık tamamlanma oranı izlenmelidir.'::text),
  (E'DF-2026-058'::text, E'DF'::text, E'Uretim sahasinda daha isi bitmemis araclarimiz kalite diizeltmelerinde géziikmekte olup, kalite biriminin heniz | Uretimden cikmayan araglarin gecikmesi veya teslim edilmemesi konusunda sorumlu gosterilmemesi | gerekmektedir . Konu hakkinda aksiyon alinmalidir'::text, E'Üretim planlama-kalite entegrasyonu yetersiz; üretimden çıkmayan araçların kalite düzeltmeleri için sorumluluk tanımı net değil.'::text, E'1. Üretimden çıkmayan araçların kalite beklemesindeki gecikmelerin sorumluluğu net olarak belirlenmelidir; Üretim Planlama ile ilgili birim arasında sorumluluk matrisi oluşturulmalıdır.\n2. Araç gecikmelerinin günlük takibi için üretim planlama panosu oluşturulmalı; gecikmeler kayıt altına alınmalıdır.\n3. Üretimden çıkmayan araçların kalite süreçlerini etkilemeyeceği bir mekanizma (ayrı alan, önceliklendirme) geliştirilmelidir.\n4. Haftalık Üretim-Kalite koordinasyon toplantısı başlatılmalıdır.'::text),
  (E'DF-2026-068'::text, E'DF'::text, E'26-001 numarali is kazasi igin aksiyon alinmalidir.'::text, E'İş kazası (26-001): Risk Değerlendirmesi güncel olmayabilir veya uygulamada sapma var; kaza zinciri yeterince analiz edilmemiş.'::text, E'1. Kaza 26-001 için detaylı Kaza Kök Neden Analizi yapılmalı (5 Neden veya SCAT yöntemi); bulgular belgeli hale getirilmelidir.\n2. Kazanın gerçekleştiği alan/proses için Risk Değerlendirmesi revize edilmeli; yeni kontrol önlemleri tanımlanmalı ve hayata geçirilmelidir.\n3. Tüm hat/saha personeline olay konusunda güvenlik brifing\'i verilmeli; imzalı katılım formu tutulmalıdır.\n4. Benzer kaza riski taşıyan diğer alanlar/prosesler değerlendirilmeli (yatay yayılım kontrolü); gerekirse fiziksel bariyer/ikaz levhası eklenmelidir.'::text),
  (E'DF-2026-069'::text, E'DF'::text, E'26-002 numarali is kazasi igin aksiyon alinmalidir .'::text, E'İş kazası (26-002): Risk Değerlendirmesi güncel olmayabilir veya uygulamada sapma var; kaza zinciri yeterince analiz edilmemiş.'::text, E'1. Kaza 26-002 için detaylı Kaza Kök Neden Analizi yapılmalı (5 Neden veya SCAT yöntemi); bulgular belgeli hale getirilmelidir.\n2. Kazanın gerçekleştiği alan/proses için Risk Değerlendirmesi revize edilmeli; yeni kontrol önlemleri tanımlanmalı ve hayata geçirilmelidir.\n3. Tüm hat/saha personeline olay konusunda güvenlik brifing\'i verilmeli; imzalı katılım formu tutulmalıdır.\n4. Benzer kaza riski taşıyan diğer alanlar/prosesler değerlendirilmeli (yatay yayılım kontrolü); gerekirse fiziksel bariyer/ikaz levhası eklenmelidir.'::text)
)
UPDATE non_conformities n
SET
  five_why_analysis = COALESCE(n.five_why_analysis, '{}'::jsonb)
    || jsonb_build_object(
      'problem', to_jsonb(x.problem),
      'rootCause', to_jsonb(x.root_cause),
      'why5', to_jsonb(x.root_cause),
      'preventiveAction', to_jsonb(x.actions_text)
    ),
  eight_d_steps = CASE
    WHEN n.type = '8D' THEN
      jsonb_set(
        jsonb_set(
          COALESCE(n.eight_d_steps, '{}'::jsonb),
          '{D4,description}',
          to_jsonb(('Kök neden (rapor özeti)'::text || E'\n\n' || x.root_cause)::text),
          true
        ),
        '{D5,description}',
        to_jsonb(('Önerilen düzeltici faaliyetler'::text || E'\n\n' || x.actions_text)::text),
        true
      )
    ELSE n.eight_d_steps
  END,
  updated_at = now()
FROM x
WHERE n.nc_number = x.nc_number AND n.type = x.typ;
