WITH x(nc_number, typ, problem, root_cause, actions_text) AS (
  VALUES
  (E'8D-2026-005'::text, E'8D'::text, E'™ GRUPOZETI | Kategori : Tasarim Hatas! | Tespit Alani : Uretilen Araclar | Toplam Kayit : 21 | Toplam Adet : 60'::text, E'Tasarım hatası kategorisinde gruplandırılmış 21 kayıt; 60 araçta tespit edilmiş. Tasarım doğrulama sürecinde yeterli test senaryoları uygulanmamış.'::text, E'1. 8D raporundaki her alt kayıt için ayrı tasarım revizyonu açılmalıdır.\n2. Gruplanan 60 araçtaki tasarım hataları önceliklendirilmeli; kritik güvenlik/fonksiyon etkisi olanlara acil MDB çıkarılmalıdır.\n3. Tasarım FMEA kapsamlı olarak güncellenmeli; hata modları ve önlemler gözden geçirilmelidir.\n4. Ar-Ge tasarım onay prosedürüne saha geri bildirimi döngüsü eklenmelidir.'::text),
  (E'DF-2026-049'::text, E'DF'::text, E'AGA6000aracimizda kazan kapaliyken , kazanin agilmasini engelleyen sistem aktif edilmedigi_ icin araclarimizda | misteri kullaniminda SSHtarafindan uygunsuzluk tespit edilmis olup aksiyon alinmalidir . | 3. |ILERLEME NOTLARI / YAPILAN CALISMALAR | | Yazilimgincellemesi yapildi tim 6000ler giincellendi'::text, E'Tasarım doğrulama aşamasında bu uygunsuzluk senaryosu yeterince test edilmemiş.'::text, E'1. Teknik resim revize edilmeli; gerekli tasarım değişikliği MDB ile yayınlanmalıdır.\n2. Prototip üzerinde doğrulama testi yapılmalıdır.\n3. Sahadaki araçlar için servis bildirimi hazırlanmalıdır.\n4. Tasarım FMEA güncellenmelidir.'::text),
  (E'DF-2026-082'::text, E'DF'::text, E'Araglarimiz igerisinde , joystick , firga kontrol butonlar! ve hareketli pargalara midahale edilen kontrol Unitelerinde | etiketleme calismasi yapiimamis olup , hangi diigme / joystick hangi ekipmani hareket ettiriyor bilinmemektedir | Kalite Kontrol birimine de bu konuyla ilgili bilgi verilmedigi tespit edilmistir . Aksiyon alinmasi gerekmektedir'::text, E'Tasarım doğrulama aşamasında bu uygunsuzluk senaryosu yeterince test edilmemiş.'::text, E'1. Teknik resim revize edilmeli; gerekli tasarım değişikliği MDB ile yayınlanmalıdır.\n2. Prototip üzerinde doğrulama testi yapılmalıdır.\n3. Sahadaki araçlar için servis bildirimi hazırlanmalıdır.\n4. Tasarım FMEA güncellenmelidir.'::text),
  (E'DF-2026-103'::text, E'DF'::text, E'AGA2100aracimizdaki kazan igi elegin késelerindeki aciklik bulunmasi sebebi ile icine giren poset vb malzemeler | fan Gizerine yapisip balansa sebep oluyor aksiyon alinmasi gerekmektedir .'::text, E'Tasarım doğrulama aşamasında bu uygunsuzluk senaryosu yeterince test edilmemiş.'::text, E'1. Teknik resim revize edilmeli; gerekli tasarım değişikliği MDB ile yayınlanmalıdır.\n2. Prototip üzerinde doğrulama testi yapılmalıdır.\n3. Sahadaki araçlar için servis bildirimi hazırlanmalıdır.\n4. Tasarım FMEA güncellenmelidir.'::text),
  (E'DF-2026-105'::text, E'DF'::text, E'MALIYETKAYDIDETAYLARI | Maliyet Tira: Hurda Maliyeti | Tarih: 09.12.2025 | Birim : Ar-Ge Direktérliigii | Parga Adi: Hiposan PTO Pompa'::text, E'Tasarım doğrulama aşamasında bu uygunsuzluk senaryosu yeterince test edilmemiş.'::text, E'1. Teknik resim revize edilmeli; gerekli tasarım değişikliği MDB ile yayınlanmalıdır.\n2. Prototip üzerinde doğrulama testi yapılmalıdır.\n3. Sahadaki araçlar için servis bildirimi hazırlanmalıdır.\n4. Tasarım FMEA güncellenmelidir.'::text),
  (E'DF-2026-004'::text, E'DF'::text, E'Sayim sonrasinda iiretim planlama tarafindan gerceklestirilen denetimde raflarda kodsuz ve etiketsiz iriinler tespit | edilmistir . | 3. |ILERLEME NOTLARI / YAPILAN CALISMALAR | | Depo Kodsuz iriin icin gerekli galigmalari gergeklestiriyor anit dokiiman yiiklenmistir .'::text, E'Depo giriş kabul sürecinde ürün etiketleme ve kodlama standardı uygulanmamakta; personel eğitimi ve giriş kontrol prosedürü yetersiz.'::text, E'1. Tüm raflardaki kodsuz/etiketsiz ürünler ivedilikle tanımlanmalı, mevcut stoklara etiket/barkod yapıştırılmalıdır.\n2. Depoya giriş kabul prosedürü yazılı hale getirilmeli; \'etiketsiz ürün depoya alınmaz\' kuralı tanımlanmalıdır.\n3. Depo personeline etiketleme ve ürün kodlama eğitimi verilmelidir.\n4. Haftalık depo turu ile etiketsiz ürün kontrolü rutin hale getirilmelidir.'::text),
  (E'DF-2026-005'::text, E'DF'::text, E'Sayim sonrasinda iiretim planiama tarafindan gerceklestirilen denetimde motor stoklama alani dis etkenlere acik | ve uygunsuz olarak tespit edilmistir .'::text, E'Depo stoklama alanı fiziksel düzenlemesi yetersiz; raf sistemi eksik veya uygunsuz, açık alan stoğu yağış/nem/toz etkisine açık.'::text, E'1. Motor ve büyük parça stoklama alanı kapalı veya örtülü hale getirilmeli; palet/raf düzenlemesi yapılmalıdır.\n2. Açık alana alınan ürünler için branda/koruyucu örtü kullanımı zorunlu hale getirilmelidir.\n3. Raf ve depolama sistemi kapasitesi gözden geçirilmeli; ihtiyaç halinde ek raf talep edilmelidir.\n4. Depo düzeni fotoğraflanarak referans düzen oluşturulmalı; 5S uygulaması başlatılmalıdır.'::text),
  (E'DF-2026-006'::text, E'DF'::text, E'Sayim sonrasinda iiretim planlama tarafindan gerceklestirilen denetimde rextrothlar zeminde ve depolama | y6ntemi uygunsuz olarak tespit edilmistir .'::text, E'Depo stoklama alanı fiziksel düzenlemesi yetersiz; raf sistemi eksik veya uygunsuz, açık alan stoğu yağış/nem/toz etkisine açık.'::text, E'1. Motor ve büyük parça stoklama alanı kapalı veya örtülü hale getirilmeli; palet/raf düzenlemesi yapılmalıdır.\n2. Açık alana alınan ürünler için branda/koruyucu örtü kullanımı zorunlu hale getirilmelidir.\n3. Raf ve depolama sistemi kapasitesi gözden geçirilmeli; ihtiyaç halinde ek raf talep edilmelidir.\n4. Depo düzeni fotoğraflanarak referans düzen oluşturulmalı; 5S uygulaması başlatılmalıdır.'::text),
  (E'DF-2026-007'::text, E'DF'::text, E'Sayim sonrasinda iiretim planlama tarafindan gerceklestirilen denetimde Ax stoklari ve fiziki stoklarin uyusmadigi | igin uygunsuz olarak tespit edilmistir . | 3. |ILERLEME NOTLARI / YAPILAN CALISMALAR | | Gerekli sayim detaylan paylasilmig ve kanit dokiiman yiiklenmistir .'::text, E'AX (ERP) sistemindeki kayıt ile fiziksel stok arasındaki fark; parti numarasına göre ayrımlı depolama yapılmamakta, sayım prosedürü eksik.'::text, E'1. Fiziksel sayım sonuçları ile AX kayıtları karşılaştırılmalı; farkların kaynağı tespit edilerek sistem kayıtları düzeltilmelidir.\n2. Parti numarasına göre fiziksel ayrımlı depolama uygulaması başlatılmalıdır.\n3. Ay sonu stok sayım prosedürü oluşturulmalı; sorumlular belirlenmeli ve takip edilmelidir.\n4. Depo giriş/çıkış hareketlerinin sisteme anlık kaydedilmesi için personel eğitimi verilmelidir.'::text),
  (E'DF-2026-008'::text, E'DF'::text, E'Sayim sonrasinda iiretim planlama tarafindan gerceklestirilen denetimde , Ax kayitlarinda parti numaralarina gére | depolama yapilirken , fiziki depolarda parti numarasi ayrimi yapilmadigi uygunsuz olarak tespit edilmistir'::text, E'AX (ERP) sistemindeki kayıt ile fiziksel stok arasındaki fark; parti numarasına göre ayrımlı depolama yapılmamakta, sayım prosedürü eksik.'::text, E'1. Fiziksel sayım sonuçları ile AX kayıtları karşılaştırılmalı; farkların kaynağı tespit edilerek sistem kayıtları düzeltilmelidir.\n2. Parti numarasına göre fiziksel ayrımlı depolama uygulaması başlatılmalıdır.\n3. Ay sonu stok sayım prosedürü oluşturulmalı; sorumlular belirlenmeli ve takip edilmelidir.\n4. Depo giriş/çıkış hareketlerinin sisteme anlık kaydedilmesi için personel eğitimi verilmelidir.'::text),
  (E'DF-2026-009'::text, E'DF'::text, E'Sayim sonrasinda iiretim planlama tarafindan gerceklestirilen denetimde Ax kayitlarinda bulunan 0 genel konumu | fiziki olarak bulunmamaktadir .0 genel konumunda bulunan iriinler hatali ,bekleyen , teslim alinmamis triinler | oldugu uygunsuz olarak tespit edilmistir .'::text, E'AX (ERP) sistemindeki kayıt ile fiziksel stok arasındaki fark; parti numarasına göre ayrımlı depolama yapılmamakta, sayım prosedürü eksik.'::text, E'1. Fiziksel sayım sonuçları ile AX kayıtları karşılaştırılmalı; farkların kaynağı tespit edilerek sistem kayıtları düzeltilmelidir.\n2. Parti numarasına göre fiziksel ayrımlı depolama uygulaması başlatılmalıdır.\n3. Ay sonu stok sayım prosedürü oluşturulmalı; sorumlular belirlenmeli ve takip edilmelidir.\n4. Depo giriş/çıkış hareketlerinin sisteme anlık kaydedilmesi için personel eğitimi verilmelidir.'::text),
  (E'DF-2026-020'::text, E'DF'::text, E'Misterimiz tarafindan iletilen ve ekte yer alan gérseller incelendiginde , KADEMEtarafindan sevk edilen son 2 | adet Ural araci Gzerinde asagida belirtilen sevkiyat kaynakli uygunsuzluklar tespit edilmistir : | Gévde saclari ve sasi tizeri boyali yiizeylerde carpma , siirtme ve lokal boya hasarlar! , | KADEMEisim plakasinin (name plate) hasar gérdiigii / deforme oldugu , | Arag izerindeki ikaz lambalarindan birinin kirik oldugu (misteri , detay igin Engr. Ahmed ile iletisime gecilmesini'::text, E'Depo yönetim prosedürü eksik veya güncel değil; personel eğitimi ve günlük rutin kontroller yetersiz.'::text, E'1. İlgili uygunsuzluk için yazılı prosedür/talimat oluşturulmalı veya güncellenmeli; depo personeline iletilmelidir.\n2. Haftalık depo kontrol turu uygulanmalı; bulgular kayıt altına alınmalıdır.\n3. Depo personeline yönlendirici eğitim verilmeli ve eğitim kaydı tutulmalıdır.\n4. 5S uygulaması kapsamında depo düzenlemesi yapılmalıdır.'::text),
  (E'DF-2026-025'::text, E'DF'::text, E'Dis kaynakli igleme g6nderilen Griinlerde takipsizlikler ve belirsizlikler tespit edilmistir .Giden Grin adeti gelen Grin | adeti sayiliyor olsa bile kaydi tutulmadigi , hangi malzemeye ne islem yapilacaginin da kag giin siirdiigiintin de | gorillebilecegi herhangi kaydi olmadigi tespit edilmistir .Bu da kalite kontrol siireclerini ve tedarikci takibini | zorlastirmaktadir . Sorun 48lik kaplinlerde yasanan miisteri sikayeti ile arastiniip tespit edilmis olup , konuyla ilgili | aksiyon alinmasi gerekmektedir .'::text, E'Dış kaynaklı işleme gönderilen ürünlerin takibi için yazılı prosedür ve kayıt sistemi mevcut değil; gönderilen/gelen adet kontrolü yapılmamakta.'::text, E'1. Dış işleme gidiş-dönüş için teslimat fişi/formu oluşturulmalı; her sevkiyatta imzalı belge alınmalıdır.\n2. Dış işlemde bulunan parçalar için AX\'ta ayrı bir depo konumu tanımlanmalıdır.\n3. İşleme gönderilen ürünlerin adet ve süre takibi haftalık olarak yapılmalıdır.\n4. Taşıma sırasında boyalı ürünlerin birbirine sürtmesini önlemek için köpük/karton ara kat kullanımı zorunlu hale getirilmelidir.'::text),
  (E'DF-2026-030'::text, E'DF'::text, E'Depo birimimize baGli teslim teselliim ve forklift kaynakli, teslim alinan driinlerde gizilmeler ve ezilmeler meydana | gelmis. teslim teselliim siireci diizensiz (teslim alinan riinlerin nereye ne sekilde teslim alinacagi ve uygun palet | takoz vb sartlarin saglanmamas: ) ayrica forklift kullaniminin 6zensiz oldugu (iriinlerin birbirleri Uzerine | bindirilmesi indirirken ve tasirken driinlerin birbirine sirtiilip boyasina ve formuna zarar verilerek yapildigi) tespit | edilmistir . Konuyla ilgili aksiyon alinmasi gerekmektedir .'::text, E'Teslim alma ve forklift operasyonları sırasında ürün hasarını önleyecek prosedür ve talimatlar tanımlı değil; operatör eğitimi eksik.'::text, E'1. Forklift operatörlerine ürün hasarı önleme eğitimi verilmeli; hassas/boyalı ürünlerde köpük/karton koruma kullanımı zorunlu hale getirilmelidir.\n2. Teslim alma prosedürü yazılı hale getirilmeli; palet ve takoz kullanım standardı belirlenmeli, ekibe iletilmelidir.\n3. Teslim alınan ürünlerde hasar kontrolü formu oluşturulmalı; giriş hasarları kayıt altına alınmalıdır.\n4. Depo içi trafik güzergahı işaretlenmeli; forklift hız limiti belirlenmeli ve uygulanmalıdır.'::text),
  (E'DF-2026-032'::text, E'DF'::text, E'Depoya teslim edilen (igeriden ve disaridan (kaynakli imalat , bdb , ginar, almaksan ,) tim diriinler.) ortam sart | kosullarindan minimum etkilesimle saklanmali ve yipranmalardan muhafaza edilmelidir . Direkt olarak zemine | birakilarak atil stoklama sisteminin 6niine gecilmesi gerekmektedir . | eee OLE ac ea Sua alas | | Altlarina saceklenerek depolanmaya baslandi'::text, E'Depo stoklama alanı fiziksel düzenlemesi yetersiz; raf sistemi eksik veya uygunsuz, açık alan stoğu yağış/nem/toz etkisine açık.'::text, E'1. Motor ve büyük parça stoklama alanı kapalı veya örtülü hale getirilmeli; palet/raf düzenlemesi yapılmalıdır.\n2. Açık alana alınan ürünler için branda/koruyucu örtü kullanımı zorunlu hale getirilmelidir.\n3. Raf ve depolama sistemi kapasitesi gözden geçirilmeli; ihtiyaç halinde ek raf talep edilmelidir.\n4. Depo düzeni fotoğraflanarak referans düzen oluşturulmalı; 5S uygulaması başlatılmalıdır.'::text),
  (E'DF-2026-044'::text, E'DF'::text, E'Teselliim ve essek diye tabir edilen tekerlekli tasima sasi dizerine HSCKiistyapilari alinirken uygunsuzluk tespit | edilmis ve 6nlem alinmasi gerekmektedir . | 3. |ILERLEME NOTLARI / YAPILAN CALISMALAR | | egitim verildi'::text, E'Depo yönetim prosedürü eksik veya güncel değil; personel eğitimi ve günlük rutin kontroller yetersiz.'::text, E'1. İlgili uygunsuzluk için yazılı prosedür/talimat oluşturulmalı veya güncellenmeli; depo personeline iletilmelidir.\n2. Haftalık depo kontrol turu uygulanmalı; bulgular kayıt altına alınmalıdır.\n3. Depo personeline yönlendirici eğitim verilmeli ve eğitim kaydı tutulmalıdır.\n4. 5S uygulaması kapsamında depo düzenlemesi yapılmalıdır.'::text),
  (E'DF-2026-059'::text, E'DF'::text, E'Dis kaynakli isleme giden iiriinler araca yiiklenirken boyali boyasiz farketmeksizin ig ige birbirlerine siirtecek | sekilde koyulup g6nderildigi tespit edilmistir .Malzemelerin formu bozulmamasi igin ve Boyali Griinlerin zarar | gérmemesi icin aksiyon alinmasi gerekmektedir . | eee OLE ac ea Sua alas | | egitim verilmistir .'::text, E'Dış kaynaklı işleme gönderilen ürünlerin takibi için yazılı prosedür ve kayıt sistemi mevcut değil; gönderilen/gelen adet kontrolü yapılmamakta.'::text, E'1. Dış işleme gidiş-dönüş için teslimat fişi/formu oluşturulmalı; her sevkiyatta imzalı belge alınmalıdır.\n2. Dış işlemde bulunan parçalar için AX\'ta ayrı bir depo konumu tanımlanmalıdır.\n3. İşleme gönderilen ürünlerin adet ve süre takibi haftalık olarak yapılmalıdır.\n4. Taşıma sırasında boyalı ürünlerin birbirine sürtmesini önlemek için köpük/karton ara kat kullanımı zorunlu hale getirilmelidir.'::text),
  (E'DF-2026-072'::text, E'DF'::text, E'26-005 numarali is kazasi igin aksiyon alinmasi gerekmektedir .'::text, E'Taşıma/kaldırma operasyonu sırasında iş güvenliği prosedürlerine uyulmamış; personele yeterli İSG eğitimi verilmemiş.'::text, E'1. Kaza ile ilgili olay kökü analizi yapılmalı; fiziksel/davranışsal kök nedenler tespit edilmelidir.\n2. İlgili operasyon için Risk Değerlendirmesi yeniden yapılmalı; kritik adımlara güvenli çalışma talimatı eklenmeli ve asılmalıdır.\n3. Benzer kaza riskini önlemek için ekipmana fiziksel engel/ikaz levhası eklenmeli; gerekirse jig/aparat tasarlanmalıdır.\n4. Tüm depo personeline İSG eğitimi verilmeli; eğitim kayıt altına alınmalıdır.'::text)
)
UPDATE non_conformities n
SET
  five_why_analysis = COALESCE(n.five_why_analysis, '{}'::jsonb)
    || jsonb_build_object(
      'problem', to_jsonb(x.problem),
      'rootCause', to_jsonb(x.root_cause),
      'why5', to_jsonb(x.root_cause),
      'preventiveAction', to_jsonb(x.actions_text)
    ),
  eight_d_steps = CASE
    WHEN n.type = '8D' THEN
      jsonb_set(
        jsonb_set(
          COALESCE(n.eight_d_steps, '{}'::jsonb),
          '{D4,description}',
          to_jsonb(('Kök neden (rapor özeti)'::text || E'\n\n' || x.root_cause)::text),
          true
        ),
        '{D5,description}',
        to_jsonb(('Önerilen düzeltici faaliyetler'::text || E'\n\n' || x.actions_text)::text),
        true
      )
    ELSE n.eight_d_steps
  END,
  updated_at = now()
FROM x
WHERE n.nc_number = x.nc_number AND n.type = x.typ;
