WITH x(nc_number, typ, problem, root_cause, actions_text) AS (
  VALUES
  (E'DF-2026-024'::text, E'DF'::text, E'AGA6000araclarimiz montajdan iktiktan sonra bazi araclarda hava tanki bosaliyor frenler devre disi kaliyor. | Konuyla ilgili aksiyon alinmasi gerekmektedir . (Devrek ve Safak temizlik araglarinda gaz kagagi mevcuttur . | 3. |ILERLEME NOTLARI / YAPILAN CALISMALAR | Devrek ve Kérfez araclari izerinde ; | + Role ventilleri kontrol edilmistir .'::text, E'Mekanik montaj sonrası hava tankı sızdırmazlık testi protokolü yeterince uygulanmamakta; bağlantı fitting/hortum kontrolü ihmal edilmektedir.'::text, E'1. AGA6000 araçlarında hava tankı ve bağlantı noktaları için montaj sonrası basınç testi prosedürü oluşturulmalı; her araçta imzalı teyit alınmalıdır.\n2. Montaj talimatına kritik hortum/fitting bağlantı kontrol adımları eklenmeli; tork değerleri belirtilmelidir.\n3. Etkilenen araçlarda (Devrek ve Şafak araçları dahil) hava tankı bağlantıları kontrol edilmeli; sızan noktalar onarılmalıdır.\n4. Montaj operatörlerine hava tankı bağlantı ve sızdırmazlık kontrol eğitimi verilmeli; eğitim kayıt altına alınmalıdır.'::text),
  (E'DF-2026-099'::text, E'DF'::text, E'Fabrikada muhafaza edilen sifir motorlar gérsellerden de gériilebilecegi gibi korunaksiz bir sekilde muhafaza | ediliyor. | * Motor uzun siire korumasiz kalmis, bu da ig aksamin kirlenme riskini artirabilir | * Depolama -tasima sirasinda koruyucu értii kullanilmamis her yerinde toz, kir olusmus | * Emme-gikis agiziari agik'::text, E'Fabrikada muhafaza edilen sıfır motorların depolama prosedürü tanımlanmamış; koruyucu örtü/muhafaza standardı uygulanmamakta.'::text, E'1. Sıfır motor depolama alanı belirli bir bölgeye tahsis edilmeli; motorlar koruyucu örtü veya muhafaza kasası ile kapatılmalıdır.\n2. Motor depolama standardı yazılı hale getirilmeli (nem, toz, güneş koruması, zemin temas yasağı); sorumlu personele iletilmelidir.\n3. Mevcut korumasız motorlar için acil koruma önlemi (branda veya PE örtü) hemen uygulanmalıdır.\n4. Depo girişine \'motor depolama kuralları\' levhası asılmalı; motor deposu aylık kontrol rutinine alınmalıdır.'::text),
  (E'DF-2026-100'::text, E'DF'::text, E'Teknik resim revizyonlarinin (giincel gizim/model degisiklikleri ) Satinalma Midirligi tarafindan zamaninda ve | kontroll bigimde ilgili tedarikgilere iletiimedigi tespit edilmistir.Bu durum tedarikgilerin eski revizyona gére dretim | yapmasina , uygunsuz parca teslim etmesine ve montaj /kalite sorunlarina yol agmaktadir. Satinalma Midurligii ; | revizyon bildirim prosediriind olusturmali , tedarikci iletisim kayitlarini takip etmeli ve her revizyon degisikliginde | tedarikgi onay/teyit siirecini yiriitmelidir .'::text, E'Teknik resim/model revizyonlarının tedarikçilere iletimi için tanımlı bir süreç ve kontrol mekanizması mevcut değil; revizyon takibi otomatize edilmemiş.'::text, E'1. Teknik resim revizyon iletim prosedürü oluşturulmalı: Ar-Ge → Satınalma → Tedarikçi iletim zinciri net tanımlanmalı, her revizyon için tedarikçi alındı onayı alınmalıdır.\n2. Tedarikçilere iletilen teknik resim versiyonlarının takibi için basit bir revizyon matrisi (Excel tabanlı da olabilir) tutulmalı; güncel versiyon her zaman kayıt altında olmalıdır.\n3. Teknik resim güncellendiğinde Satınalma birimine otomatik bildirim gönderecek bir iş akışı (e-posta alert veya ERP bildirimi) tanımlanmalıdır.\n4. Aktif tedarikçilere toplu olarak güncel teknik resimler gönderilmeli ve eski revizyonların imha edilmesi talep edilmelidir.'::text),
  (E'DF-2026-104'::text, E'DF'::text, E'MALIYETKAYDIDETAYLARI | Maliyet Tira: Hurda Maliyeti | Tarih: 30.04.2026 | Birim: Uretim Miidirligdé (Ust Yapi) | Parga Adi: JANFLASTIK'::text, E'Maliyet kaydı kapsamında Satınalma Müdürlüğü\'ne atıfta bulunulan uygunsuzluk; tedarikçi seçim ve takip mekanizması gözden geçirilmeli.'::text, E'1. İlgili parçanın tedarik sürecinde yaşanan sorun belgelenmeli; tedarikçi performans kaydına işlenmelidir.\n2. Alternatif tedarikçi araştırması başlatılmalı veya mevcut tedarikçiyle düzeltici aksiyon planı yapılmalıdır.\n3. Kritik parçalar için ikincil tedarikçi (yedek kaynak) tanımlanmalıdır.\n4. Satınalma sürecinde teknik şartname kontrolü aşaması eklenmelidir.'::text),
  (E'8D-2026-001'::text, E'8D'::text, E'MALIYETKAYDIDETAYLARI | Maliyet Turi: Yeniden islem Maliyeti | Tarih: 13.01.2026 | Birim : Tedarikgi | Parga Adi: COPKAZANI KAYNAKLI'::text, E'Tedarikçi kalite güvence sistemindeki yapısal eksiklik: kontrol planında kritik karakteristik tanımı ve periyodik denetim mekanizması yetersizdir.'::text, E'1. Uygunsuz partiler karantinaya alınmalı, %100 muayene başlatılmalıdır.\n2. Tedarikçi denetimi planlanmalı; kontrol planı kritik karakteristikler eklenerek revize edilmelidir.\n3. Tedarikçi kalite anlaşması güncellenmeli; ret oranı KPI olarak eklenmelidir.\n4. Alternatif tedarikçi yeterlilik süreci başlatılmalıdır.'::text),
  (E'DF-2026-001'::text, E'DF'::text, E'AGA2100i¢in gelen 37-5000190431 kodlu kabinlerde sizdirmazlik testleri basari ile sonuclandirilamamistir | Sizdirmazligin saglanmasi gerekmektedir .'::text, E'Tedarikçi üretiminde sızdırmazlık uygulaması (kaynak, salmastra, conta) yetersiz veya malzeme spesifikasyonuna uygun değil.'::text, E'1. Tedarikçi ile acil toplantı düzenlenmeli; sızdırmazlık testinin tedarikçi çıkış kontrolüne eklenmesi talep edilmelidir.\n2. Uygunsuz parçalar iade edilmeli, şartlı kabul yapılacaksa ikincil kontrol prosedürü uygulanmalıdır.\n3. Tedarikçiden sızdırmazlık test protokolü ve sonuç raporları talep edilmelidir.\n4. Kritik parçalar için tedarikçi onay/yeterlilik değerlendirmesi yapılmalıdır.'::text),
  (E'DF-2026-003'::text, E'DF'::text, E'ilgili parca miisteri sikayeti izerine tarafimizca incelemeye alinmis ve yapilan fonksiyonel testlerde islevierini yerine | getirmedigi gériilmis olup , kagak problemleri_ ile karsilasilmistir .'::text, E'Tedarikçi üretiminde sızdırmazlık uygulaması (kaynak, salmastra, conta) yetersiz veya malzeme spesifikasyonuna uygun değil.'::text, E'1. Tedarikçi ile acil toplantı düzenlenmeli; sızdırmazlık testinin tedarikçi çıkış kontrolüne eklenmesi talep edilmelidir.\n2. Uygunsuz parçalar iade edilmeli, şartlı kabul yapılacaksa ikincil kontrol prosedürü uygulanmalıdır.\n3. Tedarikçiden sızdırmazlık test protokolü ve sonuç raporları talep edilmelidir.\n4. Kritik parçalar için tedarikçi onay/yeterlilik değerlendirmesi yapılmalıdır.'::text),
  (E'DF-2026-010'::text, E'DF'::text, E'GIRD/ KALITEKONTROLU- UYGUNSUZLUKTESPITI | MUAYENEBILGILERI | Kayit No: 26/01/114 | Muayene Tarihi: 21.01.2026 | Tedarikgi: Dh Makine Ltd. Sti'::text, E'Tedarikçi üretim sürecinde boyutsal/görsel/fonksiyonel kalite kontrol yeterli düzeyde uygulanmamaktadır. Kontrol planında kritik karakteristikler tanımlanmamış veya muayene sürecinde sapma tespit edilememiştir.'::text, E'1. Uygunsuz \'Mafsal Baglanti Pimi\' partisi tedarikçiye iade edilmeli veya karantinaya alınmalıdır.\n2. Tedarikçiye DF-2026-010 numaralı DF kaydı iletilmeli, 15 iş günü içinde yazılı kök neden analizi ve düzeltici aksiyon planı talep edilmelidir.\n3. Tedarikçinin kontrol planı incelenmeli; kritik boyutlar ve kabul kriterleri yeniden belirlenmeli, onaylı kontrol planı alınmalıdır.\n4. Aynı tedarikçiden tekrarlayan uygunsuzluk varsa tedarikçi performans puanı düşürülmeli, alternatif tedarikçi değerlendirmesi başlatılmalıdır.'::text),
  (E'DF-2026-011'::text, E'DF'::text, E'GIRD/ KALITEKONTROLU- UYGUNSUZLUKTESPITI | MUAYENEBILGILERI | Kayit No: 25/02/052 | Muayene Tarihi: 20.02.2025 | Tedarikci: Ekser Otomotiv Makina Yedek Parcalari imalat San. Ve Tic. A.s.'::text, E'Tedarikçi üretim sürecinde boyutsal/görsel/fonksiyonel kalite kontrol yeterli düzeyde uygulanmamaktadır. Kontrol planında kritik karakteristikler tanımlanmamış veya muayene sürecinde sapma tespit edilememiştir.'::text, E'1. Uygunsuz \'37-5000209166\' partisi tedarikçiye iade edilmeli veya karantinaya alınmalıdır.\n2. Tedarikçiye DF-2026-011 numaralı DF kaydı iletilmeli, 15 iş günü içinde yazılı kök neden analizi ve düzeltici aksiyon planı talep edilmelidir.\n3. Tedarikçinin kontrol planı incelenmeli; kritik boyutlar ve kabul kriterleri yeniden belirlenmeli, onaylı kontrol planı alınmalıdır.\n4. Aynı tedarikçiden tekrarlayan uygunsuzluk varsa tedarikçi performans puanı düşürülmeli, alternatif tedarikçi değerlendirmesi başlatılmalıdır.'::text),
  (E'DF-2026-012'::text, E'DF'::text, E'GIRD/ KALITEKONTROLU- UYGUNSUZLUKTESPITI | MUAYENEBILGILERI | Kayit No: 26/01/117 | Muayene Tarihi: 23.01.2026 | Tedarikgi: Uzcelik Makine Ltd. Sti.'::text, E'Tedarikçi üretim sürecinde boyutsal/görsel/fonksiyonel kalite kontrol yeterli düzeyde uygulanmamaktadır. Kontrol planında kritik karakteristikler tanımlanmamış veya muayene sürecinde sapma tespit edilememiştir.'::text, E'1. Uygunsuz \'Konveyor Burcu\' partisi tedarikçiye iade edilmeli veya karantinaya alınmalıdır.\n2. Tedarikçiye DF-2026-012 numaralı DF kaydı iletilmeli, 15 iş günü içinde yazılı kök neden analizi ve düzeltici aksiyon planı talep edilmelidir.\n3. Tedarikçinin kontrol planı incelenmeli; kritik boyutlar ve kabul kriterleri yeniden belirlenmeli, onaylı kontrol planı alınmalıdır.\n4. Aynı tedarikçiden tekrarlayan uygunsuzluk varsa tedarikçi performans puanı düşürülmeli, alternatif tedarikçi değerlendirmesi başlatılmalıdır.'::text),
  (E'DF-2026-013'::text, E'DF'::text, E'GIRD/ KALITEKONTROLU- UYGUNSUZLUKTESPITI | MUAYENEBILGILERI | Kayit No: 26/01/116 | Muayene Tarihi: 23.01.2026 | Tedarikgi: Ozkan Makine Ltd. Sti.'::text, E'Tedarikçi üretim sürecinde boyutsal/görsel/fonksiyonel kalite kontrol yeterli düzeyde uygulanmamaktadır. Kontrol planında kritik karakteristikler tanımlanmamış veya muayene sürecinde sapma tespit edilememiştir.'::text, E'1. Uygunsuz \'Firca Baglanti Blogu\' partisi tedarikçiye iade edilmeli veya karantinaya alınmalıdır.\n2. Tedarikçiye DF-2026-013 numaralı DF kaydı iletilmeli, 15 iş günü içinde yazılı kök neden analizi ve düzeltici aksiyon planı talep edilmelidir.\n3. Tedarikçinin kontrol planı incelenmeli; kritik boyutlar ve kabul kriterleri yeniden belirlenmeli, onaylı kontrol planı alınmalıdır.\n4. Aynı tedarikçiden tekrarlayan uygunsuzluk varsa tedarikçi performans puanı düşürülmeli, alternatif tedarikçi değerlendirmesi başlatılmalıdır.'::text),
  (E'DF-2026-014'::text, E'DF'::text, E'GIRD/ KALITEKONTROLU- UYGUNSUZLUKTESPITI | MUAYENEBILGILERI | Kayit No: 26/01/115 | Muayene Tarihi: 22.01.2026 | Tedarikgi: Ozkan Makine Ltd. Sti.'::text, E'Tedarikçi üretim sürecinde boyutsal/görsel/fonksiyonel kalite kontrol yeterli düzeyde uygulanmamaktadır. Kontrol planında kritik karakteristikler tanımlanmamış veya muayene sürecinde sapma tespit edilememiştir.'::text, E'1. Uygunsuz \'Jcb74kw Motor Pompa Kampanasi\' partisi tedarikçiye iade edilmeli veya karantinaya alınmalıdır.\n2. Tedarikçiye DF-2026-014 numaralı DF kaydı iletilmeli, 15 iş günü içinde yazılı kök neden analizi ve düzeltici aksiyon planı talep edilmelidir.\n3. Tedarikçinin kontrol planı incelenmeli; kritik boyutlar ve kabul kriterleri yeniden belirlenmeli, onaylı kontrol planı alınmalıdır.\n4. Aynı tedarikçiden tekrarlayan uygunsuzluk varsa tedarikçi performans puanı düşürülmeli, alternatif tedarikçi değerlendirmesi başlatılmalıdır.'::text),
  (E'DF-2026-018'::text, E'DF'::text, E'GIRD/ KALITEKONTROLU- UYGUNSUZLUKTESPITI | MUAYENEBILGILERI | Kayit No: 26/01/079 | Muayene Tarihi: 14.01.2026 | Tedarikgi: Baloglu Hidrolik Mak.san.'::text, E'Tedarikçi üretim sürecinde boyutsal/görsel/fonksiyonel kalite kontrol yeterli düzeyde uygulanmamaktadır. Kontrol planında kritik karakteristikler tanımlanmamış veya muayene sürecinde sapma tespit edilememiştir.'::text, E'1. Uygunsuz \'Arka Kapak Silindiri\' partisi tedarikçiye iade edilmeli veya karantinaya alınmalıdır.\n2. Tedarikçiye DF-2026-018 numaralı DF kaydı iletilmeli, 15 iş günü içinde yazılı kök neden analizi ve düzeltici aksiyon planı talep edilmelidir.\n3. Tedarikçinin kontrol planı incelenmeli; kritik boyutlar ve kabul kriterleri yeniden belirlenmeli, onaylı kontrol planı alınmalıdır.\n4. Aynı tedarikçiden tekrarlayan uygunsuzluk varsa tedarikçi performans puanı düşürülmeli, alternatif tedarikçi değerlendirmesi başlatılmalıdır.'::text),
  (E'DF-2026-019'::text, E'DF'::text, E'Mustafa Geng firmasi tarafindan Uretilen AGA2100 kazanlarda , ekli teknik resimde belirtilen kaldirma kilic! boy | dlgistintin 977 mm olmasi gerekirken 968 mm olarak kesildigi ve bu sekilde kazan izerine hatali konumda | kaynatildigi tespit edilmistir . | Bu hataya bagli olarak kazanin hidrolik silindir ve arag sasesine baGlanti merkezleri 7-9 mm ice dogru kaymis, | kazan mevcut haliyle montaj yapilmaya uygun olmayan bir duruma gelmistir .'::text, E'Tedarikçi üretiminde boyutsal kontrol yeterli düzeyde uygulanmamakta; tezgah ayarları/kalibrasyon eksikliği nedeniyle tolerans dışı üretim gerçekleşmektedir.'::text, E'1. Uygunsuz parti iade edilmeli; tedarikçiden düzeltilmiş parti talep edilmelidir.\n2. Tedarikçi ölçüm cihazlarının kalibrasyonu kontrol edilmeli, gerekirse Gage R&R çalışması yapılması talep edilmelidir.\n3. Kritik boyutlar için tedarikçi ilk numune onay (PPAP) sürecine alınmalıdır.\n4. Tekrarlayan boyutsal hatalar için tedarikçi üretim tezgahlarına bakım-onarım yapılması takip edilmelidir.'::text),
  (E'DF-2026-022'::text, E'DF'::text, E'GIRD/ KALITEKONTROLU- UYGUNSUZLUKTESPITI | MUAYENEBILGILERI | Kayit No: 26/01/146 | Muayene Tarihi: 29.01.2026 | Tedarikgi: Ozkan Makine Ltd. Sti.'::text, E'Tedarikçi üretim sürecinde boyutsal/görsel/fonksiyonel kalite kontrol yeterli düzeyde uygulanmamaktadır. Kontrol planında kritik karakteristikler tanımlanmamış veya muayene sürecinde sapma tespit edilememiştir.'::text, E'1. Uygunsuz \'Jcb74kw Motor Pompa Kampanasi\' partisi tedarikçiye iade edilmeli veya karantinaya alınmalıdır.\n2. Tedarikçiye DF-2026-022 numaralı DF kaydı iletilmeli, 15 iş günü içinde yazılı kök neden analizi ve düzeltici aksiyon planı talep edilmelidir.\n3. Tedarikçinin kontrol planı incelenmeli; kritik boyutlar ve kabul kriterleri yeniden belirlenmeli, onaylı kontrol planı alınmalıdır.\n4. Aynı tedarikçiden tekrarlayan uygunsuzluk varsa tedarikçi performans puanı düşürülmeli, alternatif tedarikçi değerlendirmesi başlatılmalıdır.'::text),
  (E'DF-2026-023'::text, E'DF'::text, E'GIRD/ KALITEKONTROLU- UYGUNSUZLUKTESPITI | MUAYENEBILGILERI | Kayit No: 26/01/118 | Muayene Tarihi: 23.01.2026 | Tedarikgi: Ozkan Makine Ltd. Sti.'::text, E'Tedarikçi üretim sürecinde boyutsal/görsel/fonksiyonel kalite kontrol yeterli düzeyde uygulanmamaktadır. Kontrol planında kritik karakteristikler tanımlanmamış veya muayene sürecinde sapma tespit edilememiştir.'::text, E'1. Uygunsuz \'Pervane Baglantisi Kaynakli Komple\' partisi tedarikçiye iade edilmeli veya karantinaya alınmalıdır.\n2. Tedarikçiye DF-2026-023 numaralı DF kaydı iletilmeli, 15 iş günü içinde yazılı kök neden analizi ve düzeltici aksiyon planı talep edilmelidir.\n3. Tedarikçinin kontrol planı incelenmeli; kritik boyutlar ve kabul kriterleri yeniden belirlenmeli, onaylı kontrol planı alınmalıdır.\n4. Aynı tedarikçiden tekrarlayan uygunsuzluk varsa tedarikçi performans puanı düşürülmeli, alternatif tedarikçi değerlendirmesi başlatılmalıdır.'::text),
  (E'DF-2026-026'::text, E'DF'::text, E'GIRD/ KALITEKONTROLU- UYGUNSUZLUKTESPITI | MUAYENEBILGILERI | Kayit No: 26/01/061 | Muayene Tarihi: 13.01.2026 | Tedarikgi: Civata Ve Metal San.tic. A.s'::text, E'Tedarikçi üretim sürecinde boyutsal/görsel/fonksiyonel kalite kontrol yeterli düzeyde uygulanmamaktadır. Kontrol planında kritik karakteristikler tanımlanmamış veya muayene sürecinde sapma tespit edilememiştir.'::text, E'1. Uygunsuz \'Konveyor Mafsal Civatasi\' partisi tedarikçiye iade edilmeli veya karantinaya alınmalıdır.\n2. Tedarikçiye DF-2026-026 numaralı DF kaydı iletilmeli, 15 iş günü içinde yazılı kök neden analizi ve düzeltici aksiyon planı talep edilmelidir.\n3. Tedarikçinin kontrol planı incelenmeli; kritik boyutlar ve kabul kriterleri yeniden belirlenmeli, onaylı kontrol planı alınmalıdır.\n4. Aynı tedarikçiden tekrarlayan uygunsuzluk varsa tedarikçi performans puanı düşürülmeli, alternatif tedarikçi değerlendirmesi başlatılmalıdır.'::text),
  (E'DF-2026-027'::text, E'DF'::text, E'GIRD/ KALITEKONTROLU- UYGUNSUZLUKTESPITI | MUAYENEBILGILERI | Kayit No: 26/01/147 | Muayene Tarihi: 29.01.2026 | Tedarikgi: Uzcelik Makine Ltd. Sti.'::text, E'Tedarikçi üretim sürecinde boyutsal/görsel/fonksiyonel kalite kontrol yeterli düzeyde uygulanmamaktadır. Kontrol planında kritik karakteristikler tanımlanmamış veya muayene sürecinde sapma tespit edilememiştir.'::text, E'1. Uygunsuz \'Arka Firga Silindir Pimi\' partisi tedarikçiye iade edilmeli veya karantinaya alınmalıdır.\n2. Tedarikçiye DF-2026-027 numaralı DF kaydı iletilmeli, 15 iş günü içinde yazılı kök neden analizi ve düzeltici aksiyon planı talep edilmelidir.\n3. Tedarikçinin kontrol planı incelenmeli; kritik boyutlar ve kabul kriterleri yeniden belirlenmeli, onaylı kontrol planı alınmalıdır.\n4. Aynı tedarikçiden tekrarlayan uygunsuzluk varsa tedarikçi performans puanı düşürülmeli, alternatif tedarikçi değerlendirmesi başlatılmalıdır.'::text)
)
UPDATE non_conformities n
SET
  five_why_analysis = COALESCE(n.five_why_analysis, '{}'::jsonb)
    || jsonb_build_object(
      'problem', to_jsonb(x.problem),
      'rootCause', to_jsonb(x.root_cause),
      'why5', to_jsonb(x.root_cause),
      'preventiveAction', to_jsonb(x.actions_text)
    ),
  eight_d_steps = CASE
    WHEN n.type = '8D' THEN
      jsonb_set(
        jsonb_set(
          COALESCE(n.eight_d_steps, '{}'::jsonb),
          '{D4,description}',
          to_jsonb(('Kök neden (rapor özeti)'::text || E'\n\n' || x.root_cause)::text),
          true
        ),
        '{D5,description}',
        to_jsonb(('Önerilen düzeltici faaliyetler'::text || E'\n\n' || x.actions_text)::text),
        true
      )
    ELSE n.eight_d_steps
  END,
  updated_at = now()
FROM x
WHERE n.nc_number = x.nc_number AND n.type = x.typ;
